dist/publishers/s3/push-cos.js
=> chore: travis s3 publisher should use base64-encoded creds

README.md
Live version requires more work before it's ready for users to try with kube.
=> docs: remove live link

app/plugins/modules/core-support/src/lib/cmds/base64.ts, app/plugins/modules/core-support/src/lib/cmds/window.ts, app/plugins/modules/core-support/src/lib/new-tab.ts
=> fix(core-support): tab close, base64, window close do not require auth

app/plugins/modules/core-support/src/lib/cmds/history/history.ts, app/plugins/modules/k8s/src/test/k8s/create-pod.ts, app/plugins/modules/openwhisk/src/test/openwhisk1/create-then-delete-then-list/action-with-explicit-entity-type.ts, app/plugins/modules/openwhisk/src/test/openwhisk2/await.ts, app/plugins/modules/openwhisk/src/test/openwhisk2/history.ts, app/plugins/modules/openwhisk/src/test/openwhisk3/lcd.ts, app/plugins/modules/openwhisk/src/test/openwhisk3/roots-with-error.ts, app/plugins/modules/openwhisk/src/test/openwhisk3/seq-let.ts, app/plugins/modules/openwhisk/src/test/openwhisk3/tab-completion.ts, app/plugins/modules/openwhisk/src/test/openwhisk4/let.ts, app/plugins/modules/openwhisk/src/test/openwhisk4/pagination.ts, app/plugins/modules/openwhisk/src/test/openwhisk4/zip.ts, app/src/core/repl.ts, app/src/test/core2/clear.ts, app/src/test/core2/history.ts, app/src/test/core2/tab-completion.ts, tests/lib/ui.js
also implement a real usage model for the history command
Fixes #179
```
```
Thanks!
=> fix(core-support): add history -c support

app/src/main/spawn-electron.ts, package.json
feat(electron): Upgrade to Electron 4.0.1 and Replace deprecated app.makeSingleInstance API with Electron 4.0 supported impl
Fixes #192
=> feat(electron): Upgrade to Electron 4.0.1 and Replace deprecated app.makeSingleInstance API with Electron 4.0 supported impl

plugins/openwhisk/src/test/openwhisk2/no_wskprops.ts, plugins/plugin-openwhisk/src/lib/models/auth.ts
fix(openwhisk): add expandHomeDir when reading process.env.WSK_CONFIG_FILE
test(openwhisk): add no ~/.wskprops test to openwhisk2
Fixes #253
=> fix(OpenWhisk): add expandHomeDir when reading process.env.WSK_CONFIG_FILE

packages/app/CHANGELOG.md, packages/app/package.json, packages/kui-builder/CHANGELOG.md, packages/kui-builder/package.json, packages/proxy/CHANGELOG.md, packages/proxy/package.json, plugins/plugin-apache-composer/CHANGELOG.md, plugins/plugin-apache-composer/package.json, plugins/plugin-bash-like/CHANGELOG.md, plugins/plugin-bash-like/package.json, plugins/plugin-core-support/CHANGELOG.md, plugins/plugin-core-support/package.json, plugins/plugin-editor/CHANGELOG.md, plugins/plugin-editor/package.json, plugins/plugin-grid/CHANGELOG.md, plugins/plugin-grid/package.json, plugins/plugin-k8s/CHANGELOG.md, plugins/plugin-k8s/package.json, plugins/plugin-manager/CHANGELOG.md, plugins/plugin-manager/package.json, plugins/plugin-openwhisk-debug/CHANGELOG.md, plugins/plugin-openwhisk-debug/package.json, plugins/plugin-openwhisk/CHANGELOG.md, plugins/plugin-openwhisk/package.json, plugins/plugin-proxy-support/CHANGELOG.md, plugins/plugin-proxy-support/package.json, plugins/plugin-tutorials/CHANGELOG.md, plugins/plugin-tutorials/package.json, plugins/plugin-wskflow/CHANGELOG.md, plugins/plugin-wskflow/package.json
- @kui-shell/core@2.5.0
- @kui-shell/builder@0.5.0
- @kui-shell/proxy@0.5.0
- @kui-shell/plugin-apache-composer@0.10.0
- @kui-shell/plugin-bash-like@0.0.7
- @kui-shell/plugin-core-support@0.5.0
- @kui-shell/plugin-editor@0.0.6
- @kui-shell/plugin-grid@0.0.6
- @kui-shell/plugin-k8s@0.5.0
- @kui-shell/plugin-manager@0.0.6
- @kui-shell/plugin-openwhisk-debug@0.0.6
- @kui-shell/plugin-openwhisk@0.5.0
- @kui-shell/plugin-proxy-support@0.5.0
- @kui-shell/plugin-tutorials@0.5.0
- @kui-shell/plugin-wskflow@0.0.6
=> chore(release): publish

packages/app/src/main/spawn-electron.ts
=> fix: opening Kui Electron Builds from macOS Finder adds additional argv -psn

plugins/plugin-openwhisk/src/lib/views/sidecar/activations.ts
=> fix(plugin-openwhisk): openwhisk cost calculator should use duration field in activations

README.md, docs/dev/custom-clients.md, docs/dev/customization-guide.md
=> docs: fix broken link and incomplete text in custom client guides

clients/README.md
=> docs: fix broken custom-client-documenation link in client/README.md

packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
=> fix(packages/kui-builder): dark theme is missing a trailing semicolon

packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css
=> fix(packages/kui-builder): nord theme's cyan color isn't right

plugins/plugin-bash-like/web/css/my-diff2html.css
=> fix(plugins/plugin-bash-like): avoid use of bold fonts in git diff

tools/travis/test/install.sh
=> chore(tools/travis): update jq to 1.6 in linux and osx travis

packages/app/web/css/ui.css
=> fix(packages/app): badge text renders off-center in firefox

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
for atelier and solarized
Fixes #776
=> fix(packages/kui-builder): increase contrast for key-value yaml

plugins/plugin-k8s/src/lib/util/help.ts
=> fix(plugins/plugin-k8s): make kubectl -h detailed examples clickable

packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
remove some of the overrides that came from the original copy-paste of light.css
Fixes #882
=> fix(packages/kui-builder): tweaks to default dark theme

clients/default/package.json
=> chore(packages/proxy): build proxy in the default client of monorepo

packages/app/web/css/ui.css
=> fix(packages/app): tables go full width when sidecar is minimized

packages/kui-builder/dist/webpack/webpack.config.js
=> fix(packages/kui-builder): use webpack ignore-loader for proxy-agent

packages/app/src/webapp/views/sidecar.ts
=> fix(packages/app): /sidecar/maximize event comes too early

packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
=> fix(packages/kui-builder): light theme's baseOF is too light

.npmrc
=> chore: remove leftover top-level npmrc

plugins/plugin-core-support/src/lib/cmds/about/about.ts
Satisfies issue #1003
In the version command, optional build information is displayed in parentheses.  In the 'about' display it occupies a line below the main version.  If there is no build information supplied, the appearance is as before.
The optional build information is supplied as member `build-info` of `theme/config.json`.  Thus, it applies to external clients but also works in the default client, if that is desired.   I believe it should be up to the client to decide what build info consists of.  We use (roughly)
```
HASH=$(git rev-parse HEAD)
DIRTY=$(git status --porcelain)
if [ -n "$DIRTY" ]; then
DIRTY="++"
fi
BUILDINFO=${HASH:0:8}${DIRTY}
```
This takes the process completely out of manual control (a good thing IMO) but requires that the `config.json` file be git-ignored so …
=> feat(plugin-core-support): Version gets build info

packages/kui-builder/dist/webpack/package.json, packages/kui-builder/dist/webpack/webpack.config.js
Satisfies issue #1249
In the issue I said we needed to add support for "at least gzip".   In fact, this change, which we've been using in our fork for a while, supports "at most gzip" (plus the original brotli, still the default).
To select gzip compression, specify `WEB_COMPRESS=gzip` in the environment of the webpack build.
The compression plugin actually supports an `algorithm` option, which, if specified as a string, will support any compression supported (by name) in `zlib`.   We have experimented with a small variation on this change, in which the algorithm specified in the environment is passed to the plugin.  However, as shipped with node, `zlib` supports (by name) only `gzip` (it's default) and `deflate`.   To support others (e.g. `zopfli`) you have to make a more intrusive (and …
=> Feat(kui-builder): Flexible compression in webpack

plugins/plugin-k8s/src/test/k8s/helm.ts
=> fix(plugins/plugin-k8s): fixed the issue that empty helm list returns {} as output and added tests for empty helm list

plugins/plugin-openwhisk/src/lib/models/auth.ts
Fixes #1262
For webpack, use the origin.  For electron, allow a value to be built
in at build time.
Signed-off-by: Joshua Auerbach <josh@nimbella.com>
=> Feat(plugin-openwhisk): Improved API host defaults

packages/app/src/webapp/cli.ts
when clearing the console, block counts do not restart from 0
Fixes #1275
=> fix(packages/app): REPL block index management versus clear command

package.json
npm adds devDependencies executables to PATH when running scripts. So we don't need to use npx.
Moreover, in this way the devs share the same lerna version. The same thing happens for publishing, it's better to use the same version we're using to develop. So I've also added a new npm task: publish.
More info here: https://firstdoit.com/no-need-for-globals-using-npm-dependencies-in-npm-scripts-3dfb478908
=> style: avoiding npx for devDependencies

packages/app/src/webapp/models/table.ts, packages/app/src/webapp/views/table.ts, packages/app/web/css/ui.css, plugins/plugin-bash-like/src/lib/cmds/ls.ts
missing permissions column; also make `ls` use Light tables
Fixes #1296
Fixes #1278
=> fix: ls -l and ls -la do not display properly

packages/tests/bin/runMochaLayers.sh
To fix a bug I added in my last commit to this file. Now the `LAYER` environment variable works in all cases like before.
=> fix(packages/tests): regression in LAYER env var

packages/app/tests/lib/common.js, packages/app/tests/lib/ui.js, plugins/plugin-k8s/src/lib/model/states.ts, plugins/plugin-k8s/src/test/k8s1/hpa.ts, plugins/plugin-k8s/tests/data/k8s/hpa.yaml, plugins/plugin-k8s/tests/lib/k8s/utils.d.ts, plugins/plugin-k8s/tests/lib/k8s/utils.js
=> fix(plugins/plugin-k8s): HorizontalPodAutoscaler status support

packages/app/web/css/ui.css, plugins/plugin-bash-like/src/lib/cmds/ls.ts
=> feat(plugins/plugin-bash-like): only show OWNER and GROUP for ls -l

packages/app/src/webapp/cli.ts, plugins/plugin-core-support/src/lib/cmds/screenshot.ts
=> fix: screenshot sidecar versus escape key

plugins/plugin-k8s/src/lib/controller/status.ts, plugins/plugin-k8s/src/test/k8s1/status.ts
part of #1461
Issue Description: command `k status --all` only returns the resources under the **namespace saved in context**, which is not the expected behavior. Instead, `k status --all` should return the resources **under all the namespaces of a cluster**.
I solved this issue by introducing a mechanism to **fetch all the namespaces** in the context fetcher of `controller/status.ts`. For `k status --all`, after fetching all cluster names, the controller will fetch all the namespaces based on the cluster name. 
I also added `-n ${namespace}` in the resource fetcher in `controller/status.ts` to actually use the namespaces we fetched.
=> fix(plugins/plugin-k8s): `k status --all` should return resources across namespaces

packages/app/web/css/ui.css, plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
=> fix: allow for log-lines tables to specify a looser layout

packages/app/src/core/repl.ts, packages/app/src/models/sessionStore.ts, plugins/plugin-bash-like/src/lib/cmds/export.ts, plugins/plugin-bash-like/src/plugin.ts, plugins/plugin-bash-like/src/test/bash-like/export.ts
Signed-off-by: Xianzhi Olivia Ruan <rxianzhi@umich.edu>
Fixes #180 
Add a new command in bash-like plugin to support export feature.
Variables would be saved in sessionStorage in the structure:
```
{tabIndex:[{key:value}]}
```
=> feat(plugins/plugin-bash-like): support simple bash export command

plugins/plugin-k8s/src/lib/controller/kubectl.ts, plugins/plugin-k8s/src/lib/model/states.ts, plugins/plugin-k8s/src/lib/view/modes/conditions.ts, plugins/plugin-k8s/src/lib/view/modes/containers.ts, plugins/plugin-k8s/src/lib/view/modes/pods.ts
=> chore(plugin/plugin-k8s): add missing SidecarMode types to k8s plugin

packages/app/src/core/capabilities.ts, plugins/plugin-bash-like/src/lib/cmds/catchall.ts, plugins/plugin-proxy-support/src/preload.ts
this also adds a hasProxy Capability
Fixes #1494
=> fix: avoid catchall registration if in browser and no proxy

packages/app/src/core/command-tree.ts, packages/app/src/core/plugins.ts, packages/app/src/webapp/cli.ts, packages/app/src/webapp/util/ascii-to-usage.ts, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-bash-like/src/pty/server.ts, plugins/plugin-bash-like/web/css/xterm.css
Fixes #1503
i found some fairly big performance issues in the PTY (mostly visible if you had lots of PTY output in your scroll buffer).
*Cause*: we were incurring 6 full browser forced-reflows for every bash command. oof. i've optimized that down to 1. there is still another round of optimization needed, but this should be a considerable improvement. this also seems to remove some of the jittery scrolling effects. i also optimized a few other surrounding bits.
=> fix: optimize pty

packages/app/src/webapp/views/sidecar.ts, plugins/plugin-bash-like/src/pty/client.ts
=> fix: window resize versus pty size cache

plugins/plugin-core-support/src/lib/cmds/screenshot.ts
=> fix(plugins/plugin-core-support): screenshot of repl output is glitchy

tools/typecov/bin/build.sh
=> chore: hack for git-lfs versus travis

packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
=> fix(packages/kui-builder): light theme versus gray badges

plugins/plugin-k8s/src/lib/controller/describe.ts, plugins/plugin-k8s/src/lib/controller/kubectl.ts, plugins/plugin-k8s/src/lib/view/modes/conditions.ts, plugins/plugin-k8s/src/lib/view/modes/containers.ts, plugins/plugin-k8s/src/lib/view/modes/pods.ts, plugins/plugin-k8s/src/lib/view/modes/registrar.ts, plugins/plugin-k8s/src/preload.ts
this is an internal chore/cleanup task
Fixes #1531
=> chore(plugins/plugin-k8s): port kubectl to use mode registrar

plugins/plugin-bash-like/src/lib/cmds/bash-like.ts, plugins/plugin-bash-like/src/lib/cmds/ls.ts, plugins/plugin-bash-like/src/test/bash-like/bash-like.ts, plugins/plugin-bash-like/src/test/bash-like/ls.ts
=> fix(plugins/plugin-bash-like): ls versus wildcards

packages/app/src/webapp/util/ascii-to-table.ts, plugins/plugin-bash-like/src/test/bash-like/pty-auto-table.ts, plugins/plugin-bash-like/tests/data/table-with-duplicate-columns.txt, plugins/plugin-k8s/src/lib/view/formatTable.ts
=> fix: ascii-to-table with duplicate final column

.eslintrc.json, packages/app/src/core/find-file.ts, packages/app/src/core/plugins.ts, packages/app/src/core/usage-error.ts, packages/app/src/main/headless-pretty-print.ts, packages/app/src/models/SubwindowPrefs.ts, packages/app/src/models/command.ts, packages/app/src/models/entity.ts, packages/app/src/webapp/bottom-stripe.ts, packages/app/src/webapp/cli.ts, packages/app/src/webapp/util/ascii-to-table.ts, packages/app/src/webapp/views/sidecar.ts, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-core-support/src/lib/tab-completion.ts, plugins/plugin-editor/src/lib/cmds/edit.ts, plugins/plugin-grid/src/lib/cmds/grid.ts, plugins/plugin-grid/src/lib/util.ts, plugins/plugin-k8s/src/lib/model/resource.ts, plugins/plugin-k8s/src/lib/model/states.ts, plugins/plugin-openwhisk-debug/src/plugin.ts, plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts, plugins/plugin-openwhisk/src/lib/cmds/copy.ts, plugins/plugin-openwhisk/src/lib/cmds/load-test.ts, plugins/plugin-openwhisk/src/test/openwhisk3/popup.ts, plugins/plugin-tekton/src/lib/tekton2graph.ts, plugins/plugin-tekton/src/model/resource.ts, plugins/plugin-tutorials/src/lib/cmds/modes.ts, plugins/plugin-wskflow/src/lib/graph2doms.ts
=> style: fix typescript-eslint/member-delimiter-style rule

docs/installation.md
=> docs: remove the windows download link on installation page

packages/tests/bin/runMochaLayers.sh, packages/tests/bin/runTest.sh
=> test: filter out ow-related tests for non-ow developers in local testing

packages/kui-builder/tsconfig.json
=> chore(packages/kui-builder): add esnext support to tsconfig.json

plugins/plugin-manager/src/.eslintrc.json, plugins/plugin-manager/src/lib/cmds/install.ts, plugins/plugin-manager/src/lib/cmds/list.ts, plugins/plugin-manager/src/plugin.ts
=> style(plugins-manager): lint unused-vars

plugins/plugin-editor/.eslintrc.json, plugins/plugin-editor/src/lib/cmds/edit.ts, plugins/plugin-editor/src/lib/fetchers.ts, plugins/plugin-editor/src/lib/init/amd.ts, plugins/plugin-editor/src/lib/init/esm.ts, plugins/plugin-editor/src/lib/languages/composer-javascript.ts, plugins/plugin-editor/src/lib/open.ts, plugins/plugin-editor/src/lib/readonly.ts, plugins/plugin-editor/src/lib/util.ts, plugins/plugin-editor/src/preload.ts, plugins/plugin-editor/src/test/editor/edit.ts
=> style(plugins-editor): lint unused-vars

plugins/plugin-core-support/web/css/screenshot.css
=> fix(plugins/plugin-core-support): sidecar screenshot of tables too wide

packages/kui-builder/package.json
=> chore(packages/kui-builder): pin some floating depenencies

plugins/plugin-k8s/src/lib/view/modes/last-applied.ts, plugins/plugin-k8s/src/lib/view/modes/pods.ts, plugins/plugin-k8s/src/preload.ts, plugins/plugin-k8s/src/test/k8s1/apply-pod.ts
=> feat(plugins/plugin-k8s): add a last applied tab for k8s resources

packages/app/src/webapp/util/ascii-to-usage.ts, packages/app/web/css/ui.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/lucario.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/monokai.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/paraiso.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-bash-like/web/css/xterm.css
also some small refinements to scrollbar colors versus themes (shows up mightily in ascii-to-usage output)
Fixes #1551
=> fix: improvements for ascii-to-usage

packages/app/src/models/command.ts, plugins/plugin-proxy-support/.eslintrc.json, plugins/plugin-proxy-support/src/lib/proxy-executor.ts, plugins/plugin-proxy-support/src/preload.ts, plugins/plugin-tutorials/src/lib/cmds/list.ts
=> style(plugins-proxy-support): lint unused-vars

plugins/plugin-core-support/src/lib/text-search.ts, plugins/plugin-core-support/web/css/text-search.css
also fixes a hover effect issue with kui's text search close button -- not visible in dark themes
Fixes #1573
=> fix(plugins/plugin-core-support): ctrl+F responds in both editor and kui

packages/proxy/build.sh
=> fix(packages/proxy): proxy build fails for non-bluemix and non-kubernetes users

packages/app/web/css/left-tab-stripe.css, packages/app/web/css/ui.css, plugins/plugin-bash-like/web/css/xterm.css
this also tightens up the REPL a bit; this is partly driven by the flash avoidance fix.
to avoid setting the background of repl in alt buffer mode (which we were doing to avoid
having too much "white space" to the left of the alt buffer emacs or vi), it is helpful
to tighten up the UI a bit, so that we can avoid the whitespace altogether.
this also makes the REPL look a bit more REPL-like
Fixes #1664
=> fix: pty alt buffer flashes

packages/app/src/webapp/util/ascii-to-usage.ts, packages/app/web/css/ui.css
=> fix(packages/app): ascii-to-usage versus git commit

packages/app/src/core/repl.ts, plugins/plugin-proxy-support/src/lib/proxy-executor.ts
=> fix(packages/proxy): override execOptions.tab in proxy executor

packages/kui-builder/package.json
=> chore(packages/kui-builder): electron 5.0.3

tools/install.sh
The script includes this first line as a comment, which shows how should be used in the future: `curl -sL https://install.kui-shell.org | sh`
Until it's merged it can be tested in this way: `curl -sL https://raw.githubusercontent.com/jesusprubio/kui/install-script/tools/install.sh | sh`
Once it's merged we can use: `curl -sL https://raw.githubusercontent.com/IBM/kui/mastert/tools/install.sh | sh`
We have been asked for a one-liner to install the tool in every supported platform.
=> feat: shell script to install prebuilt releases

.eslintrc.json
Now that all the plugins pass the rule, we can simplify!
=> style: simplify ESLint overrides config

.travis.yml, packages/kui-builder/dist/webpack/Dockerfile.http, packages/kui-builder/dist/webpack/bin/webpack-client.sh, packages/kui-builder/dist/webpack/build-docker.sh, packages/kui-builder/dist/webpack/build.sh
=> test: travis test webpack build with http and no compression 

packages/kui-builder/examples/plugin-sample/package.json
=> fix(packages/kui-builder): update plugin-sample with prepack mechanism

packages/app/src/webapp/util/ascii-to-table.ts, packages/app/tests/lib/ui.js, plugins/plugin-k8s/src/lib/view/formatTable.ts, plugins/plugin-k8s/src/test/k8s1/helm.ts
this also ports the table parsing fixes to the core ascii-to-table
Fixes #1721
=> fix: helm list and helm list test fixes

packages/app/src/core/preloader.ts, packages/app/src/models/plugin.ts, plugins/plugin-k8s/src/preload.ts, plugins/plugin-proxy-support/src/preload.ts
=> fix(packages/app): register capabilities before preloading plugins

packages/app/src/models/entity.ts, packages/app/src/webapp/views/sidecar.ts, packages/app/web/css/ui.css, plugins/plugin-editor/src/lib/open.ts, plugins/plugin-k8s/src/test/k8s1/tab-completion.ts
due to some CSS bugs... this PR also generalized the handling of resource metadata a bit
Fixes #1694
=> fix(packages/app): first column with sidecar open can be scrunched

plugins/plugin-k8s/src/test/k8s1/tab-completion.ts
=> fix(plugins/plugin-k8s): k8s tab completion test regression

.eslintrc.json, packages/app/src/core/repl.ts
I'm going to add them here: #1759.
=> style: remove @typescript-eslint/no-object-literal-type-assertion rule

packages/app/web/css/top-tab-stripe.css
=> fix(packages/app): inconsistent inactive tab borders

packages/kui-builder/tsconfig.json, plugins/plugin-bash-like/src/test/bash-like/git-tab-completion.ts, plugins/plugin-core-support/src/test/core-support/tab-completion.ts, plugins/plugin-core-support/tests/lib/core-support/tab-completion-util.d.ts, plugins/plugin-core-support/tests/lib/core-support/tab-completion-util.js, plugins/plugin-k8s/src/test/k8s1/tab-completion.ts
=> test(plugins/plugin-core-support): tab-completion-util should not be symlinked into source tree

packages/app/src/webapp/views/table.ts, plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
=> fix(packages/app): watchable table: stop checking resource deletion by error message

package.json, packages/app/package.json, packages/app/web/css/ui.css, packages/kui-builder/package.json, plugins/plugin-bash-like/package.json
including electron 5.0.4
Fixes #1798
=> chore: bump version dependencies

packages/app/src/webapp/util/ascii-to-table.ts, plugins/plugin-k8s/src/lib/view/formatTable.ts
=> fix: remove regex lookbehind for webpack in firefox

.travis.yml
Use canary option to override the need of versioning with lerna publish
=> fix: use canary option to fix release error

packages/proxy/Dockerfile, packages/proxy/README.md, packages/proxy/build-docker.sh
this also downloads newer helm verisons
Fixes #1806
=> feat(packages/proxy): allow builders to choose kubectl verison for proxy

packages/kui-builder/tsconfig.json
=> fix: Remove plugin-openwhisk-debug from tsconfig

.travis.yml
Add env field to npm release stage
=> fix: avoid install on blue for npm release

packages/app/tests/lib/common.js, packages/app/tests/lib/ui.js
=> fix(packages/app): retry app launch in tests

plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts, plugins/plugin-k8s/src/test/k8s2/create-pod-popup.ts, plugins/plugin-k8s/src/test/k8s2/get-pods-with-watch.ts
=> test(plugins/plugin-k8s): remove the unnecessary test guards for cleaning resource

packages/proxy/Dockerfile
also slightly improve proxy Docker build time, by downloading helm releases in parallel
Fixes #1840
=> fix(packages/proxy): fix helm running in webpack+proxy clients

.travis.yml
=> fix: avoid dev release when doing cron release

plugins/plugin-editor/web/css/dark.css, plugins/plugin-editor/web/css/editor.css
=> fix(plugins/plugin-editor): editor text selection versus light theme

packages/app/web/css/ui.css
=> fix(packages/app): bad monospace font in webpack builds, on mac

packages/app/src/models/entity.ts, packages/app/src/webapp/cli.ts, packages/app/src/webapp/models/basicModels.ts, packages/app/src/webapp/models/table.ts, packages/app/src/webapp/views/diffTable.ts, packages/app/src/webapp/views/table.ts, plugins/plugin-k8s/src/lib/controller/contexts.ts, plugins/plugin-k8s/src/lib/controller/kedit.ts, plugins/plugin-k8s/src/lib/controller/kubectl.ts, plugins/plugin-k8s/src/lib/controller/status.ts, plugins/plugin-k8s/src/lib/view/formatEntity.ts, plugins/plugin-k8s/src/lib/view/formatMultiTable.ts, plugins/plugin-k8s/src/lib/view/helm-status.ts
Fixes #1853
Fixes #1764
About this PR:
Current Problem: The k status command uses the old watch mechanism, which doesn't work in proxy+webpack mode. Since we use k status table to create k8s resource, this issue blocks us from enabling our proxy+webpack test for k8s layers.
Solution: I ported the k status table into new watchable table, and implemented a watchable multi-table. 
Implementation Details: 
1. I changed the behavior of k status command. It used to return Table(s) with initial status - Pending and relied on cell watching mechanism (located at views/table/addCellToRow) to call the watch function and update the cell attribute. In my PR, k status command will no longer return a table with placeholder Pending status. Instead, it will wait for resource fetcher and return the real …
=> feat: port k status table into new watcher and add watchable multi-table

packages/app/src/main/tray.ts, packages/app/src/webapp/views/table.ts
Also improved the test by replacing the deprecated electron.screen with electron.remote.screen
Fixes #1932
=> fix(packages/app): Table Watcher should check if it reaches the final state before registering watcher

plugins/plugin-k8s/src/lib/util/discovery/kubeconfig.ts
=> fix(plugins/plugin-k8s): eliminated unnecessary error message for finding KUBECONFIG in local file system

plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
ibmcloud changed the format of their usage output, ugh
Fixes #1977
=> chore(plugins/plugin-bash-like): disable ibmcloud usage test

packages/kui-builder/examples/build-configs/default/theme/css/themes/tomorrow-night.css
=> fix(packages/kui-builder): ANSI black in new dark theme is not visible

plugins/plugin-k8s/src/lib/controller/kubectl.ts
=> fix(plugins/plugin-k8s): sidecar's yaml tab for namespace resource has wrong packageName

packages/webpack/package.json, packages/webpack/webpack.config.js
=> chore(packages/webpack): remove dependence on webpack-visualizer-plugin

packages/app/src/webapp/views/table.ts, packages/app/web/css/ui.css, plugins/plugin-k8s/src/lib/controller/status.ts, plugins/plugin-k8s/src/lib/view/formatTable.ts
1) the contexts table is ported to radiotable
2) remove odd use of fa-network from k status
Fixes #2089
=> chore: remove fontawesome from k8s

tools/install.sh
When the installation scripts finish the installation process at macOS, the application is not automatically open. That is not the default process of an application installation, in any case, we should ask users before doing operations in their name.
=> chore: Kui is not automatically open after installation

packages/app/src/models/execOptions.ts, packages/app/src/util/mimic-dom.ts, packages/app/src/webapp/util/time.ts, packages/app/web/css/ui.css, plugins/plugin-k8s/src/lib/controller/kubectl.ts, plugins/plugin-k8s/src/lib/util/log-parser.ts, plugins/plugin-proxy-support/src/lib/proxy-executor.ts
this introduces the passing through of navigator.language to the proxy
Fixes #1684
=> fix: kubectl logs versus webpack+proxy

packages/proxy/app/routes/exec.js, plugins/plugin-bash-like/package.json, plugins/plugin-bash-like/src/pty/stdio-channel.ts
this introduces process.env.KUI_HEARTBEAT_INTERVAL defaulting to 30s
Fixes #2199
=> fix(packages/proxy): leaking subprocesses on websocket channel death

plugins/plugin-k8s/src/lib/controller/kubectl.ts
=> fix(plugins/plugin-k8s): port kubectl run into watcher

plugins/plugin-core-support/src/lib/new-tab.ts
this is only a few lines of code that tries to be fairly conservative in grabbing focus back to the current prompt
Fixes #2323
=> fix(plugins/plugin-core-support): restore much simpler repl-focus logic

plugins/plugin-k8s/src/lib/model/states.ts, plugins/plugin-k8s/src/test/k8s1/apply-pod.ts
when sorting pod conditions to get pod status, Kui should sort the conditions by type if they have the same lastTransitionTime and status
Fixes #2327
=> fix(plugins/plugin-k8s): pod creation staus UI improvement

packages/app/tests/lib/ui.d.ts, packages/app/tests/lib/ui.js, plugins/plugin-k8s/src/lib/controller/kubectl.ts, plugins/plugin-k8s/src/lib/view/formatTable.ts, plugins/plugin-k8s/src/test/k8s1/helm.ts
also fixes some long-standing formatting issues in helm tables: "REVISION UPDATED" columns were conjoined
Fixes #2341
=> fix(plugins/plugin-k8s): helm history should be a kui table

plugins/plugin-core-support/src/lib/cmds/about/about.ts
when there is no gettingStarted defined in theme
Fixes #2380
=> fix(plugins/plugin-core-support): infinite loop in "getting started"

plugins/plugin-k8s/src/lib/view/formatTable.ts
we should hide the namespace column when sidecar is open
Fixes #2320
=> fix(plugins/plugin-k8s): ui tweaks of k get pods --all-namepaces

.eslintignore, .travis.yml, plugins/plugin-k8s/src/test/k8s2/headless-create-pod.ts, plugins/plugin-k8s/src/test/k8s2/logs-dash-f.ts, plugins/plugin-k8s/tests/data/k8s/headless/pod2.yaml, plugins/plugin-k8s/tests/lib/k8s/utils.d.ts, plugins/plugin-k8s/tests/lib/k8s/utils.js, tools/travis/test/install.sh
we are overloading the vms
Fixes #2421
=> test: split k8s travis test layer in two

lerna.json, package.json, packages/app/package.json, packages/kui-builder/package.json, packages/kui-builder/src/defaults/lerna.json, packages/proxy/package.json, packages/tests/package.json, packages/webpack/package.json, plugins/plugin-apache-composer/package.json, plugins/plugin-bash-like/package.json, plugins/plugin-core-support/package.json, plugins/plugin-editor/package.json, plugins/plugin-grid/package.json, plugins/plugin-k8s/package.json, plugins/plugin-manager/package.json, plugins/plugin-openwhisk-editor-extensions/package.json, plugins/plugin-openwhisk/package.json, plugins/plugin-operator-framework/package.json, plugins/plugin-proxy-support/package.json, plugins/plugin-tekton/package.json, plugins/plugin-tutorials/package.json, plugins/plugin-wrk/package.json, plugins/plugin-wskflow/package.json
=> chore: bump Kui's version to 3.0.0, including all the components Kui publishes

packages/app/src/core/settings.ts
cherry pick
9e4b63c28d35764cfca5ed1938b67c93d5d6af63
=> fix(packages/app): make settings.largeIcon optional in the data type

plugins/plugin-editor/web/css/theme-alignment.css
=> fix(plugins/plugin-editor): in clients/alternate light theme, editor keys sometimes too low contrast

plugins/plugin-bash-like/src/pty/client.ts
if ascii-to-usage discovers usage-like output mid-stream, it will swallow subsequent output; this PR backs that off aggressively
Fixes #2627
=> fix(plugins/plugin-bash-like): pty output sometimes not visible

clients/alternate/theme/css/top-tab-stripe-alt.css, packages/app/src/webapp/views/table.ts, packages/app/templates/index.html, packages/app/web/css/carbon-overrides-common.css, packages/app/web/css/kui-tables.css, packages/app/web/css/top-tab-stripe.css, packages/app/web/css/ui.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/lucario.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/monokai.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/paraiso.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/tomorrow-night.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css, plugins/plugin-bash-like/src/lib/cmds/git-status.ts, plugins/plugin-bash-like/web/css/my-diff2html.css, plugins/plugin-core-support/src/lib/new-tab.ts, plugins/plugin-k8s/src/test/k8s1/deployment.ts, plugins/plugin-k8s/tests/lib/k8s/utils.d.ts, plugins/plugin-k8s/tests/lib/k8s/utils.js, plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
this PR also cleans up a few other elements of design:
- sans-serif tables
- git status/diff coloring
- as part of the previous, remove no-longer-needed light-red/yellow/green css rules
- improved behavior for clicks versus active and prompt focus in sidecar
Fixes #2626
=> fix: clean up transition effects

packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
=> fix(packages/kui-builder): default dark theme has poor blue color

packages/app/web/css/top-tab-stripe-alt.css, packages/app/web/css/top-tab-stripe.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray90.css, packages/kui-builder/examples/build-configs/default/theme/css/top-tab-stripe-alt.css, packages/kui-builder/examples/build-configs/default/theme/theme.json, plugins/plugin-core-support/src/lib/cmds/theme.ts, plugins/plugin-core-support/src/lib/new-tab.ts, plugins/plugin-core-support/src/preload.ts
this also enriches themes to allow for injecting more than one css, and adding body classes
Fixes #2714
=> feat: add carbon gray10/90 themes to clients/default

packages/app/src/models/command.ts, plugins/plugin-k8s/src/lib/controller/kubectl.ts, plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
Updated yarg-parse boolean flag for `k get`
Fixed the splice bug when we tried to remove watch flags from raw arguments
Fixes #2719
=> fix(plugins/plugin-k8s): drilldown failed for `k get -w pods`

packages/app/tests/lib/ui.js, plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
this was probably two things: namespace deletion conflicts, and the grabFocus method in the core test utility was clicking on the prompt block, not the prompt
Fixes #2757
=> test: unreliable get-namespaces-with-watch test

packages/app/src/webapp/cli.ts, packages/app/src/webapp/views/table.ts, plugins/plugin-k8s/src/test/k8s2/watch-error-handling.ts
=> fix(plugins/plugin-k8s): commands resulting in an empty watch table fail to watch for updates

packages/app/web/css/kui-tables.css, packages/app/web/css/ui.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css, packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray90.css, packages/kui-builder/examples/build-configs/default/theme/theme.json
Fixes #2798
this PR also fixes an outstanding issue with poor rendering of the sidecar toolbar in the older dark themes
=> fix: default to Light tables

packages/app/src/webapp/views/table.ts, plugins/plugin-k8s/i18n/resources_en_US.json, plugins/plugin-k8s/src/lib/view/modes/events.ts, plugins/plugin-k8s/src/test/k8s2/events.ts
Fixes #2800
This PR enhances the `Events` table in Sidecar by making the content compliant with the one in `kubectl describe` output. This PR removed `Object` Column and added `Count, First Seen, and From` Columns, which are the `Event Age` in `kubectl describe`.
Before:
After:
=> feat(plugins/plugin-k8s): improve sidecar events table

packages/app/src/webapp/views/sidecar.ts, packages/app/web/css/ui.css
Fixed this issue by removing the transition effect of Sidecar resizing
Fixes #2788
=> fix(packages/app): Sidecar not showing content when it's opened in the full-screen mode

plugins/plugin-openwhisk/src/lib/cmds/auth.ts
this affects the `wsk auth list` click handlers
Fixes #2872
=> fix(plugins/plugin-openwhisk): missing wsk prefix to auth switch

packages/core/src/api/models.ts, packages/core/src/api/ui.ts, packages/core/src/webapp/util/dom.ts, packages/core/src/webapp/views/sidecar.ts, packages/core/templates/index.html, packages/core/web/css/ui.css, plugins/plugin-bash-like/src/lib/cmds/ls.ts, plugins/plugin-core-support/src/lib/new-tab.ts, plugins/plugin-editor/src/lib/cmds/edit.ts, plugins/plugin-editor/src/lib/fetchers.ts, plugins/plugin-editor/src/lib/init/defaults.ts, plugins/plugin-editor/src/lib/open.ts, plugins/plugin-editor/src/lib/overrides.ts, plugins/plugin-editor/src/lib/persisters.ts, plugins/plugin-editor/src/lib/response.ts, plugins/plugin-editor/src/lib/util.ts, plugins/plugin-editor/src/test/editor/edit.ts, plugins/plugin-editor/web/css/editor.css, plugins/plugin-editor/web/css/theme-alignment.css, plugins/plugin-grid/src/lib/util.ts, plugins/plugin-k8s/src/test/k8s1/kedit.ts, plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts, plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts, plugins/plugin-openwhisk/src/test/openwhisk2/edit-new.ts, plugins/plugin-openwhisk/src/test/openwhisk2/edit.ts
plugin-editor now only uses core APIs
part of #2833
=> chore: continued core API work with clean up plugin-editor

.eslintignore, packages/core/.gitignore, packages/core/src/api/commands.ts, packages/core/src/commands/context.ts, packages/core/src/commands/resolution.ts, packages/core/src/commands/tree.ts, packages/core/src/core/command-tree.ts, packages/core/src/core/repl.ts, packages/core/src/main/headless.ts, packages/core/src/plugins/assembler.ts, packages/core/src/plugins/commands.ts, packages/core/src/plugins/plugins.ts, packages/core/src/plugins/resolver.ts, packages/core/src/plugins/scanner.ts, packages/core/src/webapp/bootstrap/boot.ts, packages/core/src/webapp/bootstrap/init.ts, plugins/plugin-manager/src/controller/list.ts, plugins/plugin-openwhisk/src/lib/models/auth.ts, plugins/plugin-openwhisk/src/test/openwhisk4/invoke-non-existent-action.ts
this PR also refactors the command-tree logic, cleaning up some of the oldest (and poorest) code. the cleanup is almost entirely code shuffling and comment adding.
Fixes #2963
=> fix: user-installed plugins cannot always REPL.qexec other plugins

packages/builder/dist/publishers/s3/publish.sh, packages/builder/dist/publishers/s3/push-cos.js
!important!: This PR won't publish Kui-base correctly without https://github.com/IBM/kui/pull/2938, since the PR assumes Kui-base electron distribution is built with name `Kui-base-<platform>-<arch>`.
Fixes #2939
=> feat: publish kui-base electron distributions

clients/base/package.json, packages/builder/dist/electron/build.sh, packages/builder/dist/electron/dpkg-config.json
1) the `mv` command on all platforms fails if PRODUCT_NAME=CLIENT_NAME
2) on linux, the deb builders fail because our dpkg-config.json names "kui" with a lowercase k
Fixes #2968
=> fix(packages/builder): linux packaging issues

packages/core/src/repl/exec.ts
this should resolve an issue with spawn-electron's dependence on electron-context-menu, which has a dependence on cli-truncate that (with v2.0.0 of cli-truncate) is no longer compatible with edge.
Fixes #3014
=> fix(packages/core): eliminate repl/exec -> spawn-electron import path

packages/core/src/plugins/resolver.ts
=> fix(packages/core): kui hangs if prescan references non-existent plugin

plugins/plugin-editor/src/lib/open.ts
=> fix(plugins/plugin-editor): syntax coloring not always active

plugins/plugin-k8s/src/lib/controller/kubectl.ts
=> fix(plugins/plugin-k8s): latest and previous logs labels are translated but not externalized

packages/core/web/css/kui-tables.css, packages/core/web/css/top-tab-stripe.css
this PR adjusts the table rendering in the repl to look more conventionally like a console, while keeping the badge and clickable decorations
the changes are limited to: row height; table padding; and header presentation (bottom border, font weight, font color, and all-caps)
Fixes #3036
=> fix(packages/core): adjust REPL tables to be a bit more standard

packages/core/src/plugins/commands.ts
this PR adds support for process.env.KUI_BIN_PREFIX_FOR_COMMANDS. if set, then the commands table rows will prefix all command strings with that given prefix
Fixes #3070
=> feat(packages/core): plugin commands table should support command prefix

packages/core/src/webapp/views/table.ts
Fixes https://github.com/IBM/kui/issues/2507
Last item left on accessibility defect list from this issue:  https://github.com/IBM/kui/issues/2507 (`Table results (kubectl get pods) aren't accessible via tab`).  Makes clickable table names focusable with keyboard navigation.
=> fix(packages/core): A11y - Make clickable table names focusable

plugins/plugin-editor/web/css/editor.css
Fixes https://github.com/IBM/kui/issues/3075
Before:
After:
=> fix(plugins/plugin-editor): A11y - fix sidecar editor tooltip contrast issue

plugins/plugin-k8s/src/lib/controller/helm/get.ts
Fixes #2787 
Updates:
- Added an if statement in `get.ts` to make sure `helm get notes` not parsed as a yaml file.
Details:
- `helm get notes` returns a txt file instead of yaml. 
However, plugin-k8s always treat `helm get` returns as `yaml` files. Thus it will fail and throw an exception, so the `notes` tab will never show.
Reference in kubectl.ts:
https://github.com/IBM/kui/blob/master/plugins/plugin-k8s/src/lib/controller/kubectl.ts#L238-L245
```
const output =
!options.help &&
(options.output ||
options.o ||
(command === 'helm' && verb === 'get' && 'yaml') || // helm get seems to spit out yaml without our asking
(isKube && verb === 'describe' && 'yaml') ||
(isKube && verb === 'logs' && 'latest') ||
(isKube && verb === 'get' && execOptions.raw && 'json'))
```
Screen shot after fix:
=> fix(plugins/plugin-k8s): fixed `helm get notes` error in sidecar

package-lock.json, packages/core/package.json, packages/core/src/main/spawn-electron.ts
it uses the spread operator, which is incompatible with older Edge releases. we should be using electron.shell.openExternal, anyway
Fixes #3090
=> fix(packages/core): remove use of "open" npm

packages/core/src/models/mmr/content-types.ts, packages/core/src/models/mmr/show.ts, packages/core/src/webapp/bottom-stripe.ts
also removes any explicit `any` from bottom-stripe.ts
Fixes #3112
=> fix(packages/core): mmr/show has leftover debug output

packages/core/src/webapp/util/ascii-to-table.ts, plugins/plugin-bash-like/src/pty/client.ts
Fixed by removing the onclick hanlder in ascii-to-table
Fixes #2888
=> fix(packages/core): broken clickable resource names for CLIs that don't have a kui plugin

plugins/plugin-core-support/src/lib/tab-completion.ts, plugins/plugin-core-support/src/test/core-support/tab-completion.ts
Fixes #3087
this also fixes a long-standing bug with completion versus partial completion, where e.g.
"ls plugins/<tab>" would partially complete as "ls plugins/plugin-"
but then selecting a completion item would result in a doubling of plugin-
=> fix(plugins/plugin-core-support): tab completion versus cursor motion

clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts, clients/test/plugins/plugin-test/src/lib/cmds/content/text-plain.ts, clients/test/plugins/plugin-test/src/lib/cmds/mmr-name.ts, clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts, clients/test/plugins/plugin-test/src/test/response/mmr-name.ts, clients/test/plugins/plugin-test/src/test/response/string.ts, packages/test/src/api/mmr.ts, packages/test/src/api/sidecar-expect.ts, packages/test/src/index.ts
This PR: 
1) includes a new test API for MMR metadata.name
2) enhances the existing test API of string response, to avoid using `new` without storing the result.
Fixes #3138
=> test: expand Client Test to test MMR metadata name

packages/builder/examples/build-configs/default/theme/css/themes/carbon-gray90.css
Fixed by changing --color-base08 to #FF767C
Fixes #3096
=> fix: Red error text contrast issue in Carbon 90 theme

packages/builder/examples/build-configs/default/theme/css/themes/carbon-gray90.css
=> fix: wrong colors (Gray90 and Red50) in Carbon-90 theme

packages/core/src/webapp/util/ascii-to-table.ts, plugins/plugin-bash-like/src/pty/client.ts
Revert "fix(packages/core): broken clickable resource names for CLIs that don't have a kui plugin"
Also white-listed oc comamnds
This reverts commit 39500ba350b7896c831d88d4424affc376a9ed9d.
Fixes #3168
=> fix: allow ascii-to-table drilldown effect for `oc` commands (5.1.14)

clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts, clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
modes-via-MMR and modes-via-registraion should both show up
Fixes #3210
=> test: expand clients/test mmr-mode-via-registration

clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts, packages/core/src/api/commands.ts
=> fix(packages/core): CommandOptions type not exported

plugins/plugin-core-support/web/css/about.css
Fixes https://github.com/IBM/kui/issues/3252
In non-English languages; the about/getting started panel text could get stretched out and creates a defect in the character spacing leading to a less readable experience.
=> fix(plugins/plugin-core-support): getting started text is stretched in non-English

clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts, packages/core/src/api/commands.ts, packages/core/src/commands/resolution.ts, packages/core/src/commands/tree.ts, packages/core/src/core/command-tree.ts, packages/core/src/models/command.ts, packages/core/src/models/repl.ts, packages/core/src/plugins/prescan.ts, packages/core/src/plugins/scanner.ts, packages/core/src/repl/exec.ts, packages/core/src/webapp/models/table.ts, packages/core/src/webapp/print.ts, packages/core/src/webapp/views/sidecar-core.ts, plugins/plugin-bash-like/src/lib/cmds/ls.ts, plugins/plugin-bash-like/src/lib/cmds/open.ts, plugins/plugin-core-support/src/lib/cmds/about/about.ts, plugins/plugin-core-support/src/lib/cmds/history/history.ts, plugins/plugin-core-support/src/lib/cmds/theme.ts, plugins/plugin-editor/src/lib/readonly.ts, plugins/plugin-k8s/src/lib/controller/helm/get.ts, plugins/plugin-proxy-support/src/lib/proxy-executor.ts, plugins/plugin-tutorials/src/lib/cmds/get.ts
also remove `type` from the Table type definition, as it is no longer supported, and may lead to erroneous type inference
Fixes #3279
=> chore: stop using Result as a type name

clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts, clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts, clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts, clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts, packages/core/src/models/mmr/content-types.ts, packages/core/src/models/mmr/show.ts, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-core-support/src/lib/cmds/about/about.ts
this changes the schema of CommandStringContent to
```typescript
{
contentFrom: string
contentType?: SupportedStringContent
}
```
Fixes #3299
=> feat: add support for command string modes that specify contentType

package.json
specify npm 5.7.1, because we use npm ci
Fixes #3320
=> fix: incorrect nodejs "engine" spec

packages/core/src/plugins/assembler.ts
=> fix(packages/core): plugin assembler has a path separator assumption

plugins/plugin-bash-like/src/pty/session.ts
Fixed by initializing the session as electron channel factory in electron mode
Fixes #3330
=> fix: kui session is noop in electron mode

packages/builder/dist/electron/builders/electron.js
=> fix: electron cross-builds for win32 on linux hosts do not avoid asar

packages/core/src/plugins/path.ts, packages/core/src/plugins/preloader.ts, packages/core/src/plugins/resolver.ts, packages/webpack/webpack.config.js, plugins/plugin-bash-like/src/pty/client.ts
to avoid bundling commonjs bits
Fixes #3359
=> fix: optimize webpack bundle loading

packages/webpack/bin/watch.sh
=> fix: kui-watch-webpack should just watch webpack, not build

packages/core/web/css/carbon-overrides-common.css, packages/core/web/css/ui.css
Fixes 3411
this also
- hides the timestamp for processing blocks when the sidecar is open
- modifies spinner color to make it more contrasty
=> fix: repl scrollbars overlap with repl content

packages/webpack/webpack.config.js
=> fix(packages/webpack): store generated webpack bundles under contextRoot

packages/core/web/css/kui-ui.css
=> fix(packages/core): in 10.15, SFMono fonts are in a new location

packages/core/web/css/ui.css
Fixes https://github.com/IBM/kui/issues/3254
KUI is creating grammatically incorrect strings in non-English languages because of a CSS styling rule that will capitalize every word.  KUI moving forward should not do this kind of string transformation and instead write strings as they are intended to be displayed.
=> fix(packages/core) remove string capitalization styling for getting started tab

packages/webpack/build.sh
=> fix: webpack build tarCopy falsefully excludes a theme directory

packages/builder/bin/compile.sh
=> fix(packages/builder): kui-compile still points to old theme/css

.travis.yml
Fixed by disabling the publish for now
Fixes #3535
=> fix: travis failed at npm publish to @dev on master merge request

packages/core/src/models/mmr/show.ts, packages/core/src/webapp/bottom-stripe.ts, packages/test/src/api/mmr.ts, packages/test/src/api/util.ts
we update the bottom stripe, then fetch the content for the first tab, then update the Presentation (e.g. from Slim to Normal). since the middle one is asynchronous, this introduces a glitchy UI effect
Fixes #3589
=> fix(packages/core): MMR rendering is glitchy

.travis.yml, package-lock.json, packages/webpack/webpack.config.js, plugins/plugin-wskflow/package.json
it pulls in fsevents, which causes windows build issues
WARNING: for now, this disables windows tests, until we can figure out why travis build 1809 of their windows client broke us (travis build 1803 of their windows client had been fine for us)
Fixes #3610
=> chore: remove unused chokidar dependence

plugins/plugin-carbon-themes/web/css/carbon-gray90.css
Fixes https://github.com/IBM/kui/issues/3151
---
---
**DAP scan no longer flags contrast issue**
---
=> fix(plugins/plugin-carbon-themes) a11y - sidecar badge contrast fix

plugins/plugin-editor/src/view/components/Editor.tsx
=> fix(plugins/plugin-editor): Editor component should be readOnly for non-files

packages/webpack/webpack.config.js, plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx, plugins/plugin-carbon-tables/web/css/static/hack-select.scss, plugins/plugin-client-common/src/components/Confirm.tsx, plugins/plugin-client-common/src/components/Loading.tsx, plugins/plugin-client-common/src/components/Screenshot.tsx, plugins/plugin-client-common/src/components/Search.tsx, plugins/plugin-client-common/src/components/Terminal/Block/TabCompletion.tsx, plugins/plugin-client-common/src/components/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/index.ts, plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx, plugins/plugin-sidecar/src/view/components/Markdown.tsx, plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
instead, load the parts more selectively, as needed
Fixes #3744
=> fix: stop loading the entire carbon-components.min.css

packages/core/src/main/spawn-electron.ts, packages/core/src/webapp/themes/default.ts, packages/core/src/webapp/themes/init.ts, packages/core/src/webapp/themes/persistence.ts
this avoids problems stemming from theme content relying on MiniCssExtract functionality -- which apparently does not work for webview preinjection
Fixes #3809
=> fix(packages/core): avoid using webview theme preinjection

packages/core/src/webapp/bootstrap/boot.ts, packages/core/src/webapp/bootstrap/init.ts, plugins/plugin-client-common/src/components/TabContent.tsx
=> fix: TabContent constructor sometimes calls this.setState

plugins/plugin-client-default/config.d/about.json, plugins/plugin-client-default/i18n/about_en_US.json, plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
=> fix(plugin-sidecar): React doesn't re-instantiate PaginatedTable for tabs located in the same LeftNav

plugins/plugin-carbon-themes/web/css/ibm-plex.css
Reverts IBM/kui#3832
it turns out that there were two problems;
1) note that eslint messed up the formatting
2) the sass-loader doesn't seem to support scss loading of fonts. once you fix the first issue, you'll see "Can't resolve" errors in the webpack build.
=> Revert "fix(plugins/plugin-carbon-themes): reduce load time burden of ibm-ple…"

packages/core/src/models/mmr/content-types.ts, packages/core/src/webapp/models/table.ts, plugins/plugin-carbon-tables/src/view/TableCell.tsx, plugins/plugin-client-common/src/components/StatusStripe/TextWithIconWidget.tsx
instead, allow for a ReactElement
BREAKING CHANGE: table models will no longer allow for the previously supported `Node | Node[]` data type. you must instead pass a ReactElement if you want to inject custom cell content.
Fixes #3785
=> fix: table model should not allow raw HTML Node

plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
=> fix: with two radio tables open, only one seems to have selection at a time

clients/test/plugins/plugin-test/src/lib/cmds/NavResponse.ts, clients/test/plugins/plugin-test/src/test/response/NavResponse.ts, packages/test/src/api/NavResponse.ts, plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
=> fix: return an NavResponse without links results in blank page

plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx, plugins/plugin-carbon-tables/web/css/static/tables.scss
=> fix: tables should be full-width when sidecar is open

package.json, packages/builder/bin/babel.sh, packages/builder/bin/compile.sh
update kui-compile to call babel.sh via `npx kui-babel`
Fixes #3993
=> fix(packages/builder): kui-compile does not work in external clients

packages/proxy/build.sh, packages/webpack/build.sh
=> fix: proxy still runs http-allocate-cert even if NO_DOCKER is set

packages/builder/dist/headless/build.sh
cherry-pick 4921ff5cf84831da5e704fa28f63cc4c024a972b
[jq bacaae6a1] fix: headless build script has outdated use of jq
=> fix: headless build script has outdated use of jq

plugins/plugin-client-common/src/components/Sidecar/ToolbarButton.tsx, plugins/plugin-client-common/src/components/Sidecar/TopNavSidecar.tsx, plugins/plugin-client-common/web/css/static/Popup.scss, plugins/plugin-core-support/web/css/static/zoom.css
1) in popup mode, the sidecar content and other bits still have viewport-relative sizing
2) when font zooming, the sidecar tab content is zoomed twice (two nested zoomables)
3) sidecar ToolbarButtons do not respond to font zooming
Fixes #4176
Fixes #4177
=> fix: font zooming issues

plugins/plugin-client-common/src/components/StatusStripe/TextWithIconWidget.tsx, plugins/plugin-client-common/web/scss/components/Table/badges.scss, plugins/plugin-client-default/src/index.tsx, plugins/plugin-git/src/CurrentGitBranch.tsx
1) hide CurrentGitBranch in narrower windows
2) don't show the status text (only status badge) in narrower windows
Fixes #4181
=> fix: improve handling of narrower windows

packages/core/src/webapp/defaults.ts, plugins/plugin-client-common/web/scss/components/Table/badges.scss, plugins/plugin-client-common/web/scss/components/Table/tables.scss, plugins/plugin-client-common/web/scss/components/common/_narrow-window.scss
Fixes #4192
in support, this PR also adds media query support for auto-hiding table columns for narrower windows
Fixes #4193
=> feat: decrease default size of popup window

plugins/plugin-client-common/src/components/Sidecar/BaseSidecar.tsx, plugins/plugin-client-common/src/components/Sidecar/ComboSidecar.tsx, plugins/plugin-client-common/web/css/static/ui.css, plugins/plugin-client-common/web/scss/components/Table/tables.scss, plugins/plugin-kubectl/i18n/krew_en_US.json, plugins/plugin-kubectl/krew/package.json, plugins/plugin-kubectl/krew/src/controller/generic-table.ts, plugins/plugin-kubectl/krew/src/controller/help.ts, plugins/plugin-kubectl/krew/src/controller/info.ts, plugins/plugin-kubectl/krew/src/controller/list.ts, plugins/plugin-kubectl/krew/src/plugin.ts, plugins/plugin-kubectl/krew/tsconfig.json, plugins/plugin-kubectl/logs/package.json, plugins/plugin-kubectl/oc/package.json, plugins/plugin-kubectl/package.json, plugins/plugin-kubectl/src/controller/kubectl/exec.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/tekton/package.json, plugins/plugin-kubectl/tsconfig.json
=> feat: add krew support

plugins/plugin-client-common/src/components/StatusStripe/index.tsx, plugins/plugin-core-support/web/css/static/zoom.css
this also fixes an oversight with font zooming for other icons. for cmd- below the default size, those icons weren’t unzooming
this also cleans up zoom.css, avoiding repeated css paths by leveraging scss nesting
Fixes #4242
=> feat: StatusStripe should respond to font zooming

plugins/plugin-client-common/web/scss/components/common/_narrow-window.scss, plugins/plugin-kubectl/src/lib/view/formatTable.ts
this PR also uses this for the READY column in kubectl tables
Fixes #4232
=> fix: add support for hiding elements at higher zoom levels

plugins/plugin-client-common/web/css/static/repl.scss, plugins/plugin-client-common/web/css/static/status-stripe.css, plugins/plugin-kubectl/src/lib/tab-completion.ts, plugins/plugin-kubectl/src/test/k8s1/tab-completion.ts
1) kubectl tab completions have repeated prefix text
2) tab completions render side-by-side instead of below Input
3) popup tab completions are not visible
4) kubectl tab completions test was disabled, needs to be revived
Fixes #4281
=> fix: multiple tab completion bugs

plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
=> fix(plugins/plugin-kubectl): we shouldn't render namespace widget when the namespace is empty in kube config

plugins/plugin-ibmcloud/plugin/src/controller/list.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts
Fixes #4339
also removes superfluous debug output from kubectl fetch-file
=> fix: ibmcloud plugin list does not list unofficial plugins

plugins/plugin-kubectl/oc/src/controller/kubectl/catchall.ts, plugins/plugin-kubectl/oc/src/plugin.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/lib/util/help.ts, plugins/plugin-kubectl/src/test/k8s2/usage.ts
=> fix: multiple kubectl help/usage bugs

packages/test/src/api/keys.ts, plugins/plugin-client-common/i18n/editor_en_US.json, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/Toolbar.tsx, plugins/plugin-client-test/src/test/response/string.ts, plugins/plugin-kubectl/i18n/resources_en_US.json, plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts, plugins/plugin-kubectl/src/controller/kubectl/edit.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/lib/model/resource.ts, plugins/plugin-kubectl/src/plugin.ts, plugins/plugin-kubectl/src/test/k8s1/edit.ts
=> feat: use kui's editor for kubectl edit

plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-bash-like/web/css/static/xterm.css, plugins/plugin-client-common/src/components/Client/TabContent.tsx
this also fixes a long-standing minor issue where non-focused xterms had an unthemed cursor color; you will see this usually as a brief low-contrast cursor block when launching certain apps
Fixes #4397
=> fix: pty/client performance tweaks

packages/core/src/index.ts, packages/core/src/webapp/themes/Theme.ts, plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/KuiConfiguration.tsx, plugins/plugin-client-default/src/index.tsx, plugins/plugin-patternfly4-themes/theme.json
=> feat: allow themes to dictate Kui client properties

docs/components.md, plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/components/spi/Breadcrumb/impl/Carbon.tsx, plugins/plugin-client-common/src/components/spi/Breadcrumb/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Breadcrumb/index.tsx, plugins/plugin-client-common/src/components/spi/Breadcrumb/model.ts
Fixes #4445
this PR got jammed up in #4447 also; the fix for that is, after hitting ESCAPE, to look for the absence of "INSERT", rather than (as we did prior to this PR) looking for an empty string in the vim status line.
Fixes #4447
=> doc: improved documentation for component development

plugins/plugin-bash-like/fs/src/lib/open.ts, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Content/Editor/lib/file-types.ts
=> fix: js and ts files do not get syntax coloring

plugins/plugin-bash-like/fs/src/lib/ls.ts, plugins/plugin-client-common/src/components/Content/Table/TableHeader.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/width.ts, plugins/plugin-client-common/web/scss/components/common/_narrow-window.scss, plugins/plugin-core-support/src/lib/cmds/theme.ts
Fixes #4454
this also improves ls -l rendering in narrower windows, which are going to happen more often, with a 30/70 split
Fixes #4455
=> fix: use 30/70 split for LeftNavSidecar

plugins/plugin-client-common/src/components/Content/Eval.tsx
=> fix(plugins/plugin-client-common): Eval component throws console errors

packages/test/src/api/selectors.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/src/test/k8s2/get-all-namespaces.ts, plugins/plugin-kubectl/view-utilization/src/controller/get-pod-data.ts
=> fix(plugin-kubectl): k get pods --all-namespaces has a title with "default" as the namespace

packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecar.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx, plugins/plugin-core-support/src/test/core/basic-functionality.ts
=> fix: hitting escape on initial page load toggles open empty sidecar

plugins/plugin-kubectl/src/controller/kubectl/explain.ts
=> fix(plugins/plugin-kubectl): cache kind canonicalization lookup

plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-kubectl/src/controller/kubectl/fqn.ts, plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts, plugins/plugin-kubectl/src/test/k8s1/get-namespaces-with-watch.ts
1) do a bulk fetch rather than a bunch of individual gets to kubectl
2) LivePaginatedTable had a bug with bulk table updates, where the deferredUpdate array would have duplicates
Fixes #4494
=> fix: optimize kubectl watch load on apiserver

plugins/plugin-bash-like/src/pty/client.ts
current regex `:(\d+)?` will fail to parse urls without port (e.g. http://kui.io/...) 
also, the way of generating url may have problem. if current href is `https://kui.io/kui?query...`, after replace, the ending part will still be there, so url will be `https://kui.io/kui?query.../bash/...` instead of `https://kui.io/bash/...`. 
if server returns a path start from `/`, shouldn't it to be directly append after host?
Fix bash-like client url regex
=> fix(plugins/plugin-bash-like): fix url regex

plugins/plugin-client-common/web/css/static/sidecar-main.css
=> fix(plugins/plugin-client-common): sidecar breadcrumb font too small

packages/core/src/index.ts, packages/core/src/models/CellShould.ts, packages/core/src/models/RadioTable.ts, packages/core/src/models/entity.ts, plugins/plugin-client-common/src/components/Content/KuiContent.tsx, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx, plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx, plugins/plugin-client-common/src/components/spi/RadioTable/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/RadioTable/index.tsx, plugins/plugin-client-common/src/components/spi/RadioTable/model.ts, plugins/plugin-client-common/web/scss/components/RadioTable/PatternFly.scss, plugins/plugin-client-common/web/scss/components/StructuredList/Carbon.scss, plugins/plugin-client-test/src/test/response/theme.ts, plugins/plugin-core-support/src/lib/cmds/theme.ts, plugins/plugin-core-support/src/test/core-support/theme.ts
Fixes #4507
BREAKING CHANGE: any tests that depend on the old structure of the themes table will need to be updated.
Carbon provider:
=> feat: RadioTable and port of the themes table to use it

plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts, plugins/plugin-kubectl/logs/src/index.ts, plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts, plugins/plugin-kubectl/src/lib/view/modes/containers.ts
Also delegates oc logs to kubectl
Fixes #4498
=> fix: clicking on container name in details sidecar should add -c to logs command

plugins/plugin-kubectl/src/lib/util/help.ts
=> fix(plugins/plugin-kubectl): kubectl describe -h has old bold text

plugins/plugin-client-alternate/src/index.tsx, plugins/plugin-client-alternate/web/scss/components/TopTabStripe/Carbon.scss
Fixes #4608
The screenshots below captured how the alternate TopTabStripe looks: 
Carbon Gray 10:
Carbon Gray 90:
=> chore: add alternative Top Tab styles in plugin-client-alternate

packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/Toolbar.tsx, plugins/plugin-client-common/src/components/Content/Table/kui2carbon.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts, plugins/plugin-kubectl/src/test/k8s2/api-resources.ts
=> fix: kubectl api-resources has duplicate rows and odd pagination behavior

plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/src/lib/view/modes/events.ts, plugins/plugin-kubectl/src/test/k8s2/events.ts
Also refines events table to show REASON and MESSAGE columns only when sidecar open
Fixes #4604
The screenshot below captures how events table looks when sidecar open. The two tables are issued by 1. `show events` button, 2. `k get events` command.
=> fix(plugins/plugin-kubectl): showEvents button should issue a non-wide table

packages/core/src/session/init.ts, plugins/plugin-bash-like/web/css/static/xterm.css, plugins/plugin-carbon-themes/web/scss/kui--alternate.scss, plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/KuiConfiguration.tsx, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/web/css/static/Popup.scss, plugins/plugin-client-common/web/css/static/repl.scss, plugins/plugin-client-default/src/index.tsx, plugins/plugin-patternfly4-themes/web/scss/common.scss
Fixes #4596
Notes on Session Initialization: to provide custom views for
session initialization (only relevant for browser-based hosted
Kui), you can instantiate <Kui/> with these properties (defined in
KuiConfiguration):
- `loading={<div className="kui--hero-text">Hold on...</div>}`
- `reinit={<div className="kui--hero-text">Connection broken...</div>}`
- `loadingError={err => <div className="kui--hero-text">{err.toString()}</div>}`
Here, we have provided some rough examples of uses of the three. You would then instantiate via: 
```react
<Kui loading=... etc./>
```
=> feat: allow <Kui/> users to provide custom views for session init

plugins/plugin-client-common/src/components/Client/KuiConfiguration.tsx, plugins/plugin-client-common/src/components/Client/props/Branding.ts, plugins/plugin-client-common/src/components/Client/props/Input.ts, plugins/plugin-client-common/src/components/Client/props/Session.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
Fixes #4653
This PR also exercises these features plugins/plugin-client-alternate/src/index.tsx
You can try it via 
```sh
./bin/switch-client alternate
npm run watch
```
=> feat: add support for <Kui noPromptContext/> and <Kui prompt=">"/>

plugins/plugin-kubectl/src/controller/kubectl/edit.ts
=> fix(plugins/plugin-kubectl): k edit -h does not open in sidecar

plugins/plugin-kubectl/src/lib/model/resource.ts, plugins/plugin-kubectl/src/lib/view/modes/pods.ts
various isXXX checks do not confirm that the resource is the result of a `k get`
Fixes #4703
=> fix(plugins/plugin-kubectl): k edit deploy has mysterious Pod tab

package-lock.json, packages/core/src/core/jobs/job.ts, plugins/plugin-bash-like/package.json, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-kubectl/i18n/exec_en_US.json, plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts, plugins/plugin-kubectl/src/controller/kubectl/exec.ts, plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx, plugins/plugin-kubectl/src/lib/view/modes/logs.tsx, plugins/plugin-kubectl/src/lib/view/modes/yaml.ts, plugins/plugin-kubectl/src/non-headless-preload.ts, plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts
covers "exec into pod" use case
Fixes #4639
=> feat(plugins/plugin-kubectl): Terminal tab for Pod kubernetes resources

plugins/plugin-client-alternate/src/CustomInput.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/index.ts
=> feat: allow subclasses of InputProvider to specify their own State

packages/core/src/webapp/views/toolbar-text.ts, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/Toolbar.tsx, plugins/plugin-kubectl/i18n/resources_en_US.json, plugins/plugin-kubectl/src/controller/kubectl/edit.ts, plugins/plugin-kubectl/src/test/k8s1/edit.ts
=> fix: kubectl edit in sidecar doesn't show success message when a resource is applied

packages/core/src/models/mmr/content-types.ts, packages/core/src/models/mmr/types.ts, packages/core/src/repl/exec.ts, packages/test/src/api/common.ts, plugins/plugin-client-common/src/components/Content/KuiContent.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx, plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c-via-table.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-dash-f-via-table.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-dash-f.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-multi.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-via-table.ts, plugins/plugin-kubectl/logs/src/test/logs/logs.ts, plugins/plugin-kubectl/src/controller/kubectl/flags.ts, plugins/plugin-kubectl/src/controller/kubectl/get.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/lib/model/resource.ts, plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx, plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx, plugins/plugin-kubectl/src/lib/view/modes/last-applied.ts, plugins/plugin-kubectl/src/lib/view/modes/logs.tsx, plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-vi.ts, plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-via-table.ts, plugins/plugin-kubectl/src/test/k8s2/kubectl-exec.ts, plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts
this adds plumbing to allow a command respond to pass through an argv
Fixes #4762
=> feat: target kubectl logs and kubectl exec to Logs and Terminal tabs

plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts, plugins/plugin-kubectl/logs/src/test/logs/logs-via-table.ts, plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx, plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts, plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts, plugins/plugin-kubectl/tests/lib/k8s/utils.js
=> fix: the Logs/Terminal retry button should be visible on any exit code

packages/core/src/index.ts, packages/core/src/models/mmr/content-types.ts, packages/test/src/api/selectors.ts, packages/test/src/api/sidecar-expect.ts, plugins/plugin-client-common/i18n/editor_en_US.json, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarContainer.tsx, plugins/plugin-client-common/src/components/spi/Alert/impl/Carbon.tsx, plugins/plugin-client-common/src/components/spi/Alert/index.tsx, plugins/plugin-client-common/src/components/spi/Alert/model.ts, plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss, plugins/plugin-kubectl/src/controller/kubectl/edit.ts, plugins/plugin-kubectl/src/test/k8s1/edit.ts
=> fix: sidecar toolbar can't due justice to longer error messages

plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts, plugins/plugin-kubectl/src/test/k8s1/namespace.ts
=> fix: avoid using kui-custom command for switching kubectl namespace

packages/core/src/index.ts, packages/core/src/models/editable.ts, packages/core/src/models/mmr/content-types.ts, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Content/Eval.tsx, plugins/plugin-kubectl/src/controller/kubectl/edit.ts, plugins/plugin-kubectl/src/test/k8s1/edit.ts
=> fix: summary tab is not read-only for kubectl edit command

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-kubectl/src/test/k8s2/usage.ts
=> fix: pexecs serviced by now-removed splits fail

packages/core/src/core/jobs/watchable.ts, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx, plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx, plugins/plugin-client-common/src/components/Content/Table/kui2carbon.ts, plugins/plugin-client-common/web/css/static/ui.css, plugins/plugin-client-common/web/scss/components/Table/badges.scss, plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
in support of this fix, this PR allows push providers to specify whether the `update()` call should be reflected as a change in the UI. this allows the kubectl push provider to special case Events, which, though "yellow" or "red", should not be blinky, because they'll be yellow or red forever.
Fixes #4869
=> fix: don't blink yellow forever for kubectl events

plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx, plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
=> fix: empty watch tables/grids should show 'No resources'

plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
=> fix(plugins/plugin-client-common): regression: non-empty repl output has 'ok' at the end

plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
=> fix(plugins/plugin-client-common): `ok` string appears at the end of MixResponse

plugins/plugin-client-common/src/components/Content/Markdown.tsx, plugins/plugin-kubectl/src/lib/util/help.ts
and any preformatted-as-markdown tables
Fixes #5080
=> fix: kubectl help misformats helm help tables

packages/core/src/core/events.ts, packages/core/src/index.ts, packages/core/src/models/tab-state.ts, packages/core/src/webapp/tab.ts, plugins/plugin-client-common/src/components/Client/TabContainer.tsx, plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
1) we have only a /tab/switch/request (i.e. the initiation, not the completion) of a tab switch; having a channel for the completion might be possible, but is more tricky
2) the tab-state save/restore logic sometimes smashes in undefined values, which can mess up the KUBECONFIG env
3) kube's CurrentContext and CurrentNamespace widgets were performing two queries on tab startup, when only one (each) is needed
Fixes #5101
Closes #5103 
Closes #5105
=> fix: multiple issues with tab switching versus status stripe widgets

package.json, tools/travis/proxy.sh
=> fix: npm run proxy failed if the project is not named as 'kui'

plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx, plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx, plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts
regression from the switch to quiet execs for the onSelect handlers
Fixes #5144
this also fixes a react warning message that appears in the console from the title support added to RadioTables
=> fix(plugins/plugin-kubectl): CurrentNamespace/Context widgets not live

plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts, plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts, plugins/plugin-kubectl/src/test/k8s2/events-in-table.ts
=> fix(plugins/plugin-kubectl): event footer watching should also support named resources

plugins/plugin-client-common/src/components/spi/DropDown/impl/Carbon.tsx
works around bug in carbon-components-react's OverflowMenu
Fixes #5170
=> fix(plugins/plugin-client-common): Terminal focus changes unexpectedly

plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
=> fix(plugins/plugin-kubectl): drilldown command of resources in watch --all-namespace table doesn't have '-o yaml'

plugins/plugin-kubectl/oc/src/controller/oc/get/projects.ts
=> fix(plugins/plugin-kubectl): `oc get namespaces` doesn't produce a RadioTable

plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
1) blank rows when in minisplit
2) too narrow when not
Fixes #5230
=> fix(plugins/plugin-kubectl): kubernetes contexts table renders poorly

packages/core/src/index.ts, packages/core/src/models/command.ts, packages/core/src/models/entity.ts, packages/core/src/models/history.ts, packages/core/src/models/mmr/is.ts, packages/core/src/repl/events.ts, packages/core/src/repl/exec.ts, packages/core/src/webapp/cancel.ts, packages/test/src/api/cli.ts, packages/test/src/api/repl-expect.ts, packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-core-support/src/test/core-support2/history-splits.ts, plugins/plugin-core-support/src/test/core-support2/split-helpers.ts, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
1) We want to have a consistent history presented for terminals in a given position; i.e. the Nth split in the Mth tab should always present the same command history, across sessions
2) Users may close splits and close tabs. If they close the last split in a tab, or the last tab, the first constraint is easy to maintain, because there is no reordering of the splits or tabs. If, however, they close some other split or tab other than the last, the first invariant must be reestablished
For example: start with 1 split, create a second split. Exit the *first* split. Now the previously second split is the apparent first (and only) split. Next create a new second split. Now the previously second split is the first split, and the new split is the second split. Which command history should the …
=> feat: command history should be tab-specific

package-lock.json, plugins/plugin-client-common/package.json, plugins/plugin-kubectl/package.json, plugins/plugin-patternfly4-themes/package.json
also removes an unused dependence from plugin-kubectl
=> chore: bump patternfly dependence to 4.32.1

packages/core/src/core/repl.ts, packages/core/src/models/repl.ts, packages/core/src/repl/exec.ts, packages/core/src/repl/types.ts, plugins/plugin-bash-like/fs/src/lib/ls.ts
This PR takes the "semicolon invoke" logic, which previously was hacked into a few key spots (e.g. the `ls` command handler), and hoists it directly into the REPL. Thus, all command line submissions will now benefit from the same logic.
Fixes #5260
=> fix(packages/core): repl exec should invoke commands separated by semicolon

plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
This PR auto-gridify tables with more than 20 rows
Fixes #5305
=> feat: auto gridify large table

plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
=> fix(plugins/plugin-kubectl): leftover debug printfs in table-watch

plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts, plugins/plugin-bash-like/fs/src/vfs/delegates.ts, plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-s3/src/test/core/s3.ts, plugins/plugin-s3/src/vfs/forwarder.ts, plugins/plugin-s3/src/vfs/index.ts
=> feat: add support for copying out of remote storage

plugins/plugin-client-common/web/css/static/repl.scss
this PR only fixes Processing and Completed blocks. we will still have a problem with line wrapping of active inputs
Fixes #5338
=> fix(plugins/plugin-client-common): long input lines should line wrap

plugins/plugin-bash-like/fs/src/lib/ls.ts
For a typical ls command, the following screenshots show the effect of measurement 
Before the change:
After the change:
Fixes #5353
=> fix(plugins/plugin-bash-like): ls should measure gridTemplateColumns more intelligently

packages/core/src/models/command.ts, packages/core/src/repl/events.ts, packages/core/src/repl/exec.ts, packages/test/src/api/selectors.ts, plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/spi/Tag/impl/Carbon.tsx, plugins/plugin-client-common/web/css/static/repl.scss, plugins/plugin-client-test/src/lib/cmds/say-hello.ts, plugins/plugin-client-test/src/test/response/string.ts, plugins/plugin-ibmcloud/ce/src/bind.ts, plugins/plugin-ibmcloud/ce/src/controller/generic/option.ts
To register a command as experimental, users can add the command option `{ isExperimental: true }` in command registration.
For example, the following plugin.ts will give the command-line: `test string`  an experimental tag:
```typescript
import { Registrar } from '@kui-shell/core'
export default function(registrar: Registrar) {
registrar.listen('/test/string', () => 'hello world', { isExperimental: true })
}
```
Also updated ibmcloud ce commands to opt in this option
Fixes #5282
=> feat: allow command registrations to express their experimental nature

packages/core/src/core/events.ts, packages/core/src/index.ts, packages/core/src/main/menu.ts, packages/core/src/main/open.ts, packages/core/src/main/spawn-electron.ts, packages/core/src/models/history.ts, packages/core/src/repl/events.ts, packages/core/src/repl/exec.ts, plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/TabContainer.tsx, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-core-support/src/plugin.ts, plugins/plugin-core-support/src/preload.ts, plugins/plugin-core-support/src/test/core-support/replay.ts
Limitations:
1) does not handle multiple windows
2) does not handle multiple tabs
3) inconsistency between clearing of terminal and replay; clearing will not close the sidecar, but after a replay, the sidecar won't be open
Fixes #5280
Closes #5281
=> feat: initial/minimal snapshot/replay support

packages/core/src/models/command.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/controller/card.ts, plugins/plugin-client-common/src/controller/commentary.ts, plugins/plugin-client-common/src/plugin.ts, plugins/plugin-core-support/src/test/core-support/card.ts, plugins/plugin-core-support/src/test/core-support/commentary.ts, plugins/plugin-core-support/tests/data/comment.md
This PR introduces the command: commentary that add the capability of commenting in the REPL
Usage: `commentary -f file.md`
E.g. `commentary README.md`
Fixes #5428
=> feat: commentary command to add comments to REPL

packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx, plugins/plugin-client-common/src/controller/commentary.ts, plugins/plugin-core-support/src/test/core-support/card.ts, plugins/plugin-core-support/src/test/core-support/commentary.ts
this also fixes a few minor issues hidden from users:
- the test api Selectors had TERMINAl lowercase l at the end
- assert.ok which should be two assert.strictEqual in the commentary test
- in the usage for commentary, we had two entries, for -f and --file. the usage model allows for a single entry with an alias field
Fixes #5434
=> fix(plugins/plugin-client-common): add support for titles in commentary

plugins/plugin-client-common/src/components/spi/Icons/index.tsx
=> fix(plugins/plugin-client-common): defer loading of both icon sets

packages/core/src/core/events.ts, packages/core/src/index.ts, packages/core/src/repl/events.ts, plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx, plugins/plugin-client-common/src/index.ts, plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-electron-components/src/plugin.ts, plugins/plugin-kubectl/tutorials/create-jobs.json, plugins/plugin-kubectl/tutorials/list-resources.json
Fixes #5490
See the issue for a screenshot. See packages/core/src/core/events.ts for the StatusStripe related events, and replay.ts for an example controller that uses this control channel.
=> feat: allow controllers to control the color of the status stripe

packages/test/src/api/selectors.ts, plugins/plugin-bash-like/src/test/bash-like/rerun.ts, plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
This PR adds two new dropdown items to the Repl Block: Copy and Rerun. Copy button allows users to copy the command-line. Rerun button allows users to rerun the command. 
Fixes #4570
=> feat(plugins/plugin-client-common): allow easier rerunning of command from terminal

.gitignore, packages/core/src/core/events.ts, packages/core/src/index.ts, plugins/plugin-bash-like/fs/src/vfs/local.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-core-support/src/test/core-support/replay.ts
This PR adds a --freshen option to the replay command, which regenerates the notebook using the current version of Kui
Fixes #5522
=> feat: snapshot freshening

plugins/plugin-bash-like/web/scss/xterm.scss, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
=> fix: pty output has different indentation than kui command output

packages/core/src/index.ts, packages/core/src/models/TabLayoutModificationResponse.ts, packages/core/src/models/entity.ts, plugins/plugin-client-common/notebooks/welcome.json, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/controller/split.ts, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-kubectl/src/non-headless-preload.ts
This PR introduces the TabLayoutModificationResponse type, which allows controllers to specify the intent to create a new split (as opposed to how it worked prior to this PR: the split controller talked directly to the view, and its response was only a signifier of result of the split, not the desire to create a split)
Fixes #5564
=> fix: improve the replayability of terminal splitting

packages/core/src/models/CommentaryResponse.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/controller/split.ts, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-core-support/src/lib/cmds/tab-management.ts, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
Fixes #5571
this also fixes a related problem with tab close, which does not support fully closing all splits in a tab
Fixes #5572
=> fix: replay --freshen does not support multi-split notebooks

plugins/plugin-client-common/src/components/Content/Commentary.tsx, plugins/plugin-core-support/i18n/resources_en_US.json, plugins/plugin-core-support/src/lib/cmds/tab-management.ts
=> fix: tab new command should respond with ElsewhereCommentary response

plugins/plugin-client-common/notebooks/settings.json, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-kubectl/src/test/k8s1/replay.ts
This PR introduces `snapshot --exec` and `snapshot -x` options to auto re-execute commands when replaying the snapshot.
Fix #5622
=> feat: add a prefer-re-execution option to snapshot

.travis.yml, packages/core/src/core/events.ts, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-core-support/src/test/core-support/replay.ts, plugins/plugin-core-support/src/test/core-support2/history.ts, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts, plugins/plugin-git/src/CurrentGitBranch.tsx, plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx, plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
=> fix: avoid excessive status stripe overheads when replaying Notebooks

plugins/plugin-client-common/src/components/Client/TabContainer.tsx, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/visible.ts
1) avoid spurious scrolling: when clicking on a table entry while the active prompt is not in view
2) ibid: when switching tabs while the active prompt is not in view
this PR removes the old hackFocus() hack in TabContainer, which did ugly querySelectors
Fixes #5615
=> fix(plugins/plugin-client-common): improved focus behavior of terminals

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
=> fix(plugins/plugin-client-common): don't show `isTabLayoutModificationResponse` and PresentedElseWhere response in MiniSplit

plugins/plugin-client-alternate/web/scss/CustomInput.scss, plugins/plugin-client-common/src/components/Content/Table/Bar.tsx, plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/web/css/static/InputStripe.scss, plugins/plugin-client-common/web/scss/components/Terminal/Block.scss, plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
This PR may break some external tests. It introduces an `<li>` around each repl-block.
Fixes #5717
=> User should be able to tab navigate through blocks

plugins/plugin-bash-like/fs/src/lib/ls.ts, plugins/plugin-client-common/notebooks/welcome.json
=> fix: don't show the `open` command for clicking files in `ls` table

plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Namespace.ts, plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
This will speed up showing Namespaces in the sidecar, and also allow for offline viewing of Namespaces in Notebooks
Fixes #5790
=> feat(plugins/plugin-kubectl): Namespace Summary impl

docs/example/AnimalApp/tsconfig.json
The tsconfig.json of the example application AnimalApp was wrong
```
"references": { "path": "./plugins/plugin-example", "path": "./plugins/plugin-client-default" }
```
fixed as:
```
"references": [
{ "path": "./plugins/plugin-example" },
{ "path": "./plugins/plugin-client-default" }
]
```
=> Fix references in tsconfig.json of example application AnimalApp

packages/core/src/core/events.ts, packages/core/src/index.ts, packages/core/src/main/menu.ts, packages/core/src/main/open.ts, packages/core/src/main/spawn-electron.ts, packages/core/src/repl/events.ts, plugins/plugin-client-common/notebooks/settings.json, plugins/plugin-client-common/notebooks/welcome.json, plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx, plugins/plugin-client-common/src/components/Client/TabContainer.tsx, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Client/TabModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ClipboardTransfer.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts, plugins/plugin-client-default/src/index.tsx, plugins/plugin-client-test/notebooks/ls.json, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-core-support/src/lib/cmds/tab-management.ts, plugins/plugin-core-support/src/notebooks/vfs/index.ts, plugins/plugin-core-support/src/preload.ts, plugins/plugin-core-support/src/test/core-support/replay.ts, plugins/plugin-electron-components/src/plugin.ts, plugins/plugin-iter8/notebooks/welcome.json, plugins/plugin-kubectl/notebooks/create-jobs.json, plugins/plugin-kubectl/notebooks/list-resources.json, plugins/plugin-kubectl/src/test/k8s3/replay.ts
BREAKING CHANGE
Fixes #5750
Edits from @starpit: 
- Note that this PR will temporarily disable snapshot and replay of clicks. This feature will be restored shortly.
- This introduces the final "v1" schema for Notebooks. Notebooks saved prior to the merging of this PR will no longer work.
=> BREAKING CHANGE: introduce final v1 serialized form of notebooks

packages/core/src/main/menu.ts, plugins/plugin-client-common/notebooks/settings.json
This also adds an OS menu for the settings notebook
Fixes #5870
=> fix: Notebook title "Kui Setting" should be "Kui Settings"

plugins/plugin-client-common/web/scss/components/CodeSnippet/Carbon.scss, plugins/plugin-client-common/web/scss/components/CodeSnippet/PatternFly.scss
=> fix(plugins/plugin-client-common): markdown code has incorrect color in a split with inverse color

plugins/plugin-client-common/src/components/Content/Commentary.tsx, plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
=> fix(plugins/plugin-client-common): double clicking on Commentary in minisplit often has the editor completely off screen

plugins/plugin-client-notebook/src/index.tsx
=> fix(plugins/plugin-client-notebook): notebook client's version widget has a hard-wired version

packages/core/src/repl/events.ts, plugins/plugin-client-common/notebooks/welcome.json, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts, plugins/plugin-s3/notebooks/welcome.json
Add preferReExecute to Notebook metadata
Fixes #5954
=> fix: preferReExecute is lost when re-saving a notebook

plugins/plugin-client-common/notebooks/settings.json, plugins/plugin-client-common/notebooks/welcome.json, plugins/plugin-core-support/src/notebooks/vfs/index.ts, plugins/plugin-iter8/notebooks/welcome.json, plugins/plugin-s3/notebooks/parallelization.json, plugins/plugin-s3/notebooks/using-s3.json, plugins/plugin-s3/notebooks/welcome.json
In this PR, I modified the description of each notebook so they can be grouped together in the `ls -l /kui/**/*.json` table. By preserving the name field, we can make the tab title clean. For example, iter8 welcome notebook can still have the title `Welcome to Iter8`, instead of `Iter8 - Welcome to Iter8`.
Fixes #5977
=> fix(plugins/plugin-client-common): group the notebooks together in the ls -l table

plugins/plugin-client-common/web/scss/components/Terminal/Block.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Fixes #5982
Screenshots of how the input looks in different scenario:
=> fix: tweak the input background and border to enhance the readability of notebooks

plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss, plugins/plugin-client-common/web/scss/components/Terminal/MiniSplit.scss, plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
=> fix(plugins/plugin-client-common): minisplit has leftover css border rule

plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
Hovering the first block:
Hovering the 4th block:
Fixes #5979
=> fix(plugins/plugin-client-common): hovering over error block turns red to blue

packages/webpack/webpack.config.js
=> fix(packages/webpack): webpack builds may have fonts in the wrong place

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
=> fix(plugins/plugin-client-common): If a command is issued in a mini split, the next block (in the mini split) is not focused

packages/core/src/index.ts, packages/core/src/models/CommentaryResponse.ts, packages/core/src/models/TabLayoutModificationResponse.ts, packages/core/src/models/entity.ts, packages/core/src/webapp/tab.ts, packages/test/src/api/repl-expect.ts, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Client/TopTabStripe/SplitTerminalButton.tsx, plugins/plugin-client-common/src/components/Content/Commentary.tsx, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/controller/split.ts, plugins/plugin-client-common/web/scss/components/Terminal/Block.scss, plugins/plugin-core-support/src/lib/cmds/tab-management.ts, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts, plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
This PR also:
1. cleans up some unneeded code around this issue, too.
2. removes ElsewhereCommentaryResponse
2. changes TabLayoutModificationResponse to use MarkdownResponse
Fixes #6001
Closes #6068
=> fix: don't show "Created a split" when clicking on the New Split button

package.json, packages/builder/bin/hackCarbon.sh, packages/builder/package.json, tools/hackCarbon.sh
=> chore: move carbon tab scrolling workaround into packages/builder

packages/core/src/main/spawn-electron.ts
This prevents overriding our index.html in an unrecoverable way.
Fixes #2881
=> fix(packages/core): intercept window.location for electron app

packages/core/src/index.ts, packages/core/src/models/TreeResponse.ts, packages/core/src/models/mmr/content-types.ts, packages/test/src/api/mmr.ts, packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Content/KuiContent.tsx, plugins/plugin-client-common/src/components/Content/TreeView.tsx, plugins/plugin-client-common/web/scss/components/TreeView/PatternFly.scss, plugins/plugin-client-common/web/scss/components/TreeView/_mixins.scss, plugins/plugin-client-test/src/lib/cmds/content/tree.ts, plugins/plugin-client-test/src/lib/cmds/mmr-mode.ts, plugins/plugin-client-test/src/test/api1/mmr-mode.ts
=> feat: add unit support of TreeResponse as one of the contents in MultiModalResponse

plugins/plugin-carbon-themes/web/scss/charts.scss, plugins/plugin-client-common/web/css/static/ui.css, plugins/plugin-client-common/web/scss/components/Chart/_colors.scss
=> fix: default chart colors should not use blue-red diverging spectrum

plugins/plugin-client-common/web/scss/components/Table/Lightweight.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss, plugins/plugin-core-themes/web/scss/light.scss
=> fix: block timestamp in Light theme/lightweight ui has low contrast

plugins/plugin-client-common/src/components/Client/Popup.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-default/src/index.tsx
=> fix: keyboard history navigation does not work in Popup clients

packages/core/src/index.ts, packages/core/src/models/mmr/content-types.ts, packages/test/src/api/mmr.ts, plugins/plugin-client-common/src/components/Content/Editor/DiffEditor.tsx, plugins/plugin-client-common/src/components/Content/KuiContent.tsx, plugins/plugin-client-test/src/lib/cmds/mmr-mode.ts, plugins/plugin-client-test/src/test/api1/mmr-mode.ts, plugins/plugin-git/i18n/resources_en_US.json, plugins/plugin-git/src/controller/git/diff.ts, plugins/plugin-git/src/plugin.ts
=> feat: clicking changed files in the `git status widget` should show git diff` result in a DiffEditor

packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Client/StatusStripe/DropdownWidget.tsx, plugins/plugin-client-common/src/components/spi/DropDown/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/DropDown/index.tsx, plugins/plugin-client-common/src/components/spi/DropDown/model.ts, plugins/plugin-client-common/src/index.ts, plugins/plugin-client-common/web/scss/components/DropDown/Carbon.scss, plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss, plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx, plugins/plugin-kubectl/src/test/k8s3/namespace.ts
This PR refines the Dropdown widget API a small bit.
Fixes #6351
=> feat: use new Dropdown status stripe for CurrentNamespace widget

plugins/plugin-client-common/src/components/Content/Editor/DiffEditor.tsx, plugins/plugin-client-common/web/css/static/sidecar.scss, plugins/plugin-client-common/web/scss/components/Sidecar/Nested.scss
Fixed by setting sidecar to always be flex:1
Fixes #6365
=> fix(plugins/plugin-client-common): DiffEditor does not respond to resize events

packages/core/src/core/events.ts, plugins/plugin-client-common/src/components/Content/Editor/DiffEditor.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Fixes #6366
render inline when there's split
render back to original when there isn't split
=> fix: DIffEditor should render inline when in terminal split

packages/core/src/index.ts, packages/core/src/main/headless-pretty-print.ts, packages/core/src/models/TreeResponse.ts, packages/core/src/models/entity.ts, packages/core/src/models/mmr/types.ts, plugins/plugin-bash-like/src/test/bash-like/watch-ls.ts, plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/src/components/Content/KuiContent.tsx, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarContainer.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/spi/Tree/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Tree/model.ts, plugins/plugin-core-support/src/lib/cmds/watch.ts, plugins/plugin-core-support/src/plugin.ts, plugins/plugin-kubectl/src/controller/kubectl/edit.ts, plugins/plugin-kubectl/src/controller/kubectl/get.ts, plugins/plugin-kubectl/src/lib/util/tree.ts, plugins/plugin-kubectl/src/test/k8s4/edit.ts
Fixes #6379
This PR removes the toolbarText hacks in TreeResponse in favor of a general solution for MMR modes providing a toolbarTexte
=> feat: Kui implementation of `watch`

packages/core/src/models/command.ts, packages/core/src/repl/exec.ts, plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx, plugins/plugin-client-test/src/lib/cmds/semicolon.ts, plugins/plugin-client-test/src/plugin.ts, plugins/plugin-client-test/src/test/api1/semicolon.ts, plugins/plugin-s3/src/ssc/index.ts
Fixes #6396
the registration option is `semiExpand: false`, e.g.
```typescript
import { Registrar } from '@kui-shell/core'
export default function(registrar: Registrar) {
registrar.listen('/my/command', args => 'hi', { semiExpand: false })
}
```
=> feat: Allow command registrants to specify no semicolon expansion

packages/builder/tsconfig-base.json
On my laptop, this reduces a full `npm run compile` from over 120 seconds, down to around 45 seconds. From what I understand in the article referenced by the associated issue, this will only affect us in a very few places: we have I think 2 or 3 test utility files that are written in javascript, with a side `.d.ts` typing file. With skipLibcheck, typescript will not check those typings files. These only affect a small slice of test code. There will be no direct impact to user-facing code quality.
Fixes #6491
=> chore: add --skipLibCheck to our typescript compiler options

packages/builder/dist/electron/build.sh
=> fix(packages/builder): electron builder uses the top-level package.json version instead of client version when building electron dists

packages/test/src/api/table.ts, plugins/plugin-bash-like/fs/src/lib/glob.ts, plugins/plugin-client-common/web/scss/components/Table/badges.scss, plugins/plugin-ibmcloud/plugin/src/controller/available.ts, plugins/plugin-kubectl-flow-views/tekton/src/lib/read.ts, plugins/plugin-kubectl/src/controller/client/direct/404.ts, plugins/plugin-kubectl/src/controller/client/direct/create.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/unify.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/controller/fetch-file.ts, plugins/plugin-kubectl/src/controller/kubectl/source.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts, plugins/plugin-kubectl/src/lib/model/traffic-light.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts, plugins/plugin-kubectl/src/test/k8s3/source-ref.ts
This PR updates the duration over which red badges flash from 6 cycles down to 3.
This PR also works around an issue in globby. https://github.com/sindresorhus/globby/issues/166
Fixes #6504
=> feat: Expand kubectl direct watching to support heterogeneous use cases

packages/test/src/api/selectors.ts, plugins/plugin-kubectl/oc/src/controller/oc/get/projects.ts, plugins/plugin-kubectl/src/controller/kubectl/contexts.ts, plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/test/k8s/contexts.ts, plugins/plugin-kubectl/src/test/k8s/namespace.ts
BREAKING CHANGE: the `contexts` and `kubectl get ns` commands will no longer return radio tables after this PR. Instead, users are encouraged to use the selection UI in the bottom status stripe:
Fixes #6517
=> fix(plugins/plugin-kubectl): use PaginatedTable instead of RadioTable for `contexts` and `get namespaces` commands

plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts, plugins/plugin-kubectl/tests/data/k8s/many-pods-with-duplicates.yaml, plugins/plugin-kubectl/tests/data/k8s/many-pods.yaml
=> fix(plugins/plugin-kubectl): kubectl direct status watcher can get stuck

packages/core/src/models/entity.ts, packages/core/src/webapp/models/table.ts, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/kui2carbon.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/unify.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/tests/data/k8s/application/guestbook/frontend-deployment.yaml, plugins/plugin-kubectl/tests/data/k8s/application/guestbook/redis-master-deployment.yaml, plugins/plugin-kubectl/tests/data/k8s/application/guestbook/redis-slave-deployment.yaml
This PR requires adding an optional metadata attribute to the core Table.Row model
Fixes #6591
=> feat: revive "app" and "tier" columns from deprecated kubectl tree view

packages/core/src/main/headless.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts
This PR also updates the uncaughtException handler so as not the exit.
Fixes #6616
=> fix: kubectl direct streaming fails to register a stream.on('error')

plugins/plugin-kubectl/src/controller/client/direct/get.ts, plugins/plugin-kubectl/src/controller/client/direct/group.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts
Fixes #6599 
The movie here shows how this PR watch resource correctly:
https://user-images.githubusercontent.com/21212160/104780012-179a8400-574e-11eb-80de-36fa0d7d6a2c.mov
=> fix(plugins/plugin-kubectl): kubectl direct watcher does not properly filter events and resource updates

packages/core/src/webapp/models/table.ts, plugins/plugin-bash-like/fs/src/lib/ls.ts, plugins/plugin-client-common/src/components/Content/Table/Grid.tsx, plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
This PR introduces the drilldownTo attribute of Table.
Fixes #6565
=> fix: ls clicks that do another ls should not open a split

plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-kubectl/src/controller/client/direct/get.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/lib/model/resource.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/src/test/k8s2/get-dashf.ts
And uses kubernetes `name_kind_ns` as the rowKey of a Table Row
Fixes #6588
=> fix: kubectl get -f --watch doesn't watch

packages/test/src/api/repl-expect.ts, packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/web/scss/components/Table/tables.scss, plugins/plugin-kubectl/src/controller/client/direct/get.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/test/k8s2/events-in-table.ts
=> fix(plugins/plugin-kubectl): events watching returns an empty table with just a streaming events footer

plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/src/test/k8s2/aaaa-get-dashf.ts
This PR also changes`toKuiTable` to get `namespace breadcrumb` from `PartialObject`. The PR removes `the namespace breadcrumb` for `heterogeneous get`, since a watch pusher currently doesn't support updating the header. If the heterogeneous watch involves resources with different scopes, the header might be wrong.
Fixes #6642
=> fix(plugins/plugin-kubectl): direct/watch may update rows in a wrong order

plugins/plugin-kubectl/src/controller/kubectl/get.ts
=> fix(plugins/plugin-kubectl): `k get all` with direct/get doesn't fail back to the old impl of get

plugins/plugin-electron-components/src/components/UpdateChecker.tsx
=> fix(plugins/plugin-electron-components): UpdateChecker should ignore prereleases

plugins/plugin-kubectl/src/controller/kubectl/get.ts
=> Revert "fix(plugins/plugin-kubectl): `k get all` with direct/get doesn't fail back to the old impl of get"

plugins/plugin-kubectl/src/controller/client/direct/unify.ts, plugins/plugin-kubectl/src/controller/kubectl/create.ts, plugins/plugin-kubectl/src/controller/kubectl/source.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts, plugins/plugin-kubectl/src/test/k8s3/source-ref.ts
Fixes #6662
This PR also fixes a minor issue with `-k` sourceRefs. The editor did not syntax color `-k` sourceRefs (though it was properly coloring `-f` sourceRefs)
=> fix(plugins/plugin-kubectl): kubectl sourceRef fetching is expensive

package-lock.json, packages/react/package.json, plugins/plugin-client-common/package.json
We unfortunately still need to include the `carbon-icons` dependence, as `carbon-components-react1 has an unstated dependence on this package. We won't be able to remove it until we remove carbon entirely.
Fixes #6683
=> chore: remove carbon components icon package.json deps

plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx, plugins/plugin-client-common/src/components/spi/Button/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Button/model.ts, plugins/plugin-client-common/web/css/static/TabCompletion.scss, plugins/plugin-core-support/tests/lib/core-support/tab-completion-util.js
=> chore: TabCompletion component has hard-coded use of Carbon Button

plugins/plugin-kubectl/src/controller/kubectl/explain.ts, plugins/plugin-kubectl/src/controller/kubectl/get.ts, plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
=> fix(plugins/plugin-kubectl): get without kind doesn't fail back to the old get impl

plugins/plugin-client-common/web/scss/components/Navigation/Patternfly.scss, plugins/plugin-client-common/web/scss/components/Sidecar/_mixins.scss
=> fix(plugins/plugin-client-common): width-constrained NavResponse UI should spend more space on content

plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss, plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
=> fix(plugins/plugin-client-common): Dropdown hover effect in PatternFly4 Dark has no contrast

plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx, plugins/plugin-kubectl/src/controller/client/direct/columns.ts, plugins/plugin-kubectl/src/controller/client/direct/get.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/src/test/k8s2/events-in-table.ts
=> fix(plugins/plugin-kubectl): event watcher doesn't render well in minisplit

plugins/plugin-carbon-themes/web/scss/colors.scss, plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
PF4 Light theme:
Carbon Gray 90:
Fixes #6804
=> fix: In PatternFly4 Light and Carbon Gray90 themes, new tab/new split buttons lack hover effect

plugins/plugin-client-common/src/components/Content/Table/ErrorCell.tsx, plugins/plugin-core-themes/web/scss/Mercury.scss, plugins/plugin-core-themes/web/scss/atelier-seaside.scss, plugins/plugin-core-themes/web/scss/dracula.scss, plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss, plugins/plugin-core-themes/web/scss/light.scss, plugins/plugin-core-themes/web/scss/lucario.scss, plugins/plugin-core-themes/web/scss/monokai.scss, plugins/plugin-core-themes/web/scss/nord.scss, plugins/plugin-core-themes/web/scss/paraiso.scss, plugins/plugin-core-themes/web/scss/solarized-dark.scss, plugins/plugin-core-themes/web/scss/tomorrow-night.scss, plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss, plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Fixes #6784
Fixed PF Dark, Nord, Solarized-dark, Atelier and Mercury
=> fix: the x in the offline badge is sometimes low contrast, especially in dark themes

plugins/plugin-kubectl/src/controller/client/direct/unify.ts
=> fix(plugins/plugin-kubectl): multikind table isn't unified correctly when some rows are offline

plugins/plugin-client-common/src/components/Views/Sidecar/Toolbar.tsx, plugins/plugin-client-common/web/css/static/sidecar-main.css, plugins/plugin-client-common/web/scss/components/Sidecar/BottomToolbar.scss, plugins/plugin-client-common/web/scss/components/Sidecar/_mixins.scss
This PR also refactors the sidecar bottom toolbar stylings into their own file.
Fixes #6873
=> fix(plugins/plugin-client-common): tweak sidecar button spacing a bit

plugins/plugin-client-common/src/components/Content/Markdown.tsx, plugins/plugin-client-common/src/index.ts, plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
This PR also exports the Tooltip spi from plugin-client-common.
Fixes #6939
See the issue for a screenshot.
=> fix(plugins/plugin-client-common): Markdown links should have a tooltip

package-lock.json, packages/webpack/package.json
As described in the issue, the fix requires re-generating our package-lock.json. Unfortunately, doing so also introduces a bug due to a webpack hidden dependence. So we need to bump the webpack and webpack-cli deps, as well.
Fixes #6944
=> fix: Markdown misparses certain links

plugins/plugin-kubectl/oc/src/controller/oc/login.ts
=> fix(plugins/plugin-kubectl): `oc login` does not invalidate the kubectl proxy

plugins/plugin-bash-like/web/scss/xterm.scss, plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-core-support/src/test/core-support2/remove-block.ts
Also improves the cursor discoverability in an unfocused pty block
Fixes #6954
=> fix(plugins/plugin-client-common): blocks with Processing commands cannot be removed

plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
=> fix: ctrl+c then clear results in wrong command being executed

plugins/plugin-bash-like/fs/src/vfs/delegates.ts, plugins/plugin-client-test/src/test/api2/vfs.ts
=> fix: ls does not show mounts, but tab completion does

plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-bash-like/src/test/bash-like/ls.ts, plugins/plugin-client-test/src/test/api2/vfs.ts
Fixes #7008
Closes #7010 (removes some temp files created by tests)
=> fix(plugins/plugin-bash-like): ls ~ fails

packages/core/src/models/command.ts, packages/core/src/repl/enforce-usage.ts, packages/core/src/repl/exec.ts, plugins/plugin-kubectl/src/controller/kubectl/flags.ts, plugins/plugin-kubectl/src/test/k8s/namespace.ts
Fixed by enforcing minimist to parse kubectl positional argument number as string
Fixes #7016
=> fix: `kubectl create ns 1` fails with status/direct

plugins/plugin-client-common/web/scss/components/Alert/PatternFly.scss
=> fix(plugins/plugin-client-common): "lost connection to your cluster" alert takes up the full window height

plugins/plugin-client-common/src/components/spi/Select/impl/PatternFly.tsx, plugins/plugin-client-common/web/scss/components/Popover/PatternFly.scss, plugins/plugin-client-common/web/scss/components/Popover/_mixins.scss, plugins/plugin-client-common/web/scss/components/Select/PatternFly.scss, plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Fixes #7034
https://user-images.githubusercontent.com/21212160/108276468-df6bd400-7145-11eb-8806-bf8015540eb2.mov
=> feat: add typeahead to kubernetes context and namespace select widget

plugins/plugin-bash-like/src/lib/cmds/catchall.ts, plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
=> fix: kui fails to show numeric namespace for kubectl config commands

.travis.yml, plugins/plugin-kubectl/src/controller/client/direct/errors.ts, plugins/plugin-kubectl/src/controller/kubectl/get.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts
=> fix(plugins/plugin-kubectl): Kui should fall back to Kubectl CLI when kubernetes direct accesss fails

plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
=> feat: show placeholder text to explain that ctrl+d closes split

plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx, plugins/plugin-kubectl/src/controller/cli.ts, plugins/plugin-kubectl/src/index.ts
This PR allows client to default kubectl cli in `client/config.d/exec.json`. The type spec being:
```typescript
{ defaultKubectl : 'oc' | 'kubectl' }
```
Fixes #7051
=> fix(plugins/plugin-kubectl): allow clients to define a default kubectl CLI

plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
=> fix(plugins/plugin-kubectl): kubectl Logs tab does not handle Idle state

plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
=> fix(plugins/plugin-kubectl): get-watch doesn't update the watcher status when limit is reached

packages/core/src/core/jobs/watchable.ts, plugins/plugin-bash-like/src/test/bash-like/watch-ls.ts, plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-core-support/src/lib/cmds/watch.ts
This PR adds a call to the table watching api: `setBody` that allows push providers to replace the entire table body with a new one.
Fixes #7119
https://user-images.githubusercontent.com/21212160/109876370-b6683a80-7c3f-11eb-8807-cac703886e31.mov
=> feat: update core watch command to return watchable table

plugins/plugin-kubectl/src/controller/client/direct/get.ts
=> fix(plugins/plugin-kubectl): k get resourcequota fails badly if your cluster has no quotas

plugins/plugin-client-common/src/components/Content/Table/Histogram.tsx
=> fix(plugins/plugin-client-common): Histogram's inline label could be off for short bars

plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Content/Table/Histogram.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/controller/grammy.ts
1. Change grammy table title from commandLine to "Histogram"
2. Render an empty chart for empty grammy table, for better live transition
Fixes #7173
=> fix(plugins/plugin-client-common): enhance live grammy

packages/core/src/core/jobs/watchable.ts, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
=> fix: LivePaginatedTable implements WatchPusher's update incorrectly

packages/core/src/models/execOptions.ts, packages/core/src/repl/exec.ts, plugins/plugin-bash-like/fs/src/lib/fwrite.ts, plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts, plugins/plugin-bash-like/fs/src/vfs/controller/server-side.ts, plugins/plugin-bash-like/fs/src/vfs/delegates.ts, plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-bash-like/fs/src/vfs/local.ts, plugins/plugin-bash-like/src/test/bash-like/bash-like.ts, plugins/plugin-client-common/src/components/Content/Editor/SaveFileButton.ts, plugins/plugin-core-support/src/lib/cmds/replay.ts, plugins/plugin-core-support/src/notebooks/vfs/index.ts
git cherry-pick 0b0979239ad39b091402dc736a2ef7f2302cbb55
[cherry 1d8cec1d4] feat: core/repl handles redirecting command output to files in VFS
=> feat: core/repl handles redirecting command output to files in VFS

plugins/plugin-bash-like/fs/src/vfs/index.ts
git cherry-pick 3d2cad8fce4a0293d4d74a45fd00caf8e0505b18
[cherrypick3 1115e0d3f] fix(plugins/plugin-bash-like): vfs ls fails for files named as a number
=> fix(plugins/plugin-bash-like): vfs ls fails for files named as a number

plugins/plugin-bash-like/fs/src/lib/cd.ts, plugins/plugin-bash-like/fs/src/vfs/delegates.ts, plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-bash-like/fs/src/vfs/initDone.ts
Part of #7238 
git cherry-pick a26bb02ae8581c5eecec9d7754e1a425a37de1aa
[cherrypick18 15e8f66f6] fix(plugins/plugin-bash-like): improve support for async-mounted VFS
=> fix(plugins/plugin-bash-like): improve support for async-mounted VFS

bin/kubectl-kui, bin/kui, packages/builder/dist/electron/build.sh, packages/core/src/main/main.ts, packages/core/src/main/spawn-electron.ts, packages/core/src/plugins/plugins.ts, packages/core/src/plugins/preloader.ts, packages/core/src/plugins/resolver.ts, packages/core/src/repl/exec.ts, packages/webpack/bin/watch.sh, packages/webpack/build.sh, packages/webpack/headless-webpack.config.js, plugins/plugin-client-default/src/preload.ts, plugins/plugin-core-support/src/preload.ts, plugins/plugin-kubectl-flow-views/tekton/src/plugin.ts
Part of #7221 
cherry-picked three commits and squash the last two into the first one. 
git cherry-pick 6de45d75d4c7591336ef17a2bfa97ada35d3cbc1
[cherrypick 3831b18e2] feat: use webpack to build headless bundles
git cherry-pick c5061c631d1fe59fe9adfdf8fbd9a9546d487b28
[cherrypick c4d37d139] fix(packages/builder): headless+webpack additional fix (CHERRY PICK WITH PRIOR COMMIT FOR MASTER)
git cherry-pick 725dbde5056eeaabea0838a5bcaef67c37c77458
[cherrypick cd833e204] fix(packages/webpack): another headless webpack fix (CHERRY PICK WITH HEADLESS WEBPACK COMMIT FOR MASTER)
=> feat: use webpack to build headless bundles

plugins/plugin-client-default/config.d/repo.json, plugins/plugin-electron-components/src/components/UpdateChecker.tsx
This also introduces a way for custom clients to specify their own repo. See plugin-client-default/config.d/repo.json for an example.
Fixes #7266
=> fix: update UpdateChecker to point to new kubernetes-sigs/kui repo

plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
This PR updates table drilldowns in popup mode always to send to the current split. In the future, we may decide to change the UX, but at least this PR fixes the glaring bug that we have right now: in popup mode, table drilldowns open a new split, but the drilldown is nonetheless still sent to the current split.
Fixes #7287
=> fix(plugins/plugin-client-common): table drilldowns in popup act oddly

packages/core/src/main/headless-support.ts, packages/core/src/models/command.ts, packages/core/src/models/execOptions.ts, packages/core/src/repl/exec.ts
This PR adds `createErrorStream()` to go alongside the existing `createOutputStream()`
Fixes #7293
=> feat(packages/core): allow controllers to stream to stderr

plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
=> fix(plugins/plugin-kubectl): client can't modify the styles of CurrentNamespace and CurrentContext widget via classname

plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c-via-table.ts, plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-vi.ts
=> fix: invoking a non-popup window from headless kui will have incorrect uuid for splits

.github/workflows/test.yaml
Implements temporary workaround suggested in the associated github actions issue
Fixes #7309
Uses the workaround proposed in the associated github actions issue (see #7309).
=> test: highly unstable tests

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
Fixes #7307 
This PR also changed the layout of 3 and 4 splits:
=> fix(plugins/plugin-client-common): disable minisplit

packages/webpack/webpack.config.js
=> fix(packages/webpack): webpack config has bogus entry for zlib fallback

plugins/plugin-kubectl/src/controller/kubectl/exec.ts, plugins/plugin-kubectl/src/controller/kubectl/flags.ts, plugins/plugin-kubectl/src/controller/kubectl/get.ts, plugins/plugin-kubectl/src/test/k8s4/get-redirect.ts
=> fix(plugins/plugin-kubectl): redirection of output on a get resource command is ignored

plugins/plugin-kubectl/src/controller/kubectl/options.ts
=> fix(plugins/plugin-kubectl): --kubeconfig path in commands are not always expanded

plugins/plugin-kubectl/src/tab-state.ts
=> fix(plugins/plugin-kubectl): tab state manager shoud not log "command not found" errors for systems without kubectl

plugins/plugin-bash-like/fs/src/lib/fstat.ts, plugins/plugin-bash-like/fs/src/vfs/local.ts
Fixes #7405
This prevents some odd interactions with windows path resolving of backslashes.
=> fix(plugins/plugin-bash-like): stop resolve to absolute path in fstat and fslice

plugins/plugin-bash-like/fs/src/vfs/delegates.ts
=> fix(plugins/plugin-bash-like): on windows ls with no arguments results in Cannot read property 'replace' of undefined

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
=> fix(plugins/plugin-client-common): watchable blocks when replaced by rerun/reexec are not aborted

plugins/plugin-client-default/config.d/repo.json, plugins/plugin-electron-components/src/components/UpdateChecker.tsx
Fixes #7438 
In this PR, I changed UpdateChecker to get the latest release via Github API, as Github API will return the most recent non-prerelease and non-draft release. We're currently fetching feed from https://github.com/kubernetes-sigs/kui/releases.atom and have to find the latest release by ourselves, since the feed doesn't contain assets and pre-release information. For example, we were checking if a release is pre-release by checking whether the release title contains alpha, beta or rc. This won’t exclude empty releases, such as v10.3.3. If we switched to github.api, then we can get the latest release for free.
=> fix(plugins/plugin-electron-components): use github api to get the latest release

plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
=> fix(plugins/plugin-client-common): input cursor will move to the end after tab-completes

packages/builder/dist/electron/build.sh, plugins/plugin-client-common/web/scss/components/Terminal/Block.scss, plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
=> fix: using / for division is deprecated for sass

packages/core/src/core/jobs/job.ts, packages/core/src/index.ts, packages/core/src/models/execOptions.ts, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts, plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx, plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
This PR exposes a new Resizable trait from Jobs, and does some minor cleanup on the Job type. It updates pty/client.ts to pass this through to the underlying PTY, and updates the plugin-kubectl ExecIntoPod view to use it!
Fixes #7473
=> fix: PTY jobs are not resizable

plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
We need to delay the initial resize() until the xtermContainer is mounted.
Fixes #7482
=> fix: vi doesn't take up the full dimensions of the viewport

packages/core/src/main/menu.ts, plugins/plugin-core-support/src/lib/cmds/quit.ts
BREAKING CHANGE: this PR removes the `quit` command
Fixes #7487
=> fix: in electron mode, ctrl/cmd+w should always close kui tab

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss, plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss, plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
=> feat(plugins/plugin-client-common): split header with split close button

plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
=> fix(plugins/plugin-client-common): StatusStripe widgets have double borders

plugins/plugin-client-default/src/index.tsx
Fixes #7546 
When I merged PRs into master, git seemed to mess up rebasing https://github.com/kubernetes-sigs/kui/commit/0b95d9cdd216424206f57347e5de1d0821e21e53, due to duplicate variable names.
I first merged the S3 plugin PR, which removed the import of isPopup from plugin-client-default/index.tsx. https://github.com/kubernetes-sigs/kui/commit/177457f3156bf1e36d1fc671b96982ee6e89aa7f#diff-8d9874cfcd3046ea3d4915be2efb64cb7121331a6352b74ceb0e1db3824088c8L19
Then I merged the "enable split in Popup mode" PR, which uses isPopup() to put spacefiller. https://github.com/kubernetes-sigs/kui/commit/177457f3156bf1e36d1fc671b96982ee6e89aa7f#diff-8d9874cfcd3046ea3d4915be2efb64cb7121331a6352b74ceb0e1db3824088c8L19
I should get merge conflict when merging the second PR, but GitHub doesn't show …
=> fix(plugins/plugin-client-default): compilation error

plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
=> fix(plugins/plugin-client-common): split close button lacks tooltip

packages/test/src/api/selectors.ts, plugins/plugin-client-common/i18n/resources_en_US.json, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts, plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx, plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Icons/index.tsx, plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss, plugins/plugin-core-support/src/test/core-support2/split-helpers.ts, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
=> feat: SplitHeader should have a clear button

plugins/plugin-client-common/web/css/static/ToolbarButton.scss, plugins/plugin-client-common/web/css/static/sidecar-main.css
=> design: SplitHeader buttons should match in size with Sidecar toolbar buttons

plugins/plugin-s3/components/src/S3Mounts.tsx
=> fix(plugins/plugin-s3): S3Mounts widget has high overhead on startup

plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
=> fix: width of vi not correct after closing splits

docs/example/AnimalApp/plugins/plugin-client-default/src/index.tsx, plugins/plugin-client-common/src/components/Client/TopTabStripe/SplitTerminalButton.tsx, plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts, plugins/plugin-client-common/src/components/Content/Table/Grid.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx, plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx, plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-default/src/index.tsx, plugins/plugin-client-notebook/src/index.tsx, plugins/plugin-client-test/src/index.tsx
Fixes #7593 
BREAKING_CHANGE: the `splitTerminals` property of `<Kui/>` is no longer needed nor supported.
=> chore: remove splitTerminals feature flag

plugins/plugin-bash-like/src/lib/cmds/export.ts, plugins/plugin-bash-like/src/test/bash-like/export.ts
=> fix(plugins/plugin-bash-like): unable to set variable to command output

plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx, plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
Two things are going on here:
1) In CurrentContext and CurrentNamespace, we issue the calls to fetch the info twice, once on mount of each widget, and once the initial Tab is mounted; we only need the latter
2) The way plugin-kubectl caches current context and current namespace is a bit racy on initial page load. We cache the strings, rather than the Promise of the strings. This can lead to double fetching if two initial requests come in close succession. It turns out that both of these widgets ask for the current namespace, hence we run into this race.
These fixes should also resolve a Content Layout Shift glitch that you can either observe visually, or via the Performance tab in chrome/electron.
Fixes #7624
=> fix: CurrentContext and CurrentNamespace widgets double-fetch onLoad

packages/core/src/api/client.ts, packages/core/src/index.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx, plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
Fixes #7635 
This PR adds two client options:
- readonly: if true, do not show `splitHeader` and block `copy` and `remove` buttons; default to false
- executable:  if false, do not show the block `rerun` button; default to false
If client specifies `readonly: true` and `executable: false`, Kui will enter `offline` mode.
=> feat: add readonly and executable client options for replaying notebooks

plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
=> fix(plugins/plugin-client-common): FancyPipeline errors out when rerunning snapshot blocks saved before pipestage was introduced

plugins/plugin-bash-like/fs/src/lib/ls.ts, plugins/plugin-core-support/src/notebooks/vfs/index.ts
This PR also disables use of a notebook's description (which may contain markdown). I think this was the sole use of Markdown in tables.
Fixes #7667
=> fix: ls should not use Markdown for cells (slow)

plugins/plugin-kubectl/src/controller/kubectl/explain.ts, plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
=> fix(plugins/plugin-kubectl): `kubectl get all` fails with resource type error

plugins/plugin-kubectl/src/lib/view/formatTable.ts
=> fix(plugins/plugin-kubectl): click-drilling down from cluster-scoped resources can yield `-n undefined` in the command execution

plugins/plugin-kubectl/src/controller/client/proxy/index.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts, plugins/plugin-kubectl/src/test/k8s/contexts.ts
=> fix(plugins/plugin-kubectl): kubectl watchers stop receiving push notifications when context is changed

plugins/plugin-kubectl/src/controller/client/direct/create.ts, plugins/plugin-kubectl/src/controller/kubectl/create.ts, plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
=> fix(plugins/plugin-kubectl): kubectl create ns failures do not display as errors in Kui

plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Deployment.ts
=> fix(plugins/plugin-kubectl): Deployment Summary Ready shows "undefined/N" if there are no pods ready yet

packages/proxy/app/app.js, packages/proxy/app/npm-shrinkwrap.json, packages/proxy/app/package.json, packages/proxy/app/routes/exec.js, plugins/plugin-proxy-support/src/lib/proxy-executor.ts
This PR also bumps the npm-shrinklock deps in packages/proxy/app
Fixes #7772
=> feat: Add support to Kui proxy for pre-shared-key authorization

packages/core/src/models/command.ts, packages/core/src/repl/exec.ts, plugins/plugin-kubectl/src/controller/client/direct/status.ts, plugins/plugin-kubectl/src/controller/kubectl/diff.ts, plugins/plugin-kubectl/src/controller/kubectl/flags.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/controller/kubectl/status.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts, plugins/plugin-kubectl/src/test/k8s1/apply-multi-file.ts, plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts, plugins/plugin-kubectl/tests/lib/k8s/utils.js
=> fix: kubectl apply -f does not support multi-file applies

plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss, plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss, plugins/plugin-core-themes/web/scss/light.scss, plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
=> fix: StatusStripe in light themes has low contrast

plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss, plugins/plugin-carbon-themes/web/scss/carbon-gray90.scss, plugins/plugin-carbon-themes/web/scss/colors.scss, plugins/plugin-carbon-themes/web/scss/inverted.scss, plugins/plugin-client-common/web/css/static/ui.css, plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss, plugins/plugin-client-common/web/scss/Themes/_mixins.scss, plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss, plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss, plugins/plugin-core-themes/web/scss/dark.scss, plugins/plugin-core-themes/web/scss/light.scss
This PR also fixes a few related theming issues.
Fixes #7956
=> fix: Carbon Gray10 theme has poor contrast for hints

plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx, plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx, plugins/plugin-kubectl/src/lib/view/modes/logs-mode.ts, plugins/plugin-kubectl/src/lib/view/modes/logs.tsx, plugins/plugin-kubectl/src/test/k8s1/deployment.ts
Fixes #5456 
My PR is a:
☐ :nail_care: Enhancement
Please confirm that your PR fulfills these requirements
☐ Multiple commits are squashed into one commit.
☐ The commit message follows Conventional Commits, which allows us to autogenerate release notes; e.g. fix(plugins/plugin-k8s): fixed annoying bugs
☐ All npm dependencies are pinned.
=> fix(plugins/plugin-kubectl): Adding logs tab to some Kubernetes resources

package-lock.json, plugins/plugin-client-common/package.json
this avoids duplicate monaco-editor installations
=> chore: bump react-monaco-editor dependence to 0.45.0

packages/core/src/plugins/preloader.ts, packages/core/src/plugins/resolver.ts, packages/core/templates/index.ejs, packages/test/src/api/util.ts, plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Select/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Select/model.ts, plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx, plugins/plugin-client-common/src/index.ts, plugins/plugin-client-common/web/css/static/grid.scss, plugins/plugin-client-common/web/css/static/ui.css, plugins/plugin-client-default/src/index.tsx, plugins/plugin-core-support/src/notebooks/vfs/index.ts, plugins/plugin-core-support/src/test/core-support/tab-management.ts, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts, plugins/plugin-kubectl/components/src/CurrentContext.tsx, plugins/plugin-kubectl/components/src/CurrentNamespace.tsx, plugins/plugin-kubectl/src/tab-state.ts, plugins/plugin-kubectl/src/test/k8s2/get-pod-multi-tab.ts
- defers loading of notebook data
- defers loading of plugin-kubectl
- defer some of the components in plugin-client-default
This should shave about 200-300ms off page load time for electron clients (maybe a 20% improvement). The main target for this is initial page load time for browser-based clients (the uncached case). This PR should reduce the payload size of the initial bundle fetch by 2-3MB (for uncompressed bundles).
Fixes #8070
Closes #8068
BREAKING CHANGE: this alters the loading cycle in a way that may break sensitive tests, mostly by making cert
ain actions a bit more asynchronous. The only possible breakage, I believe, is in test, and very few of those. If you have a test that calls `Util.closeAllExceptFirstTab` from kui-shell/test more than once in a given mocha `describe`, …
=> chore: load-time tuning

packages/core/src/models/DescriptionList.ts, plugins/plugin-client-common/src/components/Content/KuiContent.tsx, plugins/plugin-client-common/src/components/spi/DescriptionList/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/DescriptionList/impl/PatternFlyLabelList.tsx, plugins/plugin-client-common/src/components/spi/DescriptionList/index.tsx, plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss, plugins/plugin-client-common/web/scss/components/DescriptionList/PatternFlyLabelList.scss, plugins/plugin-client-common/web/scss/components/DescriptionList/_mixins.scss, plugins/plugin-client-common/web/scss/components/DescriptionList/common.scss, plugins/plugin-kubectl/src/lib/view/modes/Labels.ts
Adds `{ spec: { as: 'labels' } }` to DescriptionList model
Fixes #8116
=> feat: use PatternFly LabelGroup for kubernetes Labels tab

plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/lib/view/modes/pods.ts
- export `getPodsCommand` from plugin-kubectl
- update `VFS.rm` to accept a `tab`, which allows `rm` impls to call `ls` impls
=> chore: a few minor tweaks to APIs

plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-kubectl/src/controller/client/direct/create.ts, plugins/plugin-kubectl/src/controller/client/direct/delete.ts, plugins/plugin-kubectl/src/controller/client/direct/errors.ts, plugins/plugin-kubectl/src/controller/client/direct/get.ts, plugins/plugin-kubectl/src/controller/client/direct/watch.ts, plugins/plugin-kubectl/src/controller/client/proxy/index.ts, plugins/plugin-kubectl/src/controller/fetch-file.ts, plugins/plugin-kubectl/src/controller/kubectl/contexts.ts, plugins/plugin-kubectl/src/controller/kubectl/get.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/lib/util/fetch-file.ts, plugins/plugin-kubectl/src/lib/view/modes/pods.ts, plugins/plugin-kubectl/src/test/k8s/contexts.ts, plugins/plugin-s3/src/providers/local-minio.ts
This PR adds support for the client/direct kubernetes impl for `--context ccc` command lines. Previously, we always shunted these command lines to the far slower `kubectl` client impl.
=> feat: allow kubectl "direct" client to work with --context

plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-client-test/src/test/bash-like/command-fs.ts
e.g. ls /kui/foo/.. should list /kui
=> fix: ls in vfs directories is not normalized

packages/core/src/repl/exec.ts, plugins/plugin-bash-like/src/lib/cmds/pipe.ts, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
Previously, we were eagerly calling toString() on the buffers
=> fix: improve support for redirecting Buffer/binary output to files

packages/core/src/index.ts, packages/core/src/repl/error.ts, packages/core/src/repl/exec.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
the repl/exec redirect handler was treating error responses as an unhandled redirect type; this is correct at some level, but not very useful to the user. let's do what bash does here, and report the original error!
=> fix: improve error handling of redirect handler vs error responses

plugins/plugin-bash-like/fs/src/vfs/controller/server-side.ts, plugins/plugin-bash-like/fs/src/vfs/delegates.ts, plugins/plugin-bash-like/fs/src/vfs/index.ts, plugins/plugin-bash-like/fs/src/vfs/local.ts, plugins/plugin-bash-like/src/lib/cmds/pipe.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx, plugins/plugin-s3/src/vfs/index.ts
So that we can stream out of vfs objects
=> feat: vfs pipe support

plugins/plugin-electron-components/src/components/UpdateChecker.tsx, plugins/plugin-kubectl/src/lib/util/fetch-file.ts
this brings in crypto and a iconv-lite, which are not needed for offline clients
=> chore: defer loading of needle

plugins/plugin-s3/ibm/src/IBMCloudS3Provider.ts, plugins/plugin-s3/ibm/src/controller/local.ts, plugins/plugin-s3/ibm/src/preload.ts, plugins/plugin-s3/ibm/src/s3provider.ts
This would result in the ibm s3 provider not initializing itself.
This PR also adds more debug to the ibm s3 provider.
=> fix(plugins/plugin-s3): null pointer exception in plugin-s3/ibm init

packages/core/src/core/jobs/watchable.ts, plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx, plugins/plugin-client-common/src/components/Content/Table/Bar.tsx, plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx, plugins/plugin-client-common/src/components/Content/Table/ProgressState.ts, plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
This PR adds a `progress()` method to the `WatchPusher` API.
```typescript
/**
* Update progress bar for a given row
*
* @param rowIdx row index (assumes no sorting, for now)
* @param percentComplete how far along is the processing of this row?
* @param [message] any transient message that might help understand the progress
* @param [totalSize] if the row represents a sized of object, how big is it?
* @param [fileName] if the row represents a named object, what is it called?
*
*/
progress: (progress: { rowIdx: number, percentComplete: number, message?: string, totalSize?: number, fileName?: string }) => void
```
=> feat: table watchers should be able to provide incremental progress

packages/proxy/app/bin/run-proxy.sh, packages/proxy/app/routes/exec.js, packages/webpack/headless-webpack.config.js
clients with their own productName (different than "Kui") will be unable to properly run the proxy process. There are a few places that assume the bundles are named e.g. "kui-min.js"
Also the kui-run-proxy script was not updated to use the minified bundles.
=> fix(packages/proxy): proxy does not properly run in external clients

plugins/plugin-bash-like/fs/src/vfs/delegates.ts
this happens if a VFS has both commands and file content in a directory
=> fix(plugins/plugin-bash-like): ls may report duplicates

plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Added a maximum width for executable blocks typically found in notebooks. This is especially helpful when the Kui window is expanded.
=> fix(plugins/plugin-client-common): Maximum width for executable block content

plugins/plugin-bash-like/src/lib/cmds/catchall.ts, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-bash-like/src/pty/index.ts
This is due to a change in bash-like's new cwd() impl
=> fix(plugins/plugin-bash-like): kubectl prereq fails

plugins/plugin-client-common/src/components/Content/Markdown.tsx, plugins/plugin-client-common/web/css/static/ui.css, plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss, plugins/plugin-client-common/web/scss/components/Table/Events.scss, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
We have a bunch of home-grown stylings for p and h1 and h2, etc. Let's stop DIYing it here.
=> feat: Use Patternfly Text components for text styling

packages/core/src/repl/split.ts, plugins/plugin-bash-like/fs/src/lib/head.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyPress.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/OnPaste.tsx
1) broken handling of manually typed backslash-escaped multiline commands
2) broken handling of pasted backslash-escaped multiline commands
part of #8274
=> fix: multi-line input is partially broken

plugins/plugin-client-common/src/components/Content/Markdown.tsx, plugins/plugin-client-common/src/components/Content/remark-tabbed/index.ts, plugins/plugin-client-common/src/components/Content/remark-tip/index.ts, plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx, plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/CodeSnippet/model.ts, plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
This PR also switches markdown tabs to use the "box light" variant from PatternFly
This PR also introduces the initial stub for the markdown-based "Inputv2"
=> fix(plugins/plugin-client-common): nested tabs and tips

plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
This mainly affects dark themes.
Fixes #8318
=> fix(plugins/plugin-client-common): improved color contrast for tooltips

plugins/plugin-bash-like/src/lib/cmds/catchall.ts, plugins/plugin-bash-like/src/lib/util/exec.ts
we seem to squash them down to `1` in cleanupError in plugin-bash-like
=> fix: some error handling paths do not propagate exit code

plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
This PR fixes execution of code blocks with '&;' in them.
It also has a small fix for validation errors: don't show them as errors in the progress stepper ui
=> fix(plugins/plugin-client-common): Code Blocks versus &;

packages/core/src/repl/exec.ts, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
1. in the core, we were transmitting on the error message for error parts of a multi-part response
2. incorrect serialization of code blocks with a part error
3. in code block rendering, no recognition of error parts
=> fix: improved error handling for MixedResponse

plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Consecutive tips, where the title has structured content, are swallowed into the prior tip, i.e. we aren't starting a new tip.
=> fix(plugins/plugin-client-common): improvements for markdown tip parsing

plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/convert.ts
This is due to a caught toString() call on a null pointer.
=> fix(plugins/plugin-kubectl): Summary tab may not render as expected

plugins/plugin-client-common/.gitignore, plugins/plugin-client-common/notebook/package.json, plugins/plugin-client-common/notebook/src/index.ts, plugins/plugin-client-common/notebook/src/load.ts, plugins/plugin-client-common/notebook/tsconfig.json, plugins/plugin-client-common/src/controller/commentary.ts, plugins/plugin-client-common/tsconfig.json, plugins/plugin-core-support/src/lib/cmds/replay.ts
due to the way replay loads notebooks, versus commentary; this PR consolidates this logic
=> fix: multi-notebook replay does not properly handle tab titles

packages/test/src/api/Sidebar.ts, packages/test/src/api/selectors.ts, plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/TabContainer.tsx, plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx, plugins/plugin-client-common/src/components/Client/props/Branding.ts, plugins/plugin-client-common/src/components/Client/props/Common.ts, plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts, plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Icons/index.tsx, plugins/plugin-client-common/src/test/core/sidebar.ts, plugins/plugin-client-common/web/scss/components/TopTabStripe/Sidebar.scss, plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss, plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss, plugins/plugin-client-default/src/index.tsx, plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts, plugins/plugin-core-themes/web/scss/light.scss
Also ports from older Patternfly Page* elements to new Masthead* elements
=> feat: Use patternfly Sidebar to display guidebooks

.prettierignore, packages/test/src/api/Markdown.ts, packages/test/src/api/selectors.ts, plugins/plugin-client-common/i18n/markdown_en_US.json, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts, plugins/plugin-client-common/src/test/core/tip.ts, plugins/plugin-client-common/tests/data/tip-no-title.md, plugins/plugin-client-common/tests/data/tip.md, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- tip without title support #8417
- minor tweaks to expandable content padding
Fixes #8417
=> fix: tip without title parsing improvements

plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
For now, we just throw away this information. For the cases where it is `target=_blank`, this does not harm Kui behavior, since it is the default behavior.
Fixes #8432
=> fix(plugins/plugin-client-common): work around mkdocs {target=} syntax

plugins/plugin-client-common/src/components/Client/Sidebar.tsx, plugins/plugin-client-common/src/components/Client/TabContainer.tsx
This also attempts to lazily load Nav/NavItem/NavExpandable/NavList components, since they aren't needed until the sidebar is expanded.
=> chore: refactor Sidebar into Sidebar.tsx

plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Event.ts
there is no sense in showing Name, and Message should be higher up in the UI
=> fix(plugins/plugin-kubectl): improve content of kubectl Events summary

plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
When editing the code block within Kui (i.e. not in the markdown text source), ... changes are possible, but re-executing the command does not reflect the updated code block text.
=> fix(plugins/plugin-client-common): markdown code block edits not durable

packages/proxy/Dockerfile, packages/proxy/build-docker.sh, packages/webpack/headless-webpack.config.js
apparently `npm view node-pty version` shows the published version of the latest dist-tag, not the version we have installed.
also, the Dockerfile does not copy the `spawn-helper` that is now part of linux (and macos) node-pty builds
this PR also fixes a spurious error in the headless bundle build
=> fix: dockerized proxy installs incorrect version of node-pty

plugins/plugin-client-common/src/components/Client/StatusStripe/SpaceFiller.tsx, plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx, plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss, plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss, plugins/plugin-client-default/config.d/notebooks.json, plugins/plugin-client-default/src/index.tsx, plugins/plugin-kubectl/notebooks/dashboard1.md, plugins/plugin-kubectl/src/non-headless-preload.ts
This PR also updates the default client so as not to hide the StatusStripe kubernetes context/namespace switcher widgets when showing a notebook/guidebook.
This PR also allows guidebook code blocks to add a `watch` topmatter, which specifies one or more channels. If an even is fired on any of those channels, the code block will automatically be re-executed.
See `plugin-client-kubectl/notebooks/dashboard1.md` for an example.
=> feat: kubernetes dashboard guidebook

plugins/plugin-carbon-themes/web/scss/colors.scss, plugins/plugin-client-common/src/components/Content/Markdown/components/details.tsx, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts, plugins/plugin-client-common/web/scss/components/ExpandableSection/_mixins.scss, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss, plugins/plugin-core-themes/web/scss/Mercury.scss, plugins/plugin-core-themes/web/scss/atelier-seaside.scss, plugins/plugin-core-themes/web/scss/dark.scss, plugins/plugin-core-themes/web/scss/dracula.scss, plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss, plugins/plugin-core-themes/web/scss/light.scss, plugins/plugin-core-themes/web/scss/lucario.scss, plugins/plugin-core-themes/web/scss/monokai.scss, plugins/plugin-core-themes/web/scss/nord.scss, plugins/plugin-core-themes/web/scss/paraiso.scss, plugins/plugin-core-themes/web/scss/solarized-dark.scss, plugins/plugin-core-themes/web/scss/tomorrow-night.scss, plugins/plugin-core-themes/web/scss/zenburn.scss, plugins/plugin-patternfly4-themes/web/scss/common.scss, plugins/plugin-patternfly4-themes/web/scss/dark.scss, plugins/plugin-patternfly4-themes/web/scss/light.scss
we were using fixed colors before. this pr allows some variation by tip, using one of
??? note "tip title"
??? bug ...
??? success ...
??? warning ...
??? todo ...
the source for this gif is 
```sh
replay https://raw.githubusercontent.com/knative/docs/main/docs/snippets/install-kn.md`
```
=> fix: improved markdown expandable section colors

plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss, plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
We can optimize the width/max-width settings here.
Also, perhaps we should flex-end align the footer buttons, to more closely mimic the positioning as done by PatternFly (background: they use absolute positioning of the nav, which forces them to use a fixed width to the nav; apparently, they need to use absolute positioning of the nav, because oddly the footer is not a sibling of the body, but rather a sibling of the nav+body pair. Probably bugs on their side.
=> fix(plugins/plugin-client-common): wizard nav can be too wide

plugins/plugin-client-common/notebooks/welcome.md
not much, but it helps a bit with avoiding overflow after which patternfly's left/right scrolling buttons in the tabs seems to stay stuck on :(
=> doc: shorten "Linux and Windows" to "Linux/Windows" in welcome.md

plugins/plugin-client-common/src/components/Content/Commentary.tsx
it shouldn't, because there is no way to restore the editor
=> fix(plugins/plugin-client-common): escape in playground cancels editor

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
renders as blank if there are not steps, but still plenty of content
or if we only have a title but no steps
=> fix(plugins/plugin-client-common): wizard behaves poorly when empty

plugins/plugin-client-common/src/components/Content/Markdown/code-indexer.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
We had required a code block id attribute in order for code block validation to function. We can assign one for the user, if not specified.
Also, the validation logic did not re-fire after a source update e.g. in the playground. Fixed
Also added types to the code-indexer rehype plugin.
=> fix(plugins/plugin-client-common): allow code block id to be optional

plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
ugh, regression in the way we assemble the list of responses from props and state
=> fix(plugins/plugin-client-common): saving code block responses is broken

plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/src/controller/snippets.ts, plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts, plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md, plugins/plugin-iter8/notebooks/tutorial1.md
Also updates the iter8 tutorial1.md to pull the content from iter8
Also adds support for renaming wizard steps in wizard topmatter
=> feat: when inlining guidebook snippets, rewrite relative image links

package-lock.json, plugins/plugin-client-common/package.json
Reverts kubernetes-sigs/kui#8535
ugh, this remark plugin is not maintained, and broken with the latest release of react-markdown.
=> Revert "chore: add remark-terms dependence (no other changes)"

packages/builder/bin/prescan.sh, packages/core/src/api/Client.ts, packages/core/src/api/index.ts, packages/core/src/index.ts, packages/core/src/main/load.ts, packages/core/src/main/menu.ts, packages/core/src/main/notebooks.ts, plugins/plugin-client-common/src/components/Client/Kui.tsx, plugins/plugin-client-common/src/components/Client/Sidebar.tsx, plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts, plugins/plugin-client-common/src/mount.ts, plugins/plugin-client-default/config.d/notebooks.json
This PR lays some groundwork that allows clients a more drop-in approach to provisioning guidebooks into a client.
1) Place the `.md` and `.json` files in your client's `notebooks/` directory
2) If you wish to have the guidebooks sidebar open by default, add `"showGuidebooksSidebar": true` to your config.d/client.json
3) If you wish Kui to operate in a mode where it shows a single guidebook at a time (rather that opening up Kui tabs for each opened guidebook), add `"singletonGuidebooks": true` to your config.d/client.json
4) (already the case before this PR): design your sidebar menu in config.d/notebooks.json
5) (new in this PR) if one of the leaf nodes in notebooks.json has `open: true`, then it will be autoplayed if you have also defined `singletonGuidebooks` and …
=> feat: `<Kui/>` component should automate more of guidebook mounting

plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss, plugins/plugin-client-common/web/scss/components/Terminal/Block.scss, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss, plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
we are using a pretty bold color right now, which is distracting. mkdocs uses a much less saturated color for the headers/button part of expandable sections.
this pr also reduces the border-radius on code blocks (6px -> 1px)
=> fix(plugins/plugin-client-common): reduce saturation of tip headers

plugins/plugin-kubectl/logs/package.json
THis should clear up a false positive dependabot alert for ansi_up
=> chore: remove unused dependences in nested package.json

plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
this is how mkdocs renders them. we have them currently as yellow.
=> fix(plugins/plugin-client-common): markdown "note" tips should be blue

plugins/plugin-client-common/src/components/Content/Markdown/components/table.tsx
In cases where the `<td/>` content is far narrower than the corresponding `<th/>` for that column, PatternFly (or is it Electron 13?) seems to favor ellipsis for the column header. This looks looks particularly bad if the td is quite narrow.
=> fix(plugins/plugin-client-common): markdown tables can have odd ellipsis

plugins/plugin-kubectl/notebooks/knative-eventing-components.md, plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md, plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
To make the titles more consistent.
=> doc: add "Knative -" prefix to some of the knative guidebook titles

packages/webpack/webpack.config.js, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter-parser.tsx, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/src/controller/snippets-inliner.ts, plugins/plugin-client-common/src/controller/snippets.ts
This change is regarding the "snippet" (a.k.a. "markdown hash include") support. It enables us to do all of the inlining at webpack bundle build time, rather than doing it dynamically.
1) decreased load time when presenting a guidebook that employs snippets
2) allows running in a browser environment where the remote fetches would be blocked by CORS
=> feat: inline markdown snippet inclusions at build time

plugins/plugin-client-common/src/components/Client/Sidebar.tsx, plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts
When you close then re-open the Sidebar, any nav items you may have expanded are now back to their initial state.
This PR also does a small bit of code cleanup in Sidebar.tsx.
=> fix(plugins/plugin-client-common): sidebar nav expansions not persisted

package-lock.json, plugins/plugin-core-support/package.json, plugins/plugin-electron-components/package.json
=> chore: bump electron/remote to de-deup 2.0.1 and 2.0.4

packages/builder/tsconfig-base.json
I thought we needed these, but it turns out that the default behavior works ok.
=> fix: update base tsconfig to avoid specifying webdriverio types

plugins/plugin-client-common/src/components/Content/Table/sort.ts
For some reason, we had hard-coded logic to allow sorting on only a few fixed column headers.
=> fix(plugins/plugin-client-common): only a few table columns are sortable

plugins/plugin-client-common/web/scss/components/Terminal/Block.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss, plugins/plugin-core-themes/web/scss/common.scss, plugins/plugin-core-themes/web/scss/light.scss
=> fix: Light theme does not get expected sepia filter for finished blocks

packages/test/src/api/Wizard.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx, plugins/plugin-client-common/web/scss/components/Wizard/_index.scss, plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
1) hide description
2) reduce font size and margins a bit
Ideally, it would be nice to pin this content and let the wizard content scroll. Given the current DOM structure, where the markdown is rendered deeply inside of Blocks etc.... this will be too hard for this PR. So let's start with at least allowing the user to reduce the amount of space taken up by the wizard header.
=> feat(plugins/plugin-client-common): allow wizard header to be collapsed

plugins/plugin-carbon-themes/web/scss/carbon-gray90.scss, plugins/plugin-carbon-themes/web/scss/colors.scss, plugins/plugin-client-common/web/scss/Lightweight/_index.scss, plugins/plugin-client-common/web/scss/Themes/_mixins.scss, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss, plugins/plugin-core-themes/web/scss/common.scss, plugins/plugin-patternfly4-themes/web/scss/common.scss, plugins/plugin-patternfly4-themes/web/scss/dark.scss, plugins/plugin-patternfly4-themes/web/scss/light.scss
Right now, we are generally using dark-to-light inversion for kui--inverted-color-context elements. This does not seem to be in spirit with dark themes.
=> fix: fixes for inverted colors in dark themes

packages/core/src/models/TabLayoutModificationResponse.ts, plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/SplitInjector.ts, plugins/plugin-client-common/src/test/core/markdown/terminal.ts, plugins/plugin-client-common/tests/data/terminal1.md, plugins/plugin-client-common/tests/data/terminal2.md, plugins/plugin-client-common/tests/data/terminal3.md
Right now, guidebooks can only have markdown content in splits. Some use cases would benefit from having one of their splits be a normal terminal.
This PR adds a `terminal` option to the guidebook topmatter, e.g. (from terminal1.md test input) this guidebook would have the first split offer a normal terminal interaction, and the second split be markdown only, without a normal terminal interaction (which is the default behavior for splits in guidebooks,  hence the `2: default`)
```markdown
---
layout:
1: terminal
2: default
---
XXXX
---
YYYY
```
=> feat: allow for guidebooks to have a "normal" split with a terminal

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Layout/BottomStrip.scss, plugins/plugin-client-common/web/scss/components/Terminal/Layout/Default.scss, plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss, plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
We have some missing rules for 5 or 6 splits. This PR addresses the 5 gap with extra CSS rules, and addresses the 6 gap by reducing the MAX_SPLITS from 6 to 5.
=> fix: creating split can cause funky layout

plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss, plugins/plugin-client-common/web/scss/components/Sidebar/_mixins.scss
patternfly 4.198.5 changed the css class of the sidebar body element.
=> fix(plugins/plugin-client-common): Sidebar footer is not bottom-justified

packages/builder/dist/electron/build.sh
This is due to the way we hack node-pty 0.10.0 in, just for win32.
=> fix(packages/builder): make sure to build win32 electron last

plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
We were using the cyan (color-base0C), which is used in lots of places. This PR adjusts to use base0E (magenta) for --options in code blocks, for a bit more variety.
=> fix(plugins/plugin-client-common): tweak code block option color

plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
We put this in place when the wizard header had a box shadow. It no longer does.
=> fix(plugins/plugin-client-common): remove wizard right-margin

packages/core/src/main/spawn-electron.ts
=> fix(packages/core): strip off chrome args for second electron instance

packages/core/src/main/spawn-electron.ts
=> fix(packages/core): strip off chrome args for second electron instance (v2)

plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss, plugins/plugin-client-common/web/scss/components/Terminal/Layout/RightStrip.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
This is due to a `min-width: 0` rule on Commentary. We put this rule in place to allow the flex box to respond to narrower windows, and re-wrap appropritately.
However, for regions that we know will be relatively narrow, we should use the define scroll overflow behavior. Text wrapping in a narrow region does not seem to be very readable.
=> fix: wide content in left or right strip does not horizontally overflow

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
This PR fixes a few issues in the guidebook layout logic that were limiting wizards to appearing in the first de
fault split.
=> fix(plugins/plugin-client-common): guidebooks cannot have wizards in second+ splits

plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/ImportsTree.tsx, plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx, plugins/plugin-client-common/src/components/spi/Icons/index.tsx, plugins/plugin-client-common/web/scss/components/Wizard/Imports.scss
=> fix(plugins/plugin-client-common): improved display of subtree status in guidebook tree view

plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
For SubTask subtrees, we should expand a bit further, unless that SubTask is already complete.
=> fix(plugins/plugin-client-common): increase default expansion depth for Imports component

plugins/plugin-kubectl/notebooks/install-knative-quickstart.md, plugins/plugin-kubectl/notebooks/knative-serving-hello-world.md
With the introduction of `:imports`, install-knative-quickstart.md needed an updated layout. The Clean Up section has been commented out for now because this guidebook is being used as an import in other files and the Clean Up content is not necessary when file is imported. Also, some validation scripts were not running due to a typo in the validation flag. This has also been fixed.
=> fix(plugins/plugin-kubectl): Fixing guidebook layouts and validation code

plugins/plugin-client-common/src/components/Content/Markdown/components/ImportsTree.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts, plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/2.ts, plugins/plugin-client-common/tests/data/guidebook-tree-model3.md, plugins/plugin-client-common/tests/data/snippets-in-tab4b.md, plugins/plugin-client-common/tests/data/snippets-in-tab5.md, plugins/plugin-client-common/tests/data/snippets-in-tab5c.md
We aren't clearing out prior subtrees on two paths in compile()
=> fix(plugins/plugin-client-common): dependence tree can place nodes in prior sibling

package-lock.json, plugins/plugin-client-common/package.json, plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/ImportsTree.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts, plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/1.ts, plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/2.ts, plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/3.ts, plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/4.ts, plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/5.ts, plugins/plugin-client-common/tests/data/guidebook-tree-model4.md, plugins/plugin-client-common/tests/data/guidebook-tree-model5.md, plugins/plugin-client-common/tests/data/snippets-in-tab6.md
This PR switches us off a dominator tree, and instead uses an algorithm closer to an iterative control dependence region optimizer.
We should no longer hoist imports that appear on only a subset of choice branches, e.g.
```
root
choice1: import foo
choice2: import bar
choice3: import foo
```
Prior to this PR, we were using a dominator tree, which blindly hoisted both up, since the root dominates those two imports.
=> fix(plugins/plugin-client-common): improved hoisting of subtasks

plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
we aren't leveraging patternfly's built-in support for secondary tabs. there is a lot of vertical padding between each layer of tabs, due to our Card wrapper around the tab body content.
=> fix(plugins/plugin-client-common): secondary markdown tabs do not display well

plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
This is a regression after a patternfly version bump. Their rules now trump our overrides.
=> fix(plugins/plugin-client-common): progress bar in wizard header has poor layout

plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
This PR updates `toMarkdownString()` i.e. the logic to turn the markdown AST back into a string, so that it supports tips.
=> fix(plugins/plugin-client-common): support for tips in guidebook wizard steps

plugins/plugin-client-common/src/components/Content/Markdown/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/arch.ts, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/homebrew.ts, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/platform.ts
1) we were recomputing these platform settings on every render
2) the default react batching doesn't seem to be sufficient for this use case, resulting in multiple recomputations of the task graph
=> fix(plugins/plugin-client-common): optimize population of platform/arch/etc. choice detection

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/CodeBlockProps.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/compile.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/deadCodeElimination.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
We look for tabs that have a first `<p>` child.
=> feat(plugins/plugin-client-common): extract description for guidebook choices

plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx, plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
we weren't picking up a description for the guide command's auto-generated wizard
=> fix(plugins/plugin-client-common): improve guide command handling of wizard description

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts, plugins/plugin-client-common/src/components/Views/Terminal/SplitInjector.ts, plugins/plugin-client-common/src/controller/guide.ts, plugins/plugin-client-common/web/scss/components/Terminal/Maximized.scss, plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss, plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss, plugins/plugin-core-themes/web/scss/light.scss, plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
1. Try not using inverted color for wizard header
2. maximize the content so that the wizard header is snapped to the bounding container
3. a few minor fixes to themes that were still hard-wiring inverted colors for wizard headers
The `guide` command will do this by default. If you want it in other guidebooks, e.g.:
```markdown
---
layout:
1: left
2: 
position: default
maximized: true
---
left content
---
right content that will be "maximized"
```
=> feat(plugins/plugin-client-common): refinements to wizard header guidebook spacing

plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
This is an issue with more backslash escaping from toMarkdown
=> fix(plugins/plugin-client-common): Guide does not properly format links

plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx, plugins/plugin-client-common/web/scss/components/Wizard/Guide.scss
align the Choices and Completed Tasks
=> fix(plugins/plugin-client-common): clean up Guide header

plugins/plugin-client-common/src/components/Content/Markdown/index.tsx, plugins/plugin-client-common/src/components/Content/Scalar/index.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
this is a regression from some css tweaks for paragraphs in guidebook markdown
=> fix(plugins/plugin-client-common): non-pty output can have extra whitespace at top

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
Right now, it always starts at the first step.
=> fix(plugins/plugin-client-common): guide wizard should start at first non-complete step

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss, plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss, plugins/plugin-client-common/web/scss/components/Text/_mixins.scss, plugins/plugin-client-common/web/scss/components/Tile/_mixins.scss, plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
We have a small wrapper over the PatternFly Wizard, to work around some issues with nesting a wizard inside of a flex region. But our typography and spacing is far off from what they have in their modal variant.
=> fix(plugins/plugin-client-common): improve spacing and typography in our Wizard wrapper

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx, plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss, plugins/plugin-client-common/web/scss/components/Wizard/Guide.scss, plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss, plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
This PR also restores the default PatternFly border behavior around the nav and footer.
=> fix(plugins/plugin-client-common): use inner scrolling for guide wizard body

plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/choice-frontier.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
The "just find all code blocks" fallback isn't handling the case where all we have is code blocks, with no titles. It presents wizard steps, one per code block, none of which have a title.
=> fix(plugins/plugin-client-common): Guide can have blank steps

plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts, plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
This PR detects when we don't have enough context for a code block, and if so looks for the nearest enclosing heading (or tip title) to add that missing context.
=> fix(plugins/plugin-client-common): improve Missing titles in guide steps

plugins/plugin-electron-components/src/components/Search.tsx, plugins/plugin-electron-components/web/scss/components/Search/Search.scss
There are two issues:
1) we are invoking the electron findInPage API with an empty string. it does not like this.
2) we are calling input.focus() in a render function. react does not like this.
I also noticed that we never unlisten from the document event listener (for cmd/ctrl+f)
=> fix(plugins/plugin-client-common): Search component may emit console errors

plugins/plugin-electron-components/src/components/UpdateChecker.tsx
This is a regression from some earlier debugging. This component should wait 60 seconds before checking for available Kui updates.
=> fix(plugins/plugin-electron-components): UpdateChecker initial delay is 0ms

plugins/plugin-s3/src/preload.ts
For some reason, we are doing this for all Kui users.
=> fix(plugins/plugin-s3): don't prefetch minio npm

.github/workflows/test.yaml
Try to optimize time to completion for a full test run.
This PR also bumps the macos version from 10.15 to 11.
=> test: split osx into two separate github actions workflows

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx, plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx, plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss, plugins/plugin-core-support/src/test/core-support2/right-strip.ts
I don't think this offers any value at this point. We will continue to support split positioning in markdown topmatter.
BREAKING CHANGE: removal of split position button from split header
=> feat: remove split position button from split header

plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
When focusing, we may call setState on an unmounted component.
=> fix(plugins/plugin-client-common): ScrollableTerminal may emit react setState errors

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/CodeBlockProps.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/compile.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/src/components/Content/Markdown/remark-import.ts
A small oversight in `isWizard` caused the dependency graph to be mal-formed
=> fix(plugins/plugin-client-common): nested import that is a wizard that has imports

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Footer.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx
Hmm, the patternfly Wizard component set does not export the default wizard footer. Our only choice seems to be to clone and own. Sigh.
=> chore(plugins/plugin-client-common): copy in WizardFooterInternal for subsequent generalization

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Footer.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx, plugins/plugin-client-common/web/scss/components/Wizard/Footer.scss, plugins/plugin-client-common/web/scss/components/Wizard/Guide.scss, plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
- updates the wizard Footer.tsx component to allow callers to slot in extra buttons
- updates Guide's use of Footer to place the choice chips in the footer, rather than in the header
- updates the chips to use an inverted color scheme
- reverts to default patternfly wizard footer button placement: next and back are now again left-aligned
=> feat(plugins/plugin-client-common): wizard footer should allow for extra buttons

plugins/plugin-client-common/notebooks/wizard.md, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/tests/data/wizard-with-splits.md
We were interpreting the title as "Title: Description". But some source material legitimately have titles with colons, e.g. "Optional: Do this".
=> fix(plugins/plugin-client-common): improved handling of wizard step titles with colons

plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
When using the `guide` command against a markdown source file that has an `imports` section in its topmatter... if that imported file is not imported anywhere else, it will be mis-rendered in Guide's wizard: tabs and tips will not have the proper indentation (or, it will not be preserved properly when round-tripping from ast back to source).
This is due to a now-unnecessary div->span hack we do in rehype-wizard.
=> fix(plugins/plugin-client-common): topmatter imports in content from guide command mis-rendered

plugins/plugin-client-common/src/components/Content/Commentary.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Footer.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx, plugins/plugin-client-common/src/components/spi/Button/impl/PatternFly.tsx, plugins/plugin-client-common/web/scss/components/Button/_mixins.scss, plugins/plugin-client-common/web/scss/components/Wizard/Footer.scss, plugins/plugin-client-common/web/scss/components/Wizard/Guide.scss, plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss, plugins/plugin-electron-components/src/components/Screenshot.tsx
This PR also
- fixes failures in run button for code blocks in guides
- adds a "this step needs a choice" UI to Guide
It does not yet enable the Run button.
=> feat(plugins/plugin-client-common): some groundwork for for running choice-free guidebooks

plugins/plugin-client-common/web/scss/components/Wizard/Guide.scss
We already have a height:100% rule. Together, this will give us the desired space-filling grid.
=> fix(plugins/plugin-client-common): tiles in guide should have width:100%

plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
We are creating a situation with nested paragraphs, which mdast-util-to-markdown does not like.
=> fix(plugins/plugin-client-common): code blocks in tips in guide are misformatted

packages/test/src/api/util.ts, plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx, plugins/plugin-client-common/src/test/core/sidebar.ts, plugins/plugin-client-common/src/test/core/splits-in-markdown.ts, plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss, plugins/plugin-client-default/src/test/core/background-tab-open.ts, plugins/plugin-core-support/src/test/core-support/tab-management.ts
This PR does get fancy, for now. It only allows tabs to be renamed in an emphemeral way. Tab renamings will not, with this PR, survive a reload of Kui, nor will they "stick" to a second window.
One does so by clicking on the tab name. You will then see a normal html input effect.
Users of the future: if you want durable tab names, open an issue and we can look into this somewhat more complex scenario.
=> feat(plugins/plugin-client-common): allow tabs to be renamed

packages/core/src/main/main.ts, packages/core/src/main/spawn-electron.ts, packages/core/src/models/SubwindowPrefs.ts, packages/core/src/webapp/bootstrap/init-electron.ts
Electron finally has support, via the `additionalData` protocol, for us to fix this.
ref: https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata
=> fix(packages/core): second windows should not be stuck with env vars from initial window

plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
=> feat(plugins/plugin-client-common): when renaming a tab, Enter should blur input

plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
Ugh, the onMouseDown preventDefault is preventing editability.
=> fix(plugins/plugin-client-common): tab renaming is broken

plugins/plugin-kubectl/src/test/k8s1/apply-multi-file.ts, plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-via-table.ts, plugins/plugin-kubectl/src/test/k8s3/run.ts, plugins/plugin-kubectl/tests/data/k8s/bunch/deployment.yaml, plugins/plugin-kubectl/tests/data/k8s/bunch/hpa.yaml, plugins/plugin-kubectl/tests/data/k8s/bunch/pod.yaml, plugins/plugin-kubectl/tests/data/k8s/crashy.yaml, plugins/plugin-kubectl/tests/data/k8s/diff/modified-crashy.yaml, plugins/plugin-kubectl/tests/data/k8s/event-generator.yaml, plugins/plugin-kubectl/tests/data/k8s/headless/pod.yaml, plugins/plugin-kubectl/tests/data/k8s/headless/pod2.yaml, plugins/plugin-kubectl/tests/data/k8s/hpa.yaml, plugins/plugin-kubectl/tests/data/k8s/job.yaml, plugins/plugin-kubectl/tests/data/k8s/kubectl-logs-two-containers.yaml, plugins/plugin-kubectl/tests/data/k8s/many-pods-with-duplicates.yaml, plugins/plugin-kubectl/tests/data/k8s/many-pods.yaml, plugins/plugin-kubectl/tests/data/k8s/tab-completion-2.yaml, plugins/plugin-kubectl/tests/data/k8s/tab-completion.yaml, plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts, plugins/plugin-kubectl/tests/lib/k8s/utils.js
Hmm, bitnami seems to have removed (or made private?) all of their images.
=> test: stop using quay.io/bitnami/nginx

plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
PTY content is picking up rules from patternfly.
=> fix(plugins/plugin-client-common): pty output paragraphs have too much spacing

plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
This is due to a change in the patternfly css. Nested tabs appear to overlap with the enclosing tabs.
=> fix(plugins/plugin-client-common): fix for nested tabs squishing

packages/builder/dist/electron/builders/electron.js
If clients, when building an electron distribution, specify `KUI_KEEP_NODE_MODULES`, then *all* node_modules will be kept in the electron builds. By specifying `KUI_KEEP_NODE_MODULE`, then clients may choose a list of node_modules to keep; generally this may be a regular expression, except that it is not allowed to use ^ or $ symbols.
Right now, we exclude almost all node_modules from the electron build, allowing only a tiny and fixed subset through (those to facilitate the build itself). This is because the webpack bundles include all of the actual logic...
However, it can be helpful for clients to have access to a subset of node_modules, of their design.
Also, our exclusion list has some items intended to exclude directories in the main Kui repo, but without a `^` in the regexp, and …
=> feat: allow clients to specify that some, or all node_modules should persist in electron builds

plugins/plugin-client-common/src/controller/guide.ts
There's no point in opening a new tab, if this is the first operation in a new window...
=> fix: guide command should not open a new tab when in popup mode

plugins/plugin-client-common/src/index.ts
=> chore: export some mising types from plugin-client-common

plugins/plugin-client-common/src/components/Content/Commentary.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/guide/index.tsx, plugins/plugin-client-common/src/index.ts
=> feat: export `CardResponse` to allow for consistent wrappering of "commentary" responses

plugins/plugin-client-common/src/test/core/markdown/wizards.ts, plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md, plugins/plugin-s3/ibm/src/plugin.ts, plugins/plugin-s3/ibm/src/preload.ts, plugins/plugin-s3/src/isEnabled.ts, plugins/plugin-s3/src/plugin.ts, plugins/plugin-s3/src/preload.ts
This one has a high startup cost, and some clients do not need this functionality in headless mode. Clients that set the environment variable `KUI_S3=false` will avoid those startup costs.
=> feat: allow plugin-s3 to be selectively disabled

packages/core/src/main/spawn-electron.ts
We are trying to use an undefined variable, but we will flow a different way, in this case. We just have a missing null pointer check in `spawn-electron`.
=> fix(packages/core): headless-to-ui transition can result in errors in getAppPath

plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
=> fix: zooming fonts in the playground notebook do not increase height of tab bar

package-lock.json, plugins/plugin-bash-like/package.json, plugins/plugin-bash-like/src/pty/copy.ts, plugins/plugin-client-common/src/components/Content/Scalar/XtermDom.tsx
we aren't properly handling the whitespace that xterm.js places in the `textContent` field.
This PR also adds support for strikethrough text.
=> fix: Xterm UI may miss whitespace

plugins/plugin-bash-like/src/pty/copy.ts
when capturing the output of the pty, line wrapping causes odd behavior, with lines squashed together strangely
this might be due to some webpack or typescript behavior for variables declared but never defined before first use? we were assuming it was `undefined`, but... this doesn't appear to be the case? in any case, we shouldn't be using variables with no defined value.
=> fix: xterm copy-out logic is erratic with line wrapping

plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
This allows us to display ansi-colored text. e.g.
```ansi
--8<-- "some-log-file-with-ansi-characters.txt"
```
=> feat(plugins/plugin-client-common): add `ansi` language tag support for markdown code blocks

plugins/plugin-client-common/src/components/Content/Markdown/components/code/filter.ts, plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
```json
---
include: thisField
---
--8<-- "foo.json"
```
```json
---
exclude:
- thisField
- thatField
---
--8<-- "foo.json"
```
```json
---
language: yaml
---
--8<-- "foo.json"
```
```json
---
languageFrom: language
include: source
---
--8<-- "foo.json"
```
Where an example foo.json might be
```json
{
"language: "python",
"source": "...some python code",
"thisField": ...,
"thatField": ...
}
```
=> feat: allow guidebooks to selectively include fields from source material

packages/builder/dist/electron/builders/notarize.js
I don't know why it's not the default, but `electron-notarize` uses the "legacy" notarization method by default. This can take several minutes, in the best of times.
This PR enables use of the newer `notarytool`. My experiments so far show that it can notarize in seconds, versus minutes.
ref: https://github.com/electron/electron-notarize#method-notarizeopts-promisevoid
=> fix: switch to using `notarytool` when notiarizing on macOS

packages/webpack/headless-webpack.config.js
we already turn "MyProduct" into "myproduct.js" as a bundle file name. i think it also makes sense to turn "My Product" into "my-product.js", to avoid downstream complications with filenames with spaces.
=> fix: if productName contains spaces, headless bundle files have spaces

plugins/plugin-client-common/web/css/static/ui.css
This PR uses a bit less transparency for the `semi-transparent` css class (which is used to render "dim" colors).
=> fix: dim colors in xterm output can have low contrast

plugins/plugin-s3/src/index.ts, plugins/plugin-s3/src/isEnabled.ts
Recently, we added a feature to plugin-s3 to allow clients to selective disable the plugin (by setting KUI_S3=false). This was done to allow certain modes, e.g. a headless mode, to avoid the costs of the plugin-s3 preloader.
However, this choice was not revocable, later in the run. Let's add that feature. This PR adds an `enable()` async function to plugin-s3.
=> feat(plugins/plugin-s3): allow dynamic enabling of s3 plugin

plugins/plugin-bash-like/src/pty/client.ts
This is due to a race condition in the initial `getSize()` call. We aren't handling isNaN on all paths.
=> fix(plugins/plugin-bash-like): xterm alt buffer mode often not full screen

plugins/plugin-kubectl/oc/src/controller/oc/get/projects.ts
Fixes #8928
This is an imperfect PR, in that the resulting Kui table shows "Namespace" in the title.
=> fix: `oc get projects` fails

packages/core/src/index.ts
This can be used for plugins that add main-process logic, but want to open up a Kui window to execute a command. It is used by the core menu logic to do just this.
=> feat: export tellRendererToExecute API from `(at)kui-shell/core`

packages/core/src/main/spawn-electron.ts
plugins are allowed to extend electron main process functionality, such as to add a tray menu. but we aren't passing them the capability to create new windows. this PR fills that gap.
=> feat: pass createWindow to electron-main plugins

plugins/plugin-client-common/src/components/Content/Markdown/components/img.tsx
e.g.
```markdown
```
Restrictions:
- only svgs for now
- the subdirectory must either be "icons" or "images" (it was "icons" in the above example)
=> feat(plugins/plugin-client-common): allow markdown images to point to client images

packages/core/src/webapp/tab.ts, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts, plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx, plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Currently, we only allow controllers to add class to splits.
=> feat: allow controllers to add class to top-level tabs

plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
The current TopTabStripe mixin is too general. This new mixin specifies only the header.
=> feat: add KuiHeader mixin

packages/core/src/main/spawn-electron.ts, packages/core/src/models/SubwindowPrefs.ts, packages/core/src/webapp/bootstrap/client.ts, packages/core/src/webapp/bootstrap/init-electron.ts, packages/react/src/index.tsx, plugins/plugin-client-common/src/components/Client/Kui.tsx
We weren't allowing the `new-window` main API to pass through a desired window title.
```typescript
const { ipcRenderer } = await import("electron")
ipcRenderer.send(
"synchronous-message",
JSON.stringify({
operation: "new-window",
title: productName + " Popup",
initialTabTitle: "Hello There",
width,
height,
argv: ["my", "command", myCommandArg1],
})
)
```
=> feat: improved support for passing through window titles for new windows

packages/core/src/main/spawn-electron.ts
The work from https://github.com/kubernetes-sigs/kui/pull/8942
does not guard against `subwindowPrefs` being undefined
=> fix(packages/core): regression due to title work, new windows may result in null pointer exception

packages/webpack/headless-webpack.config.js
=> fix: allow electron-main plugins to incorporate template pngs into the webpack build

packages/core/src/index.ts, packages/core/src/main/spawn-electron.ts
```typescript
{
title: string
width: number
height: number
}
```
This PR also exports a `CreateWindowFunction` type from `@kui-shell/core`
=> feat: createWindow API should accept options for the new window

packages/core/src/index.ts, packages/core/src/main/spawn-electron.ts, packages/core/src/models/SubwindowPrefs.ts
Right now, it only supports creating a window to execute a Kui command line.
This PR also updates the `createWindow` API so that it returns a `Promise` that resolves when the window is closed.
=> feat: `createWindow` API should allow window creation from URL

packages/core/src/main/menu.ts, packages/core/src/main/spawn-electron.ts, packages/core/src/models/SubwindowPrefs.ts
if the client is using Kui to show a random web page, Kui's main menu.ts still intercepts Ctrl/Cmd+w as a request to close a Kui tab.
=> fix: Ctrl/Cmd+W in windows opened to be non-kui does nothing

packages/webpack/webpack.config.js
=> fix(packages/webpack): use of native modules in main can cause renderer webpack build to fail

packages/webpack/headless-webpack.config.js
=> fix(packages/webpack): headless webpack builds fail with asciinema casts

packages/webpack/headless-webpack.config.js
we have type: 'ignore-loader', but it should be use: 'ignore-loader'
=> fix(packages/webpack): cast support in headless webpack config is wrong

plugins/plugin-client-common/src/components/Client/StatusStripe/Settings.tsx
I think it's pretty obvious what it is? And the tooltip, being in the corner and almost as big as the component itself, is rather annoyingly in the way more often than not.
=> fix: tooltip for theme switcher is annoying and not helping

plugins/plugin-s3/src/providers/aws.ts
Up till now, we only supported a single profile. Worse, if the user had more than one *including* a profile named "default", we would always use default; otherwise we would pick the first.
BREAKING CHANGE: with this PR, the aws s3 mount points are of the form `/s3/aws/default` and `/s3/aws/myOtherProfile`. Any logic that was hard-coding an expectation that `/s3/aws/mybucket` would work must now specify the profile explicitly e.g. `/s3/aws/default/mybucket`
Also, neither the aws config/credentials nor the `aws` CLI support encoding the endpoint url in a config file. See https://github.com/aws/aws-cli/issues/1270
Lacking this support, for now, this PR assumes that, if needed, a profile's `endpoint_url` is a config key with that name in the `config` file, e.g.
```conf
[default] …
```
=> feat: support for multiple s3 profiles

plugins/plugin-client-default/config.d/notebooks.json, plugins/plugin-kubectl/src/non-headless-preload.ts
This PR does not remove them from the repo, just removes them from the default client UI.
This should alleviate some of the excessive GETs from github.com while building webpack; the knative guidebooks reference source material from github...
=> fix: remove integration of unstable knative guidebooks

plugins/plugin-core-support/src/test/core-support/commentary-util.ts, plugins/plugin-core-support/src/test/core-support/commentary.ts
Apparently hitting escape when the editor compnent is *not* focused does not result in the editor compnent cancelling itself and disappearing.
=> test: edit commentary test is unstable

plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
Maybe from the recent monaco-editor version bumps
=> fix: monaco-editor cursor color now has low contrast

plugins/plugin-client-common/src/components/Client/Sidebar.tsx
=> fix: disable escape handler for sidebar

plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/test/k8s1/apply-pod.ts
=> fix(plugins/plugin-kubectl):  does not get from namespace

plugins/plugin-kubectl/src/lib/view/formatTable.ts
=> fix(plugins/plugin-kubectl): in split screen mode, PVC and PV tables horizontally overflow

plugins/plugin-kubectl/src/controller/kubectl/deployment.ts
=> fix(plugins/plugin-kubectl): deployments are red even though the pods may be yellow

plugins/plugin-kubectl/src/lib/view/modes/Events.tsx
Recently #9001 added a resourceVersion join key to the events drilldown query. This PR switches us over to `uid`
=> fix(plugins/plugin-kubectl): regression in events drilldown

plugins/plugin-client-common/src/components/Views/Confirm.tsx, plugins/plugin-client-common/src/controller/confirm.ts
this is annoying. if i have a table on the left, and a sidecar drilldown on the right, then click the delete button in the sidecar... the delete command is executed on the left, which scrolls my table offscreen. if i'm trying to delete multiple elements, this is annoying
=> fix(plugins/plugin-client-common): sidecar delete button from right split executes command in left split

plugins/plugin-client-common/src/components/spi/DescriptionList/impl/PatternFlyLabelList.tsx, plugins/plugin-client-common/web/scss/components/DescriptionList/PatternFlyLabelList.scss
1) our dom structure is not easy to copy/paste; e.g. triple click does not work, and our text has a key | value, which is not standard
2) we should add a click-to-copy feature
this pr changes key | value to key=value, and enables triple-click select and adds a click-to-copy
=> feat(plugins/plugin-client-common): kubectl labels ui should be more easily copy/pasteable

plugins/plugin-kubectl/src/tray/menus/index.ts, plugins/plugin-kubectl/src/tray/menus/resources/open.ts
1. make New Window operation explicit
2. Resources -> Kubernetes Resources
=> fix(plugins/plugin-kubectl): minor refinements to tray menu

.eslintignore, package-lock.json, package.json, plugins/plugin-client-common/src/components/Client/StatusStripe/MeterWidgets.tsx, plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx, plugins/plugin-client-common/src/components/Client/TabContainer.tsx, plugins/plugin-client-common/src/components/Client/TabContent.tsx, plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx, plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx, plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarContainer.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/ActiveISearch.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx, plugins/plugin-client-common/src/components/spi/Loading/model.ts, plugins/plugin-kubectl/src/test/k8s1/config-map.ts
This PR fixes a few compilation errors caught by the more strict `tsc` in 4.8.2.
This PR also fixes a few long-standing eslint errors.
=> chore: bump typescript 4.7.4 -> 4.8.2

package-lock.json, plugins/plugin-client-common/package.json
This should save about 40MiB of unpacked on-disk space!
=> chore: bump to madwizard 0.22.0 to pick up much-reduced bundle size

plugins/plugin-kubectl-tray-menu/src/tray/events.ts, plugins/plugin-kubectl-tray-menu/src/tray/renderer.ts
Dangit, local testing didn't catch this because of leftover compiled javascript modules.
=> fix: tray menu does not appear

plugins/plugin-kubectl-tray-menu/src/tray/events.ts, plugins/plugin-kubectl-tray-menu/src/tray/renderer.ts
[kui-1203 7ee72e0c1] fix: tray menu does not appear
Date: Wed Sep 7 18:16:35 2022 -0400
2 files changed, 2 insertions(+), 2 deletions(-)
=> cherry picks for 12.0.3

package-lock.json, plugins/plugin-bash-like/package.json, plugins/plugin-bash-like/src/pty/client.ts, plugins/plugin-kubectl/package.json, plugins/plugin-kubectl/src/lib/view/modes/Terminal.tsx
Caution: this introduces some breaking changes in the xterm API. Nothing at the Kui level has changed, but if other plugins are assuming the `xterm` npm comes in via kui, they may encounter breaking changes.
This PR also introduces the use of the webgl renderer for the kubectl Terminal and Logs tabs.
=> feat: bump to xtermjs 5.0.0

plugins/plugin-client-common/src/components/Content/Editor/index.tsx, plugins/plugin-client-common/web/scss/components/Sidecar/Tree.scss, plugins/plugin-kubectl/src/lib/view/modes/Annotations.ts, plugins/plugin-kubectl/src/lib/view/modes/Labels.ts, plugins/plugin-kubectl/src/lib/view/modes/yaml.ts, plugins/plugin-kubectl/src/test/k8s3/labels.ts, plugins/plugin-kubectl/src/test/k8s4/edit.ts
1) Annotations tab DescriptionList->Editor
2) in that view, also attempt to parse out annotations that are json values, and fold them into the tree presented in the editor 3) Labels tab funky custom UI->Editor
4) in *that* view, try to map '10' -> 10
5) in YAML tab, don't show .metadata.annotations, .metadata.labels, and .metadata.managedFields 6) in Editor view, fold to depth 3; previously folded to depth 2 mostly because of messy managedFields
Fixes #9072
=> feat: update Annotations and Labels tabs to use editor view for json values

package-lock.json, plugins/plugin-electron-components/package.json
=> fix: plugin-electron-components is missing stated needle dependence

.github/workflows/test.yaml
We are using `actions/checkout@v2` and `actions/setup-node@v1`. Both are deprecated, mostly due to the deprecation of node12, upon which apparently those older versions rely.
=> chore: bump github actions/checkout and actions/setup-node to v3

plugins/plugin-kubectl/helm/src/controller/helm/list.ts, plugins/plugin-kubectl/helm/src/controller/helm/status.ts, plugins/plugin-kubectl/src/lib/view/formatTable.ts
We can make the drilldown output even better, but at least with this it doesn't error out.
Fixes #9123
=> fix: helm ls -> click results in error

package-lock.json, package.json, plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts, plugins/plugin-kubectl/odo/src/controller/odo/project/list.ts, plugins/plugin-kubectl/odo/src/model/Project.ts, plugins/plugin-kubectl/src/controller/client/direct/custom-columns.ts, plugins/plugin-kubectl/src/controller/kubectl/exec.ts, plugins/plugin-kubectl/src/index.ts, plugins/plugin-kubectl/src/lib/model/resource.ts
BREAKING CHANGE: typescript 4.9 is more rigorous about enforcing certain generic types. this identified issues with some types in plugin-kubectl :(
- KubeItems is now parametric over KubeItems<KubeStatusType, ItemType>
- KubePartial is the same, now
=> chore: bump typescript 4.8.4 -> 4.9.4

plugins/plugin-kubectl/src/lib/model/resource.ts, plugins/plugin-kubectl/src/lib/view/modes/Annotations.ts
=> fix: kubernetes resource Annotations tab can show just `{}`

packages/core/src/models/mmr/types.ts, plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx, plugins/plugin-kubectl/src/controller/kubectl/edit.ts, plugins/plugin-kubectl/src/controller/kubectl/exec-to-markdown.ts, plugins/plugin-kubectl/src/controller/kubectl/exec.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts, plugins/plugin-kubectl/src/lib/view/modes/DeleteButton.tsx, plugins/plugin-kubectl/src/lib/view/modes/EditButton.tsx, plugins/plugin-kubectl/src/lib/view/modes/ShowNodeOfPodButton.tsx, plugins/plugin-kubectl/src/lib/view/modes/ShowOwnerButton.tsx, plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Generic.ts, plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Namespace.ts, plugins/plugin-kubectl/src/lib/view/modes/configmap-summary.ts, plugins/plugin-kubectl/src/lib/view/modes/involved-object.ts, plugins/plugin-kubectl/src/lib/view/modes/pods.ts, plugins/plugin-kubectl/src/lib/view/modes/show-crd-managed-resources.ts, plugins/plugin-s3/src/providers/local-minio.ts
These are mostly to defer loading some node modules until they are actually needed.
I don't think this PR saves a huge chunk of time, maybe 30-50ms.
=> fix: a few minor load time optimizations

packages/core/package.json, packages/react/package.json, plugins/plugin-bash-like/fs/package.json, plugins/plugin-bash-like/package.json, plugins/plugin-carbon-themes/package.json, plugins/plugin-client-common/package.json, plugins/plugin-client-default/package.json, plugins/plugin-core-support/package.json, plugins/plugin-core-themes/package.json, plugins/plugin-electron-components/package.json, plugins/plugin-git/package.json, plugins/plugin-kubectl-tray-menu/package.json, plugins/plugin-kubectl/helm/package.json, plugins/plugin-kubectl/logs/package.json, plugins/plugin-kubectl/oc/package.json, plugins/plugin-kubectl/odo/package.json, plugins/plugin-kubectl/package.json, plugins/plugin-patternfly4-themes/package.json, plugins/plugin-s3/package.json
this might not help much, but by adding side-effect: false to a module, we are telling webpack that it can do more splitting and tree shaking optimizations
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> fix: add side-effect: false

packages/webpack/webpack.config.js
fwiw, async script loading currently does not work, due to the way we set up the nonce. there is an inline script in the index.ejs template that uses kuiNonce, but the variable is not declared there (i think due to the way, at least this used to be required, the way the nonce is initialized)
=> fix: use defer script loading

package-lock.json, plugins/plugin-client-common/package.json
=> fix: bump to madwizard 2.4.11 to pick up missing Profile export

plugins/plugin-bash-like/src/pty/client.ts
Regression from the xterm 5.0.0 -> 5.1.0 update.
=> fix: xterm is not sized to viewport

plugins/plugin-electron-components/src/components/UpdateChecker.tsx
=> fix: UpdateChecker may call setState before mount

plugins/plugin-client-default/src/index.tsx
=> fix: CurrentContext/Namespace widgets can be lazily loaded

package-lock.json, plugins/plugin-kubectl/package.json
Strange, i hate npm. plugin-kubectl floats its xterm dependences, but apparently the prior versions were pinned by our package-lock.
=> fix: plugin-kubectl still pulls in prior xterm deps

plugins/plugin-client-common/src/components/Client/Sidebar.tsx
i think this helps. without this change, the user has to click to open a guidebook from the sidebar, then click again to toggle the sidebar closed
=> fix: auto-toggle the sidebar closed after user clicks to select an entry in the sidebar

plugins/plugin-client-common/notebooks/code-blocks.md, plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts, plugins/plugin-client-common/src/components/Content/Markdown/index.tsx, plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
also a few cleanups:
1) delay import of `turndown` module; it is rarely used and takes 100ms to load
2) remove old and untested and not-used snapshot logic in Markdown component
3) always show status *and* badge in Inputv2 (i think this was the root cause of the nominal bug)
=> fix: clicking run on guidebook code block can cause all code block text to disappear

plugins/plugin-client-common/src/components/Content/Commentary.tsx
=> fix: linked Commentary does not update until a tab switch

plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
=> fix: remove right-border on brand (e.g. "Kui |" -> "Kui")

plugins/plugin-kubectl/src/lib/view/modes/EditButton.tsx
=> fix(plugins/plugin-kubectl): edit button ignores context and kubeconfig options

plugins/plugin-client-common/src/components/Client/Kui.tsx
This can be forced by enabling React.StrictMode (which intentionally repeats component instantiation)
=> fix: Kui component may mount client notebooks multiple times

plugins/plugin-madwizard/src/preload.ts
=> fix: plugin-madwizard should not load notebook vfs in headless

packages/core/src/webapp/defaults.ts
Becauase drilldown splits the window vertically (now).
=> fix: increase default height of popup window

plugins/plugin-bash-like/fs/src/vfs/index.ts
e.g. we might mount in an order that results in /kui/madwizard being overridden by /kui (both being VFS mounts) this is due to a bug in the sorting comparator
=> fix: race condition in vfs mounting can result in ENOENT

bin/kubectl-kui
this is no longer supported (not without console warnings) in the latest electron (22)
NOTE: the production kubectl-kui does not have this problem; see packages/builder/dist/electron/build.sh
=> fix: development bin/kubectl-kui should not set NODE_OPTIONS

plugins/plugin-madwizard/web/scss/components/Terminal/_index.scss
=> fix: plugin-madwizard's Terminal component does not pull in base xterm.scss

packages/webpack/webpack.config.js
we already had one for `node:readline`
=> fix: add a browser replacement for require('readline')

plugins/plugin-madwizard/components/src/PlaygroundTerminal.tsx
in Kui, this just means "response was successful"
=> fix: PlaygroundTerminal should skip  responses

packages/core/src/models/CommentaryResponse.ts, plugins/plugin-client-common/src/components/Content/Commentary.tsx, plugins/plugin-client-common/src/components/Content/Markdown/Simple.tsx, plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx, plugins/plugin-client-common/src/controller/commentary.ts
Sometimes, the client knows that a given markdown file does not have tabs, tips, etc. We can speed up the processing of these.
=> feat: add <SimpleMarkdown/> component and `commentary --simple` to allow for fastpath

packages/core/src/core/capabilities.ts
`Capabilities.inBrowser()` should return true when prescanning for command registrations for offline clients.
=> fix: prescan for offline clients may fail to register commands

plugins/plugin-client-common/notebook/src/load.ts, plugins/plugin-client-common/src/components/Content/Editor/DiffEditor.tsx, plugins/plugin-client-common/src/components/Content/Editor/RevertFileButton.tsx, plugins/plugin-client-common/src/components/Content/Editor/SaveFileButton.tsx, plugins/plugin-client-common/src/components/Content/Editor/index.tsx
This also removes a few uses of plugin-bash-like from plugin-client-common. The two are now orthogonal.
=> chore: optimize plugin-client-common imports of kui-shell/core (second pass)

packages/webpack/webpack.config.js
It is way too big to ship with kui itself. But if clients want to use it, they can npm install it themselves, and then run the watchers/builders with `WEBPACK_ANALYZER=true`
=> fix: allow clients to build with client-provided webpack-bundle-analyzer

package-lock.json, package.json, packages/core/package.json, packages/core/src/main/spawn-electron.ts, plugins/plugin-bash-like/package.json, plugins/plugin-bash-like/src/pty/prefetch.ts
This PR also removes some old unused deps from the core. Doing this identified a missing dep in plugin-bash-like (on properties-parser). This PR thus also adds that dep to plugin-bash-like, and adds the properties-parser types, and then shifts a require to an import.
=> fix: remove electron/remote dep from core

packages/core/src/main/spawn-electron.ts
- We should be using the `webpackIgnore: true` magic comment, rather than the silly hack we had from #9265
- #9265 missed the second import of electron/remote
=> fix: improved fix for externalizing electron/remote

package.json, packages/core/src/api/Client.ts, packages/webpack/bin/watch.sh, packages/webpack/build.sh, packages/webpack/offline.js, packages/webpack/webpack.config.js, plugins/plugin-client-default/src/index.tsx, plugins/plugin-proxy-support/src/preload.ts
Either run `npm run watch:browser:offline` or start up the webpack watchers yourself with `IS_OFFLINE_CLIENT=true`
=> feat: allow quick testing of fully offline clients

packages/builder/bin/prescan.sh
if you have a `notebooks/` directory in your `at-kui-shell/client` plugin, this PR allows you to structure your guidebooks into subdirectories.
it also fixes mysterious "*.json" files being mounted into the kui vfs.
=> fix: prescan for /kui/client guidebooks doesn't handle nesting

packages/builder/bin/prescan.sh, packages/core/src/repl/error.ts, packages/webpack/webpack.config.js, plugins/plugin-bash-like/fs/src/vfs/TrieVFS.ts, plugins/plugin-client-common/notebook/src/load.ts, plugins/plugin-client-common/src/components/Client/Sidebar.tsx, plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts, plugins/plugin-client-common/src/controller/commentary.ts, plugins/plugin-core-support/src/notebooks/vfs/index.ts, plugins/plugin-madwizard/components/src/Playground.tsx, plugins/plugin-madwizard/components/src/plugin.ts
1. adds `madwizard playground file <filepath>`
2. adds `commentary delegate <delegateCommand> <filepath>` which wraps a maximized CommentaryResponse around the given `<delegateComand> <filepath>`
=> feat: improve support for showing Playground over a given filepath

plugins/plugin-kubectl/helm/src/controller/helm/status.ts, plugins/plugin-kubectl/helm/src/test/helm/helm.ts, plugins/plugin-kubectl/src/controller/kubectl/options.ts
Show managed resources and values, and offer a drilldown to managed resources.
Note: in this case, i clicked on the Show Managed Resources, but (at the time) there were none. This drilldown assumes that the helm chart uses the kubernetes label protocol of `app.kubernetes.io/name=${chartName}`
=> feat: improve helm drilldown view

plugins/plugin-kubectl/src/lib/view/modes/Containers.ts, plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Pod.ts
This can happen for pods that aren't ready yet, where there is a spec.containers but no status.containerStatuses. This PR also fixes a similar issue with the Pod summary view.
=> fix: pod Containers tab may spin forever

plugins/plugin-kubectl-core/src/index.ts, plugins/plugin-kubectl-core/src/resource.ts, plugins/plugin-kubectl/src/lib/view/modes/ShowBoundVolumeButton.ts, plugins/plugin-kubectl/src/lib/view/modes/ShowPVCsButton.ts, plugins/plugin-kubectl/src/non-headless-preload.ts
=> feat: improve Pod->PVC->PV drilldowns

package-lock.json, plugins/plugin-kubectl/package.json
=> fix: plugin-kubectl is missing explicit dep on plugin-kubectl-core

package.json
https://github.com/okonet/lint-staged#v10
> From v10.0.0 onwards any new modifications to originally staged files will be automatically added to the commit. If your task previously contained a git add step, please remove this. The automatic behaviour ensures there are less race-conditions, since trying to run multiple git operations at the same time usually results in an error.
=> chore: remove git add from lint-staged tasks

package-lock.json, plugins/plugin-client-common/package.json
This should resolve a security warning, as it brings in an outdated version of `frontmatter` 3.0.2
=> fix: remove unused and outdated remark-code-frontmatter dep

package-lock.json, plugins/plugin-s3/package.json, plugins/plugin-s3/src/providers/model.ts, plugins/plugin-s3/src/vfs/index.ts
we have been using a custom branch of minio for a long while now... based on some egregious bugs in minio a long while back. let's try moving to the mainline npm.
this should hopefully help us keep up with security fixes... there is an outstanding security issue open against xml2js, though minio has yet to address it.
=> fix: bump minio to avoid using custom branch

packages/builder/bin/prescan.sh
=> fix: sigh on windows bash pwd has /c/ but nodejs require does not like that

packages/core/src/main/spawn-electron.ts
This works around an issue where the `additionalData` parameter is `null` when using "popup window" mode. Since it is null, env vars, etc. from the second instance will not be transmitted to the first. But for now, we need to fix the bad behavior where one cannot even open a second window.
Fixes #9351
=> fix: second-instance additionalData may be null

packages/proxy/Dockerfile, packages/proxy/Dockerfile.http, tools/travis/microk8s.sh
/kind cleanup
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
=> fix: use dl.k8s.io, not kubernetes-release bucket
