kubernetes-sigs/kui

- packages/app/src/util/mimic-dom.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> fix(plugins/plugin-proxy-support): try to unwind the returned fakedom in proxy executor

- packages/app/src/webapp/views/sidecar.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/cat-to-sidecar.ts
- plugins/plugin-bash-like/tests/data/README.md
- plugins/plugin-bash-like/tests/data/big.json
- plugins/plugin-bash-like/tests/data/small.json
> fix(plugins/plugin-bash-like): bug fix for pty versus large json files

- .eslintrc.json
- packages/app/src/core/plugin-assembler.ts
- packages/app/src/core/plugins.ts
- packages/app/src/webapp/views/sidecar.ts
- plugins/plugin-bash-like/src/lib/util/json.ts
- plugins/plugin-grid/src/lib/cmds/grid.ts
- plugins/plugin-grid/src/lib/util.ts
- plugins/plugin-openwhisk-debug/src/plugin.ts
- plugins/plugin-openwhisk/src/lib/models/openwhisk-entity.ts
- plugins/plugin-openwhisk/src/lib/views/cli/activations/entity.ts
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
- plugins/plugin-openwhisk/src/views.ts
I'm going to add them here: #1759.
> style: remove @typescript-eslint/ban-types rule

- .eslintrc.json
- packages/app/src/test/core/about.ts
- packages/app/src/test/core/basic-functionality.ts
- packages/app/src/test/core/command-not-found-suggestions.ts
- packages/app/src/test/core/error-handling.ts
- packages/app/src/test/core/version.ts
- plugins/plugin-bash-like/src/test/bash-like/blank-lines.ts
- plugins/plugin-bash-like/src/test/bash-like/cd.ts
- plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
- plugins/plugin-bash-like/src/test/bash-like/echo.ts
- plugins/plugin-bash-like/src/test/bash-like/export.ts
- plugins/plugin-core-support/src/test/core-support/base64.ts
- plugins/plugin-core-support/src/test/core-support/clear.ts
- plugins/plugin-core-support/src/test/core-support/help.ts
- plugins/plugin-core-support/src/test/core-support/history.ts
- plugins/plugin-core-support/src/test/core-support/screenshot.ts
- plugins/plugin-core-support/src/test/core-support/tab-completion.ts
- plugins/plugin-core-support/src/test/core-support/text-search.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
- plugins/plugin-editor/src/test/editor/edit.ts
- plugins/plugin-k8s/src/test/k8s1/tab-completion.ts
> style: lint import/no-duplicates

- packages/app/src/webapp/bottom-stripe.ts
- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/src/webapp/views/registrar/badges.ts
- packages/app/src/webapp/views/registrar/modes.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-k8s/package.json
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/lib/model/resource.ts
- plugins/plugin-k8s/src/lib/view/modes/conditions.ts
- plugins/plugin-k8s/src/lib/view/modes/containers.ts
- plugins/plugin-k8s/src/lib/view/modes/crds.ts
- plugins/plugin-k8s/src/lib/view/modes/description.ts
- plugins/plugin-k8s/src/lib/view/modes/icon.ts
- plugins/plugin-k8s/src/lib/view/modes/last-applied.ts
- plugins/plugin-k8s/src/lib/view/modes/pods.ts
- plugins/plugin-k8s/src/preload.ts
- plugins/plugin-tekton/src/preload.ts
> feat(plugins/plugin-k8s): initial olm support

- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
> fix(packages/app): tab UI refinements

- packages/app/src/webapp/bottom-stripe.ts
- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/web/css/ui.css
- plugins/plugin-k8s/src/lib/model/resource.ts
- plugins/plugin-k8s/src/preload.ts
- plugins/plugin-operator-framework/README.md
- plugins/plugin-operator-framework/package.json
- plugins/plugin-operator-framework/src/preload.ts
- plugins/plugin-operator-framework/src/view/modes/crds.ts
- plugins/plugin-operator-framework/src/view/modes/description.ts
- plugins/plugin-operator-framework/src/view/modes/icon.ts
- plugins/plugin-operator-framework/src/view/modes/packages.ts
> feat: plugin-operator-framework

- packages/app/src/core/plugin-assembler.ts
> style: remove unused eslint-disable-line

- packages/app/templates/index.html
> fix(packages/app): prompt CWD appears clickable but is not

- packages/app/src/core/userdata.ts
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
- plugins/plugin-k8s/src/lib/view/modes/conditions.ts
- plugins/plugin-operator-framework/package.json
- plugins/plugin-operator-framework/src/controller/olm.ts
- plugins/plugin-operator-framework/src/plugin.ts
- plugins/plugin-operator-framework/src/view/modes/packages.ts
plus some small core UI and k8s fixes for tables in sidecar
Fixes #1783
> feat: experimental olm commands

- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-k8s/src/lib/view/formatTable.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
> fix: sidecar full screen behavioral tweaks

- .travis.yml
- package.json
- tools/travis/test/install.sh
> [WIP] chore: auto publish npm to dev channel

- packages/app/src/core/plugins.ts
- packages/kui-builder/bin/link-source-assets.sh
> feat: support for javascript-coded plugins

- packages/kui-builder/package.json
> chore: update ESLint deps

- .eslintrc.json
- packages/app/src/core/command-tree.ts
- packages/app/src/core/plugin-assembler.ts
- packages/app/src/core/plugins.ts
- packages/app/src/core/repl.ts
- packages/app/src/core/usage-error.ts
- packages/app/src/core/userdata.ts
- packages/app/src/main/headless-pretty-print.ts
- packages/app/src/main/headless.ts
- packages/app/src/main/main.ts
- packages/app/src/main/spawn-electron.ts
- packages/app/src/models/plugin.ts
- packages/app/src/test/core/about.ts
- packages/app/src/test/core/basic-functionality.ts
- packages/app/src/test/core/command-not-found-suggestions.ts
- packages/app/src/test/core/error-handling.ts
- packages/app/src/test/core/version.ts
- packages/app/src/util/mimic-dom.ts
- packages/app/src/webapp/bootstrap/boot.ts
- packages/app/src/webapp/bootstrap/electron.ts
- packages/app/src/webapp/bootstrap/init.ts
- packages/app/src/webapp/bottom-stripe.ts
- packages/app/src/webapp/cli.ts
- packages/app/src/webapp/electron-events.ts
- packages/app/src/webapp/picture-in-picture.ts
- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/src/webapp/util/fetch-ui.ts
- packages/app/src/webapp/util/inject.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/src/webapp/views/table.ts
> style(packages/app): lint unused-vars

- .eslintrc.json
- packages/app/src/webapp/util/search.ts
- plugins/plugin-apache-composer/src/lib/utility/usage.ts
- plugins/plugin-k8s/src/lib/view/form.ts
- plugins/plugin-openwhisk/src/lib/models/auth.ts
I'm going to add them here: #1759.
> style: fix @typescript-eslint/camelcase rule

- plugins/plugin-k8s/src/lib/util/discovery/kubeconfig.ts
> fix(plugins/plugin-k8s): fix webpack regression by dynamically import fs-extra

- plugins/plugin-core-support/src/test/core-support/theme.ts
> chore: remove unused var

- .travis.yml
- packages/app/tests/lib/common.js
- packages/tests/bin/runMochaLayers.sh
- tools/travis/installers/openwhisk.sh
- tools/travis/test/install.sh
- tools/travis/test/script.sh
> tests: run mocha targets in parallel

- .travis.yml
> chore: cron job for nightly release

- packages/app/src/core/plugins.ts
> fix(packages/app): plugin assembler versus javascript plugins

- .eslintrc.json
- packages/app/src/core/find-file.ts
- packages/app/src/core/fuzz-testing.ts
- packages/app/src/core/userdata.ts
- packages/app/src/main/headless-pretty-print.ts
- packages/app/src/main/spawn-electron.ts
- packages/app/src/webapp/bootstrap/init.ts
- packages/app/src/webapp/cli.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/kui-builder/src/kui-dist-init.ts
- plugins/plugin-apache-composer/src/test/composer1/composer-result.ts
- plugins/plugin-k8s/src/lib/controller/auth.ts
- plugins/plugin-manager/src/lib/cmds/install.ts
- plugins/plugin-openwhisk-editor-extensions/src/lib/model/composition-persister.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
- plugins/plugin-openwhisk/src/lib/cmds/activations/roots.ts
- plugins/plugin-openwhisk/src/lib/cmds/auth.ts
- plugins/plugin-openwhisk/src/lib/cmds/load-test.ts
- plugins/plugin-openwhisk/src/lib/cmds/rm.ts
- plugins/plugin-openwhisk/src/lib/cmds/rules/every.ts
- plugins/plugin-openwhisk/src/lib/models/auth.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/headless.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/at-file-params.ts
- plugins/plugin-tutorials/src/lib/cmds/modes.ts
- plugins/plugin-tutorials/src/lib/cmds/shortcuts.ts
- plugins/plugin-wskflow/src/lib/flowCommand.ts
- plugins/plugin-wskflow/src/lib/util.ts
> style: remove @typescript-eslint/no-var-requires rule

- .eslintrc.json
- packages/app/src/webapp/cli.ts
- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/src/webapp/views/table.ts
- plugins/plugin-core-support/src/lib/admin/updater.ts
- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/lib/tab-completion.ts
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/lib/tab-completion.ts
- plugins/plugin-k8s/src/lib/view/modes/containers.ts
> style: fix @typescript-eslint/no-use-before-define rule

- .travis.yml
- tools/travis/test/script.sh
- tools/travis/test/target.d/webpack.sh
> test: minimal proxy test with k8s usage

- .eslintrc.json
- packages/app/src/core/capabilities.ts
- packages/app/src/core/command-tree.ts
- packages/app/src/core/repl.ts
- packages/app/src/core/usage-error.ts
- packages/app/src/models/execOptions.ts
- packages/app/src/util/mimic-dom.ts
- packages/app/src/webapp/models/table.ts
- packages/app/src/webapp/views/sidecar.ts
- plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts
- plugins/plugin-bash-like/src/pty/channel.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/websocket-channel.ts
- plugins/plugin-core-support/src/lib/admin/updater.ts
- plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-editor/src/lib/cmds/edit.ts
- plugins/plugin-grid/src/lib/cmds/grid.ts
- plugins/plugin-grid/src/lib/grouping.ts
- plugins/plugin-k8s/src/lib/clients/kiali.ts
- plugins/plugin-k8s/src/lib/model/resource.ts
- plugins/plugin-k8s/src/lib/util/util.ts
- plugins/plugin-openwhisk/src/lib/models/namespace.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
- plugins/plugin-wrk/src/lib/chart.ts
- plugins/plugin-wrk/src/lib/replay.ts
- plugins/plugin-wskflow/src/lib/fsm2graph.ts
> style: remove @typescript-eslint/explicit-member-accessibility rule

- clients/bin/link-universe.sh
- package.json
- packages/app/src/webapp/bootstrap/electron.ts
- packages/kui-builder/bin/compile.sh
- packages/kui-builder/bin/prescan.sh
- packages/kui-builder/dist/electron/build.sh
- packages/kui-builder/dist/electron/package-lock.json
- packages/kui-builder/dist/electron/package.json
- packages/kui-builder/dist/headless/build.sh
- packages/kui-builder/dist/webpack/build.sh
- packages/kui-builder/package.json
- packages/tests/package.json
- plugins/plugin-editor/package.json
- plugins/plugin-grid/package.json
- plugins/plugin-manager/package.json
- plugins/plugin-openwhisk-editor-extensions/package.json
- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
- plugins/plugin-openwhisk/src/plugin.ts
- plugins/plugin-tekton/src/view/flow.ts
- plugins/plugin-tutorials/package.json
- plugins/plugin-wrk/package.json
- plugins/plugin-wskflow/package.json
- tools/travis/test/install.sh
> chore: dep optimization

- .travis.yml
- packages/app/src/webapp/bottom-stripe.ts
- packages/app/templates/index.html
- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/left-tab-stripe.css
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- packages/proxy/build.sh
- packages/tests/package.json
- packages/webpack/package.json
- plugins/plugin-apache-composer/src/test/composer2/composer-create-error-handling.ts
- plugins/plugin-core-support/src/lib/repl-focus.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
- plugins/plugin-core-support/web/css/screenshot.css
- plugins/plugin-grid/src/lib/util.ts
- plugins/plugin-grid/web/css/table.css
- plugins/plugin-tekton/src/model/modes/run.ts
- plugins/plugin-wskflow/src/lib/fsm2graph.ts
this also incorporates the carbon components 10 stylesheet
Fixes #1867
> feat: update sidecar tab UI

- packages/app/web/css/ui.css
> fix(packages/app): fix for a few small carbon regressions

- .eslintignore
- .prettierignore
> chore: ignore dist from clients folder

- packages/app/src/webapp/bottom-stripe.ts
- plugins/plugin-grid/src/lib/util.ts
- plugins/plugin-wskflow/src/lib/fsm2graph.ts
> chore: fix some eslint-disable warnings

- packages/app/src/core/usage-error.ts
- packages/app/src/main/headless.ts
- packages/app/src/main/spawn-electron.ts
- packages/app/templates/index.html
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-core-support/src/test/core-support/help.ts
> fix(packages/app): tab and prompt UI refinements

- plugins/plugin-openwhisk/src/test/openwhisk1/headless.ts
> chore: remove unused code

- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
- plugins/plugin-openwhisk/tests/lib/openwhisk/openwhisk.js
- plugins/plugin-tutorials/samples/@tutorials/translation-demo/lib/en2shakespeare.js
> chore: remove unneeded comments

- plugins/plugin-core-support/src/lib/cmds/about/about.ts
- plugins/plugin-grid/src/lib/util.ts
- plugins/plugin-k8s/src/lib/util/util.ts
- plugins/plugin-k8s/src/lib/view/form.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
- plugins/plugin-openwhisk/src/lib/models/openwhisk-entity.ts
- plugins/plugin-wskflow/src/lib/fsm2graph.ts
> chore: more explicit disabled rules

- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
> fix(packages/app): more refinements to prompt

- .travis.yml
- docs/dev/customization-guide.md
- packages/app/templates/index.html
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- packages/kui-builder/lib/configure.js
- packages/webpack/webpack.config.js
- tools/travis/test/test.d/build-webpack-client.sh
> feat: allow custom clients to inject static css

- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
> fix(packages/app): more prompt and tab UI tweaks

- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
> fix(packages/app): remove some UI inconsistencies

- packages/app/src/core/settings.ts
- packages/app/src/webapp/views/table.ts
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
> feat(packages/app): allow clients to choose default table style

- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/cmds/theme.ts
> fix(plugins/plugin-core-support): clean up themes table first column

- packages/app/src/webapp/views/table.ts
> fix(packages/app): add title attr to table cells

- packages/kui-builder/lib/configure.js
> chore: remove unused import

- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
> fix(packages/app): only show prompt context in electron

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Removed reference to the wrong project that the feature request template.
> Removed Strapi references

- packages/app/src/main/main.ts
- packages/proxy/app/routes/exec.js
- packages/webpack/webpack.config.js
- plugins/plugin-bash-like/src/pty/channel.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-bash-like/src/pty/stdio-channel.ts
> feat: multi-tenant proxy

- packages/app/src/core/settings.ts
- packages/app/src/webapp/views/table.ts
also add client option theme.tablePollingInterval
Fixes #1918
> fix(packages/app): decrease default table polling interval to 3s

- packages/app/src/main/main.ts
- packages/proxy/app/routes/exec.js
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-bash-like/src/pty/stdio-channel.ts
- plugins/plugin-bash-like/src/pty/websocket-channel.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
also fixes some error handling regressions due to #1907
Fixes #1923
Fixes #1920
> fix: improved proxy multitenancy

- packages/app/src/webapp/views/table.ts
> fix(packages/app): updated the remnants of table watcher with 3s default polling frequency

- packages/app/src/main/spawn-electron.ts
- packages/app/src/webapp/models/basicModels.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-k8s/src/lib/view/formatEntity.ts
> chore: fix lint warnings

- packages/app/src/core/repl.ts
- packages/app/src/core/usage-error.ts
Remove `@typescript-eslint/interface-name-prefix` rule
> chore: remove @typescript-eslint/interface-name-prefix rule

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
Remove `promise/param-names` rule.
> chore: remove promise/param-names rule

- plugins/plugin-k8s/src/test/k8s2/helm-repo-add-and-search.ts
> test: remove the helm repo after tests

- packages/app/tests/lib/common.js
- packages/proxy/app/routes/exec.js
- plugins/plugin-bash-like/src/preload.ts
- plugins/plugin-bash-like/src/pty/channel.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/prefetch.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-bash-like/src/pty/stdio-channel.ts
improve proxy support for HOME and fix plumbing to subprocess
Fixes #1952
> chore(plugins/plugin-bash-like): improve proxy versus HOME and some plumbing bugs

- plugins/plugin-apache-composer/tests/data/composer/composer-source/path-rel-require/composer_utils.js
Remove one buffer `no-deprecated-api`.
> chore: remove one buffer no-deprecated-api

- packages/kui-builder/package.json
> chore: update lint-staged version

- plugins/plugin-bash-like/src/lib/util/ascii-key-value-to-table.ts
Remove no-cond-assign disable rule.
> chore: remove no-cond-assign disable rule

- packages/app/src/main/headless.ts
Remove `no-unreachable` disable rule.
> chore: remove no-unreachable disable rule

- plugins/plugin-bash-like/src/preload.ts
- plugins/plugin-bash-like/src/pty/prefetch.ts
- plugins/plugin-bash-like/src/pty/stdio-channel.ts
> fix(plugins/plugin-bash-like): lint regressions

- packages/app/src/core/settings.ts
- packages/app/src/webapp/cli.ts
- packages/app/templates/index.html
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/repl-focus.ts
this is enabled by adding kui--bottom-input to body.class
Fixes #1955
> feat(packages/app): experimental bottom input

- .travis.yml
> test: increase the timeout for k8s tests

- plugins/plugin-k8s/src/test/k8s2/create-pod-popup.ts
- plugins/plugin-k8s/src/test/k8s2/dash-dash-ui.ts
- plugins/plugin-k8s/src/test/k8s2/headless-create-pod.ts
- plugins/plugin-k8s/src/test/k8s2/helm-repo-add-and-search.ts
- tools/travis/test/script.sh
> test: test proxy with k8s2

- plugins/plugin-k8s/tests/lib/k8s/utils.js
> test: increase the timeout for status badge checking

- plugins/plugin-editor/src/lib/open.ts
> fix(plugins/plugin-editor): editor's injection of monaco theme is broken

- packages/app/web/css/ui.css
> fix(packages/app): sidecar maximize can result in too-wide sidecar

- packages/app/src/webapp/bottom-stripe.ts
- packages/app/templates/index.html
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/tomorrow-night.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- packages/proxy/Dockerfile.http
> chore: new dark theme

- plugins/plugin-bash-like/src/pty/client.ts
> fix(plugins/plugin-bash-like): process.cwd() versus webpack

- packages/app/templates/index.html
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/test/core-support/new-tab.ts
- plugins/plugin-core-support/web/css/screenshot.css
> feat: top tab svgs

- packages/app/web/css/ui.css
> fix(packages/app): sidecar stripe button spacing bug

- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- plugins/plugin-bash-like/src/lib/cmds/git-status.ts
- plugins/plugin-k8s/src/lib/view/formatTable.ts
> chore: new table design

- tools/travis/publishers/cos.sh
> fix: mac CD build publication bug

- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
> fix secondary text color for new dark theme

- plugins/plugin-grid/src/lib/cmds/table.ts
> fix(plugins/plugin-grid): broken buttons in summary/table view

- packages/app/web/css/ui.css
> fix(packages/app): use normal font weight for table header

- packages/webpack/build.sh
- packages/webpack/webpack.config.js
> fix(packages/webpack): broken webpack builds for external clients

- packages/app/web/css/top-tab-stripe.css
> fix(packages/app): top tab contrast issues

- packages/app/src/webapp/bottom-stripe.ts
> fix(packages/app): bottom stripe tooltips should aim down

- plugins/plugin-wskflow/src/lib/util.ts
> fix(plugins/plugin-wskflow): avoid use of fontawesome for zoom to fit

- packages/app/web/css/carbon-overrides.css
> fix(packages/app): low contrast hover for inactive sidecar tab

- packages/app/templates/index.html
> fix(packages/app): use svg for sidecar back button

- packages/app/src/webapp/bottom-stripe.ts
- plugins/plugin-grid/src/lib/cmds/table.ts
> fix: switch off fontawesome for table view

- packages/app/src/webapp/views/table.ts
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- plugins/plugin-editor/src/lib/init/defaults.ts
> chore(packages/app): reduce size of sidecar header "name"

- packages/app/templates/index.html
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/text-search.ts
- plugins/plugin-core-support/web/css/text-search.css
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
removes text-search and activation list uses of fontawesome; this also removes some unused elements from the template index.html
Fixes #2002
> chore(packages/app): remove more fontawesome

- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
> fix(packages/kui-builder): text selection color in dark theme too dark

- packages/app/web/css/ui.css
> fix(packages/app): reverse-i-search has odd left-pad

- packages/app/src/webapp/views/sidecar.ts
> fix(packages/app): restore noZoom support

- plugins/plugin-k8s/src/lib/controller/describe.ts
- plugins/plugin-k8s/src/lib/controller/kedit.ts
> fix(plugins/plugin-k8s): rename Raw tab to YAML

- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
Use `skip()` instead of comment.
> chore: use skip instead of comment

- .eslintrc.json
Remove `member-delimiter-style` rule. Now Prettier manages it.
> chore: remove member-delimiter-style rule in favor of prettier

- .eslintrc.json
- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
- plugins/plugin-openwhisk/src/lib/models/auth.ts
- plugins/plugin-openwhisk/tests/lib/openwhisk/openwhisk.js
Move the unique camelcase properties to inline comment. Keep multiple in the config file.
> chore: move the unique properties to inline comment

- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
> fix(plugins/plugin-openwhisk): double left chevron in activation list UI

- .eslintrc.json
> style: remove @typescript-eslint/no-parameter-properties

- plugins/plugin-core-support/src/lib/new-tab.ts
> fix(plugins/plugin-core-support): do not propagate mouse event when clicking tab close button

- packages/app/web/css/ui.css
- plugins/plugin-editor/src/lib/init/defaults.ts
> fix: restore 14px base font size

- plugins/plugin-tutorials/samples/@tutorials/getting-started/tutorial.json
- plugins/plugin-tutorials/web/css/tutorials.css
- plugins/plugin-tutorials/web/html/index.html
they are out of date
Fixes #2041
> fix(plugins/plugin-tutorials): remove old graphics from getting started

- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/test/core-support/new-tab.ts
> fix(plugins/plugin-core-support): fixed process.chdir() issue when switching tab in browser

- packages/app/src/core/job.ts
- packages/app/src/webapp/views/table.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
- plugins/plugin-k8s/src/test/k8s2/get-pods-with-watch.ts
> feat(packages/app): stop polling resources when tab is closed

- packages/app/src/webapp/views/table.ts
> fix(packages/app): do not add repeating-pulse to not-watching cell

- packages/app/src/test/core/basic-functionality.ts
- packages/kui-builder/examples/build-configs/default/standalone.json
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- packages/kui-builder/examples/build-configs/default/webpack-watch.json
- packages/kui-builder/examples/build-configs/default/webpack.json
- packages/kui-builder/lib/configure.js
> fix(packages/kui-builder): unify the configuration settings to avoid collision

- packages/app/web/css/ui.css
> fix(packages/app): gray badge is too light in new light theme

- packages/app/src/webapp/views/table.ts
- packages/app/web/css/ui.css
> fix(packages/app): table layout/spacing fixes

- packages/app/src/webapp/views/sidecar.ts
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- plugins/plugin-k8s/src/lib/util/created-on.ts
Fixes #2057
Fixes #2058
plus a minor table alignment fix
Fixes #2056
> fix(packages/app): theme fixes

- packages/app/templates/index.html
- packages/app/web/css/ui.css
> fix(packages/app): replace fontawesome sidecar close icon with svg

- plugins/plugin-core-support/src/lib/cmds/history/history.ts
- plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
> fix(plugins/plugin-core-support): reverse-i-search versus mac browsers

- package.json
- packages/kui-builder/dist/electron/package.json
> chore(packages/app): update to electron 5.0.7

- packages/app/src/main/spawn-electron.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
> feat: set default theme to dark if isDarkMode

- packages/kui-builder/examples/build-configs/default/theme/theme.json
- plugins/plugin-core-support/src/test/core-support/theme.ts
> chore(packages/kui-builder): switch to dark theme as the default

- packages/app/src/webapp/bottom-stripe.ts
- packages/app/src/webapp/cli.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/templates/index.html
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-k8s/src/lib/controller/describe.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/lib/view/modes/crud.ts
- plugins/plugin-wskflow/src/lib/util.ts
> style: move actions icons to the new toolbar

- packages/app/web/css/ui.css
> fix(packages/app): with active reverse-i-search > appears

- packages/app/src/webapp/views/table.ts
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/cmds/theme.ts
> style: port radio tables to use real radio buttons

- packages/app/src/webapp/views/sidecar.ts
- plugins/plugin-editor/src/lib/open.ts
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
> chore: fix lint

- packages/app/templates/index.html
- packages/app/web/css/ui.css
> fix(packages/app): sidecar screenshot button border disappears

- packages/app/src/webapp/bottom-stripe.ts
- packages/app/templates/index.html
- packages/app/web/css/ui.css
- plugins/plugin-apache-composer/src/test/composer1/composer-edit.ts
- plugins/plugin-editor/src/lib/open.ts
- plugins/plugin-editor/src/lib/readonly.ts
- plugins/plugin-editor/src/lib/util.ts
- plugins/plugin-openwhisk-editor-extensions/src/preload.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/edit-new.ts
> chore(packages/app): remove fontawesome import

- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/tomorrow-night.css
- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
- plugins/plugin-core-support/src/test/core-support/screenshot.ts
- plugins/plugin-core-support/web/css/screenshot.css
> style: new notification for screenshot

- packages/app/web/css/ui.css
> fix(packages/app): sidecar toolbar half-width issue

- plugins/plugin-editor/src/lib/cmds/edit.ts
- plugins/plugin-editor/src/lib/readonly.ts
> fix(plugins/plugin-editor): remove bogus Done Editing for local files

- packages/app/src/models/entity.ts
- packages/app/src/webapp/bottom-stripe.ts
- packages/app/src/webapp/models/table.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/src/webapp/views/table.ts
- plugins/plugin-k8s/src/lib/controller/helm/get.ts
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/lib/view/form.ts
- plugins/plugin-k8s/src/lib/view/formatEntity.ts
- plugins/plugin-k8s/src/lib/view/formatTable.ts
- plugins/plugin-k8s/src/lib/view/helm-status.ts
- plugins/plugin-k8s/src/test/k8s1/helm.ts
- plugins/plugin-k8s/src/test/k8s1/kedit.ts
- plugins/plugin-k8s/tests/data/k8s/multi-no-metadata.yaml
> fix: helm get support

- packages/app/i18n/locales/en_US/translation.json
- packages/kui-builder/bin/link-source-assets.sh
- plugins/plugin-bash-like/i18n/locales/en_US/translation.json
- plugins/plugin-core-support/i18n/locales/en_US/translation.json
- plugins/plugin-k8s/i18n/locales/en_US/translation.json
> feat: i18n en_US translation files

- packages/app/src/webapp/views/table.ts
- packages/app/templates/index.html
- packages/app/web/css/carbon-overrides-common.css
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/kui-tables-common.css
- packages/app/web/css/kui-tables.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/config.json
- packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- plugins/plugin-core-support/src/test/core-support/theme.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
- plugins/plugin-k8s/src/test/k8s1/namespace.ts
- plugins/plugin-k8s/src/test/k8s2/get-pods-with-watch.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/auth.ts
> chore: switch table renderer to use standard table tags

- packages/app/web/css/ui.css
- plugins/plugin-editor/web/css/theme-alignment.css
> fix: illegible and not-themed editor tooltips

- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
- plugins/plugin-core-support/web/css/screenshot.css
Fixed the issue for negative countdown
#2107
> fix(plugins/plugin-core-support): fix negative countdown issue

- packages/app/src/webapp/bottom-stripe.ts
- plugins/plugin-k8s/src/lib/view/modes/button.ts
- plugins/plugin-k8s/src/lib/view/modes/crud.ts
- plugins/plugin-k8s/src/test/k8s2/delete-pod-via-click.ts
> fix(plugins/plugin-k8s): broken delete button in proxy-webpack

- plugins/plugin-k8s/src/lib/view/modes/last-applied.ts
> fix(plugins/plugin-bash-like): missing kind in last applied

- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/test/k8s2/helm-template.ts
- plugins/plugin-k8s/tests/data/k8s/helm-template.yaml
> fix(Plugins/plugin-k8s): fix for editing helm template files

- docs/dev/customization-guide.md
- packages/app/templates/index.html
- packages/app/web/css/top-tab-stripe-alt.css
- packages/app/web/css/top-tab-stripe.css
- packages/kui-builder/examples/build-configs/default/theme/config.json
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- packages/kui-builder/lib/configure.js
- plugins/plugin-core-support/src/lib/new-tab.ts
> chore: provide alternate top tab UI example

- packages/app/web/css/ui.css
> fix(packages/app): reduce size of table radiobuttons

- packages/app/templates/index.html
- packages/app/web/css/kui-tables.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
also reverts a mistaken update to the default client's top tab UI
Fixes #2126
> fix: improved prompt

- packages/app/web/css/ui.css
> fix(packages/app): small prompt UI refinements

- package.json
> fix: config-dev.json sticks around

- packages/app/templates/index.html
> fix(packages/app): reverse-i-search versus prompt

- packages/app/web/css/carbon-overrides.css
> fix(packages/app): invisible slash in help breadcrumbs

- packages/app/web/css/ui.css
> fix(packages/app): sidecar header overflow with badge and duration

- packages/app/web/css/kui-tables.css
- packages/app/web/css/ui.css
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
> fix: openwhisk rendering glitches

- packages/app/web/css/ui.css
> fix(packages/app): tighten up prompt UI

- packages/app/web/css/kui-tables.css
- plugins/plugin-bash-like/src/lib/cmds/git-status.ts
> fix: git status table rendering

- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> fix(plugins/plugin-proxy-executor): also look for statusCode

- packages/app/src/webapp/views/sidecar.ts
- packages/app/src/webapp/views/table.ts
- packages/app/web/css/kui-tables.css
- packages/app/web/css/not-electron.css
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/lib/cmds/git-status.ts
- plugins/plugin-openwhisk/src/lib/models/withHeader.ts
> fix: openwhisk table header rendering vs webpack

- clients/alternate/theme/css/themes/carbon-gray10.css
> chore: new magenta and cyan colors for carbon-gray10 theme

- packages/app/web/css/ui.css
- plugins/plugin-bash-like/web/css/xterm.css
> fix: xterm bg ansi color theming

- plugins/plugin-editor/web/css/theme-alignment.css
> fix(plugins/plugin-editor): monaco line number theming bug

- packages/app/web/css/kui-tables.css
- plugins/plugin-bash-like/src/lib/cmds/git-status.ts
- plugins/plugin-bash-like/src/pty/client.ts
Fixes #2167
also some small tweaks to `git status` output
> fix(plugins/plugin-bash-like): git commit output formatting

- packages/app/src/core/job.ts
- packages/app/src/core/settings.ts
- packages/app/src/webapp/views/diffTable.ts
- packages/app/src/webapp/views/table.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
- plugins/plugin-k8s/src/test/k8s1/namespace.ts
- plugins/plugin-k8s/src/test/k8s2/get-pods-with-watch.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
Also fixed the issue that watch status doesn't blink
Fixes #2079
Fixes #2076
> fix(packages/app): tweaked the table polling interval for resource creation&deletion

- clients/alternate/theme/css/themes/carbon-gray10.css
> fix: correct clients/alternate green color

- packages/kui-builder/dist/dev/build.sh
> chore: update monorepo builder to link in all client css files

- packages/app/src/core/usage-error.ts
- packages/app/src/main/headless-pretty-print.ts
- packages/app/tests/lib/headless.js
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-core-support/src/test/core-support/help.ts
- plugins/plugin-k8s/src/lib/util/help.ts
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-usage.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/headless.ts
- plugins/plugin-wskflow/src/usage.ts
> fix: usage formatting and click handler fixes

- packages/app/web/css/not-electron.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- plugins/plugin-bash-like/web/css/xterm.css
> fix: poor text coloring of pty output in light themes

- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/server.ts
> fix(plugins/plugin-bash-like): duplicate pty messages in webpack+proxy

- plugins/plugin-bash-like/src/pty/client.ts
> fix(plugins/plugin-bash-like): remove debugging output from client.ts

- .eslintrc.json
- packages/app/tests/lib/ui.js
- plugins/plugin-k8s/src/lib/controller/describe.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/lib/util/created-on.ts
- plugins/plugin-k8s/src/lib/util/log-parser.ts
- plugins/plugin-k8s/src/lib/view/modes/button.ts
- plugins/plugin-k8s/src/test/k8s1/config-map.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s1/namespace.ts
- plugins/plugin-k8s/src/test/k8s2/create-pod-popup.ts
> feat(plugins/plugin-k8s): updated k8s summary tab

- packages/app/templates/index.html
- packages/app/web/css/ui.css
switch to svgs rather than generic squares
Fixes #2191
> feat(packages/app): updated repl success indicators

- packages/app/src/webapp/cli.ts
- packages/app/templates/index.html
- packages/app/web/css/ui.css
this PR introduces a distinct screenshot icon for each repl block
Fixes #2197
> fix(packages/app): improve repl block screenshot UI

- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/src/webapp/util/ascii-to-usage.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-core-support/src/lib/cmds/zoom.ts
> fix: reduce verbosity of debug logging

- packages/app/web/css/ui.css
> fix(packages/app): don't use font-weight:500 for repl error text

- plugins/plugin-k8s/src/test/k8s/contexts.ts
- plugins/plugin-k8s/src/test/k8s1/edit.ts
- plugins/plugin-k8s/src/test/k8s1/helm.ts
- plugins/plugin-k8s/src/test/k8s1/kedit.ts
- plugins/plugin-k8s/src/test/k8s1/tab-completion.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
- tools/travis/test/script.sh
Not including:
1. context switching
2. kedit
3. kubectl edit
4. helm
Part of #2184
> test: more proxy test for k8s

- packages/app/templates/index.html
- packages/app/web/css/not-electron.css
- packages/app/web/css/top-tab-stripe.css
> fix(packages/app): hide screenshot buttons in webpack

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s2/helm-repo-add-and-search.ts
> fix(plugins/plugin-k8s): helm repo list fixes

- tools/travis/test/script.sh
> tests: don't run mocha test targets in parallel

- packages/app/src/webapp/views/table.ts
- packages/app/web/css/ui.css
> fix(packages/app): missing conditions fontawesome icons

- packages/app/src/webapp/util/ascii-to-table.ts
- plugins/plugin-k8s/src/lib/view/formatTable.ts
> fix: hide AGE column when the sidecar is open

- packages/app/web/css/kui-tables-common.css
- packages/app/web/css/kui-tables.css
- packages/app/web/css/ui.css
> fix(packages/app): tables don't render well in firefox with sidecar open

- packages/app/tests/lib/common.js
> test(packages/app): increase spectron's startTimeout

- packages/app/src/models/entity.ts
- packages/app/src/webapp/cli.ts
- packages/app/web/css/ui.css
- plugins/plugin-k8s/src/lib/view/helm-status.ts
- plugins/plugin-k8s/src/test/k8s1/helm.ts
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
this adds support for MixedResponse
Fixes #2213
> fix: helm status versus webpack+proxy

- packages/app/web/css/ui.css
> fix(packages/app): prompt lowers slightly after hitting enter

- plugins/plugin-k8s/src/lib/view/modes/containers.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
> fix(plugins/plugin-k8s): stop polling in sidecar container tab

- packages/app/src/core/usage-error.ts
- packages/app/src/models/errors.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> fix: 404 errors do not flow back from proxy properly

- plugins/plugin-k8s/src/lib/util/fetch-file.ts
> fix(plugins/plugin-k8s): k8s fetch-file should retry

- packages/app/src/core/command-tree.ts
- packages/app/src/core/settings.ts
- packages/app/src/webapp/cli.ts
- packages/app/templates/index.html
- packages/app/tests/lib/ui.js
- packages/app/web/css/carbon-overrides-common.css
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/plugin.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-core-support/src/test/core-support/text-search.ts
> feat: warn the user if the webpack->proxy connection is slow

- plugins/plugin-bash-like/src/pty/session.ts
> fix(plugins/plugin-bash-like): remove debugging leftover sleep 5

- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-k8s/src/lib/controller/describe.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s2/get-all-namespaces.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec.ts
- plugins/plugin-k8s/tests/data/k8s/kubectl-exec.yaml
- plugins/plugin-k8s/tests/lib/k8s/utils.d.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> feat: kubectl exec support

- packages/app/src/webapp/views/top-tabs.ts
- packages/app/templates/index.html
- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- packages/app/web/css/ui.css
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-bash-like/src/pty/ui.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-session-status.ts
- tools/travis/test/target.d/proxy.sh
- tools/travis/test/target.d/webpack.sh
also try to reconnect
Fixes #2256
> feat: show proxy connection status in the UI

- .travis.yml
- packages/webpack/webpack.config.js
> chore(packages/webpack): add default CSP to webpack.config.js

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
> fix(plugins/plugin-k8s): avoid infinite loop with "k"

- packages/app/src/webapp/cli.ts
- packages/app/web/css/carbon-overrides.css
- packages/kui-builder/bin/link-source-assets.sh
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- packages/kui-builder/tsconfig.json
- plugins/plugin-core-support/i18n/locales/en_US/translation.json
- plugins/plugin-core-support/src/lib/cmds/confirm.ts
- plugins/plugin-core-support/src/plugin.ts
- plugins/plugin-core-support/src/test/core-support/confirm.ts
- plugins/plugin-core-support/web/css/confirm.css
- plugins/plugin-k8s/src/lib/view/modes/button.ts
- plugins/plugin-k8s/src/test/k8s1/deployment.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s1/namespace.ts
- plugins/plugin-k8s/src/test/k8s2/delete-pod-via-click.ts
> feat(plugins/plugin-core-support) confirm modal

- plugins/plugin-core-support/i18n/locales/en_US/translation.json
also cancelled -> canceled for american english locale
Fixes #2286
> fix(plugins/plugin-core-support): typo in confirm dialog

- packages/webpack/webpack.config.js
- tools/travis/test/top.sh
> test: improve travis top output formatting

- packages/app/src/core/repl.ts
- packages/app/tests/lib/common.js
- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- packages/app/web/css/ui.css
- packages/tests/bin/runTest.sh
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-core-support/src/lib/cmds/confirm.ts
- plugins/plugin-core-support/src/test/core-support/text-search.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s1/apply-pod.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s1/edit.ts
- plugins/plugin-k8s/src/test/k8s1/status.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
- tools/travis/test/top.sh
> fix: confirm dialog versus webpack and k edit

- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-core-support/i18n/locales/en_US/translation.json
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s1/edit.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
> fix: kubectl exec vi is not full-screen

- plugins/plugin-core-support/src/lib/cmds/confirm.ts
> fix(plugins/plugin-core-support): correct example in confirm usage model

- packages/app/web/css/ui.css
- plugins/plugin-editor/web/css/editor.css
> fix(packages/app): avoid poor wrapping of sidecar toolbar text

- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
Add test for kubectl command with grep
> test: kubectl command test with grep

- packages/app/src/webapp/models/table.ts
- packages/app/src/webapp/views/table.ts
- plugins/plugin-bash-like/src/lib/cmds/ls.ts
- plugins/plugin-bash-like/src/lib/cmds/open.ts
- plugins/plugin-editor/src/lib/fetchers.ts
> fix: ls clicks in browser

- plugins/plugin-k8s/src/test/k8s/contexts.ts
- plugins/plugin-k8s/src/test/k8s1/helm.ts
- plugins/plugin-k8s/src/test/k8s2/helm-repo-add-and-search.ts
- tools/travis/test/script.sh
> test: WAIT_LAYER test should be executed before proxy tests

- .travis.yml
- packages/app/src/core/command-tree.ts
- packages/app/src/test/core/version.ts
- packages/app/src/util/i18n.ts
- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- plugins/plugin-bash-like/src/lib/cmds/ls.ts
- plugins/plugin-bash-like/src/test/bash-like-wait/pty-session-status.ts
- plugins/plugin-bash-like/src/test/bash-like/blank-lines.ts
- plugins/plugin-bash-like/src/test/bash-like/headless-host.ts
- plugins/plugin-bash-like/src/test/bash-like/ls.ts
- plugins/plugin-core-support/src/test/core-support/clear.ts
- plugins/plugin-core-support/src/test/core-support/help.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
- plugins/plugin-k8s/src/test/k8s1/apply-pod.ts
- plugins/plugin-k8s/src/test/k8s1/create-pod.ts
- tools/travis/test/script.sh
- tools/travis/test/target.d/proxy.sh
> test: improve proxy test coverage

- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-bash-like/src/test/bash-like-wait/pty-session-status.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> fix(plugins/plugin-bash-like): proxy session reconnect issues

- packages/app/web/css/ui.css
> fix(packages/app): contrast issues with minimized sidecar

- packages/app/src/util/i18n.ts
> fix(packages/app): i18n shim support for underscore versus dash

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-k8s/src/test/k8s2/logs-dash-f.ts
- plugins/plugin-k8s/tests/data/k8s/kubectl-exec.yaml
> feat(plugins/plugin-k8s): kubectl logs -f support

- clients/alternate/theme/css/themes/carbon-gray10.css
- packages/app/src/core/settings.ts
- packages/app/src/webapp/cli.ts
- packages/app/src/webapp/views/presentation.ts
- packages/app/src/webapp/views/table.ts
- packages/app/templates/index.html
- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- packages/app/web/css/carbon-overrides-common.css
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/sidecar.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- plugins/plugin-apache-composer/src/test/composer1/zzz-bottom-bar-back-button.ts
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
- plugins/plugin-core-support/web/css/about.css
- plugins/plugin-k8s/src/test/k8s2/create-pod-popup.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/bottom-stripe-activation.ts
- plugins/plugin-tutorials/samples/@tutorials/getting-started/tutorial.json
- plugins/plugin-tutorials/src/lib/cmds/play.ts
- plugins/plugin-tutorials/src/lib/cmds/shortcuts.ts
- plugins/plugin-tutorials/web/css/tutorials.css
- plugins/plugin-tutorials/web/html/index.html
> updated about UI

- packages/app/src/core/settings.ts
- packages/app/src/main/menu.ts
- packages/app/src/util/i18n.ts
- packages/app/web/css/sidecar.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- plugins/plugin-core-support/i18n/locales/en_US.json
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
- plugins/plugin-core-support/web/css/about.css
> fix: i18n support for about

- packages/app/src/webapp/util/inject.ts
- packages/app/templates/index.html
- plugins/plugin-bash-like/src/lib/cmds/open.ts
- plugins/plugin-bash-like/src/lib/util/markdown.ts
- plugins/plugin-openwhisk/src/preload.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/create-then-add-parameter/action.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/create-then-add-parameter/with-quotes.ts
> fix: move highlightjs dependence out of core index.html

- packages/app/src/webapp/models/table.ts
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
- plugins/plugin-tutorials/src/lib/cmds/list.ts
- plugins/plugin-tutorials/src/lib/cmds/play.ts
- plugins/plugin-tutorials/src/lib/cmds/shortcuts.ts
> feat: reroute getting started to use the about command

- plugins/plugin-k8s/src/test/k8s1/create-pod.ts
- plugins/plugin-k8s/src/test/k8s1/edit.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.d.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
> fix(plugins/plugin-k8s): k exec vi test failures

- packages/app/src/test/core/about.ts
- packages/app/tests/lib/common.js
- plugins/plugin-k8s/src/test/k8s1/apply-pod.ts
> fix(packages/app): false negative test failures in about

- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
> fix(plugins/plugin-k8s): remove debugging printfs from one test

- packages/app/src/webapp/cli.ts
> fix(packages/app): double status icons

- plugins/plugin-bash-like/src/pty/websocket-channel.ts
> fix(plugins/plugin-bash-like): websocket fixes for safari

- packages/app/web/css/sidecar.css
> fix(packages/app): sidecar minimized should be full height

- packages/app/src/webapp/views/table.ts
> fix(packages/app): handle empty string cell values in table renderer

- packages/app/tests/lib/common.js
> test: oops test error logging double throw

- plugins/plugin-k8s/src/lib/controller/helm/get.ts
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s1/helm.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> fix(plugins/plugin-k8s): helm error handling in webpack

- plugins/plugin-k8s/src/lib/model/states.ts
> fix(plugins/plugin-k8s): getStatusFromConditions can stay yellow

- packages/webpack/webpack.config.js
> fix(packages/webpack): only override CSP for dev-server mode

- packages/app/src/core/repl.ts
- packages/app/src/test/core/about.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
> fix(packages/app): texts after `#`get truncated in command input

- clients/alternate/theme/css/themes/carbon-gray10.css
- clients/alternate/theme/css/themes/carbon-gray90.css
- clients/alternate/theme/css/top-tab-stripe-alt.css
- clients/alternate/theme/theme.json
- packages/app/web/css/ui.css
> feat: add dark theme for clients/alternate

- packages/app/src/test/core/about.ts
- packages/app/src/test/core/input-queueing.ts
- packages/app/src/webapp/util/ascii-to-usage.ts
- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- packages/kui-builder/examples/build-configs/default/theme/theme.json
- packages/webpack/webpack.config.js
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-bash-like/src/test/bash-like/cd.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
- plugins/plugin-core-support/src/lib/cmds/prompt.ts
- plugins/plugin-core-support/src/test/core-support/clear.ts
also increases proxy test coverage for bash-like commands
Fixes #2408
> fix: cat foo.yml produces ugly output

- packages/kui-builder/examples/build-configs/default/theme/theme.json
- packages/webpack/webpack.config.js
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-focus.ts
for any commands after the first, the pty may not receive input
Fixes #2397
> fix(plugins/plugin-bash-like): xterm focus issues

- packages/app/src/test/core/basic-functionality.ts
- plugins/plugin-apache-composer/src/test/composer1/zzz-bottom-bar-back-button.ts
- plugins/plugin-bash-like/src/test/bash-like/git-diff.ts
- plugins/plugin-bash-like/src/test/bash-like/vi.ts
- plugins/plugin-grid/src/test/grid/grid.ts
- plugins/plugin-grid/src/test/grid/summary.ts
- plugins/plugin-k8s/src/test/k8s1/deployment.ts
- plugins/plugin-k8s/src/test/k8s1/hpa.ts
- plugins/plugin-k8s/src/test/k8s2/create-pod-popup.ts
- plugins/plugin-k8s/src/test/k8s2/get-all-namespaces.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/package-list.ts
Fixes #2411
ensured that tests always return oops
> test: add missing return on common.oops

- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- plugins/plugin-bash-like/src/lib/cmds/export.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-bash-like/src/test/bash-like/cat-to-sidecar.ts
- plugins/plugin-bash-like/src/test/bash-like/echo.ts
- plugins/plugin-bash-like/src/test/bash-like/export.ts
- plugins/plugin-bash-like/src/test/bash-like/ls.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
- plugins/plugin-bash-like/src/test/bash-like/vi.ts
Fixes #2413
removed localDescribe from plugin-bash-like tests for test cases that should work in webpack+proxy
> test: expand proxy coverage in bash-like

- plugins/plugin-k8s/src/test/k8s1/edit.ts
- plugins/plugin-k8s/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-k8s/src/test/k8s2/logs-dash-f.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
> test: improve reliability of k8s tests

- plugins/plugin-bash-like/src/pty/channel.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-bash-like/src/pty/stdio-channel.ts
- plugins/plugin-bash-like/src/pty/websocket-channel.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
> fix(plugins/plugin-bash-like): proxy process leak

- .travis.yml
- packages/app/src/core/usage-error.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/tests/lib/common.js
- packages/app/tests/lib/ui.js
- packages/webpack/package.json
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s1/apply-pod.ts
- plugins/plugin-k8s/src/test/k8s2/get-pod.ts
- plugins/plugin-k8s/tests/lib/k8s/utils.js
- tools/travis/test/top.sh
> fix(plugins/plugins-k8s): kubectl get -lfoo=bar was not working

- packages/app/tests/lib/common.js
> test: remove innocuous travis log lines

- plugins/plugin-bash-like/i18n/locales/en_US.json
- plugins/plugin-bash-like/src/pty/session.ts
> chore(plugins/plugin-bash-like): i18n the proxy session init messages

- clients/alternate/theme/css/themes/carbon-gray10.css
- clients/alternate/theme/css/themes/carbon-gray90.css
> fix: minor clients/alternate theme updates

- .travis.yml
> chore: fix for broken dev and nightly CD publish streams

- .travis.yml
> chore: better fix for dev and nightly publish bug

- clients/alternate/theme/css/themes/carbon-gray90.css
- packages/app/web/css/ui.css
> fix: poor rendering of confirm dialog in clients/alternate dark theme

- packages/app/src/core/utility.ts
- packages/app/src/webapp/util/ascii-to-usage.ts
- plugins/plugin-bash-like/src/lib/cmds/ls.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-core-support/src/lib/tab-completion.ts
- plugins/plugin-grid/src/lib/util.ts
- plugins/plugin-k8s/src/lib/controller/status.ts
- plugins/plugin-k8s/src/lib/util/util.ts
- plugins/plugin-manager/src/lib/cmds/list.ts
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
- plugins/plugin-tekton/src/model/modes/logs.ts
> fix: flatmap is not supported by some browsers

- plugins/plugin-k8s/src/test/k8s1/labels.ts
> test(plugins/plugin-k8s): add kubectl label tests

- packages/app/src/webapp/views/table.ts
- packages/app/web/css/kui-tables-common.css
- packages/app/web/css/kui-tables.css
- packages/app/web/css/ui.css
> fix(packages/app): clean up multi-table title UI

- .eslintignore
> test: fix travis lint race

- packages/app/src/webapp/bootstrap/boot.ts
> fix(packages/app): in electron builds, first prompt lacks CWD

- packages/app/web/css/kui-tables-common.css
> fix(packages/app): table rendering issues that lead to "white gaps"

- clients/alternate/theme/theme.json
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
> fix(plugins/plugin-core-support): allow clients to have no About image

- packages/app/web/css/kui-tables-common.css
> fix(packages/app): multi-tables in sidecar don't have table headers

- clients/alternate/theme/css/top-tab-stripe-alt.css
- packages/app/src/core/repl.ts
- packages/app/src/core/symbol-table.ts
- packages/app/src/models/execOptions.ts
- packages/app/src/webapp/cli.ts
- packages/app/templates/index.html
- packages/app/tests/lib/common.d.ts
- packages/app/tests/lib/common.js
- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- plugins/plugin-bash-like/src/lib/cmds/export.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/export.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/test/core-support/new-tab.ts
- plugins/plugin-k8s/src/test/k8s2/get-pods-with-watch.ts
> fix: multiple bugs with tab switching

- plugins/plugin-k8s/i18n/resources_en_US.json
> chore: add events string to k8s i18n

- tools/travis/test/test.d/typecov.sh
> chore: don't run typecov for non-master runs on the main fork

- .eslintignore
- packages/app/src/core/command-tree.ts
- packages/app/src/core/symbol-table.ts
- plugins/plugin-bash-like/src/lib/cmds/export.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
> chore: eslint fixes

- clients/alternate/theme/css/themes/carbon-gray10.css
- clients/alternate/theme/css/themes/carbon-gray90.css
- clients/alternate/theme/css/top-tab-stripe-alt.css
- clients/alternate/theme/theme.json
- packages/app/src/webapp/views/table.ts
- packages/app/templates/index.html
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
> fix: refine clients/alternate light theme

- packages/app/src/webapp/cli.ts
> fix(packages/app): paste versus bottom input

- clients/alternate/theme/css/themes/carbon-gray10.css
- clients/alternate/theme/css/top-tab-stripe-alt.css
> fix: clients/alternate tab ui glitches

- plugins/plugin-core-support/src/lib/new-tab.ts
> fix(plugins/plugin-core-support): new tab name carries over

- packages/app/src/webapp/cli.ts
- packages/app/web/css/ui.css
> fix(packages/app): reverse-i-search versus bottom input

- packages/app/web/css/kui-tables-common.css
- packages/app/web/css/kui-tables.css
- plugins/plugin-k8s/src/lib/view/helm-status.ts
> fix: improved display of helm status

- clients/alternate/theme/css/themes/carbon-gray10.css
- packages/app/web/css/kui-tables-common.css
> fix: sidecar multitable header glitch for clients/alternate light

- tools/travis/publishers/cos.sh
> test: mac continuous delivery pipeline fix

- packages/app/web/css/sidecar.css
> fix(packages/app): sidecar content sometimes does not scroll

- packages/app/src/core/settings.ts
- packages/webpack/webpack.config.js
- plugins/plugin-editor/src/lib/init/esm.ts
> fix: improve handling of contextRoot for custom clients

- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- plugins/plugin-core-support/src/lib/cmds/clear.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/test/core-support/clear.ts
- plugins/plugin-k8s/src/test/k8s2/get-pods-with-watch.ts
> fix(plugins/plugin-core-support): `clear` should terminate pollers

- plugins/plugin-bash-like/web/css/xterm.css
> fix(plugins/plugin-bash-like): xterm background should be transparent

- packages/app/src/util/i18n.ts
> fix(packages/app): protect against navigator.language being undefined

- packages/app/src/webapp/util/ascii-to-usage.ts
- plugins/plugin-bash-like/src/pty/client.ts
> fix(packages/app): improve ascii-to-usage for oc -h

- plugins/plugin-core-support/src/lib/cmds/about/about.ts
> fix(plugins/plugin-core-support): add alt attribute to image in About Sidecar

- clients/alternate/theme/css/themes/carbon-gray10.css
- clients/alternate/theme/css/themes/carbon-gray90.css
- packages/app/web/css/ui.css
> fix(packages/app): green and cyan text colors with high contrast

- clients/alternate/theme/css/top-tab-stripe-alt.css
- packages/app/src/webapp/bottom-stripe.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/templates/index.html
- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- packages/app/web/css/carbon-overrides-common.css
- packages/app/web/css/carbon-overrides.css
- packages/app/web/css/sidecar.css
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/test/core-support/tab-navigation.ts
> feat: tab navigation

- packages/app/src/webapp/bottom-stripe.ts
Fixes #2589
Screenshot of how the Save and Revert buttons look in this PR:
> fix(packages/app): wrong spacing between editor Save and Revert buttons

- packages/app/src/core/repl.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
enforce process.env.SHELL
Fixes #2604
> fix(plugins/plugin-bash-like): improved proxy security

- clients/alternate/theme/css/themes/carbon-gray10.css
- plugins/plugin-editor/web/css/theme-alignment.css
> fix(plugins/plugin-editor): editor text and cursor can be invisible

- packages/app/web/css/carbon-overrides-common.css
- packages/app/web/css/ui.css
> fix(packages/app): sidecar toolbar buttons spaced too widely

- packages/app/src/webapp/cli.ts
- plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
- plugins/plugin-core-support/src/lib/tab-completion.ts
> fix: reverse-i-search versus caret motion bugs

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s1/helm.ts
> fix(plugins/plugin-k8s): helm help --tls should fail nicely

- packages/app/templates/index.html
- packages/app/web/css/carbon-overrides-common.css
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
- plugins/plugin-core-support/src/lib/new-tab.ts
> fix(packages/app): tabkey navigation UI quirks

- packages/app/templates/index.html
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
- plugins/plugin-openwhisk/src/lib/models/modes.ts
- plugins/plugin-openwhisk/src/lib/models/withHeader.ts
- plugins/plugin-openwhisk/src/lib/views/mode.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/package-list.ts
this cleans up some very old crufty code in the openwhisk plugin to the latest table api
Fixes #2487
> fix(plugins/plugin-openwhisk): port openwhisk sidecar package table

- packages/app/src/models/command.ts
- packages/app/src/models/execOptions.ts
- packages/app/src/webapp/views/sidecar.ts
- packages/app/tests/lib/common.js
- plugins/plugin-bash-like/src/lib/cmds/ls.ts
- plugins/plugin-bash-like/src/lib/cmds/open.ts
- plugins/plugin-editor/src/lib/cmds/edit.ts
- plugins/plugin-editor/src/lib/fetchers.ts
- plugins/plugin-editor/src/test/editor/edit.ts
- plugins/plugin-editor/src/usage.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/edit.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> feat(plugins-plugin-editor): Enable edit new file

- packages/app/web/css/kui-tables.css
- plugins/plugin-k8s/src/lib/view/formatTable.ts
Part of #2438
1. add "message" font to Message column
2. line wrap Message column
3. Reason column color coding, using the existing `cssForKey`
4. smart color code `red-background` to Failure Reasons not in the existing `cssForKey`
5. add padding-top and padding-bottom to table data attributes td
6. fix the bug that the first column is clickable even when it's not a Name Column
> fix(plugins/plugin-k8s): `kubectl get events` table UI tweaks

- packages/app/src/webapp/cli.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
> fix(plugins/plugin-bash-like): remove debugging printf from kubectl.ts

- packages/app/templates/index.html
- packages/app/web/css/ui.css
> fix(packages/app): grid command causes top-tabs to shift right

- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/src/webapp/views/table.ts
this also fixes some long-standing issues with tables having <false> tags and class="undefined"
Fixes #2633
> feat(packages/app): ascii-to-table should render links as <a>

- packages/app/package-lock.json
- packages/app/package.json
- packages/app/src/core/repl.ts
- packages/app/src/models/entity.ts
- packages/app/src/util/async.ts
- packages/app/src/webapp/cli.ts
- packages/app/src/webapp/util/ascii-to-table.ts
- packages/app/web/css/kui-tables-common.css
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/pretty-print.ts
- plugins/plugin-bash-like/src/pty/util.ts
> fix: improve pty rendering of mixed string/table output

- packages/app/src/webapp/util/ascii-to-usage.ts
> fix(plugins/plugin-bash-like): removed regex positive lookbehind

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s2/logs.ts
> fix(plugins/plugin-k8s): k logs does not change sidecar title

- packages/app/templates/index.html
> fix(pacakges/app): Accessibility Violations: Hyperlinks must contain link text

- packages/app/src/webapp/picture-in-picture.ts
> fix(packages/app): back button does not restore click handlers

- clients/alternate/theme/css/themes/carbon-gray10.css
> fix: typo in map-key color in carbon-gray10 theme

- plugins/plugin-grid/src/lib/cmds/grid.ts
- plugins/plugin-grid/src/lib/cmds/table.ts
> fix(plugins/plugin-grid): grid and summary commands missing noAuthOk

- packages/proxy/build.sh
- tools/travis/installers/microk8s/start-cluster.sh
> test: microk8s in travis install failures

- packages/app/tests/lib/ui.d.ts
- packages/app/tests/lib/ui.js
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
- plugins/plugin-bash-like/web/css/xterm.css
- plugins/plugin-editor/src/test/editor/edit.ts
- plugins/plugin-k8s/src/test/k8s2/headless-create-pod.ts
> fix(plugins/plugin-bash-like): long output from pty gets truncated

- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
> test(plugins/plugin-bash-like): test issue with pty-copy-paste

- plugins/plugin-openwhisk/src/lib/cmds/actions/_html.ts
> chore(plugins/plugin-openwhisk): simplify htmlparser2 import

- packages/app/web/css/sidecar.css
- packages/app/web/css/top-tab-stripe.css
- packages/app/web/css/ui.css
> fix(packages/app): small design tweaks to sidecar borders

- packages/app/src/webapp/cli.ts
> fix(packages/app): bottom input should be readonly while command is live

- packages/app/src/util/i18n.ts
- plugins/plugin-core-support/i18n/resources_en_US.json
- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
> fix(plugins/plugin-core-support): some plugin-core-support strings are not externalized

- packages/app/src/webapp/cli.ts
> fix(packages/app): remove event listeners from older/inactive prompts

- packages/app/templates/index.html
> fix(packages/app): typo in one of the aria-labels

- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
> test(plugins/plugin-bash-like): improve pty scrolling behavior

- clients/alternate/theme/css/themes/carbon-gray10.css
> fix: clients/alternate zebra striping for k logs has poor contrast

- packages/app/web/css/.gitignore
> fix(packages/app): eliminate untracked _test.css warning

- packages/app/src/models/command.ts
> fix(packages/app): fix lint issue

- .travis.yml
- packages/app/web/css/.gitignore
- packages/app/web/css/top-tab-stripe-alt.css
> fix(packages/app): remove top-tab-stripe-alt.css link

- packages/app/src/webapp/bootstrap/electron.ts
> fix(packages/app): on mac electron builds, cwd and PWD mismatch

- .travis.yml
> fix: undo git clean in travis.yml

- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/test/k8s1/get-namespaces-with-watch.ts
- plugins/plugin-k8s/src/test/k8s2/watch-error-handling.ts
> fix(plugins/plugin-k8s): `kubectl get pods -w -w` hangs, `k -w get pods` does not fail

- plugins/plugin-tekton/src/controller/preview.ts
- plugins/plugin-tekton/src/lib/read.ts
> fix(plugins/plugin-tekton): improve tekton preview support for webpack

- clients/default/package.json
- packages/app/src/main/spawn-electron.ts
> fix(packages/app): set icon on linux

- plugins/plugin-core-support/src/lib/cmds/theme.ts
> fix(plugins/plugin-core-support): error initializing themes

- packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
- plugins/plugin-k8s/src/lib/model/resource.ts
- plugins/plugin-k8s/src/lib/view/modes/events.ts
- plugins/plugin-k8s/src/preload.ts
- plugins/plugin-k8s/src/test/k8s2/events.ts
- plugins/plugin-k8s/tests/data/k8s/event-generator.yaml
> feat(plugins/plugin-k8s): add Events tab for kube resources

- packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
> fix(packages/kui-builder): sidecar table text bugs in carbon-gray10

- packages/app/src/webapp/bottom-stripe.ts
- plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
> disable the padding for sidecar tables

- packages/app/web/css/kui-tables-common.css
> fix: no horizontal scrolling for wide table

- packages/app/web/css/kui-tables.css
- packages/app/web/css/ui.css
- packages/kui-builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
> fix: sidecar color fixes to accommodate sidecar dark/repl light themes

- packages/kui-builder/bin/prescan.sh
> fix(packages/kui-builder): external clients versus nodejs 12

- plugins/plugin-core-support/npm-shrinkwrap.json
- plugins/plugin-core-support/package.json
- plugins/plugin-openwhisk/npm-shrinkwrap.json
- plugins/plugin-openwhisk/package.json
> fix: make yargs-parser dependences explicit

- packages/app/web/css/top-tab-stripe.css
> fix(packages/app): top-tab-stripe-alt rules are too sticky

- plugins/plugin-k8s/src/preload.ts
> fix(plugins/plugin-k8s): don't fail if plugin-core-support unavailable

- plugins/plugin-operator-framework/src/controller/olm.ts
> fix(plugins/plugin-operator-framework): disable "remembered" config

- plugins/plugin-editor/src/lib/open.ts
> fix(plugins/plugin-editor): update the Monaco editor layout since we got rid of the transition effect of sidecar resizing

- plugins/plugin-core-support/src/lib/tab-completion.ts
> fix(plugins/plugin-core-support): code issues with microsoft edge

- lerna.json
- package.json
- packages/app/package.json
- packages/kui-builder/package.json
- packages/proxy/package.json
- packages/tests/package.json
- packages/webpack/package.json
- plugins/plugin-apache-composer/package.json
- plugins/plugin-bash-like/package.json
- plugins/plugin-core-support/package.json
- plugins/plugin-editor/package.json
- plugins/plugin-grid/package.json
- plugins/plugin-k8s/package.json
- plugins/plugin-manager/package.json
- plugins/plugin-openwhisk-editor-extensions/package.json
- plugins/plugin-openwhisk/package.json
- plugins/plugin-operator-framework/package.json
- plugins/plugin-proxy-support/package.json
- plugins/plugin-tekton/package.json
- plugins/plugin-tutorials/package.json
- plugins/plugin-wrk/package.json
- plugins/plugin-wskflow/package.json
> chore: bump to 4.4.0 in the repo

- plugins/plugin-apache-composer/samples/@demos/let.js
> fix(plugins/plugin-apache-composer): let.js demo versus safari

- .travis.yml
> chore: avoid npx lerna in travis.yml

- package-lock.json
> chore: regenerate package-lock with node v8

- .travis.yml
- tools/travis/test/install.sh
> chore: switch to `npm ci` when in travis

- tools/travis/setup-webhook.sh
> fix: setup-webhook out of date

- packages/core/src/core/find-file.ts
- packages/core/src/core/job.ts
- packages/core/src/core/repl.ts
- packages/core/src/core/settings.ts
- packages/core/src/core/symbol-table.ts
- packages/core/src/core/usage-error.ts
- packages/core/src/core/userdata.ts
- packages/core/src/main/headless-pretty-print.ts
- packages/core/src/main/menu.ts
- packages/core/src/models/history.ts
- packages/core/src/test/core/about.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/core/src/webapp/models/table.ts
- packages/core/src/webapp/util/ascii-to-table.ts
- packages/core/src/webapp/util/ascii-to-usage.ts
- packages/core/src/webapp/util/pretty-print.ts
- packages/core/src/webapp/util/time.ts
- packages/core/src/webapp/views/registrar/badges.ts
- packages/core/src/webapp/views/registrar/modes.ts
- packages/core/src/webapp/views/sidecar-selector.ts
- packages/core/src/webapp/views/table.ts
> chore(packages/core): import files with relative path inside the core module

- tools/travis/installers/microk8s/start-cluster.sh
> test: pin microk8s version

- packages/core/src/api/ui.ts
- plugins/plugin-apache-composer/src/lib/controller/cmd/preview.ts
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
- plugins/plugin-k8s/src/lib/controller/describe.ts
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/lib/view/form.ts
- plugins/plugin-k8s/src/lib/view/modes/containers.ts
- plugins/plugin-k8s/src/lib/view/modes/crud.ts
- plugins/plugin-k8s/src/lib/view/modes/events.ts
- plugins/plugin-k8s/src/lib/view/modes/last-applied.ts
- plugins/plugin-k8s/src/lib/view/modes/pods.ts
- plugins/plugin-k8s/src/preload.ts
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
- plugins/plugin-openwhisk/src/lib/models/modes.ts
- plugins/plugin-operator-framework/src/preload.ts
- plugins/plugin-operator-framework/src/view/modes/crds.ts
- plugins/plugin-operator-framework/src/view/modes/description.ts
- plugins/plugin-operator-framework/src/view/modes/packages.ts
- plugins/plugin-tekton/src/model/modes/flow.ts
- plugins/plugin-tekton/src/model/modes/logs.ts
- plugins/plugin-tekton/src/model/modes/run.ts
- plugins/plugin-tekton/src/model/modes/trace.ts
- plugins/plugin-tekton/src/preload.ts
- plugins/plugin-tekton/src/view/flow.ts
- plugins/plugin-tutorials/src/preload.ts
- plugins/plugin-wskflow/src/lib/util.ts
> chore: continued core API work with Modes

- packages/core/src/core/settings.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-manager/src/lib/cmds/commands.ts
- plugins/plugin-manager/src/lib/cmds/compile.ts
- plugins/plugin-manager/src/lib/cmds/install.ts
- plugins/plugin-manager/src/lib/cmds/list.ts
- plugins/plugin-manager/src/lib/cmds/remove.ts
- plugins/plugin-wrk/src/lib/init.ts
> chore: add userDataDir and preferences methods to Settings API

- packages/core/src/api/ui.ts
- plugins/plugin-k8s/src/lib/controller/describe.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-operator-framework/src/preload.ts
- plugins/plugin-operator-framework/src/view/modes/icon.ts
- plugins/plugin-tekton/src/model/modes/trace.ts
- plugins/plugin-tekton/src/view/flow.ts
> chore: add Badge to UI API

- packages/core/src/api/commands.ts
- packages/core/src/models/command.ts
- packages/core/src/models/entity.ts
- packages/core/src/webapp/cli.ts
- packages/core/src/webapp/views/sidecar.ts
- plugins/plugin-apache-composer/src/lib/controller/cmd/app-get.ts
- plugins/plugin-apache-composer/src/lib/controller/cmd/session-get.ts
- plugins/plugin-core-support/src/lib/cmds/clear.ts
- plugins/plugin-core-support/src/lib/cmds/window.ts
- plugins/plugin-editor/src/lib/cmds/edit.ts
- plugins/plugin-editor/src/lib/editor-provider.ts
- plugins/plugin-editor/src/lib/fetchers.ts
- plugins/plugin-editor/src/lib/open.ts
- plugins/plugin-editor/src/lib/persisters.ts
- plugins/plugin-editor/src/lib/response.ts
- plugins/plugin-editor/src/lib/util.ts
- plugins/plugin-k8s/src/lib/controller/kiali.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/invoke.ts
- plugins/plugin-tutorials/src/lib/cmds/get.ts
- plugins/plugin-tutorials/src/lib/cmds/modes.ts
> chore: improve core API for command responses

- packages/core/src/api/ui.ts
- plugins/plugin-bash-like/src/lib/cmds/git-status.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-core-support/src/lib/cmds/confirm.ts
- plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
- plugins/plugin-core-support/src/lib/cmds/prompt.ts
- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-core-support/src/lib/tab-completion.ts
- plugins/plugin-core-support/src/lib/text-search.ts
- plugins/plugin-grid/src/lib/util.ts
- plugins/plugin-k8s/src/lib/controller/auth.ts
- plugins/plugin-k8s/src/lib/util/log-parser.ts
- plugins/plugin-manager/src/lib/util.ts
- plugins/plugin-openwhisk/src/lib/cmds/auth.ts
- plugins/plugin-openwhisk/src/lib/cmds/wipe.ts
- plugins/plugin-openwhisk/src/lib/models/namespace.ts
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/activations.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts
- plugins/plugin-tekton/src/model/modes/trace.ts
- plugins/plugin-tutorials/src/lib/cmds/play.ts
> chore: continued core API work, with cli-oriented APIs

- packages/core/src/api/commands.ts
- packages/core/src/api/models.ts
- packages/core/src/models/entity.ts
- packages/core/src/webapp/views/sidecar.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-editor/src/lib/editor-provider.ts
- plugins/plugin-editor/src/lib/fetchers.ts
- plugins/plugin-k8s/src/lib/controller/helm/get.ts
- plugins/plugin-k8s/src/lib/model/resource.ts
- plugins/plugin-k8s/src/lib/view/helm-status.ts
> chore: continued core API work with new Models namespace

- packages/core/src/api/models.ts
- packages/core/src/core/repl.ts
- packages/core/src/models/history.ts
- packages/core/src/webapp/cli.ts
- plugins/plugin-core-support/src/lib/cmds/history/history.ts
- plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
- plugins/plugin-openwhisk-editor-extensions/src/preload.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/webbify.ts
- plugins/plugin-openwhisk/src/lib/cmds/activations/await.ts
- plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
- plugins/plugin-openwhisk/src/lib/cmds/rm.ts
- plugins/plugin-openwhisk/src/lib/models/openwhisk-entity.ts
> chore: continued core API work with Models.History and Models.Selection

- docs/installation.md
> docs: remove headless download

- packages/core/src/api/ui.ts
- packages/core/src/core/repl.ts
- packages/core/src/webapp/picture-in-picture.ts
- packages/core/src/webapp/views/table.ts
- packages/core/src/webapp/views/top-tabs.ts
- plugins/plugin-apache-composer/src/lib/controller/cmd/preview.ts
- plugins/plugin-apache-composer/src/lib/utility/decorate.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/ui.ts
- plugins/plugin-editor/src/lib/open.ts
- plugins/plugin-grid/src/lib/cell.ts
- plugins/plugin-grid/src/lib/cmds/grid.ts
- plugins/plugin-grid/src/lib/cmds/table.ts
- plugins/plugin-grid/src/lib/drilldown.ts
- plugins/plugin-k8s/src/lib/view/modes/containers.ts
ansi pretty printer
more removals of external use of drilldown
part of #2833
> chore: continued core API work

- packages/builder/dist/publishers/s3/publish.sh
- tools/typecov/lib/core-percent.js
> fix: electron publish breakage

- packages/builder/dist/publishers/s3/push-cos.js
> fix: lingering reference to packages/app in push-cos.js

- packages/core/src/webapp/cli.ts
- plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts
> fix: drilldown bugs in openwhisk trace view

- packages/core/src/api/models.ts
- packages/core/src/core/repl.ts
- packages/core/src/core/symbol-table.ts
- packages/core/src/models/execOptions.ts
- packages/core/src/webapp/cli.ts
- packages/core/src/webapp/views/sidecar.ts
- plugins/plugin-apache-composer/src/lib/controller/cmd/preview.ts
- plugins/plugin-apache-composer/src/lib/utility/decorate.ts
- plugins/plugin-apache-composer/src/lib/view/entity-view.ts
- plugins/plugin-apache-composer/src/test/composer1/composer-edit.ts
- plugins/plugin-bash-like/src/lib/cmds/export.ts
- plugins/plugin-core-support/src/lib/cmds/about/about.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts
- plugins/plugin-openwhisk/src/test/openwhisk3/seq-let.ts
- plugins/plugin-wskflow/src/lib/ast.ts
- plugins/plugin-wskflow/src/lib/fsm2graph.ts
- plugins/plugin-wskflow/src/lib/graph2doms.ts
- plugins/plugin-wskflow/src/lib/response.ts
- plugins/plugin-wskflow/src/lib/subtext.ts
- plugins/plugin-wskflow/src/lib/visualize.ts
> chore: more core API work with about, wskflow cleanup

- packages/builder/tsconfig-base.json
- packages/core/package.json
- packages/core/src/core/usage-error.ts
- packages/core/src/main/headless-pretty-print.ts
- packages/core/src/main/headless-support.ts
- packages/core/src/main/spawn-electron.ts
- packages/core/src/test/core/command-not-found-suggestions.ts
- packages/core/src/util/tee.ts
- packages/core/src/util/types.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/core/src/webapp/cli.ts
- packages/core/src/webapp/util/ascii-to-table.ts
- packages/core/src/webapp/views/sidecar.ts
- packages/core/tsconfig.json
- plugins/plugin-bash-like/src/pty/channel.ts
- plugins/plugin-bash-like/src/pty/stdio-channel.ts
- plugins/plugin-openwhisk/package.json
- plugins/plugin-openwhisk/src/lib/cmds/add-parameter.ts
- plugins/plugin-openwhisk/src/lib/views/render-field.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/activations.ts
- plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/action-drilldown-from-activation.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/action-list-click.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/headless.ts
- plugins/plugin-openwhisk/src/test/openwhisk4/zip.ts
- plugins/plugin-tutorials/src/lib/cmds/play.ts
- plugins/plugin-wskflow/src/lib/fsm2graph.ts
- plugins/plugin-wskflow/src/lib/graph.ts
- plugins/plugin-wskflow/tsconfig.json
> chore: improve type coverage

- package-lock.json
- packages/builder/bin/compile.sh
- packages/core/package.json
- packages/core/src/api/ui.ts
- packages/core/src/core/repl.ts
- packages/core/src/main/headless-pretty-print.ts
- packages/core/src/models/MultiModalResponse.ts
- packages/core/src/models/command.ts
- packages/core/src/models/entity.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/core/src/webapp/cli.ts
- packages/core/src/webapp/models/table.ts
- packages/core/src/webapp/views/sidecar.ts
- packages/core/web/css/ui.css
- plugins/plugin-bash-like/package.json
> feat: introduce new MultiModalResponse API

- packages/core/src/api/ui.ts
- packages/core/src/core/plugins.ts
- packages/core/src/models/entity.ts
- packages/core/src/models/errors.ts
- packages/core/src/webapp/cli.ts
- packages/core/src/webapp/views/formattable.ts
- packages/core/src/webapp/views/sidecar.ts
- packages/core/src/webapp/views/toolbar-text.ts
> feat(packages/core): improve API for providing sidecar entity content

- .gitignore
- bin/pack.sh
- clients/bin/.gitignore
- clients/bin/mkclient.sh
- packages/proxy/.npmignore
- packages/proxy/app/bin/run-proxy.sh
- packages/proxy/app/npm-shrinkwrap.json
- packages/proxy/app/package.json
- packages/proxy/app/routes/exec.js
- packages/proxy/build.sh
- packages/proxy/package.json
- tools/travis/test/target.d/proxy.sh
- tools/travis/test/target.d/webpack.sh
> chore: updates to facilitate testing of external clients

- packages/core/tsconfig.json
- plugins/plugin-apache-composer/tsconfig.json
- plugins/plugin-bash-like/tsconfig.json
- plugins/plugin-grid/tsconfig.json
- plugins/plugin-k8s/tsconfig.json
- plugins/plugin-openwhisk-editor-extensions/tsconfig.json
- plugins/plugin-openwhisk/tsconfig.json
- plugins/plugin-operator-framework/tsconfig.json
- plugins/plugin-tekton/tsconfig.json
- tsconfig.json
Reorder the top-level tsconifg refereneces paths
Fixes #2915
> chore: remove the tsconfig references in each individual component

- clients/bin/mkclient.sh
- tools/travis/test/target.d/webpack.sh
> test: external webpack client on travis

- clients/base/.gitignore
- clients/base/package.json
- clients/base/theme
- packages/core/package.json
> feat: kui-base including core and plugin-core-support only

- .travis.yml
> chore: deepen the clone prior to lerna publish

- clients/base/package.json
> fix: update kui-base dependencies to 5.0.0

- packages/builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
> fix(packages/builder): carbon gray 10 popup input font color too dark

- packages/test/src/api/common.ts
- packages/test/src/api/util.ts
> test: after npm run test, electron window should be closed

- packages/core/src/webapp/bootstrap/init.ts
> fix(packages/core): undefined window title in popup mode

- packages/core/web/css/ui.css
> fix(packages/core): popup spinner is tiny

- packages/core/src/plugins/commands.ts
> fix(packages/core): commands for plugin didn't handle no-usage case

- .travis.yml
- clients/base/package.json
- packages/builder/dist/electron/build.sh
- packages/builder/dist/electron/builders/deb.sh
- plugins/plugin-editor/src/test/editor/command-not-found-suggestions.ts
- plugins/plugin-openwhisk-editor-extensions/src/test/openwhisk-editor/command-not-found-suggestions.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/command-not-found-suggestions.ts
- plugins/plugin-openwhisk/src/test/openwhisk3/error-handling.ts
- tools/travis/publishers/cos.sh
- tools/travis/test/target.d/electron.sh
> test: travis core tests against kui-base

- packages/core/src/core/usage-error.ts
> fix(packages/core): kui hangs with command registered as subtree without usage

- packages/core/src/core/command-tree.ts
- packages/core/src/core/repl.ts
- packages/core/src/plugins/scanner.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
> chore: remove old "intention" logic

- bin/pack.sh
- clients/base/package.json
> fix: clients/base should not have hard-wired kui-packs deps

- packages/builder/tsconfig-base.json
> feat(packages/builder): add removeComments:true to tsconfig-base.json

- bin/pack.sh
- tools/travis/test/target.d/webpack.sh
> fix: improve error handling in bin/pack.sh

- packages/core/src/@types/mimic-dom.d.ts
- packages/core/src/util/mimic-dom.ts
> fix(packages/core): mimic-dom should mimic sessionStorage

- packages/core/src/webapp/cli.ts
- packages/core/src/webapp/views/table.ts
- packages/core/web/css/carbon-overrides-common.css
- packages/core/web/css/kui-tables.css
- packages/core/web/css/ui.css
improve consistency of viewport-relative sizing
fix double-tabs for drilldowns to sidecar
Fixes #2983
> fix(packages/core): improve rendering of popup mode

- bin/pack.sh
> fix: update pack.sh to work better in travis

- packages/core/web/css/carbon-overrides-common.css
- packages/core/web/css/ui.css
this also introduces a few more minor fixes for popup viewport sizing
Fixes #2987
> fix(packages/core): spinner color should follow brand palette

- clients/base/package.json
> add plugin-manager to kui-base client

- package-lock.json
- packages/core/package.json
> fix(packages/core): add missing marked dependence in packages/core

- packages/core/src/core/repl.ts
- plugins/plugin-manager/src/test/manager/plugin.ts
also cleans up lint member accessiblity violations
Fixes #3003
> fix(packages/core): remove leftover console.trace

- clients/bin/mkclient.sh
- packages/webpack/package.json
> fix: revert to webpack 4.40

- packages/builder/examples/build-configs/default/theme/theme.json
- packages/core/src/commands/tree.ts
- packages/core/src/core/command-tree.ts
- packages/core/src/plugins/assembler.ts
- packages/core/src/plugins/prescan.ts
- packages/core/src/plugins/resolver.ts
- packages/core/src/plugins/scanner.ts
- plugins/plugin-apache-composer/src/lib/controller/cmd/preview.ts
- plugins/plugin-apache-composer/src/test/composer1/composer-update.ts
- plugins/plugin-editor/src/lib/cmds/edit.ts
- plugins/plugin-grid/src/lib/cmds/grid.ts
- plugins/plugin-grid/src/lib/cmds/table.ts
- plugins/plugin-manager/src/test/manager/plugin.ts
- plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts
- plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts
- plugins/plugin-openwhisk/src/lib/cmds/actions/webbify.ts
- plugins/plugin-openwhisk/src/lib/cmds/activations/await.ts
- plugins/plugin-openwhisk/src/lib/models/modes.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/bottom-stripe-action.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/apis.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/copy.ts
- plugins/plugin-openwhisk/src/test/openwhisk2/load-test.ts
- plugins/plugin-openwhisk/src/test/openwhisk3/error-handling.ts
- plugins/plugin-openwhisk/src/test/openwhisk3/list-all.ts
- plugins/plugin-openwhisk/src/test/openwhisk3/on.ts
- plugins/plugin-openwhisk/src/test/openwhisk4/webbify.ts
> chore: remove command disambiguation support

- packages/builder/examples/build-configs/default/theme/theme.json
- plugins/plugin-k8s/src/lib/controller/auth.ts
- plugins/plugin-k8s/src/lib/controller/contexts.ts
- plugins/plugin-k8s/src/lib/controller/kedit.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
- plugins/plugin-k8s/src/lib/controller/status.ts
> fix: remove k8s command prefix for kube commands

- packages/core/src/commands/context.ts
> fix: allow KUI_COMMAND_CONTEXT env var to override default theme setting

- packages/core/src/core/repl.ts
> chore(packages/core): backport #3015 to 5_1_x

- packages/core/src/util/types.ts
> fix(packages/core): isHTML fails if input is null

- packages/core/web/css/kui-tables.css
> fix(packages/core): poor popup table cell spacing

- plugins/plugin-core-support/src/lib/cmds/history/history.ts
> fix(plugins/plugin-core-support): command `!!` returns console error

- packages/core/src/main/headless-pretty-print.ts
- plugins/plugin-k8s/src/lib/controller/kubectl.ts
> fix: some long-standing issues with table display in headless mode

- plugins/plugin-manager/src/util/ora.ts
> fix(plugins/plugin-manager): minor alignment issue with ora checkmarks

- packages/builder/examples/build-configs/default/theme/css/themes/dark.css
- packages/core/web/css/kui-tables.css
- packages/core/web/css/ui.css
> fix(packages/core): update sidecar tables to match #3037

- packages/core/web/css/kui-tables.css
> fix(packages/core): inconsistent horizontal padding in popup tables

- packages/core/src/plugins/resolver.ts
catchall plugin reification is not resilient to the case where the plugin that defines the catchall impl can no longer be found
Fixes #3050
> fix(packages/core): fix for low-level bug in resolver.resolve

- packages/core/src/webapp/print.ts
> fix(packages/core): popup kind displays CUSTOM for tables

- clients/base/theme/css/themes/carbon-gray10.css
- packages/builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
- packages/core/src/webapp/print.ts
- packages/core/src/webapp/views/table.ts
- packages/core/web/css/kui-tables.css
- packages/core/web/css/top-tab-stripe.css
- packages/core/web/css/ui.css
- plugins/plugin-manager/src/controller/install.ts
- plugins/plugin-manager/src/util/ora.ts
> fix: improve plugin install

- clients/alternate/theme/css/themes/carbon-gray10.css
- clients/base/theme/css/themes/carbon-gray10.css
- packages/builder/examples/build-configs/default/theme/css/themes/carbon-gray10.css
- packages/core/src/core/userdata.ts
- packages/core/src/main/headless-pretty-print.ts
- packages/core/src/main/headless-support.ts
- packages/core/src/plugins/commands.ts
- packages/core/src/plugins/plugins.ts
- packages/core/src/repl/exec.ts
- packages/core/src/webapp/popup.ts
- packages/core/src/webapp/print.ts
- packages/core/web/css/ui.css
- plugins/plugin-manager/src/controller/install.ts
- plugins/plugin-manager/src/test/manager/plugin.ts
- plugins/plugin-manager/src/util/ora.ts
- plugins/plugin-openwhisk/src/test/openwhisk1/headless.ts
> fix(packages/core): avoid "custom" in the sidecar "kind" display

- package-lock.json
- packages/core/package.json
- packages/core/src/main/main.ts
- packages/core/src/main/spawn-electron.ts
also electron-squirrel-starutp
the former is causing problems with Edge
Fixes #3064
> fix(packages/core): remove electron-context-menu dependence

- clients/base/theme/theme.json
> fix: remove CSP from clients/base

- packages/core/src/webapp/popup.ts
> fix(packages/core): remove debugging printf from core popup

- README.md
Fixes https://github.com/IBM/kui/issues/2896
Added contribution guidelines doc link to main readme.
> docs: add contribution guidelines link to main readme

- packages/core/src/api/ui.ts
- plugins/plugin-core-support/src/lib/cmds/clear.ts
- plugins/plugin-core-support/src/test/core-support/clear.ts
> fix(plugins/plugin-core-support) clear will close the sidecar

- packages/core/src/models/mmr/show.ts
> fix(packages/core): MultiModalResponse can have duplicate tabs

- packages/core/src/models/mmr/show.ts
> fix(packages/core): multimodalresponse does not display buttons

- packages/core/src/webapp/print.ts
- plugins/plugin-manager/src/test/manager/plugin.ts
> fix(packages/core): REPL UI should emit "ok" for multimodalresponse

- clients/base/theme/css/themes/tomorrow-night.css
- packages/builder/examples/build-configs/default/theme/css/themes/tomorrow-night.css
> fix: tomorrow night theme should use blue for table names

- packages/core/web/css/kui-tables.css
> fix(packages/core): use tighter row spacing for Light tables

- packages/test/bin/runMochaLayers.sh
> fix(packages/test): runMochaLayers versus external clients

- packages/core/web/css/ui.css
> fix(packages/core): tighten up inter-block vertical spacing

- packages/core/web/css/ui.css
> fix(packages/core): radio table height changes when selected row changes

- packages/core/src/models/tab-state.ts
- packages/core/src/webapp/picture-in-picture.ts
> fix(packages/core): drilldown versus back button race condition

- packages/core/tests/lib/headless.js
- packages/test/.npmignore
> test(packages/core): headless test rig should prepend not append path

- packages/core/tests/lib/headless.js
> test: improved fix for prependPath

- packages/builder/dist/electron/build.sh
> fix(packages/builder): electron builder versus external clients

- packages/test/src/api/common.ts
> test(packages/test): webpack mode versus external clients

- packages/core/src/api/registrars.ts
- packages/core/src/api/ui-lite.ts
- packages/core/src/api/ui.ts
- packages/core/src/models/mmr/content-types.ts
- packages/core/src/models/mmr/show.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/core/src/webapp/views/registrar/modes.ts
> feat: allow plugins to pre-register high-level Modes

- packages/core/src/models/mmr/content-types.ts
- packages/core/src/models/mmr/show.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/bottom-stripe.ts
missing commit from #3124
Fixes #3123
> feat(packages/core): addendum to #3124

- .travis.yml
> test: remove client-base osx travis test

- .travis.yml
- clients/test/.gitignore
- clients/test/package.json
- clients/test/plugins/plugin-test/.gitignore
- clients/test/plugins/plugin-test/package.json
- clients/test/plugins/plugin-test/src/plugin.ts
- clients/test/plugins/plugin-test/src/test/response/stringResponse.ts
- clients/test/plugins/plugin-test/tsconfig.json
- clients/test/theme
- clients/test/tsconfig.json
- packages/test/src/api/string-response.ts
- tools/travis/test/script.sh
- tools/travis/test/target.d/electron.sh
> feat: client test

- packages/core/src/models/mmr/show.ts
> fix(packages/core): remove debugging from mmr/show

- packages/core/src/models/entity.ts
- packages/core/src/models/mmr/show.ts
> fix(packages/core): improve support for pretty-printed names in MMR

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-namespace.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
> test: expand Client Test to test MMR metadata.namespace 

- clients/bin/mkclient.sh
- packages/builder/bin/compile.sh
> fix: mkclient.sh failed with tsc error

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-kind.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-kind.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
> test: expand Client Test to test MMR kind

- packages/core/src/api/table-models.ts
> fix(packages/core): add TableStyle and Cell to exported table-models API

- clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts
- clients/test/plugins/plugin-test/src/lib/cmds/content/text-html.ts
- clients/test/plugins/plugin-test/src/lib/cmds/content/text-markdown.ts
- clients/test/plugins/plugin-test/src/lib/cmds/metadata.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-kind.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts
- clients/test/plugins/plugin-test/src/plugin.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-kind.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/test/response/string.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
Also refactored the existing tests in `clients/test` to use the data (command, metadata, mode, etc) from `src/lib/cmd` directly.
Fixes #3160
> test: expand clients/test to test mode and label of MMR modes

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- packages/core/src/api/registrars.ts
- packages/core/src/models/mmr/show.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/core/src/webapp/print.ts
- packages/core/src/webapp/views/badge.ts
- packages/core/src/webapp/views/registrar/modes.ts
- packages/core/src/webapp/views/sidecar.ts
- packages/core/web/css/ui.css
- plugins/plugin-manager/src/controller/get.ts
> fix(packages/core): improve sidecar button behavior

- packages/core/src/webapp/views/sidecar-visibility.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
> fix(packages/core): mmr couldn't show up when the sidecar is minimized

- packages/core/src/models/mmr/show.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/views/registrar/modes.ts
- packages/core/src/webapp/views/sidecar.ts
- packages/core/src/webapp/views/table.ts
- packages/core/web/css/kui-tables.css
> feat(packages/core): mode registrations should be overridable

- docs/dev/README.md
- docs/installation.md
> docs: update the installation docs for using kui as a kubectl plugin

- clients/alternate/theme/css/themes/carbon-gray90.css
> fix: port over carbon-gray90 (IBM-Dark) updates to clients/alternate

- packages/core/src/repl/exec.ts
> fix(packages/core): on repl.exec error, emit errors to debug channel

- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- packages/core/src/webapp/views/sidecar-init.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
> fix(packages/core): sidecar basic function should not require plugins

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/plugin.ts
- clients/test/plugins/plugin-test/src/preload.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- packages/core/src/models/mmr/content-types.ts
- packages/core/src/models/mmr/show.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/models/plugin.ts
- packages/core/src/plugins/preloader.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
- packages/test/src/index.ts
- plugins/plugin-core-support/src/preload.ts
- plugins/plugin-manager/src/controller/get.ts
> feat(packages/core): pass a PreloadRegistrar to plugin preloaders

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-kind.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- packages/test/src/api/cli.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
- packages/test/src/api/util.ts
> test: add MMR toolbar text and drilldown button tests to clients/test

- tools/travis/setup-webhook.sh
> fix: setup-webhook bug with webbify path

- plugins/plugin-bash-like/src/lib/cmds/open.ts
- plugins/plugin-k8s/src/test/k8s1/kedit.ts
> fix(plugins/plugin-bash-like): open should not use kedit

- clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-kind.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-name.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts
- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-kind.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-name.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/test/response/string.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
- packages/test/src/index.ts
This PR includes tests for:
1) cycle through the sidecar tabs
2) text/plain content, including the one produced by function
3) yaml plain content
Fixes #3203
> test: more MMR tests in client/tests

- packages/builder/dist/publishers/s3/package-lock.json
- tools/travis/publishers/cos.sh
> fix: another attempt to not-modify a package-lock.json

- .travis.yml
- tools/travis/publishers/cos.sh
1) don't execute publishers/cos.sh
2) add git status and git diff to help with debugging
Fixes #3208
> fix: improve npm release stage

- .travis.yml
- README.md
- package-lock.json
- package.json
- packages/core/src/main/spawn-electron.ts
- packages/core/src/webapp/electron-events.ts
- packages/test/bin/runMochaLayers.sh
- packages/test/bin/runTest.sh
- packages/test/package.json
- packages/test/src/api/common.ts
- tools/codecov/instrument.sh
- tools/codecov/report.sh
- tools/travis/test/install.sh
- tools/travis/test/script.sh
> test: codecov

- README.md
> doc: remove lerna and github badges

- .codecov.yml
- tools/codecov/report.sh
> fix: fixup paths for codecov

- clients/test/plugins/plugin-test/src/lib/cmds/content/table-with-drilldown.ts
- clients/test/plugins/plugin-test/src/lib/cmds/table.ts
- clients/test/plugins/plugin-test/src/test/response/table.ts
- packages/test/src/api/cli.ts
- packages/test/src/api/table.ts
- packages/test/src/api/util.ts
- packages/test/src/index.ts
includes test for `onclickSilence: true`
Fixes #3219
> test: expand clients/test to test repl table drilldown

- .codecov.yml
- package-lock.json
- packages/test/src/api/common.ts
- tools/codecov/report.sh
an attempt to have reports in terms of .ts source
Fixes #3217
> fix: another fix for codecov

- packages/core/src/api/commands.ts
- packages/core/src/api/models.ts
> fix(packages/core): allow for lighter-weight imports of Commands API

- clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts
- clients/test/plugins/plugin-test/src/test/response/string.ts
- packages/core/src/api/commands.ts
- packages/core/src/models/command.ts
> fix(packages/core): add ParsedOptions to light Commands api

- packages/core/src/repl/exec.ts
- packages/core/src/webapp/views/sidecar.ts
- packages/core/web/css/ui.css
- plugins/plugin-bash-like/src/test/bash-like/cat-to-sidecar.ts
> fix(packages/core): current selection versus MetadataBearingByReference

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/preload.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
> test: add MMR defaultMode test to clients/test

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- packages/core/src/models/mmr/show.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/bottom-stripe.ts
> feat(packages/core): allow command-line overrides of default mmr mode

- packages/core/src/webapp/views/badge.ts
- packages/core/src/webapp/views/sidecar.ts
> fix(packages/core): duplicate version badges

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- packages/core/src/models/entity.ts
- packages/core/src/webapp/views/sidecar.ts
> feat(packages/core): expose name onclick to mmr

- packages/core/src/webapp/views/sidecar.ts
- packages/core/web/css/ui.css
> fix(packages/core): no sidecar title wrapping with namehash

- plugins/plugin-editor/src/lib/util.ts
> fix(plugins/plugin-editor): editor does not use metadata.name

- packages/core/src/webapp/views/sidecar.ts
> fix(packages/core): sidecar auto-close on delete versus metadata bearing

- packages/core/src/webapp/views/sidecar.ts
> fix(packages/core): name click handlers are sticky

- packages/test/src/api/sidecar-expect.ts
> fix(packages/test): nameHash waitUntil does not use waitTimeout

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-name.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-name.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-namespace.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
> test: test MMR name/namespace onclick in clients/test

- packages/test/src/api/mmr.ts
- packages/test/src/api/table.ts
- plugins/plugin-bash-like/src/test/bash-like-wait/pty-session-status.ts
- plugins/plugin-k8s/src/test/k8s1/describe.ts
- plugins/plugin-k8s/src/test/k8s2/about.ts
- plugins/plugin-k8s/src/test/k8s2/events.ts
> test: some tests use Common.oops incorrectly

- plugins/plugin-k8s/src/lib/controller/helm/get.ts
Fixes: https://github.com/IBM/kui/issues/3263
Increased stdout maxBuffer of `helm get` command to support large charts (>200KB).
> fix(plugins/plugin-k8s): increase `helm get` stdout maxBuffer

- tools/travis/publishers/cos.sh
> fix: travis doesn't push macOS build to the cos bucket

- docs/installation.md
- docs/readme/examples/kubernetes.md
> docs: fix from "examples" docs links

- packages/core/src/models/entity.ts
- packages/core/src/repl/exec.ts
> fix(packages/core): remove unused parts of Response data type

- packages/core/src/webapp/views/table.ts
> fix(packages/core): remove some old table formatting code

- packages/builder/dist/bin/compile.js
- tools/travis/test/install.sh
> fix: collect codecov for plugin assembler

- packages/core/src/api/commands.ts
- packages/core/src/api/selection.ts
- packages/core/src/models/mmr/button.ts
- packages/core/src/models/mmr/show.ts
- packages/core/src/plugins/preloader.ts
- packages/core/src/repl/exec.ts
- packages/core/src/util/is-fake-dom.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/core/src/webapp/popup.ts
- packages/core/src/webapp/print.ts
- packages/core/src/webapp/views/registrar/modes.ts
- packages/core/src/webapp/views/sidecar-visibility.ts
- packages/core/src/webapp/views/sidecar.ts
- plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
- plugins/plugin-core-support/src/lib/cmds/screenshot.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-core-support/src/lib/new-tab.ts
- plugins/plugin-tutorials/src/lib/cmds/play.ts
by refactoring the load path for mode and badge registration logic
Fixes #3286
> fix: reduce expense of preloader on webapp init

- clients/test/package.json
- clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts
- clients/test/plugins/plugin-test/src/lib/cmds/metadata.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- packages/core/src/models/mmr/button.ts
- packages/core/src/util/async.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
> test: improve test coverage of mmr buttons

- clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/models.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- packages/test/src/api/mmr.ts
> test: improve mmr mode test coverage

- clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
> test: test mmr mode order variants

- packages/builder/examples/build-configs/default/theme/css/themes/dark.css
> fix(packages/builder): improve color contrast of about in Dark theme

- plugins/plugin-editor/src/lib/readonly.ts
> fix(plugins/plugin-editor): remove leftover use of old `direct` API

- plugins/plugin-bash-like/src/pty/stdio-channel.ts
> fix: overlapping clien-to-proxy requests can lead to parse errors

- plugins/plugin-bash-like/src/index.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> chore(plugins/plugin-bash-like): export getSessionForTab for external use

- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> fix: propagate statusCode back from the proxy

- packages/webpack/webpack.config.js
> fix: add 'Access-Control-Allow-Origin': '*' to webpack dev server config

- README.md
- docs/installation.md
- plugins/plugin-bash-like/src/test/bash-like/blank-lines.ts
- plugins/plugin-core-support/src/test/core-support/screenshot.ts
> docs: add windows client download links

- packages/core/src/index.ts
> feat: core should export getAuthValue

- packages/core/src/webapp/views/registrar/badges.ts
> feat: badge registration should pass Tab context to badge renderer

- packages/core/src/index.ts
> feat: core should export unparse utility

- plugins/plugin-editor/src/index.ts
- plugins/plugin-editor/src/lib/fetchers.ts
- plugins/plugin-editor/src/lib/open.ts
- plugins/plugin-editor/src/lib/persisters.ts
- plugins/plugin-editor/src/lib/response.ts
> feat: editor's persister/fetcher API should expose tab context

- packages/builder/bin/compile.sh
- packages/webpack/webpack.config.js
- tsconfig-es6.json
> feat(packages/builder): kui-compile should allow specifying a tsconfig

- packages/core/tests/lib/headless.d.ts
- packages/core/tests/lib/headless.js
> feat: expose headless CLI test constructor

- clients/test/plugins/plugin-test/src/lib/cmds/table.ts
- clients/test/plugins/plugin-test/src/test/response/table.ts
- packages/test/src/api/table.ts
Also refactor the table api, and add job management tests
Fixes #3365
> test: augement the table watcher test to poll for deleted resource

- packages/core/src/core/jobs/job.ts
- packages/core/src/core/jobs/watchable.ts
- packages/core/src/index.ts
- packages/core/src/models/tab-state.ts
- packages/core/src/webapp/models/table.ts
- packages/core/src/webapp/print.ts
- packages/core/src/webapp/views/table.ts
> chore: introduce core/jobs/job.ts and core/jobs/watchable.ts

- clients/test/package.json
- packages/webpack/bin/watch.sh
> chore: consolidate webpack dev server sync LOCKFILE handling

- packages/builder/dist/electron/build.sh
- packages/webpack/webpack.config.js
> fix(packages/webpack): electron packager versus node-pty binaries

- plugins/plugin-editor/package.json
> fix(plugins/plugin-editor): pin monac-editor-webpack-plugin dep

- packages/core/src/util/i18n.ts
> fix(packages/core): i18n module should support numeric parmaeters

- packages/core/src/main/spawn-electron.ts
- packages/core/src/webapp/listen.ts
- packages/core/src/webapp/themes/persistence.ts
> feat(packages/core): set theme in advance (for electron)

- packages/core/web/css/ui.css
> fix(packages/core): toolbar text anchor text has low contrast

- plugins/plugin-wskflow/src/lib/graph2doms.ts
> fix(plugins/plugin-wskflow): wskflow's dynamic import of jquery and ELK

- packages/webpack/webpack.config.js
> feat(packages/webpack): allow plugins to specify webpack externals

- plugins/plugin-wskflow/src/lib/graph2doms.ts
> fix(plugins/plugins-wskflow): race in wskflow with edge labels

- packages/webpack/webpack.config.js
> fix(packages/webpack): don't ignore fsevents entirely in webpack

- packages/webpack/Dockerfile
- packages/webpack/build.sh
- packages/webpack/conf.d/enable-brotli.conf
- packages/webpack/webpack.config.js
- plugins/plugin-editor/package.json
> fix: webpack builds for production a bit broken

- packages/test/bin/runMochaLayersv2.sh
> fix(packages/test): runMochaLayersv2.sh should export WEBPACK_CLIENT_URL

- packages/webpack/webpack.config.js
> fix: improve contextRoot support for webpack

- packages/core/src/core/settings.ts
- packages/core/src/webapp/themes/default.ts
- packages/core/src/webapp/themes/find.ts
- packages/core/src/webapp/themes/persistence.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
> fix: regression due to introduced cycle dependendence

- packages/core/src/plugins/scanner.ts
> fix(packages/core): avoid double scanning for plugins

- packages/core/src/commands/tree.ts
- packages/core/src/core/command-tree.ts
- packages/core/src/repl/exec.ts
> fix(packages/core): improved fix for command lookup versus n-ary opts

- plugins/plugin-bash-like/src/lib/cmds/export.ts
- plugins/plugin-bash-like/src/test/bash-like/export.ts
> fix(plugins/plugin-bash-like): export with no args error handling

- clients/test/plugins/plugin-test/src/lib/cmds/table.ts
- clients/test/plugins/plugin-test/src/test/response/table.ts
- packages/core/src/core/jobs/watchable.ts
- packages/core/src/index.ts
- packages/core/src/webapp/models/table.ts
- packages/core/src/webapp/views/table.ts
> chore(packages/core): remove  watchable poller table

- packages/core/src/webapp/util/strip-ansi.ts
> fix: update strip-ansi to the latest

- packages/core/templates/index.html
> fix(packages/core): missing tooltip on sidecar maximize/minimize buttons

- plugins/plugin-bash-like/src/pty/prefetch.ts
- plugins/plugin-bash-like/src/pty/server.ts
> fix(plugins/plugin-bash-like): default to powershell not cmd on windows

- plugins/plugin-bash-like/src/pty/server.ts
> fix(plugins/plugin-bash-like): fix windows git bash pty regression

- plugins/plugin-bash-like/fs/src/lib/tab-completion.ts
- plugins/plugin-bash-like/fs/src/preload.ts
- plugins/plugin-core-support/src/test/core-support2/tab-completion.ts
- plugins/plugin-core-support/tab-completion/src/index.ts
- plugins/plugin-core-support/tab-completion/src/registrar.ts
- plugins/plugin-core-support/web/css/tab-completion.css
Fixes #3446
in addition to cleaning up some old and bad code, this fixes a few issues
Fixes #2403
Fixes #3447
> fix: port filesystem tab completion to tab completion API

- packages/core/src/core/command-tree.ts
- packages/core/src/webapp/oops.ts
- packages/core/web/css/ui.css
- packages/test/src/api/util.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-bash-like/web/css/xterm.css
- plugins/plugin-core-support/src/test/core-support/clear.ts
- plugins/plugin-core-support/src/test/core-support2/text-search.ts
> fix: reducing flashing effect for PTY command not found errors

- .travis.yml
- clients/test/package.json
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-kind.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-name.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-namespace.ts
- clients/test/plugins/plugin-test/src/lib/cmds/say-hello.ts
- clients/test/plugins/plugin-test/src/lib/cmds/stream-hello.ts
- clients/test/plugins/plugin-test/src/lib/cmds/table.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/string.ts
- packages/core/src/core/jobs/job.ts
- packages/core/src/core/jobs/watchable.ts
- packages/core/src/index.ts
- packages/core/src/models/command.ts
- packages/core/src/models/execOptions.ts
- packages/core/src/repl/exec.ts
- packages/core/src/webapp/models/table.ts
- packages/core/src/webapp/views/table.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/table.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/server.ts
> feat: pty should allow for streaming consumption of output

- packages/core/src/core/jobs/watchable.ts
- packages/core/src/webapp/views/table.ts
> feat(packages/core): allow push table updates to provide headers

- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/server.ts
> fix(plugins/plugin-bash-like): multiple PTYs per tab

- clients/test/plugins/plugin-test/src/lib/cmds/table.ts
- packages/core/src/core/jobs/watchable.ts
- packages/core/src/index.ts
- packages/core/src/webapp/views/table.ts
> fix: improve watch push API typing

- package-lock.json
- plugins/plugin-bash-like/fs/src/lib/ls.ts
- plugins/plugin-bash-like/package.json
> fix(plugins/plugin-bash-like): speed up date formatting in ls

- plugins/plugin-bash-like/src/pty/client.ts
> fix(plugins/plugin-bash-like): fix memory leak in pty/client

- packages/core/src/core/jobs/watchable.ts
- packages/core/src/webapp/views/table.ts
> fix(packages/core): fix memory leak in table push notification

- packages/core/src/models/command.ts
- packages/core/src/repl/exec.ts
> feat(packages/core): allow commands to tailor yargs-parser narg setting

- packages/core/src/webapp/models/table.ts
- packages/core/src/webapp/views/table.ts
- packages/core/web/css/ui.css
- plugins/plugin-bash-like/fs/src/lib/glob.ts
- plugins/plugin-bash-like/fs/src/lib/ls.ts
- plugins/plugin-bash-like/src/test/bash-like-wait/pty-session-status.ts
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-bash-like/src/test/bash-like/cd.ts
- plugins/plugin-bash-like/src/test/bash-like/ls.ts
- plugins/plugin-core-support/src/test/core-support2/history.ts
- plugins/plugin-core-support/src/test/core-support2/tab-completion.ts
performance tweaks for ls
Fixes #3473
> fix: don't default to ls -l

- packages/core/web/css/sidecar.css
> fix(packages/core): about can render with low contrast text

- packages/core/src/core/jobs/job.ts
- packages/core/src/models/tab-state.ts
- packages/core/src/webapp/views/table.ts
table push jobs will now be auto-captured to the instigating tab
Fixes #3363
> fix: improve job capture to tabs

- packages/core/web/css/ui.css
> fix(packages/core): ls grid layout tweaks

- packages/core/src/plugins/scanner.ts
> feat(packages/core): plugin scanner should also scan "client" directory

- plugins/plugin-bash-like/fs/src/lib/glob.ts
> fix(plugins/plugin-bash-like): ls versus tab switching

- packages/core/src/webapp/status-stripe.ts
- packages/core/web/css/status-stripe.css
- packages/core/web/css/ui.css
> fix(packages/core): status stripe icons not always vertically aligned

- plugins/plugin-bash-like/git/src/status-stripe.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
- plugins/plugin-bash-like/src/pty/client.ts
> fix(plugins/plugin-bash-like): clean up nested PTY execution path

- clients/test/plugins/plugin-test/src/lib/status-stripe.ts
- clients/test/plugins/plugin-test/src/preload.ts
- clients/test/plugins/plugin-test/src/test/response/status-stripe.ts
- packages/core/src/models/plugin.ts
- packages/core/src/plugins/preloader.ts
- packages/core/src/webapp/status-stripe.ts
- packages/core/templates/index.html
- packages/core/web/css/status-stripe.css
> feat: extend status stripe API to support "meters"

- packages/core/src/plugins/preloader.ts
> fix(packages/core): disable period meter updates

- packages/core/templates/index.html
- packages/core/web/css/sidecar.css
- packages/core/web/css/status-stripe.css
- packages/core/web/css/ui.css
- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
- plugins/plugin-core-themes/web/css/dracula.css
- plugins/plugin-core-themes/web/css/light.css
> fix: status stripe UI fixes to work better across themes

- plugins/plugin-carbon-themes/web/css/ibm-plex.css
> feat: add ibm-plex.css in plugin-carbon-themes

- packages/core/src/webapp/block.ts
- packages/core/src/webapp/print.ts
- packages/core/src/webapp/views/table.ts
> fix(packages/core): table updates should (sometimes) scroll into view

- packages/core/src/webapp/views/table.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
> fix(packages/core): cell onclick should be on inner

- packages/core/web/css/carbon-overrides-common.css
> fix(packages/core): override carbon's line-height:1

- packages/core/web/css/ui.css
> fix(packages/core): update bottom input UI to avoid large right-pad

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump to electron 6.1.7

- clients/test/package.json
> chore: bump clients/test to electron 6.1.7

- packages/builder/dist/electron/build.sh
> fix: exclude all but woff2 fonts for electron builds

- packages/core/src/plugins/preloader.ts
- packages/core/src/webapp/tab.ts
- plugins/plugin-bash-like/src/pty/session.ts
> fix: improved fixes for status bar

- packages/core/src/plugins/preloader.ts
> fix(packages/core): further improvements to status stripe bootstrapping

- lerna.json
> chore: improve lerna publish commit messages

- packages/webpack/build-docker.sh
> fix(packages/webpack): build-docker regression on non-mac platforms

- packages/builder/examples/build-configs/default/standalone.json
- packages/builder/examples/build-configs/default/webpack-watch.json
- packages/builder/examples/build-configs/default/webpack.json
> fix(packages/builder): remove outdated builder examples

- packages/core/src/webapp/bottom-stripe.ts
> fix(packages/core): onclicks in sidecar tables result in odd behavior

- packages/core/src/repl/exec.ts
- packages/core/src/webapp/block.ts
- packages/core/src/webapp/cancel.ts
- packages/core/src/webapp/queueing.ts
- packages/core/src/webapp/status.ts
- packages/core/src/webapp/tab.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
> feat(packages/core): improved cancel via ctrl+c

- clients/test/package.json
- plugins/plugin-client-default/package.json
> fix: inter-plugin dependencies are not specified

- plugins/plugin-core-support/src/lib/new-tab.ts
> feat(plugins/plugin-core-support): switch tabs via keyboard shortcuts

- packages/core/src/webapp/themes/persistence.ts
> fix(packages/core): webview-based theme injection can result in errors

- packages/core/src/models/mmr/show.ts
- packages/core/src/webapp/bottom-stripe.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/util.ts
cherry pick
5ce89aa49b0dd29be0b0cc3cebf30ef416507ad6
> fix(packages/core): MMR rendering is glitchy

- packages/core/src/webapp/bottom-stripe.ts
> fix(packages/core): incorrect sidecar content may be presented

- packages/core/src/webapp/listen.ts
> fix: vi will block buttom-input cross-tab

- plugins/plugin-editor/i18n/resources_de.json
- plugins/plugin-editor/i18n/resources_es.json
- plugins/plugin-editor/i18n/resources_fr.json
- plugins/plugin-editor/i18n/resources_it.json
- plugins/plugin-editor/i18n/resources_ja.json
- plugins/plugin-editor/i18n/resources_ko.json
- plugins/plugin-editor/i18n/resources_pt_BR.json
- plugins/plugin-editor/i18n/resources_zh_CN.json
- plugins/plugin-editor/i18n/resources_zh_TW.json
> chore(plugin-editor): integrate next round of translation

- packages/test/src/api/keys.ts
- plugins/plugin-client-common/src/components/TopTabStripe/index.tsx
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> fix(plugins/plugin-client-common): keyboard shortcuts for TopTabStripe aren't working

- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/TopTabStripe/NewTabButton.tsx
- plugins/plugin-client-common/src/components/TopTabStripe/Tab.tsx
> chore(plugins/plugin-client-common): use @carbon/icons-react for NewTab and CloseTab buttons

- plugins/plugin-client-common/src/components/TopTabStripe/Tab.tsx
> fix(plugins/plugin-client-common): Tab.tsx does not render "processing" state

- packages/core/src/index.ts
- packages/core/src/main/headless-pretty-print.ts
- packages/core/src/models/NavResponse.ts
- packages/core/src/models/entity.ts
- plugins/plugin-client-default/config.d/about.json
- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-sidecar/src/preload.ts
- plugins/plugin-sidecar/src/view/components/BaseSidecar.tsx
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
- plugins/plugin-sidecar/src/view/react.ts
- plugins/plugin-sidecar/src/view/react2kui.ts
> feat: a new model NavResponse supporting side navigation menu

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/TabContent.tsx
- plugins/plugin-client-common/web/css/static/split-pane.scss
- plugins/plugin-sidecar/src/view/components/BaseSidecar.tsx
- plugins/plugin-sidecar/src/view/components/ComboSidecar.tsx
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
> feat: resizable sidecar

- packages/core/src/index.ts
- packages/core/src/repl/exec.ts
- packages/core/src/webapp/block.ts
- plugins/plugin-client-common/src/components/Scalar/index.tsx
> chore: remove "subblock" API from core

- plugins/plugin-sidecar/src/view/components/BaseSidecar.tsx
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
> fix(plugins/plugin-sidecar): LeftNavSidecar appears too wide

- plugins/plugin-core-support/screenshot/src/index.ts
- plugins/plugin-sidecar/src/controller/screenshot.ts
> fix: sidecar screenshot captures blank canvas

- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/preload.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- packages/core/src/models/mmr/content-types.ts
- plugins/plugin-client-common/package.json
- plugins/plugin-client-default/package.json
- plugins/plugin-sidecar/src/view/components/Eval.tsx
> fix(packages/core): restore CommandStringContent as one of FunctionThatProducesContent types

- packages/core/src/index.ts
- packages/core/src/webapp/queueing.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/OnPaste.tsx
> chore: move remaining paste logic out of core

- plugins/plugin-client-common/src/components/Screenshot.tsx
- plugins/plugin-client-common/web/css/static/Screenshot.scss
> fix(plugins/plugin-client-common): clean up screenshot notification UI

- plugins/plugin-client-common/web/css/static/repl.scss
> fix(plugins/plugin-client-common): misaligned svgs in paginated table

- plugins/plugin-client-common/src/components/TopTabStripe/Tab.tsx
> fix(plugins/plugin-client-common): When command completes, TopTab doesn't change the process state

- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/preload.ts
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
> fix(plugins/plugin-sidecar): regressions about defaultMode and order

- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
> fix(plugins/plugin-sidecar): don't focus on TopNavSidecar tabs on click

- plugins/plugin-client-common/web/css/static/status-stripe.css
> fix(plugins/plugin-client-common): status stripe left-pad missing

- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
- plugins/plugin-bash-like/web/css/static/xterm.css
- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/css/static/ui.css
> feat(plugins/plugin-client-common): accordion blocks in Terminal

- packages/test/src/api/selectors.ts
- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-client-common/src/components/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/css/static/carbon-overrides-common.css
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-core-support/src/test/core/about.ts
- plugins/plugin-editor/web/css/static/editor.css
- plugins/plugin-sidecar/src/controller/screenshot.ts
- plugins/plugin-sidecar/src/view/components/BaseSidecar.tsx
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
- plugins/plugin-sidecar/web/css/static/sidecar.css
> chore: eliminate use of custom <repl> and <sidecar> tags

- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/index.tsx
> fix(plugins/plugin-client-common): text-selection is not working in repl
