kubernetes-sigs/kui

- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/ToolbarContainer.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
> fix(plugins/plugin-sidecar): lazily load monaco-editor

- plugins/plugin-sidecar/web/css/static/sidecar-main.css
> fix(plugins/plugin-sidecar): poor hover colors for not-selected tabs

- plugins/plugin-client-common/src/components/TabContainer.tsx
> fix(plugins/plugin-client-common): improve error handling of hackFocus

- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
> fix(Plugins/plugin-carbon-tables): Pagination UI can overflow offscreen

- plugins/plugin-client-common/src/components/Scalar/index.tsx
> fix(plugins/plugin-client-common): improve error handling of Scalar.tsx

- clients/alternate/plugins/plugin-test/src/test/bottom-input/new-tab.ts
- packages/core/src/webapp/tab.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/table.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
- plugins/plugin-bash-like/src/test/bash-like/vi.ts
- plugins/plugin-bash-like/web/css/static/xterm.css
- plugins/plugin-client-common/src/components/TabContent.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/OnKeyDown.ts
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/css/static/left-tab-stripe.css
- plugins/plugin-client-common/web/css/static/top-tab-stripe.css
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
- plugins/plugin-editor/web/css/static/editor.css
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
> fix: eliminate use of custom <tab> tag

- plugins/plugin-sidecar/src/view/components/Badge.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
> fix(plugins/plugin-sidecar): implement support for Badges as functions

- clients/test/package.json
- clients/test/plugins/plugin-test/src/lib/cmds/content/react.tsx
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- clients/test/plugins/plugin-test/tsconfig.json
- packages/core/src/index.ts
- packages/core/src/models/mmr/content-types.ts
- packages/test/src/api/mmr.ts
- plugins/plugin-sidecar/src/view/components/KuiContent.tsx
> feat: support ReactElement as MultiModalResponse modes

- packages/core/src/webapp/keys.ts
- plugins/plugin-client-common/src/components/Terminal/Block/ActiveISearch.tsx
> fix: reverse-i-search does not always terminate with current completion

- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
> fix(plugins/plugin-client-common): stop using value prop for uncontrolled input element

- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
> fix(plugins/plugin-core-support): clicking on theme name should not change theme

- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/preload.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
> test: registar badge spec via function

- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/sidecar-expect.ts
- packages/test/src/api/util.ts
> test: toolBarText in React Sidecar Mode

- packages/core/src/models/tab-state.ts
- packages/core/src/webapp/themes/Theme.ts
- packages/core/src/webapp/themes/persistence.ts
- plugins/plugin-bash-like/src/pty/session.ts
- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
- plugins/plugin-carbon-themes/theme.json
- plugins/plugin-client-common/src/components/InputStripeExperimental.tsx
- plugins/plugin-client-common/src/components/TabContainer.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/TabCompletion.tsx
- plugins/plugin-client-common/src/components/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/src/components/TopTabStripe/index.tsx
- plugins/plugin-client-common/web/css/static/InputStripeExperimental.scss
- plugins/plugin-client-default/src/Client.tsx
- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-proxy-support/src/lib/config.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
- plugins/plugin-proxy-support/src/preload.ts
> fix: some code is dependent on the existence of static config files

- plugins/plugin-client-common/src/components/Terminal/Block/BlockModel.ts
> fix(plugins/plugin-client-common): inBrowser, prompt should be basename

- packages/core/src/webapp/themes/default.ts
> fix(packages/core): eliminate static dependence on client config

- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
> fix(plugins/plugin-sidecar): eliminate the warning message in the javascript console when LeftNavSidecar opens

- plugins/plugin-editor/src/view/components/Editor.tsx
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
Also improved error handling of Editor
Fixes #3823
> fix: LeftNavSidecar fails silently for MMR with plain text mode

- packages/core/src/index.ts
- packages/core/src/webapp/bootstrap/boot.ts
> feat(packages/core): offer sandbox-friendly bootstrap endpoint

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-core-themes/web/css/light.css
- plugins/plugin-sidecar/web/css/static/sidecar.css
> fix: a few more color contrast issues with inverted sidecars

- packages/core/src/webapp/bootstrap/boot.ts
> fix(packages/core): set inBrowser for bootIntoSandbox flows

- packages/core/src/webapp/bootstrap/boot.ts
> fix(packages/core): bootIntoSandbox doesn't call domReady correctly

- packages/core/src/commands/context.ts
- packages/core/src/core/capabilities.ts
- packages/core/src/index.ts
- packages/core/src/plugins/plugins.ts
- plugins/plugin-sandbox/.gitignore
- plugins/plugin-sandbox/.npmignore
- plugins/plugin-sandbox/package.json
- plugins/plugin-sandbox/prescan.json
- plugins/plugin-sandbox/src/controller/help.ts
- plugins/plugin-sandbox/src/plugin.ts
- plugins/plugin-sandbox/tsconfig-es6.json
- plugins/plugin-sandbox/tsconfig.json
- tsconfig-es6.json
- tsconfig.json
plus add initial sandbox
Fixes #3849
> fix: core defaultContext logic assumes existence if @kui-shell/client

- plugins/plugin-client-common/.npmignore
- plugins/plugin-client-default/.npmignore
> fix: plugin-client-command/default are publishing tsbuildinfo

- packages/core/src/webapp/bootstrap/boot.ts
> fix(packges/core): bootIntoSandbox should call assertInSandbox

- plugins/plugin-sandbox/package.json
> fix(plugins/plugin-sandbox): incorrect package.json name

- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
- plugins/plugin-carbon-tables/web/css/static/pagination.scss
- plugins/plugin-carbon-tables/web/css/static/tables.scss
- plugins/plugin-client-common/src/components/TabContent.tsx
> fix: paginated tables always take up full width

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-core-themes/web/css/light.css
- plugins/plugin-sidecar/src/view/components/Markdown.tsx
- plugins/plugin-sidecar/web/css/static/sidecar.css
> fix: improve CodeSnippet rendering in Markdown

- plugins/plugin-client-common/web/css/static/ui.css
> fix(plugins/plugin-client-common): improve Markdown styling of ul

- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
this also improves the hover effect
Fixes #3872
> fix(plugins/plugin-client-common): shorten top tabs

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-core-themes/web/css/light.css
> fix: a few more color contrast issues with inverted sidecar themes

- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
- plugins/plugin-carbon-tables/web/css/static/buttons.scss
- plugins/plugin-core-support/src/test/core-support/theme.ts
forgot to import radio button scss from carbon
Fixes #3869
closes #3870
> fix(plugins/plugin-carbon-tables): improve radio button UI

- plugins/plugin-sidecar/src/view/components/Markdown.tsx
> fix(plugins/plugin-sidecar): change ReactMarkdown CodeSnippet from single to multiline style if the characters exceed 40

- plugins/plugin-carbon-tables/src/view/LivePaginatedTable.tsx
- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
- plugins/plugin-carbon-tables/web/css/static/tables.scss
- plugins/plugin-client-common/src/components/Scalar/index.tsx
- plugins/plugin-sidecar/src/view/components/KuiContent.tsx
> fix: disable pagination and use word-break in sidecar sidecar carbon-tables

- plugins/plugin-client-common/src/components/TabContainer.tsx
- plugins/plugin-core-support/src/lib/cmds/tab-management.ts
> fix: cmd+w doesn't closes the window when there's only 1 tab

- plugins/plugin-carbon-themes/web/css/kui--alternate.css
- plugins/plugin-client-common/web/css/static/status-stripe.css
> fix: improve Terminal horizontal alignment for carbon themes

- clients/test/plugins/plugin-test/src/lib/cmds/content/modes.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode.ts
- plugins/plugin-carbon-tables/src/view/LivePaginatedTable.tsx
- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
> fix(plugins/plugin-carbon-tables): sidecar table shows 20 rows at maximum even without pagination

- plugins/plugin-client-default/src/Popup.tsx
> fix(plugins/plugin-client-default): cwd+w should close popup windows

- plugins/plugin-carbon-tables/src/view/LivePaginatedTable.tsx
- plugins/plugin-carbon-tables/src/view/PaginatedTable.tsx
> fix(plugins/plugin-carbon-tables): PaginatedTable always paginates

- packages/core/src/repl/exec.ts
- plugins/plugin-client-common/src/components/Terminal/ScrollableTerminal.tsx
> fix: restore support for quiet table clicks

- packages/core/src/repl/exec.ts
> fix(packages/core): eliminate spurious console error messages

- plugins/plugin-client-default/src/Client.tsx
> fix(plugins/plugin-client-default): load Popup.tsx via React.lazy

- package-lock.json
- package.json
> chore: remove unused request and request-promise deps

- plugins/plugin-carbon-tables/web/css/static/kui-tables.scss
- plugins/plugin-carbon-tables/web/css/static/tables.scss
- plugins/plugin-sidecar/web/css/static/sidecar.css
> fix: a few small tweaks for "short" tables in sidenav

- clients/test/plugins/plugin-test/src/lib/cmds/NavResponse.ts
- clients/test/plugins/plugin-test/src/plugin.ts
- clients/test/plugins/plugin-test/src/test/response/NavResponse.ts
- packages/core/src/index.ts
- packages/core/src/models/NavResponse.ts
- packages/test/src/api/NavResponse.ts
- packages/test/src/api/selectors.ts
- packages/test/src/index.ts
- plugins/plugin-client-default/config.d/about.json
- plugins/plugin-client-default/i18n/about_en_US.json
- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
> feat: about and LeftNavSidecar should support NavLinks

- plugins/plugin-carbon-tables/web/css/static/tables.scss
> fix(plugins/plugin-carbon-tables): prevent horizontal scrollbars on paginated table container

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
- plugins/plugin-client-common/src/components/Screenshot.tsx
- plugins/plugin-client-common/web/css/static/Screenshot.scss
- plugins/plugin-core-themes/web/css/dark.css
- plugins/plugin-core-themes/web/css/light.css
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
mostly in terms of colors and color contrasts
Fixes #3933
> fix: multiple fixes for screenshot toast notification UI

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-client-common/src/components/Screenshot.tsx
- plugins/plugin-client-common/web/css/static/Button.scss
- plugins/plugin-client-common/web/css/static/Screenshot.scss
- plugins/plugin-client-default/web/css/static/carbon-overrides.css
- plugins/plugin-core-support/src/test/core-support2/screenshot.ts
> fix(plugins/plugin-client-common): improve Screenshot UI

- plugins/plugin-client-common/src/components/TopTabStripe/index.tsx
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-common/web/css/static/carbon-overrides-common.css
- plugins/plugin-client-common/web/css/static/split-pane.scss
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
e.g. TopNavSidecar tabs change to unthemed colors
Fixes #3954
> fix: improve presentation with narrow windows

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-sidecar/src/view/components/TitleBar.tsx
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
> fix: improve contrast of top tab stripe versus sidecar title stripe

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
- plugins/plugin-client-common/web/css/static/split-pane.scss
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-core-themes/web/css/light.css
- plugins/plugin-sidecar/src/view/components/BaseSidecar.tsx
- plugins/plugin-sidecar/src/view/components/TitleBar.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
this also fixes a few more sidecar inverted contrast issues
Fixes #3958
> feat: refine sidecar minimization

- clients/test/plugins/plugin-test/src/lib/cmds/NavResponse.ts
- clients/test/plugins/plugin-test/src/lib/cmds/mmr-mode-via-registration.ts
- clients/test/plugins/plugin-test/src/test/response/NavResponse.ts
- clients/test/plugins/plugin-test/src/test/response/topnav-backbutton.ts
- packages/core/src/index.ts
- packages/core/src/models/NavResponse.ts
- packages/core/src/repl/exec.ts
- packages/test/src/api/NavResponse.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-client-common/src/components/TabContent.tsx
- plugins/plugin-client-common/web/css/static/carbon-overrides-common.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-default/web/css/static/carbon-overrides.css
- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-sidecar/src/view/components/BaseSidecar.tsx
- plugins/plugin-sidecar/src/view/components/CircularBuffer.ts
- plugins/plugin-sidecar/src/view/components/ComboSidecar.tsx
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/TitleBar.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/same.ts
- plugins/plugin-sidecar/src/view/components/width.ts
- plugins/plugin-sidecar/web/css/static/Breadcrumb.scss
- plugins/plugin-sidecar/web/css/static/sidecar-main.css
- plugins/plugin-sidecar/web/css/static/sidecar.css
> feat: add history to sidecar views

- clients/test/plugins/plugin-test/src/lib/modes.ts
- packages/core/src/models/mmr/content-types.ts
- packages/core/src/repl/exec.ts
- plugins/plugin-sidecar/src/view/components/Eval.tsx
- plugins/plugin-sidecar/src/view/components/KuiContent.tsx
- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
> fix: pass argvNoOptions and ParsedOptions to FunctionThatProducesContent

- plugins/plugin-core-support/src/test/core-support2/text-search.ts
> test: stablize text-search tests

- plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx
> fix(plugins/plugin-sidecar): don't focus on LeftNavSidecar tabs on click

- plugins/plugin-core-support/about/src/about.ts
> fix(plugins/plugin-core-support): about shows wrong breadcrumbs

- clients/test/plugins/plugin-test/src/lib/modes.ts
- clients/test/plugins/plugin-test/src/preload.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-mode-via-registration.ts
- packages/core/src/models/mmr/button.ts
- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/bottom-stripe.ts
> fix: pass argvNoOptions and ParsedOptions to button function

- clients/test/plugins/plugin-test/src/lib/cmds/mmr-name.ts
- clients/test/plugins/plugin-test/src/test/response/mmr-name.ts
- packages/test/src/api/mmr.ts
- plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx
> fix(plugins/plugin-sidecar): when nameHash is displayed, TopNavSidecar doesn't render the dehashed name

- packages/builder/bin/babel.sh
> fix(packages/builder): kui-babel might not transpile subdirectories

- packages/core/src/repl/exec.ts
> fix(packages/core): leftover debugging output in core/repl/exec

- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
> fix: CurrentGitBranch fails if branch name parses as a number

- plugins/plugin-kubectl/src/controller/kubectl/describe.ts
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
> fix(plugins/plugin-kubectl): oc describe fails

- packages/core/src/index.ts
- packages/core/src/models/mmr/content-types.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-client-common/src/components/Sidecar/Eval.tsx
- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/css/static/sidecar.css
- plugins/plugin-client-common/web/css/static/status-stripe.css
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
- plugins/plugin-kubectl/src/lib/view/modes/crd-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/summary.tsx
- plugins/plugin-kubectl/src/lib/view/modes/table-to-map.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-crd.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-pod.ts
- plugins/plugin-kubectl/src/test/k8s1/deployment.ts
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
- plugins/plugin-kubectl/src/test/k8s1/namespace.ts
> feat: render kubectl summary tab using forms

- .travis.yml
- packages/test/bin/runMochaLayersv2.sh
> test: combine to travis jobs

- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-kubectl/helm/src/controller/helm/catchall.ts
- plugins/plugin-kubectl/helm/src/test/helm/helm.ts
- plugins/plugin-kubectl/src/lib/util/help.ts
> fix: helm on its own should render in sidecar

- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/scss/components/Table/kui-tables.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> feat: enhance table UI

- plugins/plugin-kubectl/src/controller/kubectl/describe.ts
- plugins/plugin-kubectl/src/lib/util/util.ts
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
> fix(plugins/plugin-kubectl): kubectl describe (--help) fails

- plugins/plugin-ibmcloud/ks/src/controller/cluster/get.ts
- plugins/plugin-ibmcloud/ks/src/controller/worker-pool/get.ts
- plugins/plugin-ibmcloud/ks/src/controller/worker/get.ts
- plugins/plugin-ibmcloud/plugin/src/controller/get.ts
- plugins/plugin-kubectl/helm/src/controller/helm/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/modes/configmap-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/table-to-map.ts
- plugins/plugin-kubectl/src/lib/view/modes/yaml.ts
- plugins/plugin-kubectl/src/non-headless-preload.ts
- plugins/plugin-kubectl/src/test/k8s1/config-map.ts
> feat(plugins/plugin-kubectl): configmap summary should show data

- bin/kubectl-kui
> feat: add development-time kubectl-kui kubectl plugin wrapper

- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
> fix: improve Form layout

- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
> fix: Form component sometimes has too-small TextInputs

- packages/test/bin/runMochaLayersv2.sh
- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
- plugins/plugin-kubectl/src/lib/view/modes/configmap-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/crd-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/table-to-map.ts
Fixes #4041
this also tweaks the Form layout a bit more
Fixes #4040
> feat: add labels to summary mode

- bin/watch-webpack.sh
- package-lock.json
- package.json
- packages/webpack/build.sh
> chore: install packages/webpack at the top-level

- bin/watch-webpack.sh
- packages/webpack/build.sh
> chore: eliminate the unnecessary scripts to npm install packages/webpack

- plugins/plugin-client-common/src/components/Table/TableCell.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
> fix: when sidecar is open, only show status badge, not status text

- packages/builder/dist/electron/build.sh
> fix: integrate "production" kubectl-kui scripts into electron tarball

- README.md
- plugins/plugin-client-common/web/css/static/Popup.scss
> fix(plugins/plugin-client-common): css regression of sidecar-header in popup mode

- plugins/plugin-client-common/src/components/Table/TableCell.tsx
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
this PR also cleans up some "undefined" in td classNames
Fixes #4059
> fix: STATUS cell not centered when sidecar is open

- plugins/plugin-wskflow/src/lib/graph2doms.ts
- plugins/plugin-wskflow/web/css/static/wskflow.css
this PR also makes the SVG part of the flow screenshotable (separately from the sidecar as a whole)
Fixes #4071
> fix: improve color contrast of wskflow

- plugins/plugin-client-common/src/components/Sidecar/TitleBar.tsx
- plugins/plugin-client-common/web/css/static/sidecar-main.css
> fix(plugins/plugin-client-common): reduce size of sidecar window buttons

- .travis.yml
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
this also does some purely syntactic cleanup of .travis.yml
Fixes #4077
> fix: kubectl summary Form TextInputs can be cropped

- plugins/plugin-client-common/web/css/static/status-stripe.css
> fix: improved color contrast in bottom stripe light themes (on hover)

- plugins/plugin-bash-like/web/css/static/xterm.css
- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-core-themes/web/css/dark.css
- plugins/plugin-core-themes/web/css/light.css
- plugins/plugin-editor/web/css/static/theme-alignment.css
> fix: text selection in active xterms for light themes is not visible

- plugins/plugin-kubectl/logs/src/modes/show-logs.ts
- plugins/plugin-kubectl/logs/src/preload.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs.ts
> feat(plugins/plugin-kubectl): restore Show Logs button for kubectl

- plugins/plugin-client-common/src/components/Sidecar/TitleBar.tsx
> fix: breadcrumb in TopNavSidecar isn't zoomable

- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
> fix: kubectl summary form clipping

- plugins/plugin-carbon-themes/web/css/carbon-gray10.css
- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
> fix(plugins/plugin-carbon-themes): carbon themes have dead css rules

- plugins/plugin-client-common/src/components/Sidecar/TitleBar.tsx
- plugins/plugin-client-common/src/components/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/src/components/Sidecar/breadcrumb.ts
- plugins/plugin-client-common/web/css/static/Breadcrumb.scss
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/util/name.ts
Fixes #4099
this also adds support for versions as breadcrumbs
> fix: improve kubectl breadcrumb detection

- plugins/plugin-client-default/config.d/style.json
- plugins/plugin-core-support/src/test/core-support/text-search.ts
- plugins/plugin-core-support/src/test/core-support/theme.ts
> feat: switch to Carbon Gray 10 as default theme in plugin-default-client

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/web/css/static/Tooltip.scss
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/modes/ShowOwnerButton.tsx
- plugins/plugin-kubectl/src/non-headless-preload.ts
- plugins/plugin-kubectl/src/test/k8s1/deployment.ts
> feat: add Show Owner Reference button for kube resources

- plugins/plugin-client-common/web/css/static/Tooltip.scss
> fix(plugins/plugni-client-common): improve contrast of Toolbar tooltips

- plugins/plugin-kubectl/src/lib/view/modes/pods.ts
> feat(plugins/plugin-kubectl): ReplicaSet should have Pods tab

- plugins/plugin-client-common/web/css/static/Form.scss
- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
> fix: remove use of inline styling in Form.tsx

- plugins/plugin-kubectl/tekton/src/lib/tekton2graph.ts
- plugins/plugin-kubectl/tekton/src/view/flow.ts
- plugins/plugin-wskflow/web/css/static/wskflow.css
> fix: tekton Step nodes show with hashed background

- plugins/plugin-kubectl/src/lib/view/modes/DeleteButton.tsx
> fix: ensure kubectl Delete toolbar button appears at far right

- plugins/plugin-kubectl/src/lib/view/modes/Form.tsx
> fix(plugins/plugin-kubectl): more refinements to Form layout heuristics

- packages/core/src/webapp/models/table.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/src/components/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Table/TableCell.tsx
- plugins/plugin-client-common/src/components/Table/Toolbar.tsx
- plugins/plugin-client-common/src/components/Table/index.tsx
- plugins/plugin-client-common/web/css/static/ToolbarButton.scss
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/Table/pagination.scss
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/test/k8s1/namespace.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
> feat: improve pagination and toolbar UIs of PaginatedTable

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Table/Toolbar.tsx
- plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
- plugins/plugin-client-common/web/scss/components/Table/kui-tables.scss
- plugins/plugin-kubectl/src/controller/kubectl/explain.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
> feat: kubectl tables should show official kind in title

- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pods-with-watch.ts
> fix(plugins/plugin-kubectl): watch table doesn't have breadcrumbs title

- packages/core/src/core/jobs/watchable.ts
- plugins/plugin-client-common/src/components/Table/LivePaginatedTable.tsx
- plugins/plugin-kubectl/src/controller/kubectl/fqn.ts
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
> fix(plugins/plugin-kubectl): kubectl watch tables can be misparsed

- plugins/plugin-client-common/src/components/Table/Grid.tsx
- plugins/plugin-client-common/src/components/Table/PaginatedTable.tsx
> fix: table status grid layout seems buggy

- packages/proxy/build.sh
- packages/webpack/build.sh
> fix: remove docker-related bits in {proxy,webpack}/build.sh

- README.md
> doc: increase size of first image in readme

- plugins/plugin-kubectl/src/controller/kubectl/api-resources.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/test/k8s2/api-resources.ts
> fix(plugins/plugin-kubectl): kubectl api-resources table shows 'unknown' in title

- plugins/plugin-client-default/i18n/about_en_US.json
> fix(plugins/plugin-client-default): add missing newline in about text

- bin/kubectl-kui
- packages/builder/dist/electron/build.sh
- packages/core/src/main/spawn-electron.ts
- packages/core/src/webapp/defaults.ts
- packages/test/src/api/common.ts
Also fixes the color of status badge: Error and ImagePullBackOff
Fixes #4161
> feat: resize the popup window

- packages/core/src/main/main.ts
- packages/core/src/main/spawn-electron.ts
- packages/core/src/models/SubwindowPrefs.ts
> feat(packages/core): position popup windows more intelligently

- packages/core/src/main/spawn-electron.ts
> fix(packages/core): another undefined use of Electron

- packages/core/src/main/spawn-electron.ts
> fix(packages/core): broken open external link support

- packages/core/src/models/NavResponse.ts
- plugins/plugin-client-common/src/components/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-default/config.d/about.json
- plugins/plugin-client-test/src/lib/cmds/NavResponse.ts
- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-kubectl/helm/src/controller/helm/status.ts
- plugins/plugin-kubectl/krew/src/controller/info.ts
- plugins/plugin-kubectl/src/controller/kubectl/explain.ts
- plugins/plugin-kubectl/src/controller/kubectl/kustomize.ts
- plugins/plugin-kubectl/src/lib/util/help.ts
> fix: eliminate complex nesting of NavResponse model

- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
issue: https://github.com/IBM/kui/issues/4210
fix in 6_0_x
> fix(plugins/plugin-proxy-support): fixed env for proxy executor

- plugins/plugin-client-common/src/components/Sidecar/BaseSidecar.tsx
- plugins/plugin-client-common/src/components/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/src/components/Sidecar/same.ts
> fix(plugins/plugin-client-common): sidecar history should respect PWD

- plugins/plugin-bash-like/src/pty/client.ts
> fix(plugins/plugin-bash-like): remove leftover debug in client.ts

- package-lock.json
- plugins/plugin-ibmcloud/package.json
- plugins/plugin-kubectl/package.json
> chore: remove inter-monorepo dependencies from ibmcloud and kubectl

- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/src/lib/view/modes/ShowNodeOfPodButton.tsx
- plugins/plugin-kubectl/src/non-headless-preload.ts
- plugins/plugin-kubectl/src/test/k8s1/create-pod.ts
> feat(plugins/plugin-kubectl): add Show Node button for kubectl pods

- README.md
- packages/builder/dist/electron/build.sh
> feat: add windows support for running kui as a kubectl plugin

- plugins/plugin-carbon-themes/web/css/carbon-gray90.css
- plugins/plugin-carbon-themes/web/css/kui--alternate.css
- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
> fix: > prompt text has poor vertical alignment

- packages/builder/dist/electron/build.sh
> fix(packages/builder): win32 electron build breakage

- plugins/plugin-carbon-themes/web/css/kui--alternate.css
- plugins/plugin-client-common/web/css/static/repl.scss
1) use normal font size
2) opacity for context
3) for carbon themes, use plex sans condensed for context
Fixes #4250
> fix: a few more tweaks to prompt

- packages/proxy/conf.d/proxy.conf
> feat: proxy nginx should support serving gzip_static content

- plugins/plugin-carbon-themes/web/css/kui--alternate.css
- plugins/plugin-client-common/src/components/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
> fix: reverse-i-search text should be monospace

- docs/example/README.md
- docs/example/plugin-example/README.md
- docs/example/plugin-example/package.json
- docs/example/plugin-example/src/commands/hello-cat-dog-terminal.ts
- docs/example/plugin-example/src/commands/hello-catnav.ts
- docs/example/plugin-example/src/commands/hello-sidecat.ts
- docs/example/plugin-example/src/index.ts
- docs/example/plugin-example/src/plugin.ts
- docs/example/plugin-example/src/view/CatDogWidget.tsx
- docs/example/plugin-example/src/view/Sidecat.tsx
- docs/example/plugin-example/tsconfig.json
> docs: add the code examples on wiki to docs/examples

- plugins/plugin-kubectl/helm/src/controller/helm/status.ts
> fix(plugins/plugin-kubectl): avoid use of /s regexp

- docs/README.md
> doc: add docs/README.md

- README.md
> doc: fix broken docs link

- plugins/plugin-client-alternate/config.d/limits.json
- plugins/plugin-client-default/config.d/limits.json
> fix: remove limits.json from client config.d

- plugins/plugin-client-default/config.d/name.json
> fix(plugins/plugin-client-default): remove unused fields from name.json

- packages/core/src/main/spawn-electron.ts
- plugins/plugin-client-alternate/config.d/client.json
- plugins/plugin-client-default/config.d/client.json
> fix: remove unsed fields from client.json

- plugins/plugin-client-alternate/config.d/style.json
- plugins/plugin-client-default/config.d/style.json
> fix: remove unused fields from config.d/style.json

- plugins/plugin-client-alternate/config.d/style.json
- plugins/plugin-client-default/config.d/style.json
- plugins/plugin-core-support/src/test/core/basic-functionality.ts
> fix: remove invalid bodyCss fields in config.d/style.json

- plugins/plugin-kubectl/tests/lib/k8s/utils.js
> fix(plugins/plugin-kubectl): update deprecated import of uuid

- package-lock.json
- package.json
- plugins/plugin-skeleton/.gitignore
- plugins/plugin-skeleton/.npmignore
- plugins/plugin-skeleton/Readme.md
- plugins/plugin-skeleton/package.json
- plugins/plugin-skeleton/src/index.ts
- plugins/plugin-skeleton/src/plugin.ts
- plugins/plugin-skeleton/src/preload.ts
- plugins/plugin-skeleton/tsconfig.json
- tsconfig.json
> feat: add plugin-skeleton for new contributors to prototype code

- plugins/plugin-carbon-themes/web/scss/ibm-plex.scss
> fix(plugins/plugin-carbon-themes): missing import of medium font weight

- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Client/KuiConfiguration.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
- plugins/plugin-client-default/src/index.tsx
> chore: productName should be a property of KuiConfiguration

- plugins/plugin-client-alternate/config.d/client.json
- plugins/plugin-client-default/config.d/client.json
> chore: remove unused userAgent field from config.d

- docs/example/AnimalApp/README.md
- docs/example/AnimalApp/plugins/plugin-example/src/commands/hello-cat-dog-terminal.ts
- docs/example/AnimalApp/plugins/plugin-example/src/commands/hello-catnav.ts
- docs/example/AnimalApp/plugins/plugin-example/src/commands/hello-sidecat.ts
- docs/example/AnimalApp/plugins/plugin-example/src/view/mmr-example.ts
- docs/example/AnimalApp/plugins/plugin-example/src/view/nav-example.ts
- docs/example/AnimalApp/plugins/plugin-example/src/view/ok.ts
- docs/example/AnimalApp/plugins/plugin-example/src/view/stringHello.ts
- docs/example/AnimalApp/plugins/plugin-example/src/view/table.ts
> docs: add the source code of new wiki examples to AnimalApp

- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/oc/src/controller/exec.ts
- plugins/plugin-kubectl/oc/src/controller/kubectl/catchall.ts
- plugins/plugin-kubectl/oc/src/controller/raw.ts
- plugins/plugin-kubectl/src/controller/kubectl/exec-to-markdown.ts
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/lib/util/help.ts
- plugins/plugin-kubectl/src/test/k8s2/usage.ts
- tools/travis/microk8s.sh
> feat(plugins/plugin-kubectl): improve odo usage experience

- plugins/plugin-bash-like/src/pty/kuirc.ts
- plugins/plugin-bash-like/src/pty/prefetch.ts
- plugins/plugin-bash-like/src/pty/server.ts
> fix(plugins/plugin-bash-like): avoid using login shell for PTYs

- .travis.yml
- tools/go/ibmcloud/.gitignore
- tools/go/ibmcloud/Makefile
- tools/go/ibmcloud/README.md
- tools/go/ibmcloud/go.mod
- tools/go/ibmcloud/go.sum
- tools/go/ibmcloud/launcher/launcher.go
- tools/travis/ibmcloud-plugin-build-install.sh
This PR also adds a Makefile to facilitate builds.
Fixes #4359
> fix: update ibmcloud plugin compilation to use client version

- README.md
- tools/go/ibmcloud/README.md
> chore: add installation docs for use as an ibmcloud CLI plugin

- packages/core/src/index.ts
- packages/core/src/repl/exec.ts
- packages/core/src/webapp/tab.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
1) renders poorly due to losing xterm-alt-buffer-mode class
2) loses focus e.g. for an active vi session
Fixes #2579
> fix: PTY behaves oddly when switching tabs

- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/ComboSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-kubectl/src/test/k8s2/get-pod-multi-tab.ts
> fix: sidecar views do not respect tab-specificity

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump to electron 7.2.3

- plugins/plugin-carbon-themes/web/scss/ibm-plex.scss
- plugins/plugin-carbon-themes/web/scss/kui--alternate.scss
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
> fix: prompt text alignment issues

- package-lock.json
- packages/webpack/package.json
- packages/webpack/webpack.config.js
> chore: add css resolve-url-loader to webpack config

- package-lock.json
- package.json
- packages/webpack/webpack.config.js
- plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-patternfly4-themes/package.json
- plugins/plugin-patternfly4-themes/theme.json
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/fonts.scss
- plugins/plugin-patternfly4-themes/web/scss/mono.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
- plugins/plugin-patternfly4-themes/web/scss/sans.scss
> feat: patternfly4 themes

- plugins/plugin-client-common/src/components/Views/Breadcrumb/index.tsx
> fix(plugins/plugin-client-common): Table loads before breadcrumbs, oddly

- plugins/plugin-patternfly4-themes/web/scss/mono.scss
- plugins/plugin-patternfly4-themes/web/scss/sans.scss
Fixes #4389
this also enables overpass-mono for monospace
> fix(plugins/plugi-patternfly4-themes): add missing sans 500 font-weight

- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/Navigation/Carbon.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/Navigation/Patternfly.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/Navigation/index.tsx
- plugins/plugin-client-common/web/css/static/sidecar.css
- plugins/plugin-patternfly4-themes/web/scss/common.scss
> feat: add Patternfly Navigation for LeftNavSidecar

- package-lock.json
- plugins/plugin-bash-like/package.json
> fix(plugins/plugin-bash-like): update plugin-bash-like dependencies

- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix(plugins/plugin-patternfly4-themes): darken status stripe

- plugins/plugin-client-common/web/css/static/Screenshot.scss
- plugins/plugin-client-common/web/css/static/status-stripe.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Breadcrumb/Patternfly.scss
- plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
- plugins/plugin-patternfly4-themes/theme.json
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> feat: patternfly4 dark theme

- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-client-common/src/components/Client/Popup.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/ComboSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/width.ts
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-common/web/css/static/sidecar-carbon.css
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> feat: top tab buttons

- docs/README.md
> docs: developer guide for Patternfly 4 support

- docs/README.md
- docs/components.md
- package-lock.json
- plugins/plugin-client-common/src/components/Client/Screenshot.tsx
- plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/NewTabButton.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/src/components/Content/Table/Toolbar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/Toolbar.tsx
- plugins/plugin-client-common/src/components/spi/Icons/impl/CarbonIcons.tsx
- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly4Icons.tsx
- plugins/plugin-client-common/src/components/spi/Icons/index.tsx
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-git/package.json
- plugins/plugin-git/src/CurrentGitBranch.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
- plugins/plugin-kubectl/src/lib/view/modes/DeleteButton.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ShowNodeOfPodButton.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ShowOwnerButton.tsx
- plugins/plugin-proxy-support/src/view/ProxyOfflineIndicator.tsx
> feat: SPI for icons

- docs/components.md
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/List/Carbon.scss
- plugins/plugin-client-common/web/scss/components/StructuredList/Carbon.scss
> fix(plugins/plugin-client-common): improved rendering of markdown links

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump monaco-editor from 0.18 to 0.20

- docs/components.md
- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/spi/Navigation/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Navigation/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Navigation/index.tsx
- plugins/plugin-client-common/src/components/spi/Navigation/model.ts
- plugins/plugin-client-common/web/css/static/sidecar.css
- plugins/plugin-client-common/web/scss/components/Navigation/Carbon.scss
> chore: move Navigation impls under spi/

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-kubectl/src/lib/util/help.ts
> fix: clicking on certain links in kubectl help result in odd behavior

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/needs-multi-line.ts
- plugins/plugin-client-common/src/components/spi/CodeSnippet/index.tsx
- plugins/plugin-client-common/src/components/spi/CodeSnippet/model.ts
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/CodeSnippet/PatternFly.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
> feat: spi for CodeSnippet

- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: improve contrast of cyan in Patternfly4 Light theme

- plugins/plugin-kubectl/odo/package.json
- plugins/plugin-kubectl/odo/src/controller/odo/catalog/list/components.ts
- plugins/plugin-kubectl/odo/src/controller/odo/catalog/list/services.ts
- plugins/plugin-kubectl/odo/src/controller/raw.ts
- plugins/plugin-kubectl/odo/src/plugin.ts
- plugins/plugin-kubectl/odo/tsconfig.json
- plugins/plugin-kubectl/src/controller/kubectl/exec.ts
- plugins/plugin-kubectl/tsconfig.json
> feat: initial odo catalog list enhancements

- plugins/plugin-kubectl/src/test/k8s2/get-pod-with-not-found.ts
> fix(plugins/plugin-kubectl): add missing test for get with not found

- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling.ts
> fix(plugin-kubectl): kubectl get error-type -w doesn't fail fast

- packages/core/src/webapp/queueing.ts
> fix(packages/core): pty-client fails when an external kui client doesn't have invisible-global-input in index.html

- packages/core/src/index.ts
- packages/core/src/models/CellShould.ts
- packages/core/src/models/RadioTable.ts
- packages/core/src/models/entity.ts
- packages/core/src/repl/exec.ts
- packages/test/src/api/repl-expect.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/index.tsx
- plugins/plugin-client-common/web/css/static/carbon-overrides-common.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/RadioTable/Carbon.scss
- plugins/plugin-client-common/web/scss/components/RadioTable/common.scss
- plugins/plugin-client-common/web/scss/components/StructuredList/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
- plugins/plugin-kubectl/src/test/k8s1/namespace.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
Fixes #4510
this requires support for pagination in RadioTable
Fixes #4511
> feat: port kubectl get ns to RadioTable

- plugins/plugin-client-common/web/scss/components/StructuredList/Carbon.scss
- plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
- plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
> feat(plugins/plugin-kubectl): port kubectl contexts table to RadioTable

- plugins/plugin-kubectl/odo/src/controller/odo/project/list.ts
- plugins/plugin-kubectl/odo/src/model/Project.ts
- plugins/plugin-kubectl/odo/src/plugin.ts
- plugins/plugin-kubectl/src/controller/kubectl/exec.ts
- plugins/plugin-kubectl/src/index.ts
> feat(plugins/plugin-kubectl): enhance odo project list as RadioTable

- plugins/plugin-client-common/src/components/spi/Breadcrumb/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Breadcrumb/impl/PatternFly.tsx
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/scss/components/Breadcrumb/Carbon.scss
> 8.7.1 (part two)

- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-kubectl/src/test/k8s1/labels.ts
> fix: TopNavSidecar does not always show updates

- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-kubectl/src/test/k8s1/labels.ts
cherry pick 251e5c416a30136f4b22ebc6af688724d6e085a8
> 8.7.1 (part 3)

- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-client-default/config.d/proxy.json
Add shellExe & shellOpts in `client/config.d/proxy.json`
if shellExe is empty string, will use default. (`/bin/bash`)
if shellOpts is undefined/empty array, will use default. (`--rcfile kuirc`)
> fix(plugins/plugin-bash-like): enable configurable shell

- plugins/plugin-client-common/src/components/Views/WatchPane.tsx
- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/web/scss/components/Card/Patternfly.scss
- plugins/plugin-client-common/web/scss/components/WatchPane/WatchPane.scss
> fix(plugins/plugin-client-common): WatchPane spacing fixes

- packages/test/src/api/mmr.ts
- plugins/plugin-carbon-themes/web/scss/kui--alternate.scss
- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/css/static/split-pane.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
> fix: improve alignment of icons

- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/web/scss/components/WatchPane/WatchPane.scss
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/lib/view/modes/events.ts
- plugins/plugin-kubectl/src/test/k8s2/events.ts
> fix(plugins/plugin-kubectl): k get events -w bombs

- package-lock.json
- plugins/plugin-carbon-themes/web/scss/kui--alternate.scss
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
> remove accordion

- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix: PaginatedTable fails at distinguishing the rowKeys of `k get --all-namespaces` table

- plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
> fix(plugins/plugin-carbon-themes): WatchPane has blueish cast

- packages/webpack/webpack.config.js
- plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.css
> fix: some UI elements missing from editor UI

- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/test/k8s1/secrets.ts
> fix(plugins/plugin-kubectl): kubectl create secret hangs yellow

- plugins/plugin-carbon-themes/web/scss/kui--alternate.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
> fix: improve alignment of Terminal timestamp

- plugins/plugin-carbon-themes/web/scss/kui--alternate.scss
- plugins/plugin-client-common/src/components/Client/Screenshot.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/index.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/model.ts
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/DropDown/Carbon.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
Fixes #4589
and adds a Screenshot button to the DropDown
part of #4556
> feat: Dropdown spi and use in Terminal Block

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Views/WatchPane.tsx
- plugins/plugin-client-common/src/components/Views/util/CircularBuffer.ts
- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-kubectl/src/test/k8s1/aaa-get-namespaces-with-watch.ts
> feat: add Stop Watching capability to WatchPane

- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-common/web/css/static/ui.css
> fix: productName in carbon theme shouldn't have hover effect

- plugins/plugin-kubectl/src/lib/view/modes/configmap-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/crd-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/summary.ts
- plugins/plugin-kubectl/src/test/k8s-popup/create-pod-popup.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-crd.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-pod.ts
- plugins/plugin-kubectl/src/test/k8s1/config-map.ts
- plugins/plugin-kubectl/src/test/k8s1/deployment.ts
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
- plugins/plugin-kubectl/src/test/k8s1/namespace.ts
> fix(plugins/plugin-kubectl): revert to editor-based Summary tab

- plugins/plugin-client-common/web/css/static/repl.scss
> fix(plugins/plugin-client-common): don't use text-02 for finished Inputs

- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/test/k8s2/api-resources.ts
> fix(plugins/plugin-kubectl): inconsistent capitalization of breadcrumbs

- plugins/plugin-carbon-themes/theme.json
- plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
- plugins/plugin-carbon-themes/web/scss/carbon-gray90.scss
- plugins/plugin-carbon-themes/web/scss/charts.scss
- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-carbon-themes/web/scss/inverted.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
this also does some sass mixin cleanup for the carbon themes
Fixes #4597
> fix: improve color contrast of charts in light themes

- plugins/plugin-kubectl/view-utilization/src/controller/get-node-data.ts
- plugins/plugin-kubectl/view-utilization/src/view/bar.tsx
> fix: kubectl top node should show % text

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/model.ts
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/DropDown/Carbon.scss
> fix(plugins/plugin-client-common): DropDown theme alignment issues

- plugins/plugin-client-common/src/components/Views/Terminal/Block/ActiveISearch.tsx
> fix(plugins/plugin-client-common): reverse-i-search text too small

- plugins/plugin-client-common/src/components/spi/DropDown/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/impl/PatternFly.tsx
- plugins/plugin-client-common/web/scss/components/DropDown/Carbon.scss
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
> fix(plugins/plugin-client-common): more DropDown theming fixes

- packages/core/src/models/execOptions.ts
- packages/core/src/models/mmr/content-types.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-client-common/src/components/Content/Editor/index.tsx
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarContainer.tsx
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
> fix: reduce No log data followed by log data behavior in kube logs

- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Card/model.ts
- plugins/plugin-client-common/src/components/spi/DropDown/model.ts
> fix(plugins/plugin-client-common): reverse the dependency of Card and DropDown

- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/common/_stippling.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
1) add stippling for red grid cells
2) adjust some of the theme red colors
3) add resource name to `title` i.e. tooltip
Fixes #4601
> fix: improve accessibility of table in grid form

- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
> fix(plugins/plugin-client-common): small shift in Input row

- packages/core/src/main/menu.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyDown.ts
> fix: control+w should not close window on linux and windows

- plugins/plugin-kubectl/i18n/logs_en_US.json
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
> fix(plugins/plugin-kubectl): i18n for No log data message

- packages/core/src/models/execOptions.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
- plugins/plugin-kubectl/tests/data/k8s/kubectl-logs-two-containers.yaml
> fix: container filter of logs tab shows accumulated logs from previous selection

- plugins/plugin-client-common/src/components/spi/DropDown/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/index.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/model.ts
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/Dropdown/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Dropdown/PatternFly.scss
> feat(plugins/plugin-client-common): backport Dropdown spi

- plugins/plugin-client-alternate/src/CustomInput.tsx
- plugins/plugin-client-alternate/web/scss/CustomInput.scss
- plugins/plugin-client-common/src/components/Client/InputStripe.tsx
- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyDown.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyPress.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/index.ts
> feat: <Kui> should allow for custom Input elements

- plugins/plugin-client-common/src/components/spi/DropDown/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/DropDown/model.ts
- plugins/plugin-client-common/web/scss/components/DropDown/Carbon.scss
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
> feat: add isSelected and Divider to log container selection menu

- plugins/plugin-client-common/web/css/static/inverted-colors.css
- plugins/plugin-client-common/web/scss/components/DropDown/Carbon.scss
> fix: sidecar container selection kebab has different color with its menu

- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarContainer.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-kubectl/src/test/k8s-popup/create-pod-popup.ts
> fix: avoid recomputing tabs when switching back and forth

- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c-via-table.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-f-via-table.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-via-table.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/lib/view/modes/events.ts
- plugins/plugin-kubectl/src/test/k8s-popup/create-pod-popup-via-table.ts
- plugins/plugin-kubectl/src/test/k8s1/aaa-get-namespaces-with-watch-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/events-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-vi.ts
- plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-via-table.ts
> feat: only enable WatchPane based on a feature flag

- plugins/plugin-kubectl/src/lib/util/help.ts
> fix(plugins/plugin-kubectl): helm help parsed usage incorrectly

- plugins/plugin-kubectl/src/test/k8s-popup/create-pod-popup-via-table.ts
> test: test regression in create-pod-popup

- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
- plugins/plugin-kubectl/src/test/k8s1/edit.ts
> fix(plugins/plugin-kubectl): remove kubectl edit cancel button

- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
> fix(plugins/plugin-kubectl): auto-pause logs when user scrolls

- plugins/plugin-client-common/web/css/static/status-stripe.css
also avoid bold font
Fixes #4698
> fix(plugins/plugin-client-common): increase font size of status stripe

- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
> fix: place namespace breadcrumb first

- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/spi/Loading/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Loading/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Loading/index.tsx
- plugins/plugin-client-common/src/components/spi/Loading/model.ts
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/css/static/loading.scss
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Loading/Carbon.scss
1) move to spi
2) add PatternFly impl
3) increase size of spinner
4) center
Fixes #4702
> fix(plugins/plugin-client-common): refine Loading component

- plugins/plugin-kubectl/src/lib/tab-completion.ts
1) edit, logs, attach for pods
2) node-specific operations
Fixes #4704
> fix(plugins/plugin-kubectl): improve kubectl tab completion

- plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
this also switches from clear() to reset() when switching containers, in order to fully clear the terminal
Fixes #4722
> fix(plugins/plugin-kubectl): ExecIntoPod's terminal is not theme-aligned

- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-client-default/config.d/about.json
- plugins/plugin-client-test/src/test/response/topnav-backbutton.ts
- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-core-support/src/test/core/about.ts
> fix: about should show breadcrumbs

- plugins/plugin-kubectl/i18n/exec_en_US.json
- plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
> fix(plugins/plugin-kubectl): automatically abort idle PTYs

- packages/test/src/api/NavResponse.ts
- packages/test/src/index.ts
- plugins/plugin-core-support/src/test/core/about.ts
- plugins/plugin-kubectl/src/test/k8s2/usage.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
> test: LeftNavSidecar content after switching commands

- packages/core/src/webapp/tab.ts
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
- plugins/plugin-kubectl/src/lib/view/modes/Events.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
- plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
this PR covers both the auto-xon/xoff part:
Fixes #4741
and the auto-focus part:
Fixes #4748
> fix: TopNavSidecar tabs should auto-pause and auto-focus when switching

- plugins/plugin-client-common/src/components/spi/Icons/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Icons/index.tsx
- plugins/plugin-kubectl/i18n/logs_en_US.json
- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts
- plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
- plugins/plugin-kubectl/src/lib/view/modes/Events.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
- plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts
Fixes #4755
Carbon Component:
Patternfly 4:
> feat: add Retry button to sidecar toolbar when log streaming stopped abnormally

- packages/test/src/api/cli.ts
- packages/test/src/api/common.ts
- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/table.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
> fix: Input element throws react error

- package-lock.json
- package.json
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
> fix(plugins/plugin-client-common): opening TopNavSidecar results in react Warning in console

- package-lock.json
- package.json
- packages/core/package.json
- plugins/plugin-core-support/package.json
> chore: bump yargs-parser version

- packages/core/src/models/mmr/types.ts
- packages/core/src/webapp/models/table.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
- plugins/plugin-kubectl/helm/src/controller/helm/history.ts
- plugins/plugin-kubectl/helm/src/controller/helm/list.ts
- plugins/plugin-kubectl/helm/src/controller/helm/repo.ts
- plugins/plugin-kubectl/helm/src/controller/helm/search.ts
- plugins/plugin-kubectl/helm/src/controller/helm/status.ts
- plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts
- plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts
- plugins/plugin-kubectl/odo/src/controller/odo/project/list.ts
- plugins/plugin-kubectl/src/controller/kubectl/api-resources.ts
- plugins/plugin-kubectl/src/controller/kubectl/config.ts
- plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
- plugins/plugin-kubectl/src/controller/kubectl/exec.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/options.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/lib/view/modes/involved-object.ts
- plugins/plugin-kubectl/src/lib/view/modes/show-crd-managed-resources.ts
- plugins/plugin-kubectl/src/plugin.ts
- plugins/plugin-kubectl/view-utilization/src/controller/get-pod-data.ts
> fix: eliminate assumptions that "default" is the default kube namespace

- packages/core/src/models/mmr/types.ts
- plugins/plugin-bash-like/web/css/static/xterm.css
- plugins/plugin-client-common/src/components/Content/Editor/index.tsx
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/util/same.ts
- plugins/plugin-client-common/src/components/spi/Icons/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Icons/index.tsx
- plugins/plugin-client-common/web/css/static/SidecarCommon.css
- plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts
- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/modes/EditButton.tsx
- plugins/plugin-kubectl/src/lib/view/modes/yaml.ts
- plugins/plugin-kubectl/src/non-headless-preload.ts
- plugins/plugin-kubectl/src/test/k8s1/edit.ts
covers the three points in the issue
Fixes #4783
> feat: improve kubectl edit experience

- packages/test/src/api/table.ts
- plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/index.tsx
- plugins/plugin-client-common/src/components/Views/WatchPane.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/index.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/model.ts
- plugins/plugin-client-test/src/index.tsx
- plugins/plugin-client-test/src/lib/cmds/content/table-with-drilldown.ts
- plugins/plugin-kubectl/src/test/k8s2/api-resources.ts
> fix: allow user to disable table title by feature flags, and disable table pagination

- package-lock.json
npm bug? somehow the last PR didn't update package-lock.json (despite changing it)
Fixes #4775
> chore: correct fix for yargs-parser version bump

- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
- plugins/plugin-kubectl/tests/data/k8s/bunch/pod.yaml
> test: kubectl logs tests were broken by nginx 1.19 release

- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix(plugins/plugin-kubectl): status shows as Containercreating when it should be ContainerCreating

- packages/core/src/models/execOptions.ts
- packages/core/src/models/mmr/content-types.ts
- packages/core/src/webapp/views/toolbar-text.ts
- packages/test/src/api/keys.ts
- plugins/plugin-client-common/src/components/Content/Editor/index.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/Toolbar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarContainer.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
- plugins/plugin-kubectl/src/test/k8s1/edit.ts
> fix: kubectl edit apply twice does not work

- plugins/plugin-kubectl/logs/src/test/logs/logs-multi.ts
- plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
- plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
> fix(plugins/plugin-kubectl): Logs tab should have a default tail limit

- packages/core/src/index.ts
- packages/core/src/models/command.ts
- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts
- plugins/plugin-kubectl/src/controller/kubectl/apply-subcommands.ts
- plugins/plugin-kubectl/src/controller/kubectl/options.ts
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/lib/view/modes/last-applied.ts
- plugins/plugin-kubectl/src/plugin.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-subcommands.ts
Fixes #4822
this includes a newly exported type from the core: ViewTransformer
> feat: kubectl apply view-last-applied

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-kubectl/src/lib/util/help.ts
> feat: improve rendering of kubectl subcommand help

- plugins/plugin-client-common/src/components/Client/Screenshot.tsx
- plugins/plugin-client-common/src/components/spi/Alert/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Alert/model.ts
> fix(plugins/plugin-client-common): Screenshot results in a react console error

- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/util/parse.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Node.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
- plugins/plugin-kubectl/view-utilization/src/controller/get-node-data.ts
- plugins/plugin-kubectl/view-utilization/src/controller/get-pod-data.ts
> feat(plugins/plugin-kubectl): optimizing Node summary impl

- package-lock.json
- packages/core/package.json
- packages/core/src/main/headless-support.ts
> fix(packages/core): add missing readline dependence

- package-lock.json
- packages/core/package.json
- packages/core/src/core/find-file.ts
- packages/core/src/index.ts
- plugins/plugin-kubectl/tekton/src/preload.ts
not used, and imports a problematic dependence
Fixes #4839
> fix: remove augmentModuleLoadPath API

- packages/core/src/index.ts
- packages/core/src/models/editable.ts
- plugins/plugin-client-common/src/components/Content/Editor/index.tsx
- plugins/plugin-client-common/web/scss/components/Editor/Editor.scss
- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
- plugins/plugin-kubectl/src/test/k8s1/edit.ts
> feat: line highlights on editor save, used for k edit apply errors

- packages/core/src/plugins/plugins.ts
> fix(packages/core): eliminate races and buggy fallback in prescan loader

- plugins/plugin-kubectl/src/controller/kubectl/apply-subcommands.ts
- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
- plugins/plugin-kubectl/src/lib/view/modes/last-applied.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-subcommands.ts
> fix(plugins/plugin-kubectl): kubectl apply edit-last-applied freezes in kui

- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
> fix(plugins/plugin-client-common): missed i18n strings in Dropdown menus

- packages/builder/tsconfig-base.json
> fix(packages/builder): remove duplicate removeComments field in tsconfig

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support2/remove-output.ts
> fix(plugins/plugin-client-common): clicking the remove button of a repl block results in an error white screen

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
> fix: split screen terminals sometimes incorrect handle exit

- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> fix(plugins/plugin-client-common): table container should only be width:100% for table not display-as-grid

- packages/builder/dist/electron/build.sh
This change is suggested because I'm submitting a Cask to Homebrew and would like to include the kubectl-kui binary in /usr/local/bin directly while installing the application to /Applications. 
Additionally, I ran by habit "kubectl kui get pods" from inside Kui and it appeared to hang indefinitely. This script prevents that, though it doesn't produce pretty output like Kui normally would.
> fix: Update kubectl-kui location on macOS to inside Kui.app/Contents/Resources

- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix: erratic scroll region behavior

- README.md
> doc: update to new location of kubectl-kui on macOS

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
- plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/web/css/static/status-stripe.css
- plugins/plugin-client-test/src/test/response/status-stripe.ts
- plugins/plugin-git/i18n/resources_en_US.json
- plugins/plugin-git/src/CurrentGitBranch.tsx
- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
- plugins/plugin-kubectl/i18n/resources_en_US.json
- plugins/plugin-kubectl/src/test/k8s1/namespace.ts
> fix: improve hover effect for status stripe buttons

- plugins/plugin-client-common/web/css/static/ui.css
> fix: page-content p should not use text-align: justify

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
> fix(plugins/plugin-client-common): add error icon for error blocks

- plugins/plugin-kubectl/src/controller/kubectl/explain.ts
- plugins/plugin-kubectl/src/test/k8s1/explain.ts
also allows traversal to subfields
Fixes #4921
> fix(plugins/plugin-kubectl): kubectl explain subfields

- package.json
> chore: bump top-level package.json version to 8.10.0

- package-lock.json
- plugins/plugin-bash-like/fs/src/lib/fwrite.ts
- plugins/plugin-bash-like/fs/src/lib/mkTemp.ts
- plugins/plugin-bash-like/fs/src/plugin.ts
- plugins/plugin-bash-like/package.json
- plugins/plugin-kubectl/src/controller/kubectl/edit.ts
> fix: avoid hard-coded use of /tmp in kubectl edit

- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-carbon-themes/web/scss/patternfly-alignment.scss
- plugins/plugin-core-themes/theme.json
- plugins/plugin-core-themes/web/css/fonts.css
- plugins/plugin-core-themes/web/scss/atelier-seaside.scss
- plugins/plugin-core-themes/web/scss/dark.scss
- plugins/plugin-core-themes/web/scss/dracula.scss
- plugins/plugin-core-themes/web/scss/fonts.scss
- plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss
- plugins/plugin-core-themes/web/scss/light.scss
- plugins/plugin-core-themes/web/scss/lucario.scss
- plugins/plugin-core-themes/web/scss/monokai.scss
- plugins/plugin-core-themes/web/scss/nord.scss
- plugins/plugin-core-themes/web/scss/paraiso.scss
- plugins/plugin-core-themes/web/scss/solarized-dark.scss
- plugins/plugin-core-themes/web/scss/tomorrow-night.scss
- plugins/plugin-core-themes/web/scss/zenburn.scss
- plugins/plugin-patternfly4-themes/web/scss/kui-alignment.scss
> fix: support for using patternfly components with non-patternfly themes

- plugins/plugin-client-common/src/components/Client/StatusStripe/TagWidget.tsx
- plugins/plugin-client-common/src/components/spi/Tag/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Tag/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Tag/index.tsx
- plugins/plugin-client-common/src/components/spi/Tag/model.ts
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/css/static/status-stripe.css
- plugins/plugin-client-common/web/scss/components/Tag/Carbon.scss
- plugins/plugin-core-support/src/components/UpdateChecker.tsx
and update UpdateChecker to use it
Fixes #4951
> feat(plugins/plugin-client-common): add support for Tags in StatusStripe

- packages/core/src/index.ts
- packages/core/src/models/entity.ts
- packages/core/src/webapp/views/toolbar-text.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/src/components/spi/Alert/impl/Carbon.tsx
- plugins/plugin-client-common/src/controller/alert.ts
- plugins/plugin-client-common/src/plugin.ts
- plugins/plugin-client-common/web/css/static/Screenshot.scss
- plugins/plugin-client-common/web/scss/components/Alert/Carbon.scss
- plugins/plugin-core-support/src/test/core-support/alert.ts
> feat: add alert command to display Alert component in Terminal

- .travis.yml
- plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts
- plugins/plugin-kubectl/logs/src/index.ts
- plugins/plugin-kubectl/logs/src/test/logs/helpers.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-multi.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs-tab-previous.ts
- plugins/plugin-kubectl/logs/src/test/logs/logs.ts
- plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
> fix(plugins/plugin-kubectl): oc logs does not work

- package-lock.json
- plugins/plugin-bash-like/package.json
- plugins/plugin-bash-like/src/pty/copy.ts
> chore(plugins/plugin-bash-like): bump xtermjs dependence to 4.7.0

- plugins/plugin-client-common/src/components/Client/Screenshot.tsx
> fix(plugins/plugin-client-common): Screenshot modal never goes away

- package-lock.json
- packages/webpack/package.json
- packages/webpack/webpack.config.js
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Card/model.ts
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
- plugins/plugin-client-default/i18n/about_en_US.json
- plugins/plugin-client-default/icons/svg/kui-dark.svg
- plugins/plugin-client-default/src/@types/images.d.ts
- plugins/plugin-client-default/src/index.tsx
> feat: Update default loadingDone to use Card component

- plugins/plugin-carbon-themes/web/scss/carbon-gray90.scss
- plugins/plugin-client-common/web/css/static/Confirm.scss
- plugins/plugin-core-themes/web/scss/dark.scss
> fix: Confirm dialog color contrast issues

- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Card/model.ts
- plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
- plugins/plugin-client-default/icons/svg/kui-dark.svg
- plugins/plugin-client-default/src/@types/images.d.ts
- plugins/plugin-client-default/src/index.tsx
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
this also adds support for display the title or body in the header
Fixes #4996
> fix: Card component does not render well in dark themes

- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Pinned.scss
- plugins/plugin-core-themes/web/scss/dark.scss
- plugins/plugin-core-themes/web/scss/light.scss
> fix: increase contrast in watch pane

- .travis.yml
- packages/test/src/api/cli.ts
- packages/test/src/api/repl-expect.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/web/scss/xterm.scss
- plugins/plugin-client-alternate/src/test/bottom-input/new-tab.ts
- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-default/src/index.tsx
- plugins/plugin-client-test/src/test/response/status-stripe.ts
- plugins/plugin-core-support/src/test/core-support2/remove-output.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling.ts
> feat: add capability to show welcome widget to new users in Terminal

- packages/builder/dist/headless/build.sh
> fix(packages/builder): headless build should not rebuild node-pty

- plugins/plugin-client-common/web/scss/components/Terminal/Pinned.scss
> fix(plugins/plugin-client-common): WatchPane has incorrect padding

- packages/test/src/api/selectors.ts
- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Content/Table/ErrorCell.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/kui2carbon.ts
- plugins/plugin-client-common/src/components/spi/Loading/impl/Carbon.tsx
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/scss/components/Loading/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
- plugins/plugin-client-common/web/scss/components/Table/kui-tables.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Pinned.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
- plugins/plugin-client-default/src/index.tsx
- plugins/plugin-core-themes/web/scss/dark.scss
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix: reduce custom CSS rules for table UI

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): double watch panes may open up

- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-common/web/css/static/master-font-size.scss
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/css/static/sidecar-carbon.css
- plugins/plugin-client-common/web/css/static/sidecar.css
- plugins/plugin-client-common/web/css/static/status-stripe.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> fix(plugins/plugin-client-common): font size issues with LeftNavSidecar

- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/css/static/sidecar-carbon.css
- plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix(plugins/plugin-client-common): a few more rem/em font-size issues

- plugins/plugin-client-common/web/scss/components/Terminal/Pinned.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
> fix(plugins/plugin-client-common): watch pane grid cells too large

- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> fix(plugins/plugin-client-common): decrease height of table footer

- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
make it closer to carbon "Default" tab UI
Fixes #5056
> fix(plugins/plugin-client-common): improve top Tab UI

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): clicking 'remove' of a watchable response doesn't abort the underlying pty job

- plugins/plugin-client-common/web/css/static/master-font-size.scss
- plugins/plugin-core-support/web/css/static/zoom.css
> fix(plugins/plugin-core-support): sidecar "window" buttons are too large

- plugins/plugin-kubectl/oc/src/controller/oc/get/projects.ts
> fix(plugins/plugin-kubectl): oc get ns does not present a RadioTable

- packages/core/src/core/jobs/watchable.ts
- packages/core/src/webapp/models/table.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx
- plugins/plugin-client-common/src/components/Content/Table/Toolbar.tsx
- plugins/plugin-client-common/src/components/Content/Table/kui2carbon.ts
- plugins/plugin-client-common/web/scss/components/Table/Events.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod-with-watch-events.ts
> feat: support for events in table footer

- plugins/plugin-core-support/src/lib/cmds/quit.ts
> fix(plugins/plugin-core-support): cmd+w does not close window

- package-lock.json
- package.json
- plugins/plugin-client-test/src/lib/cmds/mmr-mode.ts
- plugins/plugin-ibmcloud/ks/src/controller/cluster/get.ts
- plugins/plugin-ibmcloud/ks/src/controller/worker-pool/get.ts
- plugins/plugin-ibmcloud/ks/src/controller/worker/get.ts
- plugins/plugin-ibmcloud/ks/src/models/cluster.ts
- plugins/plugin-ibmcloud/ks/src/models/worker-pool.ts
- plugins/plugin-ibmcloud/ks/src/models/worker.ts
- plugins/plugin-ibmcloud/ks/src/modes/dashboard.ts
- plugins/plugin-ibmcloud/ks/src/modes/health.ts
- plugins/plugin-ibmcloud/ks/src/modes/show-pool.ts
- plugins/plugin-ibmcloud/ks/src/modes/show-workers.ts
- plugins/plugin-ibmcloud/ks/src/modes/state.ts
- plugins/plugin-ibmcloud/ks/src/modes/update-cluster.ts
- plugins/plugin-ibmcloud/plugin/src/controller/command/get.ts
- plugins/plugin-ibmcloud/plugin/src/controller/get.ts
- plugins/plugin-ibmcloud/plugin/src/controller/repo/get.ts
- plugins/plugin-ibmcloud/plugin/src/models/plugin.ts
- plugins/plugin-ibmcloud/plugin/src/models/repository.ts
- plugins/plugin-ibmcloud/plugin/src/modes/show-all-commands.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-crd.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-pod.ts
> chore: bump to typescript 3.9

- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx
> feat(plugins/plugin-client-common): show table row count in card header

- packages/test/src/api/selectors.ts
- plugins/plugin-core-support/src/test/core-support/alert.ts
> test(plugins/plugin-core-support): highly unstable alert test

- plugins/plugin-core-support/src/test/core-support/text-search.ts
- plugins/plugin-electron-components/src/components/Search.tsx
also fixes a deprecation warning from the Carbon Search component
Fixes #5167
> test: improve reliability of text search test

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx
- plugins/plugin-client-common/src/components/Content/Table/Toolbar.tsx
- plugins/plugin-client-common/web/scss/components/Table/Events.scss
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/test/k8s2/events-in-table.ts
this adds support to the Markdown view component for "quiet" execs
Fixes #5173
> feat: clicking on events in watch table should drill down to events

- plugins/plugin-carbon-themes/web/scss/inverted.scss
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-client-common/web/css/static/sidecar-main.css
this also improves color contrast of red for carbon gray 10 in the sidecar
Fixes #5175
> fix(plugins/plugin-client-common): sidecar badges may not be flush-right

- packages/core/src/util/i18n.ts
> fix(packages/core): i18n treats 0 parameter as undefined

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/web/scss/components/Table/sizing.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
> fix(plugins/plugin-client-common): improve display of empty watch tables

- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
> fix: (plugins/plugin-kubectl): kubectl get pod -w --all-namespaces behaves oddly

- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/web/scss/components/Table/Lightweight.scss
- plugins/plugin-client-common/web/scss/components/Table/carbon-kui-theme-alignment.scss
1) no nRows header
2) reduce top-padding
Fixes #5216
> fix(plugins/plugin-client-common): minor improvements for ls -l output

- package.json
> chore: bump top-level package.json to 8.11.0

- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> fix(plugins/plugin-client-common): close tabs doesn't produce the correct tab content

- packages/core/src/core/events.ts
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Content/Editor/index.tsx
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix: Editor component does not respond to tab layout changes

- plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx
- plugins/plugin-client-common/web/scss/components/RadioTable/Carbon.scss
- plugins/plugin-client-common/web/scss/components/StructuredList/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> fix(plugins/plugin-client-commong): show RadioTable selected row in the table body and header breadcrumb

- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
- plugins/plugin-client-common/src/controller/confirm.ts
> fix(plugins/plugin-client-common): clicking on pod delete button can cause command to be executed in minisplit

- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
- plugins/plugin-git/package.json
- plugins/plugin-git/src/controller/git/branch.ts
- plugins/plugin-git/src/plugin.ts
- plugins/plugin-git/src/test/core-support/git-branch.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
- plugins/plugin-kubectl/src/test/k8s1/namespace.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
> feat(plugins/plugin-git): git branch should respond with RadioTable

- plugins/plugin-client-common/src/components/Views/Terminal/getSize.ts
> fix(plugins/plugin-client-common): pty commands fail in minisplits

- packages/core/src/core/events.ts
- packages/core/src/models/tab-state.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
> fix: switching splits does not participate in tab state

- plugins/plugin-client-common/web/css/static/repl.scss
> fix(plugins/plugin-client-common): reduce contrast of block left bars

- packages/core/src/webapp/models/table.ts
- packages/test/src/api/table.ts
- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-test/src/lib/cmds/content/table-with-drilldown.ts
- plugins/plugin-client-test/src/test/response/table.ts
> feat: allow table model to specify a gridable column index

- packages/core/src/repl/exec.ts
- packages/test/src/api/keys.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyDown.ts
- plugins/plugin-core-support/src/test/core-support2/history-splits.ts
- plugins/plugin-core-support/src/test/core-support2/history.ts
- plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
> fix: multiple command history regressions

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-kubectl/src/test/k8s1/create-pod.ts
> fix(plugins/plugin-client-common): Grid regression: grid colors not right

- packages/core/src/repl/split.ts
- plugins/plugin-core-support/src/lib/cmds/echo.ts
- plugins/plugin-core-support/src/plugin.ts
- plugins/plugin-core-support/src/test/core/command-line-parsing.ts
> fix(packages/core): backslashes not always properly parsed

- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecar.tsx
- plugins/plugin-client-common/web/css/static/sidecar.scss
- plugins/plugin-client-common/web/css/static/split-pane.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
> fix(plugins/plugin-client-common): CSS no longer is reactive to narrow window

- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
- plugins/plugin-core-support/src/test/core-support2/history-splits.ts
> fix(plugins/plugin-client-common): inconsistent top padding above Cards

- plugins/plugin-s3/src/test/core/s3.ts
- plugins/plugin-s3/src/vfs/index.ts
> feat(plugins/plugin-s3): support for inter-s3 copying

- plugins/plugin-bash-like/fs/src/lib/glob.ts
- plugins/plugin-bash-like/fs/src/lib/tab-completion.ts
> feat(plugins/plugin-bash-like): tab completion for s3 buckets

- packages/test/src/api/table.ts
- plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/web/scss/components/Table/Bar.scss
- plugins/plugin-ibmcloud/ce/src/controller/job/kubectl.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat(plugins/plugin-client-common): improved SequenceDiagram view

- packages/core/src/webapp/models/table.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/web/scss/components/Table/Bar.scss
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat: cold start delays

- packages/core/src/models/execOptions.ts
- plugins/plugin-ibmcloud/ce/src/controller/generic/list.ts
- plugins/plugin-ibmcloud/ce/src/controller/job/kubectl.ts
- plugins/plugin-ibmcloud/ce/src/controller/kubectl/index.ts
- plugins/plugin-ibmcloud/ce/src/plugin.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat: allow for limiting the number of kubectl table rows

- packages/test/src/api/repl-expect.ts
- plugins/plugin-ibmcloud/ce/src/bind.ts
- plugins/plugin-ibmcloud/ce/src/controller/job/kubectl.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/options.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat: generalized kubectl get with limit

- plugins/plugin-client-common/web/css/static/repl.scss
> fix(plugins-client-common): the experimental tag should use sans serif

- plugins/plugin-kubectl/src/test/k8s1/limit.ts
> test(plugins/plugin-kubectl): add test for kubectl get with limit

- plugins/plugin-kubectl/src/controller/kubectl/raw.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix(plugins/plugin-kubectl): header-only tables improperly parsed

- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/web/scss/components/Table/Timeline.scss
> fix(plugins/plugin-client-common): Timeline may not render properly

- .travis.yml
- plugins/plugin-kubectl/src/controller/kubectl/exec.ts
- plugins/plugin-kubectl/src/controller/kubectl/run.ts
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/util/version.ts
- plugins/plugin-kubectl/src/test/k8s1/run.ts
- plugins/plugin-kubectl/src/test/k8s2/api-resources.ts
- tools/travis/microk8s.sh
> chore: bump microk8s to 1.17 (was: 1.15)

- package.json
> chore: bump top-level package.json to 8.12.0

- plugins/plugin-client-common/src/components/Content/Table/Timeline.tsx
- plugins/plugin-client-common/web/scss/components/Table/Timeline.scss
> fix(plugins/plugin-client-common): refine Timeline a bit more

- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-test/src/lib/cmds/content/table-with-drilldown.ts
- plugins/plugin-kubectl/krew/src/controller/popeye.ts
> fix: grid colors are sometimes off

- plugins/plugin-iter8/src/modes/decisionForm.tsx
- plugins/plugin-iter8/src/modes/exprForm.tsx
- plugins/plugin-iter8/src/web/scss/static/decisionForm.scss
- plugins/plugin-iter8/src/web/scss/static/exprForm.scss
> fix(plugins/plugin-iter8): avoid collisions with global css rules

- plugins/plugin-iter8/src/components/cluster-info.ts
- plugins/plugin-iter8/src/components/delete-metric.ts
- plugins/plugin-iter8/src/components/metric-config.ts
- plugins/plugin-iter8/src/components/restore-metric.ts
- plugins/plugin-iter8/src/components/traffic-split.ts
- plugins/plugin-iter8/src/models/metrics.tsx
- plugins/plugin-iter8/src/modes/config.tsx
- plugins/plugin-iter8/src/modes/decisionForm.tsx
- plugins/plugin-iter8/src/modes/exprForm.tsx
- plugins/plugin-iter8/src/modes/get-metrics.tsx
- plugins/plugin-iter8/src/modes/state-models.ts
- plugins/plugin-iter8/src/plugin.ts
- plugins/plugin-iter8/src/utility/get-iter8-req.ts
- plugins/plugin-iter8/src/utility/iter8-svc-status.ts
> fix(plugins/plugin-iter8): Removed execSync from iter8 plugin

- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-kubectl/src/test/k8s1/replay.ts
> fix: snapshot command throws errors when capturing watch responses

- packages/core/src/repl/exec.ts
- packages/core/src/repl/split.ts
- packages/test/src/api/repl-expect.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/test/bash-like/blank-lines.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/controller/commentary.ts
> feat: pass command line comments to commentary command

- plugins/plugin-core-support/src/lib/cmds/replay.ts
- plugins/plugin-kubectl/src/test/k8s1/replay.ts
> fix: snapshot command fails at `k get -o yaml`

- packages/test/src/api/cli.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Experimental.scss
> feat(plugins/plugin-client-common): Improve notebook-style ui

- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-kubectl/src/controller/kubectl/deployment.ts
- plugins/plugin-kubectl/src/lib/util/expound.ts
- plugins/plugin-kubectl/src/lib/util/util.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/plugin.ts
- plugins/plugin-kubectl/src/test/k8s1/deployment.ts
> feat(plugins/plugin-kubectl): add status column to kube deployment table

- plugins/plugin-bash-like/fs/src/lib/ls.ts
> fix(plugins/plugin-bash-like): use standard table UI for ls -l output

- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Generic.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Job.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
> fix(plugins/plugin-kubectl): add Summary impl for kubernetes Jobs

- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Else.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> feat(plugins/plugin-client-common): improve presentation of sidecar-destined responses

- packages/core/src/main/menu.ts
> feat(packages/core): add Notebook to Electron Menu

- packages/core/src/core/events.ts
- packages/core/src/index.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Client/StatusStripe/CurrentWorkingDirectory.tsx
- plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyDown.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support/replay.ts
- plugins/plugin-git/src/CurrentGitBranch.tsx
- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
this also fixes a few react leaks in status stripe widgets
Fixes #5495
> fix: restore status stripe to default behavior on terminal clear

- packages/core/src/main/menu.ts
> fix(packages/core): change menu title Notebook -> Notebooks

- plugins/plugin-kubectl/tutorials/list-resources.json
> fix(plugins/plugin-kubectl): wordsmithing to list-resources notebook

- plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-notebook/src/preload.ts
- plugins/plugin-client-test/src/preload.ts
- plugins/plugin-core-support/src/tutorials/vfs/index.ts
- plugins/plugin-kubectl/src/non-headless-preload.ts
- plugins/plugin-s3/src/test/core/s3.ts
- plugins/plugin-s3/src/vfs/forwarder.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix: vfs fixes for multi-source copying and for s3 globbing

- packages/core/src/repl/exec.ts
- packages/core/src/repl/split.ts
- plugins/plugin-bash-like/src/test/bash-like/ls.ts
- plugins/plugin-bash-like/src/test/bash-like/semicolons.ts
> fix(packages/core): improve parsing of semicolons

- packages/core/src/core/events.ts
- packages/core/src/repl/events.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Client/TabModel.ts
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
- plugins/plugin-client-common/web/css/static/TopTabStripe.scss
- plugins/plugin-client-notebook/src/index.tsx
- plugins/plugin-client-notebook/tutorials/welcome.json
- plugins/plugin-core-support/src/lib/cmds/replay.ts
- plugins/plugin-core-support/src/lib/cmds/tab-management.ts
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
- plugins/plugin-kubectl/tutorials/create-jobs.json
- plugins/plugin-kubectl/tutorials/list-resources.json
and use of this in the replay command
Fixes #5525
> feat: custom tab titles

- packages/core/templates/index.ejs
- packages/webpack/webpack.config.js
- plugins/plugin-client-default/config.d/opengraph.json
- plugins/plugin-client-notebook/config.d/opengraph.json
> feat: restore opengraph properties on index.ejs

- packages/core/src/index.ts
- packages/core/src/models/CommentaryResponse.ts
- packages/test/src/api/repl-expect.ts
- plugins/plugin-client-common/src/components/Client/TopTabStripe/SplitTerminalButton.tsx
- plugins/plugin-client-common/src/components/Content/Commentary.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/controller/split.ts
- plugins/plugin-client-common/src/plugin.ts
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-notebook/tutorials/welcome.json
- plugins/plugin-core-support/src/lib/cmds/replay.ts
- plugins/plugin-core-support/src/test/core-support2/history-splits.ts
- plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
> fix: improved support for replaying splits

- packages/test/src/api/repl-expect.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/controller/split.ts
- plugins/plugin-client-common/src/plugin.ts
- plugins/plugin-client-notebook/tutorials/welcome.json
- plugins/plugin-core-support/src/lib/cmds/replay.ts
- plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
> feat: inverse splits

- plugins/plugin-client-common/web/scss/components/Table/Bar.scss
> fix(plugins/plugin-client-common): SequenceDiagram bars are too narrow

- packages/core/src/models/history.ts
> fix(packages/core): new tabs may be inoperable

- plugins/plugin-carbon-themes/web/scss/charts.scss
- plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/web/scss/components/Table/Bar.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram.scss
- plugins/plugin-kubectl/src/test/k8s2/job.ts
> fix(plugins/plugin-client-common): SequenceDiagram UI refinements

- packages/core/src/main/menu.ts
- plugins/plugin-iter8/notebooks/welcome.json
- plugins/plugin-iter8/src/preload.ts
> plugins/plugin-iter8: added a welcome notebook

- packages/core/src/webapp/models/table.ts
- plugins/plugin-core-support/src/lib/cmds/replay.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat(packages/core): allow controller to opt in/out recording table row onclicks when snapshot

- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): h2 in Notebooks have double underline

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support2/insert.ts
> feat(plugins/plugin-client-common): allow users to insert command before a repl block

- packages/core/src/index.ts
- packages/core/src/models/RadioTable.ts
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/RadioTable/model.ts
- plugins/plugin-core-support/src/lib/cmds/theme.ts
- plugins/plugin-git/src/controller/git/branch.ts
- plugins/plugin-kubectl/oc/src/controller/oc/get/projects.ts
- plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
- plugins/plugin-kubectl/src/controller/kubectl/exec.ts
- plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts
> fix: RadioTables are not replayable

- .travis.yml
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/controller/split.ts
- plugins/plugin-client-common/src/plugin.ts
- plugins/plugin-client-default/src/test/core/background-tab-open.ts
- plugins/plugin-core-support/src/test/core-support/replay.ts
- plugins/plugin-core-support/src/test/core-support2/history.ts
- plugins/plugin-core-support/src/test/core-support2/remove-output.ts
- plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
- plugins/plugin-kubectl/src/test/k8s1/labels.ts
- plugins/plugin-kubectl/src/test/k8s1/secrets.ts
- plugins/plugin-kubectl/src/test/k8s1/source-ref.ts
- plugins/plugin-kubectl/src/test/k8s2/events-tab.ts
- plugins/plugin-kubectl/src/test/k8s2/events-via-table.ts
- plugins/plugin-s3/src/test/core/s3.ts
- tools/travis/check-error-handlers.sh
> test: some test error handlers do not properly fail

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): remove active prompts in an offline notebook

- packages/core/src/core/events.ts
- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Client/TabModel.ts
- plugins/plugin-core-support/src/lib/cmds/tab-management.ts
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> fix: new tab command can hang if title is provided

- packages/test/src/api/repl-expect.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support/clear.ts
- plugins/plugin-core-support/src/test/core-support/replay.ts
> fix: terminal clearing versus splits results in non-replayable splits

- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/test/bash-like/rerun.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-core-support/src/test/core-support2/copy-input.ts
- plugins/plugin-core-support/src/test/core-support2/remove-output.ts
- plugins/plugin-core-support/src/test/core-support2/reorder-blocks.ts
- plugins/plugin-kubectl/src/test/k8s1/deployment.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling.ts
> fix: improve the discoverability of repl-block action buttons

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix: output only Actions should also render on hover

- plugins/plugin-bash-like/src/test/bash-like/rerun.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-core-support/src/test/core-support2/copy-input.ts
- plugins/plugin-core-support/src/test/core-support2/remove-output.ts
- plugins/plugin-core-support/src/test/core-support2/reorder-blocks.ts
> feat: add capability to click to edit/rerun a command

- plugins/plugin-core-support/src/lib/cmds/kui-config.ts
- plugins/plugin-core-support/src/lib/cmds/tab-management.ts
- plugins/plugin-core-support/src/plugin.ts
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> feat(plugins/plugin-core-support): conditional opening of tabs

- packages/core/src/core/events.ts
- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Client/TabModel.ts
- plugins/plugin-core-support/src/lib/cmds/tab-management.ts
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> feat: ability to register an onClose handler when opening a tab

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/MiniSplit.scss
> input spinner is not visible in minisplits

- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): ls /s3 fails poorly with wildcards

- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/css/static/ui.css
this also removes some outdated css rules from the old ui.css
Fixes #5697
> fix(plugins/plugin-client-common): never show "ok"

- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): Commentary is always full width

- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix(plugins/plugin-client-common): empty blocks have excessive height

- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
- plugins/plugin-s3/src/test/core/s3.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): improve globbing in s3 rm commands

- packages/core/src/main/menu.ts
- packages/core/src/main/open.ts
- packages/core/src/main/save.ts
- packages/core/src/main/tell.ts
This also reorders the New and Open File menu options to be more consistent with norms.
Fixes #5715
> feat(packages/core): Add File->Save as Notebook

- packages/core/src/index.ts
- packages/core/src/models/XtermResponse.ts
- packages/core/src/models/entity.ts
- packages/test/src/api/repl-expect.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/pty/client.ts
- plugins/plugin-bash-like/src/pty/copy.ts
- plugins/plugin-bash-like/src/pty/drrf.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-focus.ts
- plugins/plugin-bash-like/src/test/bash-like/replay.ts
- plugins/plugin-bash-like/web/scss/xterm.scss
- plugins/plugin-client-common/src/components/Content/Scalar/XtermDom.tsx
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> feat: save/restore pty command output

- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-s3/src/providers/ibmcloud.ts
- plugins/plugin-s3/src/providers/index.ts
- plugins/plugin-s3/src/providers/local-minio.ts
- plugins/plugin-s3/src/providers/model.ts
- plugins/plugin-s3/src/test/core/s3.ts
- plugins/plugin-s3/src/vfs/index.ts
> feat: mount all s3 providers

- packages/core/src/core/events.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-client-common/src/components/Views/Sidecar/ComboSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecar.tsx
- plugins/plugin-core-support/src/test/core-support/replay.ts
- plugins/plugin-kubectl/src/test/k8s3/replay.ts
> fix: sidecar shouldn't be opened automatically when replay

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix(plugins/plugin-client-common): table is misaligned with command input

- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
> fix(plugins/plugin-client-common): re-snapshoting a notebook can fail

- plugins/plugin-client-common/web/scss/components/Terminal/MiniSplit.scss
> fix(plugin-client-common): show the last input block in minisplit

- plugins/plugin-core-support/src/lib/cmds/replay.ts
> fix(plugins/plugin-core-support): clicks in replayed table are erratic

- packages/core/src/core/events.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix: for replayed notebooks, don’t show timestamp

- packages/test/src/api/cli.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnPaste.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ClipboardTransfer.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support/copy-block.ts
> feat(plugins/plugin-client-common): block-level copy/paste

- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ClipboardTransfer.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix(plugins/plugin-client-common): focus a block upon moving or pasting it

- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-s3/src/vfs/forwarder.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix: improve vfs cp to handle disparate source

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump to electron 7.3.3

- plugins/plugin-kubectl/src/lib/model/states.ts
- plugins/plugin-kubectl/src/lib/view/css-for-value.ts
> fix(plugins/plugin-kubectl): k8s table should display status Propagated and Subscribed as green

- plugins/plugin-kubectl/src/lib/model/states.ts
- plugins/plugin-kubectl/src/lib/view/css-for-value.ts
> fix(plugins/plugin-kubectl): kubectl table should show PropagationFailed status as offline

- packages/core/src/webapp/models/table.ts
- plugins/plugin-bash-like/fs/src/lib/ls.ts
- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
> fix: ls comand is not snapshotable

- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts
- plugins/plugin-kubectl/src/test/k8s3/replay.ts
> fix: snapshot and replay of table clicks for Notebook v1

- plugins/plugin-electron-components/src/components/UpdateChecker.tsx
> fix(plugins/plugin-electron-components): Update available fires when older legacy dist tags are released

- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix(plugins/plugin-patternfly4-themes): switching from PatternFly4 Dark to PF4 Light and back to PF4 Dark results in poor colors

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-patternfly4-themes/package.json
> chore: bump to patternfly 4.50.2

- package-lock.json
- package.json
> chore: bump to typescript 4

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump to monaco-editor 0.21.2

- plugins/plugin-kubectl/src/test/k8s3/replay.ts
> test: k8s replay tests are unreliable

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): when replaying notebooks, tab should be scrolled to top

- plugins/plugin-iter8/notebooks/welcome.json
- plugins/plugin-kubectl/notebooks/create-jobs.json
- plugins/plugin-kubectl/notebooks/list-resources.json
> fix: improve existing notebooks for v1

- plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts
> fix(plugins/plugin-client-common): remove clicks from NotebookImpl

- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
> fix(plugins/plugin-client-common): disable Timeline option for Tables

- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support/replay.ts
> fix: re-saving a notebook via File->Save as Notebook does not preserve notebook title

- package.json
> chore: bump top-level package.json to 9.0.0

- packages/core/src/main/spawn-electron.ts
> fix(packages/core): Remove autoHideMenuBar:true for linux and windows

- package-lock.json
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/package.json
> fix(plugins/plugin-bash-like): ls on windows behaves poorly

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support/replay.ts
- plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts
> fix(plugins/plugin-client-common): tab switching can be slow on windows

- plugins/plugin-client-common/notebooks/welcome.json
- plugins/plugin-client-common/src/components/Content/Commentary.tsx
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/controller/commentary.ts
- plugins/plugin-core-support/src/test/core-support/commentary.ts
- plugins/plugin-iter8/notebooks/welcome.json
- plugins/plugin-kubectl/notebooks/create-jobs.json
- plugins/plugin-kubectl/notebooks/list-resources.json
Fixes #5916
Fixes #5672
Closes #5922
> fix: store the commentary text result to the command when editing is done

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
> fix(plugins/plugin-client-common): do not show the command rerun and remove button for offline kui

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix(plugins/plugin-client-common): empty pty response yields blank line

- packages/core/src/main/menu.ts
- plugins/plugin-ibmcloud/cos/src/controller/config.ts
- plugins/plugin-ibmcloud/cos/src/controller/endpoint.ts
- plugins/plugin-ibmcloud/cos/src/controller/validate.ts
- plugins/plugin-ibmcloud/cos/src/plugin.ts
- plugins/plugin-ibmcloud/i18n/cos_en_US.json
- plugins/plugin-s3/notebooks/using-s3.json
- plugins/plugin-s3/notebooks/welcome.json
- plugins/plugin-s3/src/preload.ts
> fix: a few more improvements to s3 onboarding

- packages/core/src/index.ts
- packages/core/src/models/entity.ts
- plugins/plugin-client-common/i18n/errors_en_US.json
- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
> fix: improve error reporting from APIs

- plugins/plugin-s3/notebooks/using-s3.json
> fix(plugins/plugin-s3): using s3 notebook has an ECONNREFUSED

- plugins/plugin-client-notebook/src/index.tsx
> fix(plugins/plugin-client-notebook): github button in notebook client does not have hover effect

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix(plugins/plugin-client-common): active pty output doesn't have repl-context

- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/web/scss/components/Alert/Carbon.scss
> fix(plugins/plugin-client-common): the alert showing lost connection has incorrect height

- plugins/plugin-ibmcloud/cos/src/controller/local.ts
- plugins/plugin-ibmcloud/cos/src/model/Config.ts
> fix(plugins/plugin-ibmcloud): ibmcloud cos initialization bug

- .travis.yml
- packages/test/src/api/util.ts
- plugins/plugin-bash-like/src/test/bash-like/replay.ts
- plugins/plugin-core-support/src/test/core-support/commentary.ts
- plugins/plugin-core-support/src/test/core-support/replay.ts
- plugins/plugin-kubectl/src/test/k8s3/replay.ts
> test: snapshot tests should test against a unique file name each time

- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
> fix(plugins/plugin-client-common): restore hiding of In[1] in minisplit

- plugins/plugin-client-common/notebooks/settings.json
> fix(plugins/plugin-client-common): update the commentary in settings notebook to store the texts as command

- packages/core/src/models/RadioTable.ts
- plugins/plugin-client-common/src/components/spi/RadioTable/impl/Carbon.tsx
- plugins/plugin-core-support/src/lib/cmds/theme.ts
> fix: RadioTable should have option to not echo the onSelect command

- plugins/plugin-client-common/web/scss/components/CodeSnippet/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): sidecar markdown code snippet has poor color

- package-lock.json
- package.json
- plugins/plugin-client-common/package.json
carbon 7.22 fixed the issue that clicking a sidecar tab will cause scrolling
Fixes #6011
Closes #6012
> fix(plugins-client-common): bump carbon-components-react to 7.22

- packages/core/src/core/repl.ts
- packages/core/src/index.ts
- packages/core/src/models/command.ts
- packages/core/src/models/execOptions.ts
- packages/core/src/models/repl.ts
- packages/core/src/repl/exec.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support/replay.ts
> feat: introduce reexec for rerunning commands

- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-carbon-themes/web/scss/inverted.scss
- plugins/plugin-client-common/web/scss/components/Terminal/MiniSplit.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: A few more themes tweaks are needed

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
> fix(plugins/plugin-client-common): custom repl-prompt is misaligned with repl-output

- packages/core/src/main/menu.ts
- plugins/plugin-client-common/notebooks/make-notebook.json
- plugins/plugin-client-default/src/preload.ts
> feat: Make a notebook about making notebooks

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump react-markdown to 5.0.x

- README.md
> docs: update travis badge to point to travis-ci.com

- packages/core/src/repl/events.ts
- packages/core/src/repl/exec.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Announcement.scss
> fix: block focus regressions

- package-lock.json
- package.json
> chore: bump top-level version to 9.1.0

- .travis.yml
> chore: Stop forcing xenial in travis

- packages/core/src/main/spawn-electron.ts
> fix(packages/core): will-navigate handler is too aggressive

- README.md
- plugins/plugin-client-common/notebooks/welcome.json
> chore: Reference new arm64 builds

- packages/core/src/main/spawn-electron.ts
> fix(packages/core): will-navigate handler is too aggressive #6085

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/index.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/model.ts
- plugins/plugin-client-common/web/scss/components/Accordion/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Accordion/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Accordion/_mixins.scss
> feat: use Accordion for SourceRef

- packages/test/src/api/repl-expect.ts
- packages/test/src/api/util.ts
- plugins/plugin-client-common/src/test/editor/common.ts
- plugins/plugin-client-common/src/test/editor/edit-remove-block.ts
- plugins/plugin-client-common/src/test/editor/edit.ts
> test(plugins/plugin-client-common): add test for 6093/6099

- plugins/plugin-client-common/web/scss/PatternFly/common.scss
> fix(plugins/plugin-client-common): RadioTable has small font size

- plugins/plugin-client-common/src/components/spi/Accordion/impl/Carbon.tsx
> fix(plugins/plugin-client-common): clicking the editor in carbon accordion will change the accordion label

- .travis.yml
> chore: Update travis.yml to avoid homebrew auto-cleanup

- plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
> fix(plugins/plugin-client-common): TabCompletion UI can fail

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Content/KuiContent.tsx
- plugins/plugin-client-common/src/components/Content/Tree.tsx
- plugins/plugin-client-common/src/components/spi/TreeView/index.tsx
- plugins/plugin-client-common/web/scss/components/Tree/_mixin.scss
- plugins/plugin-client-common/web/scss/components/Tree/index.scss
> fix(plugins/plugin-client-common): externalize PatternFly TreeView component to SPI

- package-lock.json
- packages/builder/package.json
> chore: bump babel dependencies

- plugins/plugin-carbon-themes/web/scss/charts.scss
- plugins/plugin-patternfly4-themes/web/scss/charts.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: chart colors for patternfly themes aren't in a diverging series

- plugins/plugin-client-common/web/scss/components/Tree/index.scss
> fix(plugins/plugin-client-common): typo "soild" in Tree.scss

- plugins/plugin-iter8/notebooks/welcome.json
> fix(plugins/plugin-iter8): minor install command edit in notebook

- packages/core/src/webapp/themes/Theme.ts
- packages/core/src/webapp/themes/persistence.ts
- plugins/plugin-client-common/src/components/Content/Editor/lib/fonts.ts
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/css/static/sidecar-carbon.css
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/css/static/sidecar.scss
- plugins/plugin-client-common/web/scss/PatternFly/common.scss
- plugins/plugin-client-common/web/scss/components/Sidecar/Nested.scss
- plugins/plugin-client-common/web/scss/components/Table/Lightweight.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_index.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Table/Timeline.scss
- plugins/plugin-client-common/web/scss/components/Table/sizing.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Announcement.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/MiniSplit.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-client-common/web/scss/components/common/_Lightweight.scss
- plugins/plugin-client-common/web/scss/components/common/_mixins.scss
- plugins/plugin-core-themes/theme.json
> feat: lightweight ui options for core themes

- plugins/plugin-bash-like/fs/src/lib/ls.ts
> fix(plugins/plugin-bash-like): ls -l should show size column in splits

- package-lock.json
- plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-s3/package.json
- plugins/plugin-s3/src/jobs/index.ts
- plugins/plugin-s3/src/jobs/providers/CodeEngine2.ts
- plugins/plugin-s3/src/providers/MinioConfig.ts
- plugins/plugin-s3/src/providers/aws.ts
- plugins/plugin-s3/src/providers/index.ts
- plugins/plugin-s3/src/ssc/controller.ts
- plugins/plugin-s3/src/ssc/index.ts
- plugins/plugin-s3/src/vfs/forwarder.ts
- plugins/plugin-s3/src/vfs/index.ts
> feat: experimental parallelized cp aginst s3 vfs

- package.json
> chore: bump top-level package.json to 9.2.0

- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-client-common/web/scss/components/Editor/Editor.scss
- plugins/plugin-client-common/web/scss/components/Editor/diff.scss
- plugins/plugin-core-themes/web/scss/atelier-seaside.scss
- plugins/plugin-core-themes/web/scss/dark.scss
- plugins/plugin-core-themes/web/scss/dracula.scss
- plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss
- plugins/plugin-core-themes/web/scss/light.scss
- plugins/plugin-core-themes/web/scss/lucario.scss
- plugins/plugin-core-themes/web/scss/monokai.scss
- plugins/plugin-core-themes/web/scss/nord.scss
- plugins/plugin-core-themes/web/scss/paraiso.scss
- plugins/plugin-core-themes/web/scss/solarized-dark.scss
- plugins/plugin-core-themes/web/scss/tomorrow-night.scss
- plugins/plugin-core-themes/web/scss/zenburn.scss
- plugins/plugin-kubectl/src/lib/util/tree.ts
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: monaco diff view colors are not themed

- plugins/plugin-s3/src/jobs/providers/CodeEngine.ts
> fix(plugins/plugin-se): CodeEngine.ts uses invalid option

- plugins/plugin-client-common/web/scss/components/Tree/index.scss
- plugins/plugin-kubectl/src/lib/util/tree.ts
> fix(plugins/plugin-kubectl): unlabeled resources shouldn’t have badge for children's count

- packages/core/src/webapp/themes/persistence.ts
- plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
- plugins/plugin-core-themes/web/scss/dark.scss
- plugins/plugin-core-themes/web/scss/light.scss
> fix: Tree view badges can have low contrast

- plugins/plugin-kubectl-flow-views/tekton/src/view/flow.ts
> fix(plugins/plugin-kubectl-flow-views): `tekton flow` command fails

- plugins/plugin-bash-like/fs/src/lib/ls.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/src/test/bash-like/ls.ts
- plugins/plugin-s3/src/jobs/providers/CodeEngine2.ts
- plugins/plugin-s3/src/ssc/index.ts
- plugins/plugin-s3/src/ssc/scaleOut.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix: port gunzip and gzip to use new job controller

- plugins/plugin-client-common/web/scss/components/CodeSnippet/Carbon.scss
- plugins/plugin-s3/src/jobs/providers/CodeEngine2.ts
- plugins/plugin-s3/src/ssc/index.ts
- plugins/plugin-s3/src/ssc/scaleOut.ts
- plugins/plugin-s3/src/vfs/index.ts
> feat: port experimental scale-out grep to use new job controller

- plugins/plugin-bash-like/fs/src/lib/ls.ts
> fix(plugins/plugin-bash-like): ls -l does not show stat data

- plugins/plugin-client-common/web/css/static/ui.css
> fix(plugins/plugin-client-common): `ls` in minisplit has tall rows

- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): scale-out gzip not quite right

- plugins/plugin-client-common/web/scss/components/Navigation/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Navigation/Patternfly.scss
- plugins/plugin-client-common/web/scss/components/Navigation/common.scss
> fix(plugins/plugin-client-common): LeftNav UIs can be too wide

- plugins/plugin-bash-like/fs/src/lib/ls.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-bash-like): ls on s3 vfs directory can fail

- plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
- plugins/plugin-client-common/src/components/spi/Popover/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Popover/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Popover/index.tsx
- plugins/plugin-client-common/src/components/spi/Popover/model.ts
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/scss/components/Popover/Carbon.scss
- plugins/plugin-client-common/web/scss/components/Popover/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Popover/common.scss
- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
- plugins/plugin-client-default/src/index.tsx
- plugins/plugin-git/i18n/resources_en_US.json
- plugins/plugin-git/src/CurrentGitBranch.tsx
This PR introduces the Popover component spi.
Fixes #6325
> feat: use a Popover UI for git branch status stripe widget

- plugins/plugin-client-common/web/scss/components/Table/Lightweight.scss
- plugins/plugin-client-common/web/scss/components/Table/_lightweight_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/MiniSplit.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
> fix(plugins/plugin-client-common): a few minor UI glitches in Block css

- plugins/plugin-core-support/src/lib/cmds/theme.ts
> fix(plugins/plugin-core-support): Simplify themes table

- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-client-common/web/scss/Themes/_mixins.scss
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
- plugins/plugin-core-themes/theme.json
- plugins/plugin-core-themes/web/scss/Mercury.scss
This PR introduces a new Light theme, Mercury, that demonstrates the use of a new mixin Reset that addresses the concern of this issue.
Fixes #6372
> feat: Improve support for designing light themes

- packages/test/src/api/mmr.ts
- plugins/plugin-kubectl/src/controller/kubectl/diff.ts
- plugins/plugin-kubectl/src/controller/kubectl/options.ts
- plugins/plugin-kubectl/src/lib/util/util.ts
- plugins/plugin-kubectl/src/plugin.ts
- plugins/plugin-kubectl/src/test/k8s4/diff.ts
> feat: use Monaco DiffEditor `kubectl diff`

- plugins/plugin-client-common/web/css/static/sidecar.scss
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/Themes/_mixins.scss
- plugins/plugin-client-common/web/scss/components/CodeSnippet/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Navigation/Patternfly.scss
- plugins/plugin-core-themes/web/scss/Mercury.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/fonts.scss
- plugins/plugin-patternfly4-themes/web/scss/mono.scss
- plugins/plugin-patternfly4-themes/web/scss/sans.scss
> fix: Clean up the way patternfly fonts are incorporated into themes

- package.json
> chore: bump main package.json to 9.3.0

- OWNERS
- OWNERS_ALIASES
- SECURITY_CONTACTS
> Add owners files (fixes #6400)

- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_index.scss
- plugins/plugin-ibmcloud/ce/src/controller/job/kubectl.ts
> fix: SequenceDiagram bar widths are pretty buggy

- plugins/plugin-client-common/web/scss/components/Popover/common.scss
- plugins/plugin-electron-components/src/components/UpdateChecker.tsx
> fix: UpdateChecker popover can be too height

- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-ibmcloud/ce/src/controller/job/kubectl.ts
- plugins/plugin-ibmcloud/ce/src/controller/jobrun/submit.ts
- plugins/plugin-kubectl/src/controller/kubectl/raw.ts
- plugins/plugin-s3/src/jobs/providers/CodeEngine2.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix: s3 job watcher sometimes fails due to startup issues

- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-s3/src/jobs/providers/CodeEngine2.ts
- plugins/plugin-s3/src/ssc/scaleOut.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix: kubectl watcher should auto-terminate, if given a bound up front

- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix: Improve debuggability of s3 vfs mounting

- package-lock.json
- package.json
- packages/builder/dist/electron/package.json
> chore: bump to electron 10.2.0

- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
> fix: compilation failures due perhaps to typescript 4.1.3 upgrade??

- plugins/plugin-iter8/src/components/delete-metric.ts
- plugins/plugin-iter8/src/components/metric-config.ts
- plugins/plugin-iter8/src/components/restore-metric.ts
- plugins/plugin-iter8/src/modes/get-metrics.tsx
> fix(plugins/plugin-iter8): fix for typing errors in plugin-iter8

- plugins/plugin-kubectl/src/controller/kubectl/status.ts
> fix(plugins/plugin-kubectl): kubectl delete poller may get stuck Green

- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix(plugins/plugin-client-common): minor Output alignment regression

- package.json
> chore: remove profanity

- packages/webpack/webpack.config.js
> fix(packages/webpack): webpack 5 has deprecated [hash]

- packages/core/src/webapp/models/table.ts
- plugins/plugin-bash-like/src/pty/server.ts
- plugins/plugin-client-common/web/scss/components/Table/Events.scss
- plugins/plugin-kubectl/src/controller/client/direct/errors.ts
- plugins/plugin-kubectl/src/controller/client/direct/get.ts
- plugins/plugin-kubectl/src/controller/client/direct/watch.ts
- plugins/plugin-kubectl/src/controller/fetch-file.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/lib/util/fetch-file.ts
- plugins/plugin-kubectl/src/lib/util/json.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
> feat: Extend kubectl optimizations to table watching

- packages/test/src/api/repl-expect.ts
> test: the "watch directory listing" test can fail (false positive)

- plugins/plugin-client-common/src/components/Client/KuiConfiguration.tsx
- plugins/plugin-client-common/src/controller/user-settings.ts
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> test: new tab conditional tests are buggy

- tools/travis/microk8s.sh
> chore: Travis: socat install no longer needed

- .travis.yml
> fix: Travis: some layers needlessly re-run switch-client

- plugins/plugin-kubectl/src/controller/client/direct/url.ts
> fix(plugins/plugin-kubectl): get-direct does not support field-selectors

- plugins/plugin-client-common/src/components/Content/Editor/lib/defaults.ts
> fix(plugins/plugin-client-common): monaco editor always consumes mouse wheel scrolling events

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-patternfly4-themes/package.json
- plugins/plugin-patternfly4-themes/web/scss/common.scss
This PR also bumps to @patternfly/react-core@4.84.4
Fixes #6496
> fix: in patternfly-based themes, CurrentContext DropDown renders poorly

- plugins/plugin-client-test/src/index.tsx
- plugins/plugin-client-test/src/test/api2/table.ts
> test: test client has test failures due to using splits, but not setting the splitTerminals feature flag

- tools/travis/microk8s.sh
> test: sometimes the kubectl download silently fails

- packages/core/src/webapp/themes/persistence.ts
> fix(packages/core): For some users, the Themes selector may not be shown

- packages/core/src/webapp/models/table.ts
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableHeader.tsx
- plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix: kubectl contexts table has odd CURRENT column

- packages/core/src/webapp/themes/persistence.ts
> fix(packages/core): first-time users may not see Themes widget

- packages/test/src/api/repl-expect.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
- plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
- plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts
> chore: port TopTabStripe from carbon to patternfly

- plugins/plugin-git/src/controller/git/branch.ts
> fix(plugins/plugin-git): git branch command fails if the underlying git command decides to paginate

- plugins/plugin-kubectl/src/controller/kubectl/exec.ts
- plugins/plugin-kubectl/src/controller/kubectl/run.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/plugin.ts
> chore(plugins/plugin-kubectl): remove status command

- README.md
> doc: Update README text

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/impl/Carbon.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Accordion/model.ts
- plugins/plugin-client-common/web/scss/components/Accordion/PatternFly.scss
> fix(plugins/plugin-client-common): Improve rendering of Source Reference UI

- plugins/plugin-kubectl/src/controller/client/direct/url.ts
- plugins/plugin-kubectl/src/controller/client/direct/watch.ts
> fix(plugins/plugin-kubectl): direct watcher improperly formats event url

- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-core-support/src/test/core-support/clear.ts
> fix: ctrl+L in the first block makes the prompt inactive

- plugins/plugin-bash-like/src/pty/websocket-channel.ts
> fix(plugins/plugin-bash-like): reloading browser when streaming events may cause websocket channel to crash

- plugins/plugin-bash-like/src/pty/websocket-channel.ts
> fix(plugins/plugin-bash-like): improve error handling of proxy

- plugins/plugin-bash-like/src/pty/stdio-channel.ts
- plugins/plugin-bash-like/src/pty/websocket-channel.ts
> fix(plugins/plugin-bash-like): further improve error handling in proxy

- plugins/plugin-kubectl/src/controller/client/direct/watch.ts
> chore(plugins/plugin-kubectl): remove leftover debug messages in direct/watch

- packages/test/src/api/sidecar-expect.ts
- packages/test/src/api/util.ts
- plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts
> fix: kubectl Terminal tab test is flakey

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-kubectl/src/controller/kubectl/source.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/lib/util/fetch-file.ts
- plugins/plugin-kubectl/src/test/k8s3/source-ref.ts
> fix(plugins/plugin-kubectl): show SourceRef when creating heterogeneous resources

- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
> fix(plugins/plugin-client-common): repl context will overflow when scrollback has over 100 inputs

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
> fix(plugins/plugin-client-common): tab completion can be flakey

- plugins/plugin-bash-like/fs/src/lib/fstat.ts
fstat inefficiently does stat-then-readFile for cases that just want the file bits
Fixes #6659
> fix(plugins/plugin-bash-like): improve efficiency of fetching file data

- plugins/plugin-client-common/web/scss/components/Navigation/Patternfly.scss
> fix(plugins/plugin-client-common): PatternFly NavResponse does not unexpand

- plugins/plugin-kubectl/src/controller/kubectl/status.ts
> feat(plugins/plugin-kubectl): static get -f should show sourceRef

- plugins/plugin-bash-like/src/pty/client.ts
> fix(plugins/plugin-bash-like): pty/client has remnants of global sidecar

- plugins/plugin-client-common/src/components/spi/Alert/impl/PatternFly.tsx
- plugins/plugin-client-common/src/index.ts
- plugins/plugin-client-common/web/scss/components/ButtonSet/_index.scss
- plugins/plugin-electron-components/src/components/Screenshot.tsx
- plugins/plugin-electron-components/web/scss/components/Screenshot/Screenshot.scss
> chore: Update Screenshot.tsx to use Button spi

- plugins/plugin-client-common/src/components/spi/Button/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Button/model.ts
- plugins/plugin-iter8/src/modes/MultiSelect.tsx
- plugins/plugin-iter8/src/modes/decisionForm.tsx
- plugins/plugin-iter8/src/modes/exprForm.tsx
- plugins/plugin-iter8/src/modes/get-metrics.tsx
- plugins/plugin-iter8/src/web/scss/static/exprForm.scss
- plugins/plugin-iter8/src/web/scss/static/metrics.scss
> chore: remove Carbon dependencies from plugin-iter8

- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Icons/index.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-electron-components/src/components/Search.tsx
- plugins/plugin-electron-components/web/scss/components/Search/Search.scss
https://user-images.githubusercontent.com/21212160/105772336-06acf800-5f30-11eb-9d22-09ff2dfde4a7.mov
Part of #4364
> chore(plugins/plugin-client-common): remove Carbon impl for Search

- package-lock.json
- package.json
- plugins/plugin-client-common/package.json
> chore: remove all remaining Carbon Components dependencies

- packages/builder/dist/electron/build.sh
This will indirectly fix the mentioned issue, once the fix is released.
9_3_x series: should land in 9.3.12
10_0_x series: should land in the first release
Fixes #6725
> fix(packages/builder): remove jq dependence from electron builder

- packages/core/src/webapp/themes/Theme.ts
- plugins/plugin-client-common/src/components/Client/DefaultKuiConfiguration.ts
- plugins/plugin-client-common/src/components/Client/Kui.tsx
> chore: Remove now-unsupported "carbon" ThemeProperty

- plugins/plugin-client-common/web/scss/components/Navigation/Patternfly.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> fix(plugins/plugin-client-common): table and nav content are not left-aligned with breadcrumb

- plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts
- plugins/plugin-kubectl/logs/src/test/logs/usage.ts
> fix(plugins/plugin-kubectl): k logs has bad error message

- packages/core/src/webapp/tab.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/plugin.ts
- plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Fixes #6747
This PR also fixes the lack of contrast between mini and regular terminals when using the PatternFly4 Light theme
Fixes #6743
> feat: improve the split layout progression

- plugins/plugin-client-common/web/css/static/TabCompletion.scss
- plugins/plugin-client-common/web/css/static/ui.css
> fix(plugins/plugin-client-common): tab-completion font-family regression

- packages/core/src/main/menu.ts
> chore(packages/core): Remove S3 and OpenWhisk notebook menu items

- plugins/plugin-client-common/web/scss/components/Alert/PatternFly.scss
- plugins/plugin-electron-components/src/components/Screenshot.tsx
> fix: in screenshot alert, the icon and title text are misaligned

- plugins/plugin-client-alternate/config.d/style.json
- plugins/plugin-client-default/config.d/style.json
- plugins/plugin-client-notebook/config.d/style.json
- plugins/plugin-core-support/src/test/core-support/theme-common.ts
> feat: Make PatternFly4 Light the default theme

- package.json
> chore: bump base version to 10.0.0

- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix(plugins/plugin-kubectl): kubectl get events -o wide shows incorrect Last Seen column

- plugins/plugin-client-common/web/scss/components/Table/_lightweight_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
> fix(plugins/plugin-client-common): remove block border and refine input border for minisplits

- plugins/plugin-client-common/web/scss/components/Table/_lightweight_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
https://user-images.githubusercontent.com/21212160/106197190-6568b080-6180-11eb-9c5b-4e7b9837ed0d.mov
Fixes #6808
> fix(plugins/plugin-client-common): Block borders aren't quite right

- plugins/plugin-client-common/web/scss/components/Popover/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Popover/common.scss
> fix(plugins/plugin-client-common): popover has odd spacing and overflow

- plugins/plugin-client-common/notebooks/make-notebook.json
- plugins/plugin-client-common/notebooks/settings.json
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_index.scss
- plugins/plugin-client-default/src/test/core/background-tab-open.ts
- plugins/plugin-iter8/notebooks/welcome.json
- plugins/plugin-kubectl/notebooks/create-jobs.json
- plugins/plugin-kubectl/notebooks/crud-operations.json
- plugins/plugin-kubectl/notebooks/deploy-applications.json
> chore: update welcome notebook

- plugins/plugin-kubectl/src/controller/kubectl/explain-fastpath.ts
> feat(plugins/plugin-kubectl): add explain fastpath for events

- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-default/src/index.tsx
- plugins/plugin-electron-components/src/components/Screenshot.tsx
> fix: Screenshot alert is not visible in narrower windows

- plugins/plugin-kubectl/src/lib/view/modes/Events.tsx
- plugins/plugin-kubectl/src/test/k8s2/events-sidecar-button.ts
- plugins/plugin-kubectl/src/test/k8s2/events-via-table.ts
> fix(plugins/plugin-kubectl): replace Sidecar Events Mode with a toolbar button to show events table in REPL

- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Event.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
> feat(plugins/plugin-kubectl): Add Summary impl for Events

- packages/core/src/models/mmr/types.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-client-common/src/components/Views/Sidecar/Toolbar.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx
- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-kubectl/src/lib/view/modes/Events.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ShowNodeOfPodButton.tsx
- plugins/plugin-kubectl/src/lib/view/modes/ShowOwnerButton.tsx
> feat: show buttons of related resources in sidecar footer

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/SourceRef.tsx
> chore(plugins/plugin-client-common): extract sourceRef out of Input.tsx

- plugins/plugin-kubectl/src/controller/kubectl/explain-fastpath.ts
> feat(plugins/plugin-kubectl): add explain fastpaths for *.v1.apps

- plugins/plugin-kubectl/src/controller/kubectl/explain-fastpath.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Secret.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
> feat(plugins/plugin-kubectl): add Secret explain and Summary fastpaths

- plugins/plugin-iter8/src/modes/decisionForm.tsx
> fix(plugins/plugin-iter8): remove use of patternfly's Touchspin

- packages/core/src/main/menu.ts
- plugins/plugin-client-common/src/components/Client/TopTabStripe/SplitTerminalButton.tsx
> fix: change new split keyboard shortcut from cltrOrMeta+U -> +Y

- packages/core/src/repl/split.ts
> fix(packages/core): improved support for ls versus backslash on windows

- plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
> fix(plugins/plugin-client-common): spinner is off-center by 1px

- packages/test/src/api/util.ts
> test(packages/test): doList test utility function does not work

- plugins/plugin-kubectl/src/test/k8s-popup/create-pod-popup-via-table.ts
- plugins/plugin-kubectl/src/test/k8s-popup/create-pod-popup.ts
- plugins/plugin-kubectl/src/test/k8s-popup/headless-create-pod.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
- plugins/plugin-kubectl/src/test/k8s/namespace.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-pod.ts
- plugins/plugin-kubectl/src/test/k8s1/apply-subcommands.ts
- plugins/plugin-kubectl/src/test/k8s1/create-pod.ts
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
- plugins/plugin-kubectl/src/test/k8s1/get-dash-o-name.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/events-sidecar-button.ts
- plugins/plugin-kubectl/src/test/k8s2/get-all-namespaces.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod-multi-tab.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod-with-not-found.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pods-with-watch.ts
- plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/kubectl-exec.ts
- plugins/plugin-kubectl/src/test/k8s2/terminal-tab.ts
- plugins/plugin-kubectl/src/test/k8s3/labels.ts
- plugins/plugin-kubectl/src/test/k8s3/replay.ts
- plugins/plugin-kubectl/src/test/k8s3/tab-completion.ts
- plugins/plugin-kubectl/src/test/k8s4/delete-pod-via-click.ts
- plugins/plugin-kubectl/src/test/k8s4/semicolons.ts
- plugins/plugin-kubectl/src/test/k8s4/top.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
- plugins/plugin-kubectl/tests/lib/k8s/utils.js
> chore(plugins/plugin-kubectl): shift more uses of dockerhub to quay.io
