README.md

point to the live install

---

tools/scancode/scancode.sh

update scancode git clone to use https:// not git://

---

README.md

add license badge to readme

---

app/config/envs/webpack-local.json
dist/webpack/.gitignore
dist/webpack/package-lock.json
dist/webpack/package.json

improve webpack-local

---

app/config/envs/webpack-local.json
app/content/css/themes/kui.css
app/plugins/modules/tutorials/@tutorials/activation-debugging/package-lock.json

fix for missing icon in webpack-local

---

.travis.yml
app/package-lock.json
app/package.json
app/plugins/modules/apache-composer/package-lock.json
app/plugins/modules/k8s/src/test/k8s/create-pod.ts
package.json
tests/lib/common.js
tests/lib/ui.js
tools/travis/installers/kubeadm-dind/start-cluster.sh
tools/travis/test/install.sh

use kubeadm-dind for cluster

---

README.md

updated travis status badge

---

app/plugins/modules/core-support/src/lib/cmds/run.ts
app/plugins/modules/k8s/src/lib/cmds/status.ts
app/plugins/modules/k8s/src/lib/cmds/util.ts

fix for k8s status on directories

---

app/plugins/modules/openwhisk/src/lib/cmds/actions/invoke.ts
app/plugins/modules/openwhisk/src/lib/cmds/openwhisk-core.ts

improve lazy loading of openwhisk

---

app/plugins/modules/k8s/src/lib/cmds/contexts.ts

remove needsUI from k8s status

---

app/plugins/modules/apache-composer/src/lib/controller/client.ts
app/plugins/modules/apache-composer/src/lib/controller/commands.ts
app/plugins/modules/apache-composer/src/lib/utility/ast.ts
app/plugins/modules/apache-composer/src/lib/utility/compile.ts
app/plugins/modules/apache-composer/src/lib/utility/messages.ts
app/plugins/modules/apache-composer/src/lib/utility/usage.ts
app/plugins/modules/apache-composer/src/lib/view/entity-view.ts
app/plugins/modules/apache-composer/src/test/composer1/app-init-reset.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-delete.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-edit.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-kill.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-list.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-result.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-session-last.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-update.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-viz-no-auth.ts
app/plugins/modules/apache-composer/src/test/composer1/composer-viz.ts
app/plugins/modules/apache-composer/src/test/composer2/composer-create.ts
app/plugins/modules/apache-composer/src/test/composer2/composer-headless.ts
app/plugins/modules/apache-composer/src/test/composer3/docs-introductory-scenario.ts
app/plugins/modules/wskflow/src/lib/preview.ts
app/plugins/modules/wskflow/src/lib/util.ts
app/plugins/modules/wskflow/src/usage.ts
app/src/webapp/cli.ts
package.json
tools/travis/test/install.sh
tools/travis/test/script.sh

[Ready ]fix tslint errors and enable tslint tests

---

app/content/css/ui.css
app/plugins/modules/core-support/src/lib/cmds/history/history.ts
app/plugins/modules/core-support/src/lib/cmds/history/reverse-i-search.ts
app/plugins/modules/core-support/src/lib/text-search.ts
app/plugins/modules/core-support/src/preload.ts
app/plugins/modules/core-support/web/css/text-search.css
app/plugins/modules/field-installed-plugins/src/lib/cmds/remove.ts
app/src/models/history.ts
app/src/test/core2/text-search.ts
app/src/webapp/cli.ts
app/src/webapp/keys.ts

also fix some bugs in the display of the history index `history`
Fixes #66

add reverse-i-search functionality

---

app/plugins/modules/core-support/src/lib/tab-completion.ts
app/plugins/modules/core-support/web/css/tab-completion.css

fix for tab completion popup positioning

---

app/plugins/modules/apache-composer/src/lib/utility/compile.ts
app/plugins/modules/wskflow/src/lib/preview.ts

[Ready] fix(apache-composer): find @ files in browser

---

app/plugins/modules/apache-composer/src/lib/controller/cmd/app-list.ts

[Ready] fix(apache-composer): prevent sorting app list

---

app/content/css/ui.css
app/plugins/modules/grid/web/css/table.css

fix(grid): remove ugly borders from grid view

---

app/plugins/modules/editor/src/lib/placeholders.ts

fix(editor): fix for apache-composer placeholder

---

README.md

docs: add conventional commit badge to README.md

---

app/content/css/ui.css
app/plugins/modules/bash-like/src/lib/cmds/bash-like.ts
app/src/core/repl.ts
app/src/test/core2/bash-like.ts
app/src/webapp/cli.ts
app/templates/index.html
tests/lib/ui.js

feat(core): add support for streaming output to webapp's cli

---

README.md

docs: Fix typo on subtitle (string #86)

---

app/plugins/modules/wskflow/src/lib/graph2doms.ts
app/plugins/modules/wskflow/wskflow.css

fix(apache-composer): refine dashed borders of viz #97

---

.travis.yml
README.md
app/content/css/ui.css
app/plugins/modules/apache-composer/package-lock.json
app/plugins/modules/apache-composer/package.json
app/plugins/modules/apache-composer/src/test/composer1/composer-list.ts
app/plugins/modules/openwhisk/src/lib/cmds/actions/let.ts
app/plugins/modules/openwhisk/src/test/openwhisk4/let.ts
tools/travis/done.js
tools/travis/installers/openwhisk-runtimes-with-nodejs8.json
tools/travis/installers/openwhisk.sh
tools/travis/setup-webhook.sh

feat(core): enable auto-publishing of dev builds after travis success

---

app/plugins/modules/apache-composer/src/lib/controller/cmd/app-list.ts
app/plugins/modules/apache-composer/src/test/composer2/composer-headless.ts

[Ready] feat(apache-composer): app list --count --skip --limit

---

tools/travis/publishers/cos.sh

chore: add missing apt-get update in travis s3 publisher

---

app/plugins/modules/bash-like/src/lib/cmds/bash-like.ts
app/plugins/modules/bash-like/src/lib/cmds/ls.ts

fix(bash-like): ls and cd should not require openwhisk creds

---

README.md
docs/dev/README.md
docs/installation.md
docs/readme/examples/composer.md
docs/readme/examples/kubernetes.md
docs/readme/examples/openwhisk.md
tools/travis/done.js

docs: document PATH

---

README.md
docs/installation.md
docs/readme/examples/composer.md
docs/readme/examples/kubernetes.md
docs/readme/examples/openwhisk.md

docs: refine READMEs

---

app/plugins/modules/bash-like/src/lib/cmds/bash-like.ts
app/plugins/modules/bash-like/src/lib/cmds/open.ts

Fixes #121
Fixes #122
```
```
Thanks!

fix(bash-like): open and pwd should not require authentication

---

app/plugins/modules/editor/src/lib/cmds/edit-amd.ts
docs/readme/examples/composer.md

docs: improve readmes

---

docs/dev/README.md

docs: add complete path to PATH

---

app/plugins/modules/apache-composer/src/lib/controller/cmd/app-config.ts
app/plugins/modules/apache-composer/src/lib/controller/cmd/app-create.ts
app/plugins/modules/apache-composer/src/lib/controller/cmd/app-delete.ts
app/plugins/modules/apache-composer/src/lib/controller/cmd/app-invoke.ts
app/plugins/modules/apache-composer/src/lib/controller/cmd/session-list.ts

[Ready] fix(apache-composer): inconsistent debug header in composer commands

---

app/plugins/modules/apache-composer/src/lib/utility/compile.ts
app/plugins/modules/editor/src/lib/cmds/edit-amd.ts

[Ready] style(apache-composer): rename variables and functions in compile.ts

---

app/content/css/left-tab-stripe.css
app/plugins/modules/core-support/src/lib/new-tab.ts

fix(core-support): tab button coloring and scrolling improvements

---

app/plugins/modules/core-support/src/lib/new-tab.ts
app/plugins/modules/core-support/src/lib/repl-focus.ts
app/src/webapp/cli.ts
app/templates/index.html

fix(webapp): improve text selection and mouse click behavior

---

app/plugins/modules/field-installed-plugins/package-lock.json
app/plugins/modules/field-installed-plugins/package.json

fix(field-installed-plugins): fix for npm install error

---

app/bin/kubectl-wsk
app/plugins/modules/bash-like/src/lib/cmds/bash-like.ts
app/plugins/modules/openwhisk/src/test/openwhisk1/headless.ts
app/src/core/repl.ts
app/src/main/headless-support.ts
app/src/main/headless.ts

fix(headless): command not found handler for headless mode

---

app/plugins/modules/k8s/src/lib/cmds/kubectl.ts
app/plugins/modules/k8s/src/test/k8s/create-pod.ts
app/plugins/modules/k8s/tests/lib/k8s/wipe.js
app/plugins/modules/openwhisk/src/test/openwhisk1/headless.ts
app/src/models/execOptions.ts
tests/lib/common.js
tests/lib/headless.d.ts
tests/lib/headless.js
tests/lib/ui.js

test(k8s): new headless tests for k8s

---

app/plugins/modules/apache-composer/src/test/composer1/composer-edit.ts
app/plugins/modules/apache-composer/tests/lib/composer-viz-util.js
app/plugins/modules/wskflow/src/lib/graph2doms.ts

[ready] test(apache-composer): add wskflow tests for live composing

---

app/plugins/modules/core-support/src/lib/cmds/help.ts
app/plugins/modules/core-support/src/plugin.ts
app/plugins/modules/editor/src/lib/readonly.ts
app/plugins/modules/editor/src/preload.ts
app/plugins/modules/grid/src/lib/util.ts
app/plugins/modules/openwhisk/src/lib/cmds/auth.ts
app/plugins/modules/openwhisk/src/lib/cmds/beautify.ts
app/plugins/modules/openwhisk/src/lib/cmds/openwhisk-core.ts
app/plugins/modules/openwhisk/src/lib/models/auth.ts
app/plugins/modules/openwhisk/src/lib/models/modes.ts
app/plugins/modules/openwhisk/src/lib/models/namespace.ts
app/plugins/modules/openwhisk/src/lib/models/synonyms.ts
app/plugins/modules/openwhisk/src/lib/views/cli/activations/entity.ts
app/plugins/modules/openwhisk/src/plugin.ts
app/plugins/modules/openwhisk/src/preload.ts
app/plugins/modules/openwhisk/src/test/openwhisk1/basic-stuff.ts
app/plugins/modules/openwhisk/src/test/openwhisk2/auth.ts
app/src/core/capabilities.ts
app/src/core/command-tree.ts
app/src/core/plugins.ts
app/src/core/repl.ts
app/src/main/headless-pretty-print.ts
app/src/main/headless.ts
app/src/main/tray.ts
app/src/models/history.ts
app/src/test/core1/basic-functionality.ts
app/src/webapp/bootstrap/boot.ts
app/src/webapp/query.ts
tests/lib/ui.js

fix: remove more openwhiskisms from the core

---

app/plugins/modules/core-support/src/lib/cmds/help.ts
app/plugins/modules/k8s/src/lib/cmds/auth.ts
app/plugins/modules/k8s/src/lib/cmds/copy.ts
app/plugins/modules/k8s/src/lib/cmds/kedit.ts
app/plugins/modules/k8s/src/lib/cmds/kubectl.ts
app/plugins/modules/k8s/src/lib/cmds/status.ts
app/plugins/modules/k8s/src/plugin.ts
app/plugins/modules/openwhisk/package-lock.json
app/plugins/modules/openwhisk/package.json
app/plugins/modules/openwhisk/src/lib/models/auth.ts
app/plugins/modules/openwhisk/src/preload.ts
app/src/core/command-tree.ts
app/src/core/plugins.ts

chore(core): optimize kubectl kui load paths

---

app/content/css/ui.css
app/templates/index.html

fix(webapp): spinner behaves badly when sidecar is open

---

app/plugins/modules/core-support/src/lib/cmds/help.ts
app/plugins/modules/openwhisk/src/test/openwhisk1/help.ts
app/src/core/command-tree.ts
app/src/core/plugins.ts

this allows us to simplify the help commandin core-support, removing the garbage override function
Fixes #166

chore(core): add requiresFullyQualifiedRoute support to command resolver

---

app/plugins/modules/apache-composer/package.json
app/plugins/modules/bash-like/package.json
app/plugins/modules/core-support/package.json
app/plugins/modules/editor/package.json
app/plugins/modules/field-installed-plugins/package.json
app/plugins/modules/grid/package.json
app/plugins/modules/k8s/package.json
app/plugins/modules/openwhisk-debug/package.json
app/plugins/modules/openwhisk/package.json
app/plugins/modules/tutorials/package.json
app/plugins/modules/wskflow/package.json

chore: add prefix @kui-plugin to the name in package.json of each module

---

app/plugins/modules/k8s/src/test/k8s/create-pod.ts
app/plugins/modules/k8s/src/test/k8s/dash-dash-ui.ts
app/plugins/modules/openwhisk/src/test/openwhisk1/headless.ts
dist/headless/build.sh
kui.js
package.json
tests/lib/headless.js
tools/travis/setup-webhook.sh

chore(core): remove top-level kui.js script and update files using kui.js with bin/kui
Fixes #194

chore(core): remove top-level kui.js script and update files using kui.js with bin/kui

---

dist/webpack/README.md
dist/webpack/build.sh
dist/webpack/package-lock.json

also update docs to point to build.sh
Fixes #207

fix(webpack): disable pre and post for webpack builds

---

.gitignore

fix: add /package-lock.json to gitignore

---

app/plugins/modules/openwhisk/src/lib/models/namespace.ts
app/src/core/repl.ts
app/src/main/headless.ts

chore(core): remove more openwhisk bits from headless

---

app/plugins/modules/bash-like/src/lib/cmds/git-commit.ts
app/plugins/modules/bash-like/src/lib/cmds/git-diff.ts
app/plugins/modules/bash-like/src/lib/cmds/git-status.ts
app/plugins/modules/bash-like/src/lib/cmds/ls.ts
app/plugins/modules/bash-like/src/lib/util/markdown.ts
app/plugins/modules/core-support/src/lib/cmds/help.ts
app/plugins/modules/k8s/src/lib/cmds/kubectl.ts
app/src/core/command-tree.ts
app/src/core/plugin-assembler.ts
app/src/core/repl.ts
app/src/core/usage-error.ts
app/src/webapp/util/ascii-to-usage.ts
dist/webpack/webpack.config.js

this also fixes a few minor issues with the webpack builds, e.g. in the treatment of child_process
Fixes #218

feat(core): add requiresLocal support to the command evaluator

---

app/plugins/modules/bash-like/src/lib/cmds/bash-like.ts
app/plugins/modules/bash-like/src/lib/cmds/open.ts
app/plugins/modules/core-support/src/lib/cmds/screenshot.ts
app/plugins/modules/openwhisk-debug/src/plugin.ts
dist/webpack/webpack.config.js

fix: add requiresLocal to more commands

---

app/content/css/ui.css
dist/webpack/package.json
docs/dev/README.md
docs/dev/packaging.md
docs/installation.md

docs: updated developer docs

---

app/plugins/modules/wskflow/wskflow.css
dist/webpack/webpack.config.js

this resolves a webpack build error
Fixes #222

fix(wskflow): change // to /* in wskflow.css

---

README.md
docs/dev/README.md

docs: fix broken image links in READMEs

---

packages/app/bin/kubectl-kui
packages/app/bin/kubectl-wsk
packages/app/bin/kui
packages/app/package.json
packages/app/src/core/plugin-assembler.ts
packages/app/src/core/plugins.ts
packages/kui-builder/bin/compile.sh
packages/kui-builder/bin/link-build-assets.sh
packages/kui-builder/bin/link-source-assets.sh
packages/kui-builder/dist/bin/compile.js
packages/kui-builder/package.json
plugins/plugin-apache-composer/package.json
plugins/plugin-bash-like/package.json
plugins/plugin-core-support/package.json
plugins/plugin-editor/package.json
plugins/plugin-grid/package.json
plugins/plugin-k8s/package.json
plugins/plugin-manager/package.json
plugins/plugin-openwhisk-debug/package.json
plugins/plugin-openwhisk/package.json
plugins/plugin-tutorials/package.json
plugins/plugin-wskflow/package.json

chore(kui-builder): updates to allow for nested installation

---

packages/app/src/webapp/bottom-stripe.ts
packages/kui-builder/dist/bin/compile.js
plugins/plugin-grid/src/lib/mirror.ts
plugins/plugin-wskflow/src/lib/fsm2graph.ts

chore: remove various leftover debugging printfs

---

packages/kui-builder/dist/webpack/publish.js

fix(webpack): restore webpack publisher functionality

---

plugins/plugin-apache-composer/src/lib/controller/client.ts
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-apache-composer/src/lib/utility/parse.ts

fix(apache-composer): app create -r waits for all actions being successfully deployed

---

package.json
packages/app/.npmignore
packages/app/package.json
packages/app/src/main/headless.ts
packages/app/src/main/main.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/test/core/version.ts
packages/kui-builder/.gitignore
packages/kui-builder/bin/link-build-assets.sh
packages/kui-builder/bin/link-source-assets.sh
packages/kui-builder/dist/electron/bin/postinstall.sh
packages/kui-builder/dist/electron/build.sh
packages/kui-builder/dist/headless/build.sh
packages/kui-builder/dist/headless/package.json
packages/kui-builder/dist/webpack/build.sh
packages/kui-builder/package.json
plugins/plugin-openwhisk/src/test/openwhisk1/headless.ts

chore: update kui-builder for improved consummability

---

.travis.yml
packages/kui-builder/dist/electron/build.sh
packages/kui-builder/dist/headless/build.sh
packages/kui-builder/dist/webpack/build.sh
packages/kui-builder/dist/webpack/package.json
tools/travis/test/install.sh
tools/travis/test/script.sh
tools/travis/test/test.d/lint.sh
tools/travis/test/test.d/webpack.sh

test: add webpack build tests

---

packages/proxy/routes/exec.js

fix(proxy): we weren't handling execOptions undefined

---

packages/kui-builder/dist/webpack/README.md
packages/kui-builder/dist/webpack/build-docker.sh
packages/kui-builder/dist/webpack/sample-overrides/css/themes/kui-fun.css
packages/kui-builder/dist/webpack/sample-overrides/theme.json
packages/kui-builder/lib/configure.js

fix(webpack): improve theme override support

---

plugins/plugin-proxy-support/src/lib/proxy-executor.ts

fix(plugin-proxy-support): needle url issue

---

packages/kui-builder/dist/webpack/bin/ssl.sh
packages/kui-builder/dist/webpack/build.sh
plugins/plugin-proxy-support/src/lib/proxy-executor.ts
tools/travis/test/script.sh

Fixes #312
also fixes some lint errors
Fixes #313

test: fix for lint failures not failing travis

---

packages/app/content/css/.gitignore
packages/kui-builder/dist/dev/build.sh
packages/kui-builder/package.json

fix: local dev-mode ./bin/kui is missing theme

---

plugins/plugin-apache-composer/src/initRequirePath.ts
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-apache-composer/src/plugin.ts
plugins/plugin-apache-composer/src/preload.ts
plugins/plugin-apache-composer/src/test/composer1/composer-viz.ts
plugins/plugin-apache-composer/tests/data/composer/composer-source-expect-errors/openwhisk-composer-throw-err.js

fix(apache-composer): help editor find openwhisk-composer module by moving appModulePath to apache-composer preload

---

plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-wskflow/src/lib/preview.ts

fix(wskflow): fix for preview @demos in webpack mode

---

package.json

fix(core): make sure lerna bootstrap --hoist fails fast

---

plugins/plugin-apache-composer/src/lib/controller/client.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-create.ts
plugins/plugin-apache-composer/src/lib/model/editor/composition-persister.ts
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-apache-composer/src/lib/utility/usage.ts
plugins/plugin-apache-composer/src/test/composer1/composer-edit.ts
plugins/plugin-apache-composer/src/test/composer1/composer-viz.ts
plugins/plugin-apache-composer/src/test/composer1/wskflow_tests.ts
plugins/plugin-apache-composer/src/test/composer2/composer-create-error-handling.ts
plugins/plugin-apache-composer/src/test/composer2/composer-create.ts
plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts
plugins/plugin-tutorials/lib/@tutorials/wookie/tutorial.json

fix(editor): deploy button in sidecar will call pexec(app update) to show more info in cli and sidecar
Fixes #316
Fixes #318

fix(apache-composer): remove app create -r

---

tools/travis/publishers/cos.sh

fix(core): travis after_success script refers to old directory structure

---

packages/app/src/core/plugin-assembler.ts
packages/app/src/core/plugins.ts
packages/app/src/main/headless.ts
packages/app/src/main/store.ts
packages/app/src/util/mimic-dom.ts
packages/kui-builder/dist/bin/compile.js

fix(core): more gracefully handle dom and errors in plugin compiler

---

docs/installation.md

docs: clarify the kubectl plugin situation

---

packages/app/src/webapp/bootstrap/electron.ts

fix(core): confine global repl hack to test mode

---

.travis.yml
packages/app/src/main/spawn-electron.ts
packages/app/tests/lib/common.js
packages/app/tests/lib/ui.js
plugins/plugin-openwhisk/src/lib/cmds/auth.ts
tests/bin/allocate.sh
tests/bin/runLocal.sh
tests/bin/runTest.sh
tools/travis/installers/openwhisk-runtimes-with-java8-and-nodejs8.json
tools/travis/installers/openwhisk.sh
tools/travis/test/install.sh
tools/travis/test/script.sh

chore: improve parallelism in travis

---

packages/proxy/package.json
plugins/plugin-apache-composer/package.json
plugins/plugin-bash-like/package.json
plugins/plugin-core-support/package.json
plugins/plugin-editor/package.json
plugins/plugin-grid/package.json
plugins/plugin-k8s/package.json
plugins/plugin-manager/package.json
plugins/plugin-openwhisk-debug/package.json
plugins/plugin-openwhisk/package.json
plugins/plugin-proxy-support/package.json
plugins/plugin-tutorials/package.json
plugins/plugin-wskflow/package.json

fix: proxy package and plugin have improper package.json

---

packages/app/src/core/plugins.ts

fix(core): another fix for error handling in plugin precompiler

---

lerna.json

chore: add lerna publish commit message to lerna.json

---

plugins/plugin-apache-composer/package.json
plugins/plugin-bash-like/package.json
plugins/plugin-core-support/package.json
plugins/plugin-editor/package.json
plugins/plugin-grid/package.json
plugins/plugin-k8s/package.json
plugins/plugin-manager/package.json
plugins/plugin-openwhisk-debug/package.json
plugins/plugin-openwhisk/package.json
plugins/plugin-proxy-support/package.json
plugins/plugin-tutorials/package.json
plugins/plugin-wskflow/package.json

chore: fix prepublish scripts to use tar instead of cp

---

packages/app/CHANGELOG.md
packages/app/package.json
packages/kui-builder/CHANGELOG.md
packages/kui-builder/package.json
packages/proxy/CHANGELOG.md
packages/proxy/package.json
plugins/plugin-apache-composer/CHANGELOG.md
plugins/plugin-apache-composer/package.json
plugins/plugin-bash-like/CHANGELOG.md
plugins/plugin-bash-like/package.json
plugins/plugin-core-support/CHANGELOG.md
plugins/plugin-core-support/package.json
plugins/plugin-editor/CHANGELOG.md
plugins/plugin-editor/package.json
plugins/plugin-grid/CHANGELOG.md
plugins/plugin-grid/package.json
plugins/plugin-k8s/CHANGELOG.md
plugins/plugin-k8s/package.json
plugins/plugin-manager/CHANGELOG.md
plugins/plugin-manager/package.json
plugins/plugin-openwhisk-debug/CHANGELOG.md
plugins/plugin-openwhisk-debug/package.json
plugins/plugin-openwhisk/CHANGELOG.md
plugins/plugin-openwhisk/package.json
plugins/plugin-proxy-support/CHANGELOG.md
plugins/plugin-proxy-support/package.json
plugins/plugin-tutorials/CHANGELOG.md
plugins/plugin-tutorials/package.json
plugins/plugin-wskflow/CHANGELOG.md
plugins/plugin-wskflow/package.json

- @kui-shell/core@2.2.0
- @kui-shell/builder@0.2.0
- @kui-shell/proxy@0.2.0
- @kui-shell/plugin-apache-composer@0.7.0
- @kui-shell/plugin-bash-like@0.0.3
- @kui-shell/plugin-core-support@0.2.0
- @kui-shell/plugin-editor@0.0.3
- @kui-shell/plugin-grid@0.0.3
- @kui-shell/plugin-k8s@0.2.0
- @kui-shell/plugin-manager@0.0.3
- @kui-shell/plugin-openwhisk-debug@0.0.3
- @kui-shell/plugin-openwhisk@0.2.0
- @kui-shell/plugin-proxy-support@0.2.0
- @kui-shell/plugin-tutorials@0.2.0
- @kui-shell/plugin-wskflow@0.0.3
chore(release): publish %s
- @kui-shell/core@2.3.0
- @kui-shell/builder@0.3.0
- @kui-shell/proxy@0.3.0
- @kui-shell/plugin-apache-composer@0.8.0
- @kui-shell/plugin-bash-like@0.0.4
- @kui-shell/plugin-core-support@0.3.0
- @kui-shell/plugin-editor@0.0.4
- @kui-shell/plugin-grid@0.0.4
- …

chore(release): publish 

---

packages/app/CHANGELOG.md
packages/app/package.json
packages/kui-builder/CHANGELOG.md
packages/kui-builder/package.json
packages/proxy/CHANGELOG.md
packages/proxy/package.json
plugins/plugin-apache-composer/CHANGELOG.md
plugins/plugin-apache-composer/package.json
plugins/plugin-bash-like/CHANGELOG.md
plugins/plugin-bash-like/package.json
plugins/plugin-core-support/CHANGELOG.md
plugins/plugin-core-support/package.json
plugins/plugin-editor/CHANGELOG.md
plugins/plugin-editor/package.json
plugins/plugin-grid/CHANGELOG.md
plugins/plugin-grid/package.json
plugins/plugin-k8s/CHANGELOG.md
plugins/plugin-k8s/package.json
plugins/plugin-manager/CHANGELOG.md
plugins/plugin-manager/package.json
plugins/plugin-openwhisk-debug/CHANGELOG.md
plugins/plugin-openwhisk-debug/package.json
plugins/plugin-openwhisk/CHANGELOG.md
plugins/plugin-openwhisk/package.json
plugins/plugin-proxy-support/CHANGELOG.md
plugins/plugin-proxy-support/package.json
plugins/plugin-tutorials/CHANGELOG.md
plugins/plugin-tutorials/package.json
plugins/plugin-wskflow/CHANGELOG.md
plugins/plugin-wskflow/package.json

- @kui-shell/core@2.4.0
- @kui-shell/builder@0.4.0
- @kui-shell/proxy@0.4.0
- @kui-shell/plugin-apache-composer@0.9.0
- @kui-shell/plugin-bash-like@0.0.5
- @kui-shell/plugin-core-support@0.4.0
- @kui-shell/plugin-editor@0.0.5
- @kui-shell/plugin-grid@0.0.5
- @kui-shell/plugin-k8s@0.4.0
- @kui-shell/plugin-manager@0.0.5
- @kui-shell/plugin-openwhisk-debug@0.0.5
- @kui-shell/plugin-openwhisk@0.4.0
- @kui-shell/plugin-proxy-support@0.4.0
- @kui-shell/plugin-tutorials@0.4.0
- @kui-shell/plugin-wskflow@0.0.5
```
```
*type* is one of: feat, fix, docs, chore, style, …

chore(release): publish

---

docs/installation.md

docs: Fixes Issue #380, add node dependency to documentation

---

.gitignore
docs/installation.md

docs: improve installation docs

---

plugins/plugin-apache-composer/package.json
plugins/plugin-apache-composer/src/test/composer3/docs-introductory-scenario.ts
tests/bin/runLocal.sh
tests/bin/runTest.sh

Fixes #392 
this also fixes some of the chaos with runLocal versus ctrl-C for local/laptop development

fix(plugin-apache-composer): update to latest openwhisk-composer

---

plugins/plugin-k8s/src/lib/cmds/states.ts

fix(plugin-k8s): show VirtualService kind as Online

---

packages/app/src/webapp/views/table.ts

fix(app): table watch handler was installing a row-level onclick handler

---

docs/installation.md

docs: fix grammar typo in installation docs

---

packages/app/src/main/store.ts

fix(app): tone down ENOENT while precompiling plugin model

---

docs/installation.md

docs: fix a few typos in installation.md

---

docs/installation.md

docs: fix a typo in installation.md

---

packages/app/src/core/repl.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/webapp/util/fetch-ui.ts

fix(app): fixes for --ui and headless to graphics transitions

---

plugins/plugin-k8s/src/lib/cmds/kubectl.ts

fix(plugin-k8s): fix helm delete (--wait not a supported option)

---

plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/test/bash-like/cd.ts

fix(plugin-bash-like): when cd fails, throw stderr

---

docs/installation.md

docs: fixes for two typos in installation.md

---

docs/dev/build-customization.md

docs: update build customization docs to reflect new custom client work

---

plugins/plugin-apache-composer/src/lib/controller/client.ts

fix(plugin-apache-composer): update to latest apache-composer API

---

clients/README.md
docs/dev/custom-clients.md
docs/dev/customization-guide.md
packages/kui-builder/dist/electron/README.md
packages/kui-builder/dist/headless/README.md
packages/kui-builder/dist/webpack/README.md

docs: improve custom client docs

---

packages/kui-builder/bin/link-build-assets.sh
packages/kui-builder/bin/watch.sh
packages/kui-builder/dist/electron/build.sh
packages/kui-builder/dist/webpack/build.sh

Fixes #448
this also cleans up electron/build.sh, but only refactoring cleanups

fix(kui-builder): update kui-watch to support external clients

---

docs/installation.md
packages/kui-builder/bin/link-source-assets.sh

docs: suggest a curl download command for double-clickable installation

---

packages/app/package-lock.json
packages/app/package.json
packages/app/src/webapp/views/sidecar.ts
packages/kui-builder/package.json
plugins/plugin-k8s/package.json
plugins/plugin-k8s/src/lib/cmds/kubectl.ts
plugins/plugin-k8s/src/lib/cmds/states.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts

Fixes #457
also adds zapr log formatting
Fixes #458

fix(plugin-k8s): improve k8s in absence of plugin-openwhisk

---

plugins/plugin-apache-composer/src/lib/view/entity-view.ts
plugins/plugin-apache-composer/src/test/composer1/composer-viz.ts
plugins/plugin-wskflow/src/lib/fsm2graph.ts
plugins/plugin-wskflow/src/lib/preview.ts
plugins/plugin-wskflow/src/lib/util.ts
plugins/plugin-wskflow/src/lib/visualize.ts

[Ready] fix(plugin-wskflow): add preview notice to sidecar header

---

plugins/plugin-k8s/package.json
plugins/plugin-k8s/src/lib/cmds/kubectl.ts

fix(plugin-k8s): add /usr/local/bin to PATH

---

clients/default/.gitignore
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts

fix(plugin-openwhisk): openwhisk action invoke not always blocking

---

plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts

fix(plugin-openwhisk): remove debugging output from openwhisk-core

---

packages/app/templates/index.html
plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts

fix(plugin-openwhisk): code highlight race bugs

---

packages/kui-builder/dist/headless/build.sh

fix(kui-builder): more fixes for headless build

---

plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts

fix(plugin-openwhisk): fix for activation pagination in webpack

---

packages/kui-builder/dist/electron/build.sh
packages/kui-builder/dist/publishers/s3/publish.sh

fix(kui-builder): more fixes for CD pipeline

---

plugins/plugin-openwhisk/src/test/openwhisk2/edit-new.ts
plugins/plugin-openwhisk/src/test/openwhisk2/edit.ts

test(plugin-editor): test lock and unlock buttoms

---

package.json
packages/app/package.json
packages/kui-builder/dist/electron/package.json
packages/kui-builder/dist/webpack/package-lock.json
packages/kui-builder/dist/webpack/package.json
packages/kui-builder/package.json
plugins/plugin-bash-like/package.json
plugins/plugin-k8s/package.json
plugins/plugin-openwhisk/package.json
plugins/plugin-tutorials/package.json
plugins/plugin-wskflow/package.json
tests/package.json

chore: bump verison dependencies

---

plugins/plugin-k8s/src/lib/cmds/contexts.ts

fix(plugin-k8s): in contexts table, make context name clickable

---

packages/app/src/core/command-tree.ts
packages/app/tests/lib/common.js
plugins/plugin-k8s/src/lib/cmds/kubectl.ts
plugins/plugin-k8s/src/test/k8s/create-pod.ts
plugins/plugin-k8s/src/test/k8s/headless-create-pod.ts

fix(plugin-k8s): add "k" alias for "kubectl"

---

plugins/plugin-k8s/src/test/k8s/headless-create-pod.ts

fix(plugin-k8s): fix for racy headless-create-pod tests

---

.travis.yml
package.json
packages/tests/bin/runMochaLayers.sh
packages/tests/package.json
tools/travis/test/script.sh

chore(tests): some cleanup to test binaries

---

README.md

fix(docs): remove odd final paragraph in README

---

packages/app/src/webapp/picture-in-picture.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/kedit.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts
plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
plugins/plugin-k8s/src/lib/view/insert-view.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts
plugins/plugin-k8s/src/lib/view/modes/status.ts

feat(plugin-k8s): add conditions and containers tabs to kubectl get

---

packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css
packages/tests/bin/runTest.sh
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts
plugins/plugin-k8s/src/test/k8s/create-pod.ts
plugins/plugin-k8s/src/test/k8s/deployment.ts
plugins/plugin-k8s/src/test/k8s/get-pod.ts

test(plugins/plugin-k8s): add kubectl get tab switching tests

---

packages/app/src/core/userdata.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/webapp/util/inject.ts
packages/app/templates/index.html
packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-bash-like/src/lib/cmds/open.ts
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-core-support/src/plugin.ts
plugins/plugin-core-support/src/preload.ts
plugins/plugin-core-support/src/test/core-support/theme.ts
plugins/plugin-editor/src/lib/file-types.ts
plugins/plugin-editor/src/lib/init/amd.ts
plugins/plugin-editor/src/lib/init/esm.ts
plugins/plugin-editor/web/css/editor.css
plugins/plugin-editor/web/css/mono-blue.css
plugins/plugin-grid/src/test/grid/grid.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts
plugins/plugin-tutorials/web/css/main.css
plugins/plugin-wskflow/src/lib/graph2doms.ts
plugins/plugin-wskflow/web/css/wskflow.css

feat(packages/app): dark theme support

---

packages/app/src/core/userdata.ts
packages/kui-builder/dist/webpack/build.sh
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/lib/configure.js
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-proxy-support/src/lib/proxy-executor.ts

fix(packages/kui-builder): theming fixes for webpack

---

packages/app/src/webapp/picture-in-picture.ts
packages/app/templates/index.html
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
plugins/plugin-bash-like/src/lib/cmds/open.ts
plugins/plugin-bash-like/src/lib/util/markdown.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts

also some minor dark mode tweaks for markdown rendering
Fixes #159

fix(plugins/plugin-bash-like): improve markdown rendering

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-editor/web/css/tomorrow-night.css

fix(plugins/plugin-editor): improved dark mode for editor

---

plugins/plugin-wskflow/web/css/wskflow.css

fix(plugins/plugin-wskflow): fix for Y and N coloring in wskflow

---

plugins/plugin-k8s/src/lib/view/formatTable.ts

fix(plugins/plugin-k8s): fix for overflowing UPDATED column in helm list

---

plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts

fix(plugins/plugin-k8s): make helm status rows clickable

---

packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css

fix(packages/app): dark mode fixes for help display

---

plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-core-support/web/css/about.css

plus no spinning icon!
Fixes #540

fix(plugins/plugin-core-support): dark mode fixes for about

---

packages/app/web/css/ui.css
plugins/plugin-tutorials/web/css/tutorials.css

fix(plugins/plugin-tutorial): tutorials versus dark mode fixes

---

packages/app/web/css/ui.css

fix(packages/app): increase contrast of yellow badge

---

plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts
plugins/plugin-k8s/src/test/k8s/config-map.ts

fix(plugins/plugin-k8s): fix for get configmap

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
plugins/plugin-bash-like/src/lib/cmds/open.ts
plugins/plugin-editor/web/css/tomorrow-night.css

fix: more dark mode tweaks, including for editor text

---

packages/app/src/test/core/basic-functionality.ts
packages/app/tests/lib/ui.js
plugins/plugin-apache-composer/src/test/composer1/composer-viz-no-auth.ts
plugins/plugin-openwhisk/src/lib/models/auth.ts
plugins/plugin-openwhisk/src/test/openwhisk1/basic-stuff.ts
plugins/plugin-openwhisk/src/test/openwhisk3/run.ts
plugins/plugin-openwhisk/tests/lib/openwhisk/openwhisk.js

chore(plugin-openwhisk, plugin-apache-composer): remove all openwhisk.ng.bluemix.net

---

packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css

fix(packages/kui-builder): minor dark mode border color tweak

---

plugins/plugin-core-support/package.json
plugins/plugin-core-support/src/plugin.ts
plugins/plugin-core-support/src/preload.ts

fix(plugins/plugin-core-support): add missing deps to package.json

---

plugins/plugin-apache-composer/package.json

fix(plugins/plugin-apache-composer): add missing deps to package.json

---

plugins/plugin-k8s/package.json
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts

Fixes #564
also adds missing deps to package.json
Fixes #568

fix(plugins/plugin-k8s): fix for proxied drilldown from kubectl get

---

packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-k8s/src/lib/view/formatMultiTable.ts

Fixes #575
this also cleans up the dark mode scroll thumbs a bit

fix: some tables overflow due to buggy scrollable css

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/web/css/my-diff2html.css

Fixes #578
this also introduces named colors to the themes

fix: ansi-to-html color definition updates

---

packages/app/web/css/ui.css

fix(packages/app): adjust behavior of usage with sidecar open

---

packages/app/src/core/usage-error.ts
plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
plugins/plugin-k8s/src/test/k8s/usage.ts

test(plugins/plugin-bash-like): enable some usage tests

---

plugins/plugin-editor/package.json

fix(plugins/plugin-editor): add missing deps to package.json

---

plugins/plugin-k8s/src/lib/util/discovery/helm-client.ts

fix(plugins/plugin-k8s): helm client checker fix for webpack

---

plugins/plugin-bash-like/src/lib/cmds/bash-like.ts

fix(plugins/plugin-bash-like): ansi color bg/fg bug fix

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/table.ts
packages/app/tests/lib/ui.js
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/util/git-support.ts
plugins/plugin-bash-like/web/css/my-diff2html.css
plugins/plugin-openwhisk-debug/src/plugin.ts
plugins/plugin-openwhisk/src/test/openwhisk3/local.ts

fix(packages/app): make annoying 'ok' invisible

---

packages/app/src/webapp/cli.ts
packages/app/templates/index.html
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-bash-like/web/css/my-diff2html.css
plugins/plugin-core-support/src/lib/cmds/theme.ts

fix: switch to base16 theme scheme

---

packages/app/src/core/repl.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css

fix(packages/app): fix for spinner going off-viewport

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-bash-like/web/css/my-diff2html.css
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-core-support/src/test/core-support/theme.ts
plugins/plugin-tutorials/web/css/tutorials.css

fix: color contrast issues with dark mode

---

packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/monokai.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/paraiso.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-wskflow/web/css/wskflow.css

feat: add a few more themes

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/table.ts
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/paraiso.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/lib/repl-focus.ts
plugins/plugin-core-support/src/test/core-support/theme.ts
plugins/plugin-editor/src/lib/init/amd.ts
plugins/plugin-editor/src/lib/init/esm.ts
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-editor/web/css/dark.css
plugins/plugin-grid/web/css/table.css

fix: clicks on sidecar header etc. result in prompt losing focus

---

packages/app/package-lock.json
packages/app/package.json
packages/app/src/main/spawn-electron.ts
packages/kui-builder/package.json

fix: handle custom clients that don't provide plugin-core-support

---

packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-grid/web/css/table.css

fix: smoother transitions as themes switch

---

packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-bash-like/web/css/my-diff2html.css

fix: git diff should use side-by-side

---

packages/app/web/css/ui.css

fix(packages/app): fix for row striping contrast in sidecar tables

---

plugins/plugin-core-support/src/lib/cmds/help.ts

fix(plugins/plugin-core-support): help command should not require proxy

---

packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-grid/web/css/table.css
plugins/plugin-wrk/.gitignore
plugins/plugin-wrk/README.md
plugins/plugin-wrk/bin/lt
plugins/plugin-wrk/package.json
plugins/plugin-wrk/scripts/echo.lua
plugins/plugin-wrk/scripts/plain.lua
plugins/plugin-wrk/src/lib/chart.ts
plugins/plugin-wrk/src/lib/graphics.ts
plugins/plugin-wrk/src/lib/history-table.ts
plugins/plugin-wrk/src/lib/history.ts
plugins/plugin-wrk/src/lib/init.ts
plugins/plugin-wrk/src/lib/lt.ts
plugins/plugin-wrk/src/lib/openwhisk.ts
plugins/plugin-wrk/src/lib/replay.ts
plugins/plugin-wrk/src/lib/scriptgen.ts
plugins/plugin-wrk/src/lib/table.ts
plugins/plugin-wrk/src/lib/theme.ts
plugins/plugin-wrk/src/lib/util.ts
plugins/plugin-wrk/src/lib/wrk.ts
plugins/plugin-wrk/src/plugin.ts

feat(plugins/plugin-wrk): wrk plugin

---

plugins/plugin-wrk/src/lib/init.ts

also fix wrk init to limit the number of parallel make jobs
Fixes #632

fix(plugins/plugin-wrk): add wrk clean

---

packages/app/web/css/ui.css

fix(packages/app): fix use of undefined css variable

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/paraiso.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css

fix(packages/kui-builder): fixes for nord and zenburn colors

---

packages/app/src/core/repl.ts
packages/app/src/webapp/picture-in-picture.ts
packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/package.json
plugins/plugin-k8s/src/lib/clients/kiali.ts
plugins/plugin-k8s/src/lib/controller/istio.ts
plugins/plugin-k8s/src/lib/controller/kiali.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/util/fetch-file.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts
plugins/plugin-k8s/src/lib/util/selectors.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts
plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-k8s/src/plugin.ts

feat(plugins/plugin-k8s): initial istio and kiali support

---

plugins/plugin-bash-like/package.json
plugins/plugin-openwhisk-editor-extensions/package.json

fix: add missing debug deps

---

plugins/plugin-k8s/src/lib/controller/istio.ts

fix(plugins/plugin-k8s): k8s versus webpack bug

---

plugins/plugin-core-support/web/css/text-search.css

fix(plugins/plugin-core-support): text search stripe versus dark mode

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/monokai.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css

fix(packages/kui-builder): improve row striping contrast of dark themes

---

packages/app/web/css/ui.css
plugins/plugin-grid/src/lib/cmds/grid.ts

fix(packages/app): balloon-css tooltips should follow theme

---

plugins/plugin-k8s/src/lib/controller/kiali.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts

fix(plugins/plugin-k8s): minor k8s table formatting issues

---

packages/app/src/core/usage-error.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/util/help.ts
plugins/plugin-k8s/src/test/k8s/usage.ts

fix(plugins/plugin-k8s): kubectl logs -h does not display usage

---

packages/app/web/css/left-tab-stripe.css
plugins/plugin-core-support/src/lib/cmds/screenshot.ts

fix: screenshots of repl output should have padding

---

packages/app/web/css/ui.css

fix(packages/app): table row selection does not pre-highlight on hover

---

packages/app/web/css/ui.css

fix(packages/app): remove table border transition effect

---

packages/app/src/core/repl.ts
packages/app/src/webapp/bootstrap/electron.ts
packages/app/tests/lib/ui.js
plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
plugins/plugin-core-support/src/test/core-support/clear.ts
plugins/plugin-core-support/src/test/core-support/tab-completion.ts
plugins/plugin-openwhisk/src/test/openwhisk3/ctrl-c.ts
plugins/plugin-openwhisk/src/test/openwhisk3/tab-completion.ts

chore(packages/tests): remove global repl hack

---

packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/ls.ts

fix: allow clients to take control over entity name table cell coloring

---

packages/app/tests/lib/ui.js

test(packages/app): update test struct matcher to support array subsets

---

packages/app/web/css/ui.css

fix(packages/app): tighten spacing in repl UI

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css
packages/kui-builder/examples/build-configs/default/theme/theme.json

fix(packages/kui-builder): shorten atelier and gruvbox theme names

---

packages/app/web/css/ui.css

fix(packages/app): tone down dark mode entity display

---

packages/app/web/css/ui.css

feat(packages/app): eliminate | repl spinner

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-bash-like/src/lib/cmds/git-status.ts
plugins/plugin-bash-like/web/css/my-diff2html.css

fix: git status UI fixes

---

packages/app/src/webapp/cli.ts

fix(packages/app): try to keep the REPL prompt in focus

---

plugins/plugin-core-support/src/lib/text-search.ts
plugins/plugin-core-support/src/preload.ts

chore(plugins/plugin-core-support): stop injecting kui's text-search bar in browser mode

---

packages/app/web/css/ui.css

fix(packages/app): make sure badges don't overflow tables

---

packages/app/web/css/ui.css

fix(packages/app): height of first repl input changes after execution

---

packages/app/package-lock.json
packages/app/package.json
packages/app/src/webapp/bottom-stripe.ts

feat(packages/app): support declarative bottom stripe direct buttons

---

packages/app/web/css/ui.css

when sidecar opens/closes
Fixes #711

fix(packages/app): fix small vertical wiggle in table cells

---

plugins/plugin-k8s/package.json
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/util/selectors.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-k8s/src/lib/view/modes/status.ts

fix(plugins/plugin-k8s): fix mode button operation when running in proxy

---

packages/app/templates/index.html
packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-core-support/src/lib/new-tab.ts

fix: various small fixes for tab UI

---

packages/app/web/css/left-tab-stripe.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
plugins/plugin-bash-like/web/css/my-diff2html.css

fix: a few more tab tweaks

---

packages/app/src/webapp/views/presentation.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/tests/lib/ui.js
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-bash-like/src/test/bash-like/git-diff.ts
plugins/plugin-bash-like/web/css/my-diff2html.css

also port git diff to use this new feature
Fixes #294
Fixes #721

feat: sidecar full screen

---

plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/test/k8s/run.ts

feat(plugins/plugin-k8s): improve kubectl run behavior

---

packages/app/web/css/ui.css

fix(packages/app): poor display of multi-line table cells

---

packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/util/help.ts

fix(packages/app): further improve multi-line table rendering

---

plugins/plugin-proxy-support/src/lib/proxy-executor.ts

fix(plugins/plugin-proxy-support): webpack+proxy versus usage errors

---

plugins/plugin-wskflow/src/lib/fsm2graph.ts
plugins/plugin-wskflow/src/lib/graph2doms.ts

fix(plugins/plugin-wskflow): fix for overflowing inline function labels

---

packages/app/src/webapp/util/time.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/resource.ts

fix: make improved use of sidecar header for k8s

---

packages/app/src/webapp/cli.ts
packages/app/web/css/left-tab-stripe.css
plugins/plugin-core-support/src/lib/repl-focus.ts

this also refactors some of the repl-focus that had been in cli.ts into repl-focus.ts
Fixes #741

fix: user should be able to select text in sidecar header

---

packages/app/package.json
packages/kui-builder/package.json
packages/tests/package.json

chore: bump version dependencies, including electron

---

packages/app/src/main/spawn-electron.ts

chore(packages/app): specify nodeIntegration:true for electron 5

---

clients/default/package.json
packages/app/src/test/core/about.ts
packages/app/src/util/mimic-dom.ts
packages/app/src/webapp/bootstrap/boot.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/templates/index.html
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-core-support/package.json
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/src/preload.ts
plugins/plugin-core-support/web/css/about.css
plugins/plugin-tutorials/web/css/tutorials.css

feat: switch about window to use a sidecar DOM

---

packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/util/help.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts

feat: pretty-print kubectl error+usage output

---

plugins/plugin-editor/web/css/dark.css
plugins/plugin-editor/web/css/editor.css
plugins/plugin-editor/web/css/mono-blue.css

fix(plugins/plugin-editor): monaco-editor scrollbar positioning issues

---

plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/web/css/about.css

fix(plugins/plugin-core-support): reduce size of about icons

---

tools/travis/installers/kubeadm-dind/dind-cluster-v1.12.sh
tools/travis/installers/kubeadm-dind/start-cluster.sh

fix: travis versus kubeadm-dind

---

plugins/plugin-editor/web/css/dark.css

fix(plugins/plugin-editor): improve key-value coloration in editor

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/picture-in-picture.ts
packages/app/tests/lib/ui.js
plugins/plugin-editor/web/css/dark.css
plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/util/created-on.ts
plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-k8s/src/lib/view/modes/status.ts
plugins/plugin-k8s/src/test/k8s/config-map.ts
plugins/plugin-k8s/src/test/k8s/create-pod.ts
plugins/plugin-k8s/src/test/k8s/describe.ts
plugins/plugin-k8s/src/test/k8s/get-pod.ts
plugins/plugin-k8s/tests/lib/k8s/defaults.js
plugins/plugin-k8s/tests/lib/k8s/wipe.js

feat(plugins/plugin-k8s): kubectl describe refinements

---

plugins/plugin-k8s/src/lib/view/helm-status.ts

fix(plugins/plugin-k8s): helm status click handler for configmaps

---

plugins/plugin-k8s/src/lib/controller/describe.ts

fix(plugins/plugin-k8s): add a few more fields to kubectl describe

---

packages/app/web/css/ui.css

in multi-table output
Fixes #778

fix(packages/app): increase contrast of table header

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-editor/src/lib/open.ts

fix: improved support for long vertical "resource type" sidecar header

---

plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/test/k8s/config-map.ts

fix(plugins/plugin-k8s): add Data to describe output

---

packages/app/src/webapp/views/sidecar.ts

fix(packages/app): tweak sidecar header type shorthand heuristic

---

packages/app/web/css/ui.css

fix(packages/app): minor spacing tweaks to repl

---

packages/app/tests/lib/ui.js
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/test/k8s/config-map.ts
plugins/plugin-k8s/src/test/k8s/create-pod.ts
plugins/plugin-k8s/src/test/k8s/namespace.ts

fix(plugins/plugin-k8s): k get namespace does not show green for Active

---

plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts

fix(plugins/plugin-k8s): status table for namespaces misaligned columns

---

packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts

fix: fix for overflowing badge text

---

packages/app/src/webapp/views/table.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/test/k8s/get-all-namespaces.ts

this also improves support in the core table renderer for string onclicks
Fixes #797

fix: improve support for kube all-namespaces

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css

fix(packages/kui-builder): increase nord theme yaml key contrast

---

plugins/plugin-bash-like/web/css/my-diff2html.css

fix(plugins/plugin-bash-like): git diff character diffs overlap

---

packages/app/web/css/ui.css

fix(packages/app): improve handling of heterogeneous badges

---

plugins/plugin-k8s/src/lib/view/formatTable.ts

fix(plugins/plugin-k8s): kube Status should be STATUS

---

plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/test/k8s/deployment.ts

feat(plugins/plugin-k8s): add delete button to kube describe sidecar

---

packages/app/web/css/ui.css

fix(packages/app): text placement of minimized sidecar title

---

packages/app/web/css/ui.css

fix(packages/app): improve consistency of "ok" spacing

---

plugins/plugin-k8s/src/lib/controller/istio.ts
plugins/plugin-k8s/src/lib/controller/kiali.ts

feat(plugins/plugin-k8s): kiali get apps --interval support

---

packages/app/web/css/ui.css

fix(packages/app): improve text contrast for README.md rendering

---

packages/app/src/core/usage-error.ts

fix(packages/app): usage rendering always shows red text

---

packages/app/src/main/headless-pretty-print.ts

fix(packages/app): headless pretty printer fixes for usage output

---

packages/app/web/css/ui.css

fix(packages/app): bottom stripe does not scale well with fonts

---

packages/app/src/webapp/views/sidecar.ts
packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-editor/src/lib/init/defaults.ts

feat: --ui should open repl-free windows

---

packages/app/src/main/spawn-electron.ts
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-bash-like/src/lib/cmds/git-status.ts
plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts

fix: improved activation list UI

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-openwhisk/src/lib/views/sidecar/activations.ts
plugins/plugin-openwhisk/src/test/openwhisk1/bottom-stripe-activation.ts

fix: simplify core log formatter

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-openwhisk/src/lib/views/sidecar/activations.ts

fix: use 2-space indent for js-beautify

---

plugins/plugin-core-support/src/lib/repl-focus.ts
plugins/plugin-editor/src/test/editor/edit.ts

fix: paste in editor results in loss of editor focus

---

packages/app/src/webapp/views/table.ts
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts

stop using tiny text, use badges for rule status
Fixes #851

fix: refinements to openwhisk list views

---

packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css

fix: eliminate tiny fonts for "package prefix" of default table view

---

plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/web/css/screenshot.css
plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts

in particular, activation list table squishing improvements
Fixes #858

fix: refine screenshot squishing behavior

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-soft.css
packages/kui-builder/examples/build-configs/default/theme/theme.json

feat(packages/kui-builder): add atelier soft theme

---

plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts

fix(plugins-plugin-k8s): helm status tables may have no header row

---

packages/app/src/main/spawn-electron.ts
packages/app/src/webapp/bootstrap/init.ts
packages/app/src/webapp/views/presentation.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/templates/index.html
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-bash-like/src/lib/util/sidecar-support.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-grid/src/lib/cmds/grid.ts
plugins/plugin-grid/src/lib/cmds/table.ts
plugins/plugin-grid/web/css/table.css

fix: repl should use outer scrolling when in popup mode

---

packages/app/src/main/spawn-electron.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/web/css/ui.css
plugins/plugin-core-support/web/css/text-search.css

fix: resolve multiple issues with popups

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/picture-in-picture.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/src/webapp/views/table.ts
packages/app/templates/index.html
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-grid/src/lib/cmds/grid.ts
plugins/plugin-grid/src/lib/cmds/table.ts
plugins/plugin-grid/src/test/grid/grid.ts
plugins/plugin-grid/web/css/table.css

fix: refinements to popup UI

---

packages/app/src/webapp/cli.ts

fix(packages/app): update last updated date daily

---

packages/app/src/core/repl.ts
packages/app/src/util/mimic-dom.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/picture-in-picture.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/templates/index.html
packages/app/web/css/ui.css

feat(packages/app): popup window should offer an <input>

---

packages/app/src/core/usage-error.ts

fix(packages/app): usage links should be target:blank

---

packages/app/templates/index.html
packages/app/web/css/ui.css

fix(packages/app): tweaks for sidecar bottom stripe UI

---

packages/app/src/main/menu.ts

fix(packages/app): cmd+W does not close dev tools window

---

packages/app/web/css/ui.css
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/test/core-support/screenshot.ts
plugins/plugin-core-support/web/css/screenshot.css

fix: screenshot UI improvements

---

plugins/plugin-bash-like/src/lib/cmds/ls.ts

fix(plugins/plugin-bash-like): improved ls support on linux

---

packages/app/src/main/spawn-electron.ts
packages/app/src/webapp/defaults.ts
plugins/plugin-grid/src/lib/cmds/grid.ts
plugins/plugin-grid/src/lib/cmds/table.ts

and adjust grid and table commands to use it
Fixes #897

fix: export default window width and height

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/keys.ts

fix(packages/app): pageup/down key support for webpack

---

packages/app/templates/index.html
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
plugins/plugin-openwhisk/src/lib/views/sidecar/entity.ts
plugins/plugin-openwhisk/src/test/openwhisk1/package-list.ts

fix: openwhisk package list UI fixes

---

plugins/plugin-bash-like/src/lib/cmds/ls.ts

fix(plugins/plugin-bash-like): fix for ls on linux (-B)

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/keys.ts

fix(packages/app): fix for pageup/pagedown keys in webpack

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/util/created-on.ts

also updates created on subtext for k8s
Fixes #907

fix: enhanced support for subtext rendering of sidecar

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/picture-in-picture.ts
packages/app/templates/index.html
packages/app/web/css/ui.css

fix(packages/app): several UI fixes for back button

---

packages/app/templates/index.html
packages/app/web/css/ui.css
plugins/plugin-core-support/web/css/screenshot.css

this also adds 'hide-with-screenshot' css support
Fixes #912

fix: make sidecar header repl look more like a repl

---

packages/app/web/css/ui.css
plugins/plugin-core-support/web/css/screenshot.css

fix: increase contrast of screenshot "ok" icon

---

packages/app/web/css/ui.css
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/web/css/screenshot.css

fix: further screenshot ui improvements

---

packages/app/src/core/repl.ts
packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css

fix(packages/app): popup mode was not displaying errors

---

packages/app/web/css/ui.css
plugins/plugin-grid/web/css/table.css

fix: UI tweaks for grid+table views

---

.travis.yml
tools/travis/installers/kubeadm-dind/start-cluster.sh

fix: travis downloading of helm breakage

---

packages/app/src/core/usage-error.ts
packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css

fix(packages/app): popup scrolling issues

---

packages/app/src/main/headless-pretty-print.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-list.ts
plugins/plugin-apache-composer/src/lib/utility/usage.ts
plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
plugins/plugin-openwhisk/src/lib/models/withHeader.ts

fix: app list table header row

---

plugins/plugin-bash-like/src/lib/util/markdown.ts

fix(plugins/plugin-bash-like): markdown versus popup mode

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/sidecar.ts

feat(packages/app): cmd/ctrl+L in popup mode should focus sidecar input

---

packages/app/web/css/ui.css
plugins/plugin-bash-like/package.json
plugins/plugin-bash-like/src/lib/cmds/open.ts
plugins/plugin-bash-like/src/lib/util/markdown.ts

feat(plugins/plugin-bash-like): asciidoc support

---

packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/view/formatTable.ts

and also label at least one as such
Fixes #936

fix: make sure we don't label multiple columns as NAME-like

---

packages/app/src/webapp/views/table.ts

fix(packages/app): extend picture-in-picture use for popup mode

---

packages/app/web/css/ui.css

fix(packages/app): minor spacing glitch in sidecar header

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-soft.css
plugins/plugin-k8s/src/lib/controller/contexts.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts

feat: k8s tables should have header

---

packages/app/web/css/ui.css

fix(packages/app): grid legend overflow

---

packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-soft.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dracula.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/monokai.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/paraiso.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/zenburn.css

fix(packages/app): eliminate use of fade-in for usage-error UI

---

plugins/plugin-grid/web/css/table.css

fix(plugins/plugin-grid): grid sub-grids do not flex wrap

---

packages/app/src/core/repl.ts
packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-usage.ts

fix(packages/app): some usage error formatting issues

---

packages/app/src/core/usage-error.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css

fix: a few minor usage tweaks

---

plugins/plugin-core-support/src/lib/cmds/clear.ts

fix(plugins/plugin-core-support): clear command needs inBrowserOk:true

---

package.json
packages/app/package.json
packages/kui-builder/package.json
plugins/plugin-k8s/package.json
plugins/plugin-wskflow/package.json

including latest electron 4.1.1
Fixes #962

chore: update dependencies

---

packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts

fix: screenshot should respect scrollTop

---

packages/app/src/webapp/cli.ts

fix(packages/app): paste versus popup mode

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css

fix(packages/kui-builder): dark theme table header color fix

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/web/css/ui.css

fix(packages/app): popup tables should snap to fit

---

plugins/plugin-editor/web/css/dark.css
plugins/plugin-editor/web/css/mono-blue.css

fix(plugins/plugin-editor): editor versus light theme

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/tests/lib/ui.js
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-bash-like/src/lib/cmds/open.ts
plugins/plugin-editor/src/lib/cmds/edit.ts
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-editor/src/lib/persisters.ts
plugins/plugin-editor/src/lib/readonly.ts
plugins/plugin-editor/src/lib/util.ts
plugins/plugin-editor/web/css/editor.css
plugins/plugin-k8s/src/lib/controller/kedit.ts
plugins/plugin-k8s/src/test/k8s/kedit.ts
plugins/plugin-k8s/web/css/main.css

fix: kedit breakage

---

packages/app/src/webapp/views/sidecar.ts
packages/app/web/css/ui.css
plugins/plugin-editor/src/lib/cmds/edit.ts
plugins/plugin-editor/src/lib/fetchers.ts
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-editor/src/lib/persisters.ts
plugins/plugin-editor/web/css/editor.css
plugins/plugin-k8s/src/lib/controller/kedit.ts
plugins/plugin-k8s/src/lib/view/form.ts
plugins/plugin-k8s/src/test/k8s/kedit.ts
plugins/plugin-k8s/web/css/main.css

improve look of form; make form default tab; change tab names
editor also now updates to name changes
Fixes #986

fix: refinements to kedit

---

plugins/plugin-editor/src/lib/persisters.ts
plugins/plugin-k8s/src/lib/controller/kedit.ts
plugins/plugin-k8s/src/lib/view/form.ts
plugins/plugin-k8s/src/test/k8s/kedit.ts

fix: cross-editing between form and monaco issues for kedit

---

packages/app/web/css/ui.css

fix(packages/app): repl input should overflow with ellipsis

---

plugins/plugin-k8s/src/lib/model/states.ts

fix(plugins/plugin-k8s): Unschedulable should be considered offline-like

---

plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/controller/istio.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts
plugins/plugin-k8s/src/test/k8s/create-pod-popup.ts

fix(plugins/plugin-k8s): update to istio 1.1

---

packages/app/web/css/ui.css
plugins/plugin-openwhisk/src/lib/models/withHeader.ts

fix: overflowing table cells

---

packages/app/src/webapp/views/table.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts
plugins/plugin-k8s/src/test/k8s/get-pods-with-watch.ts

Fixes #981 
this doesn't yet support adding and deleting rows from the watch

feat: kubectl get -w

---

packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/controller/istio.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/test/k8s/describe.ts

fix(plugins/plugins-k8s): describe versus unknown resource type

---

packages/app/src/webapp/keys.ts
plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts

fix: two reverse-i-search issues

---

plugins/plugin-k8s/src/lib/controller/istio.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts

fix(plugins/plugin-k8s): revert to istio 1.0.6

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/keys.ts

feat(packages/app): cmd+K on macos should clear repl

---

packages/app/web/css/ui.css
plugins/plugin-editor/web/css/dark.css
plugins/plugin-k8s/src/lib/util/log-parser.ts

fix: improved log rendering, especially for istio

---

plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts

fix(plugins/plugin-apache-composer): compilation failures

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/util/time.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts

also bottom strip improved error handling for direct()
Fixes #1019

fix: log parsing updates

---

packages/app/src/webapp/util/time.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts

fix: improve prettyPrintTime for small deltas

---

packages/app/web/css/ui.css
plugins/plugin-wskflow/src/lib/graph2doms.ts
plugins/plugin-wskflow/web/css/wskflow.css

fix: wskflow theming and css cleanup

---

packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css

improve consistency of sidecar UI
Fixes #1027
avoid repl flowing off left
Fixes #1028

fix(packages/app): sidecar and repl UI glitch fixes

---

packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/ls.ts

LAST MODIFIED column should take up less width
Fixes #1030

fix: improve ls output with sidecar open

---

packages/app/templates/index.html
packages/app/web/css/left-tab-stripe.css

fix(packages/app): refinements to left tab stripe ui

---

packages/app/web/css/left-tab-stripe.css

fix(packages/app): no border-right for left tab stripe

---

packages/app/src/webapp/util/time.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/util/log-parser.ts

fix: log formatting issues

---

packages/app/src/webapp/util/time.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/util/log-parser.ts

feat: k8s parsing of nginx access logs

---

plugins/plugin-bash-like/src/lib/util/markdown.ts

fix(plugins/plugin-bash-like): markdown missing overflow:auto

---

packages/app/templates/index.html
packages/app/web/css/ui.css

fix(packages/app): update "total catastrophe" rendering

---

packages/app/src/core/repl.ts
packages/app/src/test/core/input-queueing.ts
packages/app/src/webapp/cli.ts
packages/app/templates/index.html
packages/app/tests/lib/ui.js
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
plugins/plugin-core-support/src/lib/cmds/sleep.ts
plugins/plugin-core-support/src/plugin.ts
plugins/plugin-grid/src/test/grid/grid.ts

feat(packages/app): queue up input while commands are executed

---

packages/app/templates/index.html
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/dark.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css

Fixes #1046
also fixes bad paths to application icon in light.css and dark.css
Fixes #432

fix: restore missing application icon

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css

fix(packages/kui-builder): increase contrast of yellow in atelier theme

---

packages/app/src/webapp/views/table.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/test/k8s/get-namespaces-with-watch.ts

fix: slowPoll sometimes never terminates

---

plugins/plugin-bash-like/src/plugin.ts

chore(plugins/plugin-base-like): disable bogus git commit command

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

fix: PTY should respond to sidecar open/close

---

packages/app/src/core/command-tree.ts
packages/app/src/core/repl.ts
packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-bash-like/src/test/bash-like/vi.ts
plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): improve exit code handling of pty

---

plugins/plugin-apache-composer/src/test/composer1/wskflow_tests.ts
plugins/plugin-core-support/src/test/core-support/text-search.ts
plugins/plugin-k8s/src/test/k8s/get-namespaces-with-watch.ts
plugins/plugin-k8s/src/test/k8s/get-pods-with-watch.ts

fix(packages/tests): fix misusage of reverse waitForVisable and waitForExist

---

packages/app/src/main/menu.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/electron-events.ts
plugins/plugin-core-support/src/lib/cmds/clear.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/new-tab.ts

fix: tab management should work when tabs are active

---

packages/app/web/css/ui.css

fix(packages/app): don't rotate application icon

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/theme.json

feat: switch from IBM Plex Mono to Roboto Mono

---

packages/app/web/css/ui.css

fix(packages/app): improve text contrast

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): resolve many pty rendering glitches

---

packages/app/src/webapp/views/sidecar.ts

fix(packages/app): sidecar sticks to fullscreen

---

packages/app/web/css/ui.css

fix(packages/app): increase bottom padding for active repl block

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/nord.css

fix(packages/kui-builder): fix nord theme's text color

---

packages/app/web/css/ui.css

fix(packages/app): sidecar back button is huge

---

plugins/plugin-bash-like/src/pty/client.ts

fix(plugins/plugin-bash-like): pty output sometimes not visible

---

plugins/plugin-bash-like/web/css/xterm.css

feat(plugins/plugin-bash-like): make top-sliver in PTY mode draggable

---

packages/app/src/webapp/cli.ts
plugins/plugin-bash-like/src/pty/client.ts

fix: improved scrolling behavior for PTY

---

packages/app/web/css/ui.css

fix(packages/app): another tweak to default font color

---

packages/app/src/webapp/cli.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-bash-like/web/css/xterm.css

fix: improve input queueing versus PTY

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts

fix(plugins/plugin-bash-like): cache websocket channels

---

packages/app/src/core/command-tree.ts
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/lib/cmds/catchall.ts
plugins/plugin-bash-like/src/preload.ts
plugins/plugin-core-support/src/lib/cmds/run.ts
plugins/plugin-editor/src/preload.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/plugin.ts
plugins/plugin-k8s/src/preload.ts
plugins/plugin-openwhisk/src/preload.ts
plugins/plugin-proxy-support/src/preload.ts

chore: load time tuning

---

packages/app/web/css/ui.css
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/web/css/about.css

fix: improved about window UI

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css

fix(packages/kui-builder): light theme white on white

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/cli.ts
packages/app/tests/lib/ui.js
plugins/plugin-apache-composer/src/lib/view/entity-view.ts
plugins/plugin-apache-composer/src/test/composer3/docs-introductory-scenario.ts
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-editor/src/preload.ts
plugins/plugin-editor/web/css/dark.css
plugins/plugin-tutorials/web/css/tutorials.css
plugins/plugin-wskflow/src/lib/preview.ts
plugins/plugin-wskflow/src/lib/util.ts
plugins/plugin-wskflow/web/css/wskflow.css

also updates wskflow tabs to monaco and proxy support
Fixes #1107
Fixes #1110

fix: wskflow versus popup mode

---

packages/app/web/css/ui.css

fix(packages/app): remove direction: rtl from sidecar header

---

clients/bin/link-universe.sh
plugins/plugin-bash-like/package.json
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts

fix: trim pty bits from headless build

---

plugins/plugin-apache-composer/src/test/composer2/popup.ts

test(plugins/plugin-apache-composer): add popup test for apache-composer

---

packages/app/web/css/ui.css

fix(packages/app): usage UI uses REM font size

---

plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-bash-like/src/test/bash-like/git-diff.ts

fix(plugins/plugin-bash-like): git diff shouldn't force full screen

---

plugins/plugin-k8s/src/lib/util/fetch-file.ts
plugins/plugin-k8s/src/test/k8s/redirects.ts

fix(plugins/plugin-k8s): apply fails if URL redirects

---

packages/app/src/webapp/cli.ts
plugins/plugin-bash-like/src/pty/client.ts

fix: PTY scrolling is a bit off

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css

fix(packages/kui-builder): increase contrast of blue in atelier theme

---

docs/dev/custom-clients.md
packages/kui-builder/README.md
packages/proxy/README.md

docs: update packaging docs

---

plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/web/css/screenshot.css

fix(plugins/plugin-core-support): repl screenshot snap bugs

---

plugins/plugin-k8s/src/lib/view/formatMultiTable.ts

fix(plugins/plugin-k8s): k8s tables in sidecar have odd font size

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/atelier-seaside.css

fix(packages/kui-builder): increase atelier theme's text contrast a bit

---

plugins/plugin-tutorials/src/lib/cmds/list.ts

fix(plugins/plugin-tutorials): now playing text is too small

---

packages/app/web/css/ui.css

feat: minimal table rendering mode

---

plugins/plugin-editor/src/lib/open.ts

fix(plugins/plugin-editor): bugs in editor theme switching

---

.npmrc
clients/bin/link-universe.sh
clients/default/.gitignore
clients/default/package.json
packages/app/src/main/spawn-electron.ts
packages/app/tests/lib/ui.js
packages/kui-builder/dist/webpack/webpack.config.js
packages/kui-builder/package.json
plugins/plugin-bash-like/bin/build-pty.sh
plugins/plugin-bash-like/bin/postinstall.sh
plugins/plugin-bash-like/package.json
plugins/plugin-bash-like/src/pty/channel.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
plugins/plugin-wskflow/package.json

fix: node-pty versus electron

---

plugins/plugin-tutorials/src/lib/cmds/play.ts

fix(plugins/plugin-tutorials): webpack versus tutorial play

---

packages/kui-builder/dist/webpack/build.sh
plugins/plugin-core-support/src/test/core-support/help.ts
plugins/plugin-openwhisk/src/test/openwhisk1/help.ts

fix(packages/kui-builder): webpack versus linux

---

packages/app/src/core/repl.ts
packages/app/src/models/execOptions.ts
packages/app/tests/lib/ui.js
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/lib/cmds/catchall.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/test/bash-like/vi.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/test/k8s/config-map.ts
plugins/plugin-k8s/src/test/k8s/edit.ts
plugins/plugin-k8s/src/test/k8s/get-all-namespaces.ts
plugins/plugin-k8s/src/test/k8s/namespace.ts

feat: kubectl edit support

---

plugins/plugin-editor/src/lib/open.ts

fix: editor sometimes doesn't show vertical "icon" text

---

packages/kui-builder/dist/webpack/webpack.config.js
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts
plugins/plugin-wskflow/src/lib/preview.ts

fix: apache-composer versus webpack fixes

---

docs/installation.md

docs: add Node.js installation guide

---

clients/bin/link-universe.sh
clients/default/package.json
packages/kui-builder/dist/webpack/Dockerfile
packages/kui-builder/dist/webpack/bin/ssl.sh
packages/kui-builder/dist/webpack/conf.d/enable-brotli.conf
packages/kui-builder/dist/webpack/webpack.config.js
packages/proxy/Dockerfile
packages/proxy/app/bin/www
packages/proxy/bin/run-proxy.sh
plugins/plugin-bash-like/package.json
plugins/plugin-bash-like/src/lib/cmds/catchall.ts
plugins/plugin-bash-like/src/pty/channel.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts

fix: webpack+proxy versus pty

---

plugins/plugin-wrk/package.json

fix(plugins/plugin-wrk): switch to https for wrk dependence

---

packages/app/templates/index.html
packages/app/web/css/ui.css

fix(packages/app): text selection regression

---

clients/bin/link-universe.sh
clients/default/package.json
packages/kui-builder/dist/publishers/s3/publish.sh
tools/travis/test/target.d/electron.sh

fix: build mac DMG on travis

---

plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/model/states.ts

fix(plugins/plugins-k8s): Ingress never shows as Online

---

packages/app/tests/lib/ui.js
plugins/plugin-k8s/src/lib/controller/contexts.ts
plugins/plugin-k8s/src/test/k8s/contexts.ts
plugins/plugin-k8s/src/test/k8s/namespace.ts

fix(plugins/plugin-k8s): k8s contexts click handler regression

---

packages/app/web/css/ui.css

fix(packages/app): poor overflow in contexts table

---

packages/app/src/webapp/cli.ts
plugins/plugin-bash-like/src/pty/client.ts

fix: PTY copy support

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
plugins/plugin-bash-like/src/test/bash-like/vi.ts

tests(plugins/plugin-bash-like): fix pty paste, add pty copy/paste tests

---

README.md
packages/app/src/core/repl.ts
packages/app/src/webapp/cli.ts
tools/travis/publishers/cos.sh
tools/typecov/bin/upload.sh
tools/typecov/lib/badge.js
tools/typecov/lib/model.js
tools/typecov/package-lock.json
tools/typecov/package.json

feat: type coverage metric

---

README.md

docs: typecov core badge issue

---

README.md

docs: update typecov badge links

---

packages/app/src/core/command-tree.ts
packages/app/src/core/fuzz-testing.ts
packages/app/src/core/plugin-assembler.ts
packages/app/src/core/plugins.ts
packages/app/src/core/repl.ts
packages/app/src/core/utility.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/models/execOptions.ts
packages/app/src/models/history.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/picture-in-picture.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts

fix: initial work on improving core type coverage

---

packages/app/src/core/repl.ts
packages/app/src/main/headless.ts
packages/app/src/main/main.ts
packages/app/src/main/menu.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/models/ReplResponse.ts
packages/app/src/models/SubwindowPrefs.ts
packages/app/src/models/errors.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/electron-events.ts
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-k8s/src/lib/controller/auth.ts
tools/travis/publishers/cos.sh
tools/travis/test/test.d/typecov.sh
tools/typecov/bin/build.sh
tools/typecov/bin/typecov.sh

fix: further work on type coverage

---

packages/app/src/webapp/cli.ts

fix(packages/app): oops handler for qexec issued by onclick

---

packages/app/src/core/capabilities.ts
packages/app/src/core/command-tree.ts
packages/app/src/core/find-file.ts
packages/app/src/core/oops.ts
packages/app/src/core/utility.ts
packages/app/src/main/headless-support.ts
packages/app/src/main/headless.ts
packages/app/src/main/main-models.ts
packages/app/src/main/menu.ts
packages/app/src/main/spawn-electron.ts
packages/app/src/main/store.ts
packages/app/src/main/tray.ts
packages/app/src/models/history.ts
packages/app/src/util/mimic-dom.ts
packages/app/src/webapp/bootstrap/boot.ts
packages/app/src/webapp/bootstrap/init.ts
packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/util/dom.ts
packages/app/src/webapp/util/fetch-ui.ts
packages/app/src/webapp/util/fetcher.ts
packages/app/src/webapp/util/inject.ts
packages/app/src/webapp/util/time.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-grid/src/lib/cmds/grid.ts

fix: yet more typecov work

---

packages/app/src/core/command-tree.ts
packages/app/src/core/usage-error.ts
packages/app/src/main/main.ts
packages/app/src/main/spawn-electron.ts

fix: more type coverage for core

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/models/table.ts
packages/app/src/webapp/views/table.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-core-support/src/lib/cmds/history/history.ts
plugins/plugin-core-support/src/lib/cmds/theme.ts

chore(plugins/plugin-core-support): port plugin-core-support to new table model

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): PTY copies wrong line

---

packages/app/src/webapp/util/ascii-to-usage.ts

fix(packages/app): ascii-to-usage triggers too aggressively

---

plugins/plugin-core-support/src/lib/cmds/quit.ts

fix(plugins/plugin-core-support): quit command versus auth

---

packages/app/src/core/command-tree.ts
packages/app/src/core/repl.ts
packages/app/src/core/usage-error.ts
packages/app/src/main/headless.ts
packages/app/src/util/types.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/util/ascii-to-usage.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-create.ts
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-core-support/src/lib/cmds/help.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/lib/cmds/zoom.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/util/help.ts
plugins/plugin-openwhisk-debug/src/plugin.ts
plugins/plugin-openwhisk/src/lib/cmds/beautify.ts
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts
plugins/plugin-proxy-support/src/lib/proxy-executor.ts

chore: add types to the usage model

---

.gitignore
clients/default/package.json
package.json
packages/kui-builder/dist/electron/build.sh
packages/kui-builder/npmrc

fix: external electron builds versus pty

---

packages/app/src/core/command-tree.ts
packages/app/src/core/repl.ts
packages/app/src/core/usage-error.ts
packages/app/src/models/execOptions.ts
packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts

chore: complete type coverage of command tree

---

packages/app/src/core/plugin-assembler.ts
packages/app/src/core/plugins.ts
packages/app/src/main/headless-pretty-print.ts
packages/app/src/models/plugin.ts
packages/app/src/util/mimic-dom.ts

chore: more types

---

packages/app/src/models/command.ts
packages/app/src/models/plugin.ts
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/src/lib/cmds/about/usage.ts
plugins/plugin-core-support/src/lib/cmds/base64.ts
plugins/plugin-core-support/src/lib/cmds/clear.ts
plugins/plugin-core-support/src/lib/cmds/echo.ts
plugins/plugin-core-support/src/lib/cmds/history/history.ts
plugins/plugin-core-support/src/lib/cmds/open-ui-from-terminal.ts
plugins/plugin-core-support/src/lib/cmds/prompt.ts
plugins/plugin-core-support/src/lib/cmds/quit.ts
plugins/plugin-core-support/src/lib/cmds/run.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/lib/cmds/sleep.ts
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-core-support/src/lib/cmds/window.ts
plugins/plugin-core-support/src/plugin.ts

chore: yet more types

---

packages/kui-builder/examples/plugin-sample/src/lib/cmds/create-echo.ts
packages/kui-builder/examples/plugin-sample/src/lib/cmds/open-sidecar.ts
packages/kui-builder/examples/plugin-sample/src/lib/cmds/say-hello.ts
packages/kui-builder/examples/plugin-sample/src/plugin.ts
packages/kui-builder/examples/plugin-sample/src/test/sample/sample-test.ts
plugins/plugin-core-support/src/plugin.ts

chore: add types to sample plugin

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/models/basicModels.ts
packages/app/src/webapp/models/table.ts
packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/controller/contexts.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts

chore(plugins/plugin-k8s): port k8s tables to new table module

---

plugins/plugin-bash-like/src/pty/client.ts

fix(plugins/plugin-bash-like): nano versus pty

---

packages/app/tests/lib/ui.js
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/new-tab.ts

fix(plugins/plugin-core-support): PTY content escapes to new tabs

---

packages/app/src/test/core/basic-functionality.ts
packages/app/web/css/ui.css
packages/kui-builder/npmrc
packages/kui-builder/package.json
plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
plugins/plugin-bash-like/src/test/bash-like/vi.ts
plugins/plugin-openwhisk/src/test/openwhisk3/paste.ts

chore(packages/kui-builder): electron 5

---

plugins/plugin-bash-like/src/pty/client.ts

feat(plugins/plugin-bash-like): linkify links in PTY output

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/gruvbox-dark-medium.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/lucario.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/solarized-dark.css
plugins/plugin-bash-like/src/pty/client.ts

fix(plugins/plugin-bash-like): poor PTY text selection color

---

packages/app/web/css/ui.css

fix(packages/app): ls files should render with normal text

---

packages/app/src/models/command.ts
plugins/plugin-openwhisk/src/lib/cmds/actions/invoke.ts
plugins/plugin-openwhisk/src/lib/models/synonyms.ts
plugins/plugin-openwhisk/src/plugin.ts

chore(plugins/plugin-openwhisk): add types to openwhisk invoke command

---

plugins/plugin-openwhisk/src/lib/cmds/actions/invoke.ts

Fixes #370
Signed-off-by: Joshua Auerbach <josh@nimbella.com>

fix(plugin-openwhisk): invoke -r should block

---

plugins/plugin-bash-like/package.json
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts

fix(plugins/plugin-bash-like): improve PTY race conditions

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): fixes for empty row handling in pty

---

packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css

white and black are inverted
Fixes #1286

fix(packages/kui-builder): light theme versus pty

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/models/table.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/view/formatMultiTable.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-k8s/src/lib/view/modes/status.ts
plugins/plugin-k8s/src/test/k8s/deployment.ts

fix(plugins/plugin-k8s): fix kubectl table regression in sidecar

---

packages/app/web/css/ui.css

fix(packages/app): fix sidecar multi-table ui

---

package.json

```
```
*component* optionally is the name of the module you are fixing; either "core" or a named module in `plugins/` directory. Note: Please specify the full name of the module (e.g. plugin-bash-like) instead of abbreviation. It helps us generate the correct CHANGELOG.md.
Thanks!

style: task npm start

---

packages/app/src/models/command.ts
plugins/plugin-grid/src/lib/cmds/grid.ts
plugins/plugin-grid/src/lib/cmds/table.ts
plugins/plugin-grid/src/lib/util.ts
plugins/plugin-grid/src/plugin.ts

feat(plugins/plugin-grid): add more types

---

packages/app/src/core/userdata.ts
packages/app/src/models/history.ts
packages/app/src/models/store.ts
packages/app/src/webapp/util/inject.ts
packages/kui-builder/dist/webpack/package-lock.json
packages/kui-builder/dist/webpack/package.json
packages/kui-builder/dist/webpack/webpack.config.js
plugins/plugin-core-support/src/lib/cmds/zoom.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/auth.ts
plugins/plugin-k8s/src/lib/util/discovery/kubeconfig.ts
plugins/plugin-k8s/src/plugin.ts
plugins/plugin-openwhisk/src/lib/models/auth.ts
plugins/plugin-openwhisk/src/lib/models/namespace.ts
plugins/plugin-proxy-support/src/lib/proxy-executor.ts

feat: allow for client-provided localStorage impl

---

docs/CODE_OF_CONDUCT.md

docs: Add Code of Conduct

---

docs/CODEOWNERS

docs: Add code owners

---

plugins/plugin-tutorials/src/lib/cmds/get.ts
plugins/plugin-tutorials/src/lib/cmds/list.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts
plugins/plugin-tutorials/src/lib/cmds/shortcuts.ts
plugins/plugin-tutorials/src/plugin.ts

feat(plugins/plugin-tutorial): add more types

---

packages/app/package.json
packages/kui-builder/package.json
packages/tests/package.json
plugins/plugin-grid/package.json
plugins/plugin-grid/src/lib/cmds/table.ts
plugins/plugin-k8s/package.json
plugins/plugin-openwhisk-debug/package.json
plugins/plugin-openwhisk/package.json
plugins/plugin-tutorials/package.json
plugins/plugin-wrk/package.json
plugins/plugin-wskflow/package.json

including electron 5.0.1
Fixes #1311

chore: bump npm versions

---

README.md

docs:  README.md installation section tweak 

---

packages/kui-builder/dist/webpack/build.sh

chore: make docker build optional for webpack builder

---

plugins/plugin-bash-like/src/pty/channel.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/pty/websocket-channel.ts

chore(plugins/plugin-bash-like): refactor pty to isolate WebSocket code

---

packages/app/src/webapp/views/sidecar.ts
packages/app/templates/index.html
packages/kui-builder/dist/webpack/webpack.config.js
packages/proxy/Dockerfile
packages/proxy/bin/run-proxy.sh
packages/proxy/build.sh
plugins/plugin-editor/package.json
plugins/plugin-editor/src/lib/init/esm.ts
plugins/plugin-editor/src/lib/open.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts

fix: webpack versus editor

---

packages/app/web/css/ui.css

fix(packages/app): fix for sidecar header overflow on firefox

---

packages/kui-builder/tslint.json

style: disable tslint rule: strict-type-predicates

---

plugins/plugin-k8s/src/lib/view/modes/status.ts

fix(plugins/plugin-k8s): k status tab versus webpack+proxy

---

plugins/plugin-editor/src/lib/init/defaults.ts
plugins/plugin-editor/src/lib/open.ts

fix(plugins/plugin-editor): editor plugin hard-wires font size

---

packages/app/templates/index.html
plugins/plugin-editor/src/lib/init/esm.ts

fix: expose webpack hash to plugins

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-editor/src/lib/open.ts

also fixes a recent regression with editor relayout versus sidecar toggle
Fixes #1317

fix: editor swallows escape sidecar toggle

---

plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): add left-pad for alt buffer mode

---

plugins/plugin-core-support/src/lib/cmds/help.ts
plugins/plugin-core-support/src/lib/cmds/zoom.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/preload.ts

also adds more types to plugin-core-support
Fixes #1357

fix(plugins/plugin-core-support): font zooming versus shift key

---

packages/app/src/main/spawn-electron.ts

clicking on the mac dock icon will open a new window, if you have previously closed a window, even if you still have one open
Fixes #1316

fix(packages/app): mac activate handling issues

---

packages/app/web/css/ui.css

fix(packages/app): stop disabling default font smoothing policy

---

packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/theme.json

feat: use system fonts

---

plugins/plugin-tekton/package.json
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/plugin.ts
plugins/plugin-wskflow/src/lib/flowCommand.ts
plugins/plugin-wskflow/src/lib/graph2doms.ts
plugins/plugin-wskflow/src/lib/inject.ts
plugins/plugin-wskflow/src/lib/preview.ts
plugins/plugin-wskflow/src/lib/visualize.ts
plugins/plugin-wskflow/src/plugin.ts
plugins/plugin-wskflow/web/css/wskflow.css

feat(plugins-plugin-tekton): intial tekton pipeline views

---

packages/app/web/css/ui.css
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/lib/cmds/git-diff.ts
plugins/plugin-bash-like/src/lib/cmds/git-status.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-bash-like/src/lib/cmds/open.ts
plugins/plugin-bash-like/src/plugin.ts
plugins/plugin-bash-like/src/pty/server.ts

fix(plugins/plugin-bash-like): ls should support sorting by size

---

plugins/plugin-bash-like/package.json

chore(plugins/plugin-bash-like): update to final xterm 3.13

---

plugins/plugin-wskflow/package.json

chore(plugins/plugin-wskflow): pin floating debug dependence in wskflow

---

plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/new-tab.ts

fix(plugins/plugin-core-support): per-tab state

---

plugins/plugin-wskflow/src/lib/preview.ts

fix(plugins/plugin-wskflow): don't override bash "source" command

---

plugins/plugin-core-support/src/lib/cmds/quit.ts
plugins/plugin-core-support/src/test/core-support/new-tab.ts

fix(plugins/plugin-core-support): exit command should close tab

---

packages/app/web/css/ui.css

fix(packages/app): repl input should use normal font weight

---

plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/new-tab.ts

fix(plugins/plugin-core-support): new tab from pty active tab

---

packages/app/src/core/repl.ts
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/test/bash-like/cd.ts

fix: cd versus spaces and backslash escape

---

plugins/plugin-bash-like/src/lib/cmds/git-status.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css
plugins/plugin-openwhisk/src/test/openwhisk3/local.ts

fix(plugins/plugin-bash-like): fixes for pty buggy scrollbars

---

plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/lib/cmds/catchall.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-bash-like/src/test/bash-like/cd.ts

fix(plugins/plugins-bash-like): ls versus whitespace and trailing slash

---

plugins/plugin-tekton/package.json

fix(plugins/plugin-tekton): pin deps for tekton

---

plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-core-support/src/test/core-support/tab-completion.ts

fix(plugins/plugin-core-support): tab completion versus spaces

---

packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

this eliminates the "horizontal landing zone" drag region
Fixes #1399

fix: improved pty alt buffer mode

---

plugins/plugin-editor/src/test/editor/edit.ts

fix(plugins/plugin-editor): editor test race condition

---

docs/dev/README.md
packages/tests/bin/runMochaLayers.sh
plugins/plugin-openwhisk/tests/lib/openwhisk/openwhisk.js

Thanks to Minikube I can run them with a couple of little changes. Now I need help with this one, which is failing. Any idea?
Thanks :)

style: test working locally

---

plugins/plugin-editor/src/lib/open.ts
plugins/plugin-editor/src/test/editor/edit.ts
plugins/plugin-k8s/src/lib/clients/kiali.ts
plugins/plugin-k8s/src/lib/controller/auth.ts
plugins/plugin-k8s/src/lib/controller/istio.ts
plugins/plugin-k8s/src/lib/controller/kedit.ts
plugins/plugin-k8s/src/lib/controller/kiali.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/test/k8s2/kedit.ts
plugins/plugin-k8s/tests/data/k8s/single-paragraph.yaml
plugins/plugin-k8s/tests/data/k8s/trailing-dash-dash-dash.yaml
plugins/plugin-k8s/web/css/main.css

fix(plugins/plugin-k8s): kedit versus empty final paragraph yamls

---

plugins/plugin-bash-like/src/pty/server.ts

feat(plugins/plugin-bash-like): set KUI env var for bash subprocesses

---

plugins/plugin-bash-like/src/pty/client.ts
tools/travis/test/test.d/typecov.sh

fix(plugins/plugin-bash-like): new tab versus alt buffer race fix

---

CONTRIBUTING.md
docs/pull_request_template.md

docs: add the contribution checklist to the pull request template

---

docs/dev/README.md

docs: tweak the local testing instruction in docs/dev/README

---

packages/app/web/css/left-tab-stripe.css

fix(packages/app): missing right-pad on tables

---

plugins/plugin-openwhisk/src/lib/cmds/auth.ts

fix(plugins/plugin-openwhisk): port wsk auth list to the table model

---

packages/app/tests/lib/ui.d.ts

fix(packages/app): eliminate some any types from ui.d.ts

---

packages/app/web/css/ui.css
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-wskflow/src/lib/graph2doms.ts
plugins/plugin-wskflow/web/css/wskflow.css

feat(plugins/plugin-tekton): tekton support for step visualization

---

packages/app/src/webapp/bottom-stripe.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-wskflow/src/lib/preview.ts
plugins/plugin-wskflow/src/lib/util.ts

fix: improvements for wskflow zoom buttons

---

README.md

fix: typo in link for lernaJs ( badge )

---

docs/pull_request_template.md

docs: fixed incorrect pointer in pull_request_template

---

packages/app/web/css/ui.css

fix(packages/app): code-style text in repl is too small

---

plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/test/k8s1/create-pod.ts

feat(plugins/plugin-k8s): improve support for kubectl --filename

---

packages/app/src/models/execOptions.ts
packages/app/src/webapp/bottom-stripe.ts
plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/view/modes/registrar.ts
plugins/plugin-tekton/src/lib/controller/get/step.ts
plugins/plugin-tekton/src/lib/controller/get/task.ts
plugins/plugin-tekton/src/lib/read.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/model/flowMode.ts
plugins/plugin-tekton/src/model/resource.ts
plugins/plugin-tekton/src/preload.ts

feat: improved support for custom k8s modes

---

plugins/plugin-k8s/src/lib/util/log-parser.ts

feat(plugins/plugin-k8s): improve k8s log parsing

---

plugins/plugin-tekton/src/controller/get/step.ts
plugins/plugin-tekton/src/controller/get/task.ts
plugins/plugin-tekton/src/controller/preview.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/model/flowMode.ts
plugins/plugin-tekton/src/plugin.ts
plugins/plugin-tekton/src/preload.ts
plugins/plugin-tekton/src/view/flow.ts

chore(plugins/plugin-tekton): code cleanup for plugin-tekton

---

packages/app/templates/index.html
packages/app/web/css/left-tab-stripe.css

feat(packages/app): add tooltips to new tab and theme buttons

---

packages/app/src/core/find-file.ts
plugins/plugin-apache-composer/src/preload.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-tekton/samples/@demos/tekton/pipeline.yaml
plugins/plugin-tekton/samples/@demos/tekton/pipeline2.yaml
plugins/plugin-tekton/samples/@demos/tekton/simple.yaml
plugins/plugin-tekton/src/preload.ts

also update findFile to support subdirectories for specials, and plugins offering a default viewer for files in their special directories
Fixes #1499

feat: add tekton sample inputs

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-tekton/src/view/flow.ts

feat(plugins/plugin-tekton): add Runnable badge to tekton flow view

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

fix: pty versus resize fixes

---

plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/test/k8s2/helm-repo-add-and-search.ts

feat(plugins/plugin-k8s): improved helm search output

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
plugins/plugin-core-support/src/lib/repl-focus.ts

chore: remove more uses of global tab

---

plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): pty stays stuck at last fixed width

---

plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): another fix for stale pty width

---

plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): pty vs inverted colors and light mode

---

packages/app/src/core/usage-error.ts
packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): pty sizing and resizing issues

---

.vscode/extensions.json

style: add ESLint plugin as VSCode recommendation

---

.eslintrc.json
packages/app/src/models/ReplResponse.ts
packages/app/src/webapp/cli.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts

style: fix @typescript-eslint/no-empty-interface rule

---

.eslintrc.json
packages/app/src/core/capabilities.ts
packages/app/src/core/plugins.ts
packages/app/src/core/repl.ts
packages/app/src/core/userdata.ts
packages/app/src/core/utility.ts
packages/app/src/models/command.ts
packages/app/src/models/execOptions.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-bash-like/src/lib/cmds/git-status.ts
plugins/plugin-k8s/src/lib/util/selectors.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts

style: fix @typescript-eslint/no-var-requires rule

---

plugins/plugin-tekton/src/lib/tekton2graph.ts

style: fix @typescript-eslint/prefer-interface rule

---

.eslintrc.json
plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts
plugins/plugin-apache-composer/src/test/composer3/session-list-scanlimit.ts
plugins/plugin-apache-composer/src/test/composer3/session-list.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-tutorials/src/lib/cmds/list.ts
plugins/plugin-wrk/src/lib/chart.ts
plugins/plugin-wrk/src/lib/history-table.ts

style: fix comma-spacing rule

---

.eslintrc.json
packages/app/src/core/plugin-assembler.ts
packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/views/sidecar.ts

style: fix standard/object-curly-even-spacing rule

---

.eslintrc.json
plugins/plugin-wrk/src/lib/history.ts

style: Remove key-spacing rule

---

.eslintrc.json
plugins/plugin-apache-composer/src/test/composer1/composer-viz.ts
plugins/plugin-k8s/src/lib/model/states.ts

style: fix standard/array-bracket-even-spacing rule

---

.eslintrc.json
plugins/plugin-apache-composer/src/lib/controller/cmd/session-get.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/session-list.ts
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-apache-composer/src/test/composer2/composer-create.ts
plugins/plugin-apache-composer/src/test/composer3/session-list-limit.ts
plugins/plugin-apache-composer/src/test/composer3/session-list-scanlimit.ts
plugins/plugin-apache-composer/src/test/composer3/session-list.ts
plugins/plugin-core-support/src/preload.ts
plugins/plugin-openwhisk/src/test/openwhisk2/edit-new.ts
plugins/plugin-tutorials/src/lib/cmds/get.ts
plugins/plugin-wrk/src/lib/graphics.ts
plugins/plugin-wskflow/src/lib/graph2doms.ts
plugins/plugin-wskflow/src/lib/preview.ts

style: Remove no-multi-spaces rule

---

.eslintrc.json
plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts

style: Remove block-spacing rule

---

.eslintrc.json
packages/app/src/main/headless.ts
plugins/plugin-k8s/src/lib/controller/kedit.ts

style: Remove no-unreachable rule

---

.eslintrc.json
packages/app/src/util/mimic-dom.ts
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts

style: Remove eqeqeq rule

---

packages/app/src/webapp/models/basicModels.ts
packages/app/src/webapp/models/table.ts
packages/app/src/webapp/views/diffTable.ts
packages/app/src/webapp/views/table.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts

feat: watchable table

---

plugins/plugin-k8s/src/lib/view/formatTable.ts

fix(plugins/plugin-k8s): k get all shows "ALL" for each subtable

---

.eslintrc.json
plugins/plugin-bash-like/src/lib/util/markdown.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-openwhisk/src/lib/models/auth.ts
plugins/plugin-openwhisk/src/test/openwhisk3/run.ts
plugins/plugin-wrk/src/lib/openwhisk.ts
plugins/plugin-wrk/src/lib/util.ts

style: Remove node/no-deprecated-api rule

---

packages/app/src/core/repl.ts
packages/app/src/models/execOptions.ts
packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts

fix(plugins/plugin-core-support): reverse-i-search bugs

---

.eslintrc.json
plugins/plugin-k8s/src/lib/controller/kubectl.ts

style: fix promise/param-names rule

---

.eslintrc.json
plugins/plugin-tutorials/src/lib/cmds/play.ts

style: fix no-eval rule

---

.eslintrc.json
packages/app/src/core/repl.ts
packages/app/src/webapp/views/table.ts
plugins/plugin-k8s/src/lib/util/util.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-usage.ts
plugins/plugin-tutorials/src/lib/cmds/list.ts
plugins/plugin-tutorials/src/lib/cmds/modes.ts
plugins/plugin-tutorials/src/lib/usage.ts

style: fix object-property-newline rule

---

.eslintrc.json
plugins/plugin-apache-composer/src/lib/utility/sample-inputs.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/util/util.ts
plugins/plugin-k8s/src/lib/view/formatEntity.ts
plugins/plugin-tutorials/src/lib/cmds/get.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts

style: fix space-infix-ops rule

---

packages/app/src/webapp/views/sidecar.ts
plugins/plugin-editor/src/lib/util.ts

fix(plugins/plugin-editor): fixed the zooming issue in monaco-editor

---

.eslintrc.json
packages/app/src/core/plugins.ts
packages/app/src/core/repl.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/util/ascii-to-table.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/lib/repl-focus.ts
plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-k8s/src/lib/controller/contexts.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/util/discovery/kubeconfig.ts
plugins/plugin-k8s/src/lib/view/form.ts
plugins/plugin-k8s/src/lib/view/formatTable.ts
plugins/plugin-openwhisk-debug/src/plugin.ts
plugins/plugin-tutorials/src/lib/cmds/list.ts
plugins/plugin-tutorials/src/lib/cmds/wskflow.ts
plugins/plugin-wskflow/src/lib/graph2doms.ts

style: fix operator-linebreak rule

---

plugins/plugin-tekton/src/lib/success.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/model/fetch.ts
plugins/plugin-tekton/src/model/modes/flow.ts
plugins/plugin-tekton/src/model/modes/trace.ts
plugins/plugin-tekton/src/model/resource.ts
plugins/plugin-tekton/src/preload.ts

this generalizes the trace view that is in the openwhisk plugin; temporarily, the generalized view will be housed in plugin-tekton, until it stabilizes; then we should move it to the core, as it is a generally useful view
Fixes #1580

feat(plugins/plugin-tekton): tekton trace view

---

.eslintrc.json
packages/app/src/core/command-tree.ts
packages/app/src/core/oops.ts
packages/app/src/core/repl.ts
packages/app/src/core/usage-error.ts
packages/app/src/main/main.ts
packages/app/src/models/errors.ts
packages/app/src/util/types.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-openwhisk/src/lib/cmds/auth.ts
plugins/plugin-openwhisk/src/test/openwhisk3/popup.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/model/modes/run.ts
plugins/plugin-wskflow/src/lib/fsm2graph.ts

style: fix no-unneeded-ternary rule

---

.eslintrc.json
plugins/plugin-openwhisk/src/lib/cmds/auth.ts
plugins/plugin-wrk/src/lib/scriptgen.ts

style: fix no-template-curly-in-string rule

---

.eslintrc.json
packages/app/src/core/repl.ts
plugins/plugin-k8s/src/lib/model/states.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts
plugins/plugin-openwhisk-debug/src/plugin.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts

style: fix space-unary-ops rule

---

.eslintrc.json
packages/app/src/core/repl.ts
packages/app/src/webapp/util/inject.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-config.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-create.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-delete.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/app-invoke.ts
plugins/plugin-apache-composer/src/lib/controller/cmd/session-list.ts
plugins/plugin-apache-composer/src/lib/utility/compile.ts
plugins/plugin-apache-composer/src/test/composer2/composer-create.ts
plugins/plugin-apache-composer/src/test/composer2/composer-headless.ts
plugins/plugin-apache-composer/src/test/composer3/session-list.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-bash-like/src/pty/server.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/util/log-parser.ts
plugins/plugin-k8s/src/lib/util/retry.ts
plugins/plugin-k8s/src/test/k8s1/deployment.ts
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts
plugins/plugin-tutorials/src/lib/cmds/api.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts
plugins/plugin-tutorials/src/lib/cmds/wskflow.ts
plugins/plugin-wrk/src/lib/openwhisk.ts
plugins/plugin-wskflow/src/lib/flowCommand.ts

style: fix padded-blocks rule

---

packages/app/tests/lib/common.js
plugins/plugin-openwhisk/tests/lib/openwhisk/openwhisk.js

test: disable mocha.it retries in local testing

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css

fix(plugins/plugin-bash-like): improve reflow of pty output

---

packages/app/src/webapp/cli.ts

fix(packages/app): pageup/pagedown scroll more than one more

---

.eslintrc.json
plugins/plugin-apache-composer/src/lib/controller/cmd/session-get.ts
plugins/plugin-bash-like/src/lib/cmds/git-commit.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-k8s/src/lib/controller/auth.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts

style: fix prefer-promise-reject-errors rule

---

.eslintrc.json
plugins/plugin-tutorials/src/lib/cmds/list.ts

style: fix no-constant-condition rule

---

.eslintrc.json
packages/app/src/core/command-tree.ts
packages/app/src/core/usage-error.ts
packages/app/src/main/headless-pretty-print.ts
packages/app/src/webapp/util/ascii-to-usage.ts
packages/app/src/webapp/views/show-options.ts
plugins/plugin-bash-like/src/pty/channel.ts
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/util/util.ts
plugins/plugin-openwhisk/src/lib/models/namespace.ts
plugins/plugin-wskflow/src/lib/preview.ts

style: fix no-useless-constructor rule

---

plugins/plugin-tutorials/.eslintrc.json
plugins/plugin-tutorials/src/lib/cmds/get.ts
plugins/plugin-tutorials/src/lib/cmds/list.ts
plugins/plugin-tutorials/src/lib/cmds/modes.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts
plugins/plugin-tutorials/src/lib/usage.ts
plugins/plugin-tutorials/src/preload.ts

style(plugins-tutorials): lint unused-vars

---

plugins/plugin-openwhisk-editor-extensions/.eslintrc.json
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts
plugins/plugin-openwhisk-editor-extensions/src/plugin.ts
plugins/plugin-openwhisk-editor-extensions/src/preload.ts

style(plugins-openwhisk-editor-extensions): unused

---

.eslintrc.json
packages/app/src/webapp/cli.ts
packages/app/src/webapp/util/inject.ts
plugins/plugin-core-support/src/lib/cmds/history/reverse-i-search.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts

style: fix no-useless-return rule

---

packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/util/ascii-to-table.ts
packages/app/src/webapp/views/sidecar.ts
packages/app/src/webapp/views/table.ts
packages/app/web/css/ui.css
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-k8s/src/lib/view/modes/registrar.ts
plugins/plugin-tekton/src/model/modes/logs.ts
plugins/plugin-tekton/src/model/modes/run.ts
plugins/plugin-tekton/src/model/modes/trace.ts
plugins/plugin-tekton/src/model/resource.ts
plugins/plugin-tekton/src/preload.ts

plus some core and k8s enhancements to help
depends on #1608
Fixes #1609

feat: tekton log navigation support

---

packages/app/src/webapp/cli.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts
plugins/plugin-k8s/src/test/k8s1/helm.ts

fix(plugins/plugin-k8s): fixed missing notes of helm status

---

tools/travis/test/test.d/typecov.sh

test: ensure bc exists for typecov check in travis

---

.travis.yml

chore: add services: docker to travis.yml

---

plugins/plugin-openwhisk-debug/.eslintrc.json
plugins/plugin-openwhisk-debug/src/plugin.ts

style(plugins-openwhisk-debug): lint unused vars

---

plugins/plugin-grid/.eslintrc.json
plugins/plugin-grid/src/lib/cmds/grid.ts
plugins/plugin-grid/src/lib/cmds/table.ts
plugins/plugin-grid/src/lib/grouping.ts
plugins/plugin-grid/src/lib/legend.ts
plugins/plugin-grid/src/lib/util.ts
plugins/plugin-grid/src/test/grid/timeline.ts

style(plugins-grid): lint unused-vars

---

plugins/plugin-core-support/.eslintrc.json
plugins/plugin-core-support/src/lib/admin/updater.ts
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-core-support/src/lib/cmds/echo.ts
plugins/plugin-core-support/src/lib/cmds/help.ts
plugins/plugin-core-support/src/lib/cmds/history/history.ts
plugins/plugin-core-support/src/lib/cmds/open-ui-from-terminal.ts
plugins/plugin-core-support/src/lib/cmds/prompt.ts
plugins/plugin-core-support/src/lib/cmds/run.ts
plugins/plugin-core-support/src/lib/cmds/screenshot.ts
plugins/plugin-core-support/src/lib/cmds/sleep.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/lib/repl-focus.ts
plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-core-support/src/lib/text-search.ts
plugins/plugin-core-support/src/test/core-support/base64.ts
plugins/plugin-core-support/src/test/core-support/clear.ts
plugins/plugin-core-support/src/test/core-support/help.ts
plugins/plugin-core-support/src/test/core-support/history.ts
plugins/plugin-core-support/src/test/core-support/screenshot.ts
plugins/plugin-core-support/src/test/core-support/tab-completion.ts
plugins/plugin-core-support/src/test/core-support/text-search.ts
plugins/plugin-core-support/src/test/core-support/theme.ts

style(plugins-core-support): lint unused-vars

---

docs/dev/README.md
docs/dev/local-testing.md

docs: fix some broken links in docs/dev/README.md

---

packages/app/src/webapp/util/ascii-to-table.ts
packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
plugins/plugin-bash-like/src/pty/client.ts

also a few related fixes to table CSS for overflow-x
Fixes #1572

fix: improvements to ascii-to-table

---

packages/kui-builder/package.json

chore: update lint package versions

---

plugins/plugin-tutorials/src/lib/cmds/list.ts
plugins/plugin-wrk/.eslintrc.json
plugins/plugin-wrk/src/lib/chart.ts
plugins/plugin-wrk/src/lib/graphics.ts
plugins/plugin-wrk/src/lib/history-table.ts
plugins/plugin-wrk/src/lib/init.ts
plugins/plugin-wrk/src/lib/lt.ts
plugins/plugin-wrk/src/lib/theme.ts
plugins/plugin-wrk/src/plugin.ts

style(plugins-wrk): lint unused-vars

---

.eslintrc.json
plugins/plugin-apache-composer/.eslintrc.json
plugins/plugin-bash-like/.eslintrc.json
plugins/plugin-core-support/.eslintrc.json
plugins/plugin-editor/.eslintrc.json
plugins/plugin-grid/.eslintrc.json
plugins/plugin-manager/src/.eslintrc.json
plugins/plugin-openwhisk-debug/.eslintrc.json
plugins/plugin-openwhisk-editor-extensions/.eslintrc.json
plugins/plugin-proxy-support/.eslintrc.json
plugins/plugin-tutorials/.eslintrc.json
plugins/plugin-wrk/.eslintrc.json
plugins/plugin-wskflow/.eslintrc.json

style: unify eslintrc setup files

---

packages/app/web/css/left-tab-stripe.css
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css

Fixes #1653
Fixes #1652
Fixes #1651

fix: for a few minor UI glitches

---

.eslintrc.json
plugins/plugin-tekton/src/controller/get/step.ts
plugins/plugin-tekton/src/controller/get/task.ts
plugins/plugin-tekton/src/controller/preview.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/model/modes/flow.ts
plugins/plugin-tekton/src/model/modes/logs.ts
plugins/plugin-tekton/src/model/modes/run.ts
plugins/plugin-tekton/src/model/modes/trace.ts
plugins/plugin-tekton/src/preload.ts
plugins/plugin-tekton/src/view/flow.ts

style(plugin-tekton): lint unused-vars

---

.eslintrc.json
packages/kui-builder/examples/plugin-sample/src/lib/cmds/create-echo.ts
packages/kui-builder/examples/plugin-sample/src/lib/cmds/open-sidecar.ts
packages/kui-builder/examples/plugin-sample/src/lib/cmds/say-hello.ts
packages/kui-builder/src/kui-dist-init.ts

style(packages/kui-builder): lint unused-vars

---

packages/app/src/webapp/cli.ts
packages/app/web/css/ui.css
packages/kui-builder/examples/build-configs/default/theme/css/themes/light.css
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/web/css/xterm.css
plugins/plugin-core-support/src/preload.ts

fix: remove UI inconsistencies with cursor block

---

packages/app/web/css/ui.css

fix(packages/app): minimized sidecar vertical text outflow

---

packages/app/src/models/entity.ts
packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/views/modes/registrar.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-k8s/src/lib/controller/describe.ts
plugins/plugin-k8s/src/lib/controller/kedit.ts
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/model/resource.ts
plugins/plugin-k8s/src/lib/view/modes/conditions.ts
plugins/plugin-k8s/src/lib/view/modes/containers.ts
plugins/plugin-k8s/src/lib/view/modes/last-applied.ts
plugins/plugin-k8s/src/lib/view/modes/pods.ts
plugins/plugin-k8s/src/preload.ts
plugins/plugin-tekton/src/preload.ts

chore: move sidecar view registrar to core

---

.travis.yml
packages/kui-builder/dist/webpack/bin/webpack-client.sh
packages/kui-builder/dist/webpack/build-docker.sh
packages/proxy/Dockerfile.http
packages/proxy/app/bin/www
packages/proxy/build-docker.sh
packages/proxy/build.sh
tools/travis/test/target.d/webpack.sh

test: travis test proxy build with http

---

packages/app/src/core/command-tree.ts
packages/app/src/core/repl.ts
packages/app/src/models/command.ts
packages/app/templates/index.html
packages/app/web/css/top-tab-stripe.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/text-search.ts

feat: top tab stripe

---

packages/app/src/core/settings.ts
packages/app/src/main/menu.ts
packages/app/src/test/core/about.ts
packages/app/web/css/top-tab-stripe.css
packages/kui-builder/examples/build-configs/default/theme/theme.json
plugins/plugin-core-support/src/lib/cmds/about/about.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts

fix(packages/app): remove stale entries from OS Help menu

---

plugins/plugin-tutorials/samples/@tutorials/getting-started/tutorial.json

1) refine intro paragraph
2) add themes to Next Steps
Fixes #1705

fix(plugins/plugin-tutorials): getting started updates

---

plugins/plugin-k8s/src/lib/view/modes/last-applied.ts
plugins/plugin-k8s/src/preload.ts

style: remove unused imports

---

.eslintrc.json
packages/app/src/webapp/query.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/compose.ts
plugins/plugin-openwhisk-editor-extensions/src/lib/cmds/new.ts

style: fix no-lone-blocks rule

---

.eslintrc.json
plugins/plugin-bash-like/src/lib/util/ascii-key-value-to-table.ts

style: fix no-cond-assign rule

---

packages/app/templates/index.html
packages/app/web/css/top-tab-stripe.css
plugins/plugin-core-support/src/lib/cmds/theme.ts
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/theme.ts

feat(packages/app): remove theme button from UI

---

packages/app/src/main/menu.ts

fix(packages/app): linux OS menu items do not work

---

.eslintrc.json
packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/cli.ts
packages/app/src/webapp/views/sidecar.ts
plugins/plugin-grid/src/lib/util.ts
plugins/plugin-k8s/src/lib/util/created-on.ts
plugins/plugin-openwhisk/src/lib/models/withHeader.ts
plugins/plugin-tutorials/src/lib/cmds/modes.ts
plugins/plugin-tutorials/src/lib/cmds/play.ts
plugins/plugin-wrk/src/lib/openwhisk.ts

style: fix no-mixed-operators rule

---

packages/app/src/webapp/cli.ts
packages/app/src/webapp/prompt.ts
packages/app/templates/index.html
packages/app/web/css/ui.css
plugins/plugin-openwhisk/src/test/openwhisk2/auth.ts
plugins/plugin-openwhisk/src/test/openwhisk4/let.ts
plugins/plugin-openwhisk/src/test/openwhisk4/zip.ts

plus a few other minor refinements
Fixes #1727

feat(packages/app): show cwd in prompt

---

packages/kui-builder/package.json
plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-core-support/src/test/core-support/tab-completion.ts
plugins/plugin-core-support/src/tests/lib/tab-completion-util.ts
plugins/plugin-core-support/web/css/tab-completion.css
plugins/plugin-k8s/src/lib/controller/kubectl.ts
plugins/plugin-k8s/src/lib/tab-completion.ts
plugins/plugin-k8s/src/preload.ts
plugins/plugin-k8s/src/test/k8s1/tab-completion.ts
plugins/plugin-k8s/tests/data/k8s/tab-completion-2.yaml
plugins/plugin-k8s/tests/data/k8s/tab-completion.yaml
plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts

feat(plugins/plugin-k8s): tab completion

---

packages/app/web/css/ui.css

fix(packages/app): increase spacing between repl blocks

---

plugins/plugin-bash-like/src/lib/tab-completion/git.ts
plugins/plugin-bash-like/src/preload.ts
plugins/plugin-bash-like/src/test/bash-like/git-tab-completion.ts
plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-core-support/web/css/tab-completion.css
plugins/plugin-k8s/src/lib/tab-completion.ts

plus some cleanup to tab completion core code and core UI
Fixes #1735

feat: git branch tab completion

---

plugins/plugin-bash-like/src/pty/client.ts
plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts

fix(plugins/plugin-bash-like): pty output with many rows can cause hang

---

packages/app/templates/index.html
packages/app/web/css/top-tab-stripe.css
plugins/plugin-core-support/src/lib/new-tab.ts
plugins/plugin-core-support/src/test/core-support/new-tab.ts

feat: tab close button

---

.eslintrc.json
packages/app/src/core/usage-error.ts
packages/app/src/webapp/util/ascii-to-usage.ts
packages/app/src/webapp/util/search.ts
plugins/plugin-bash-like/src/test/bash-like/cd.ts
plugins/plugin-k8s/src/lib/controller/auth.ts
plugins/plugin-k8s/src/lib/controller/status.ts
plugins/plugin-k8s/src/lib/view/helm-status.ts

style: fix no-useless-escape rule

---

.eslintrc.json
plugins/plugin-bash-like/src/pty/client.ts

style: fix no-control-regex rule

---

plugins/plugin-bash-like/package.json
plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
plugins/plugin-bash-like/src/lib/cmds/ls.ts
plugins/plugin-bash-like/src/lib/util/markdown.ts
plugins/plugin-bash-like/src/test/bash-like/cd.ts
plugins/plugin-bash-like/src/test/bash-like/git-tab-completion.ts
plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
plugins/plugin-core-support/src/lib/tab-completion.ts
plugins/plugin-tutorials/package.json

chore: remove unused vars

---

.eslintrc.json
packages/app/src/core/capabilities.ts
packages/app/src/webapp/bottom-stripe.ts
packages/app/src/webapp/views/table.ts
plugins/plugin-k8s/src/lib/clients/kiali.ts

style: fix no-return-assign rule

---

packages/app/web/css/top-tab-stripe.css

fix(packages/app): some small refinements to tab close button UI
