kubernetes-sigs/kui

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-patternfly4-themes/package.json
> chore: bump patternfly deps

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-kubectl/src/test/k8s3/replay.ts
> feat: preserve changes of table view state in Notebook

- packages/core/src/core/jobs/job.ts
- packages/core/src/core/jobs/watchable.ts
- packages/core/src/index.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-kubectl/src/controller/client/direct/watch.ts
- plugins/plugin-kubectl/src/test/k8s1/aaa-get-namespaces-with-watch-via-table.ts
Fixes #1747
https://user-images.githubusercontent.com/21212160/106631648-f0fc8b80-654a-11eb-90f2-d557f86e2e92.mov
> feat: pause and resume watchable jobs

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Fixes #6930
https://user-images.githubusercontent.com/21212160/106665657-9546f800-6574-11eb-9438-2de57462995f.mov
> fix(plugins/plugin-client-common): redirectToPlainSplitIfNeeded may favor smaller terminals

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): when there're 3 splits, clicking table in the first split will create the 4th split

- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
> fix(plugins/plugin-client-common): The pause watching icon should be grey

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
> fix(plugins/plugin-client-common): when there're 3 splits, clicking table cells in the first split fail

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
> fix(plugins/plugin-client-common): table clicks fail when the maximum number of splits is reached

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/krew/src/controller/popeye.ts
- plugins/plugin-kubectl/notebooks/popeye.json
- plugins/plugin-kubectl/src/non-headless-preload.ts
> feat(plugins/plugin-kubectl): popeye dashboard

- package.json
> chore: bump the top-level package.json version to 10.1.1

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-core-support/src/test/core-support2/history.ts
> feat(plugins/plugin-client-common): empty tables use PatternFly's "empty state" UI

- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableHeader.tsx
- plugins/plugin-client-common/src/components/Content/Table/sort.ts
- plugins/plugin-client-common/web/scss/components/Table/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-core-support/src/test/core-support2/history.ts
> fix(plugins/plugin-client-common): restore Table sorting

- plugins/plugin-bash-like/fs/src/lib/ls.ts
- plugins/plugin-bash-like/src/test/bash-like/ls.ts
> fix(plugins/plugin-bash-like): ls | grep or ls | wc do not work

- packages/core/src/repl/tab-completion.ts
- plugins/plugin-bash-like/fs/src/lib/tab-completion.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-client-test/src/preload.ts
- plugins/plugin-client-test/src/test/api2/tab-completion.ts
- plugins/plugin-core-support/src/index.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
- plugins/plugin-core-support/src/test/core-support2/tab-completion.ts
Fixes #6989
https://user-images.githubusercontent.com/21212160/107400493-db99db00-6acf-11eb-9cd3-94919adf4acc.mov
> feat(plugins/plugin-bash-like): tab-complete VFS mounts

- plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
Fixes #6993
https://user-images.githubusercontent.com/21212160/107414059-81087b00-6adf-11eb-8de2-5914b908823c.mov
> fix(plugins/plugin-client-common): Tab Completion view color codes partial completions if no slashes

- plugins/plugin-bash-like/fs/VFS_Architecture.md
> doc(plugins/plugin-bash-like): Document VFS Architecture

- packages/core/src/index.ts
- packages/core/src/models/tab-state.ts
- packages/core/src/util/home.ts
- plugins/plugin-bash-like/fs/src/lib/cd.ts
- plugins/plugin-bash-like/fs/src/plugin.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/test/bash-like/cd.ts
- plugins/plugin-bash-like/src/test/bash-like/export.ts
- plugins/plugin-bash-like/src/test/bash-like/replay.ts
- plugins/plugin-bash-like/src/test/bash-like/rerun.ts
- plugins/plugin-client-common/src/components/Client/StatusStripe/CurrentWorkingDirectory.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-test/src/test/api2/cd-vfs.ts
- plugins/plugin-client-test/src/test/api2/vfs.ts
- plugins/plugin-core-support/src/test/core-support/tab-management.ts
> feat: cd command handles VFS mounts

- plugins/plugin-bash-like/fs/src/lib/cd.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-client-test/src/test/api2/vfs.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
> fix: cd and ls don't always work against vfs

- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/fs/src/lib/head.ts
- plugins/plugin-bash-like/fs/src/lib/open.ts
- plugins/plugin-bash-like/fs/src/plugin.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-bash-like/src/test/bash-like/head.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
> feat: head command against vfs

- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
> fix(plugins/plugin-bash-like): change fslice's default bytes from 1MB to 4KB

- plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
Fixes #7036
pf4-dark:
carbon-gray90:
> fix: missing some theme alignment rules for pf-t-dark

- plugins/plugin-client-common/src/components/spi/Select/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Select/model.ts
> feat(plugins/plugin-client-common): add Select description and isDisabled props

- plugins/plugin-client-common/src/components/Client/StatusStripe/CurrentWorkingDirectory.tsx
- plugins/plugin-client-common/web/scss/components/Popover/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Popover/common.scss
> fix(plugins/plugin-client-common): make popover-select widget narrower

- plugins/plugin-kubectl/src/test/k8s3/run.ts
- plugins/plugin-kubectl/tests/data/k8s/job.yaml
- plugins/plugin-kubectl/tests/data/k8s/kubectl-exec.yaml
- plugins/plugin-kubectl/tests/data/k8s/kubectl-logs-two-containers.yaml
> test: leftover image pull from dockerhub

- NOTICE
> chore: add a CNCF CLA Notice for contributors who couldn't be reached

- README.md
> chore: add stars/forks badges to README.md

- plugins/plugin-client-notebook/src/index.tsx
- plugins/plugin-core-support/src/lib/cmds/replay.ts
> feat(plugins/plugin-core-support): replay --close-current-tab

- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
> fix(plugins/plugin-client-common): offline notebooks have unnecessary buttons

- packages/core/src/models/CommentaryResponse.ts
- packages/webpack/webpack.config.js
- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Card/model.ts
- plugins/plugin-client-common/src/controller/commentary.ts
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Card/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-notebook/README.md
- plugins/plugin-client-notebook/notebooks/readme.json
- plugins/plugin-client-notebook/src/index.tsx
- plugins/plugin-client-notebook/src/preload.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
plus improved support for baseUrl in Markdown
Fixes #7074
> feat: improved support for commentary-from-file

- package.json
> chore: bump top-level package.json to 10.2.0

- package-lock.json
- plugins/plugin-bash-like/package.json
> chore: bump to xterm-helpers 1.0.1

- NOTICE
> chore: update the NOTICE file to list contributors who haven't signed CLA

- NOTICE
> chore: update NOTICE file to reflect new CLA signers

- NOTICE
remove avery huang
Fixes #7098
> chore: update NOTICE to reflect recent CLA signers

- plugins/plugin-bash-like/fs/src/lib/head.ts
- plugins/plugin-bash-like/fs/src/lib/tail.ts
- plugins/plugin-bash-like/fs/src/plugin.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-bash-like/src/test/bash-like/head.ts
- plugins/plugin-bash-like/src/test/bash-like/tail.ts
WARNING: this PR does not yet support tail +N. We will need to fix that in a subsequent PR.
Fixes #7109
> feat(plugins/plugin-bash-like): support bash command tail against vfs

- plugins/plugin-client-common/web/css/static/sidecar-main.css
> fix(plugins/plugin-client-common): sidecar toolbar text can overflow

- plugins/plugin-core-support/src/lib/cmds/watch.ts
> fix(plugins/plugin-core-support): `watch ls` does not update the header

- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
> fix(plugins/plugin-client-common): in splits, spinner is not centered

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Experimental.scss
> fix(plugins/plugin-client-common): Experimental tag is not centered

- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_index.scss
reduces CPU consumption for large live tables
Fixes #7133
> fix(plugins/plugin-client-common): reduce animations in SequenceDiagram

- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
This PR also updates kubectl get-watch to take advantage of this bug fix, further batching up UI updates. This optimization wasn't possible prior to this bug fix, because LivePaginatedTable was handling update() calls in a pretty buggy fashion across calls to update().
Fixes #7137
> fix: LivePaginatedTable may drop updates

- package-lock.json
- packages/core/src/index.ts
- packages/core/src/webapp/models/table.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/test/bash-like/grammy.ts
- plugins/plugin-bash-like/tests/data/grammy1.txt
- plugins/plugin-bash-like/tests/data/grammy2.txt
- plugins/plugin-bash-like/tests/package.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Table/Histogram.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/Toolbar.tsx
- plugins/plugin-client-common/src/controller/grammy.ts
- plugins/plugin-client-common/src/plugin.ts
Fixes #7138
Example: 
`grammy plugins/plugin-bash-like/tests/data/grammy1.txt `,  
`grammy plugins/plugin-bash-like/tests/data/grammy* `
`watch grammy plugins/plugin-bash-like/tests/data/grammy*`
> feat: view table as histogram

- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Namespace.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
> feat(plugins/plugin-kubectl): Namespace Summary should summarize namespace resourecequota, if existing

- plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
> fix(plugins/plugin-client-common): spinner spacing regression

- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> fix(plugins/plugin-kubectl): clicking a namespace row will issue command with --ns undefined

- plugins/plugin-bash-like/fs/src/vfs/index.ts
> chore(plugins/plugin-bash-like): remove debug output from findMount

- packages/core/src/models/execOptions.ts
- plugins/plugin-client-common/src/controller/grammy.ts
- plugins/plugin-core-support/src/lib/cmds/watch.ts
> feat: cache files when watching a command

- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/test/bash-like/grammy.ts
- plugins/plugin-bash-like/tests/data/grammy1.txt
- plugins/plugin-client-common/src/controller/grammy.ts
> fix(plugins/plugin-client-common): improve the error-handling of grammy parsing histogram data

- .travis.yml
> chore: do not upload code cov report

- packages/core/src/index.ts
- packages/core/src/webapp/models/table.ts
- plugins/plugin-client-common/src/components/Content/Table/Histogram.tsx
- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-kubectl/src/controller/kubectl/watch/get-watch.ts
> fix: LivePaginatedTable.setBody can be very slow

- plugins/plugin-client-common/src/components/Content/Table/Histogram.tsx
Fixed by turning off the aniamte for now
Fixes #7193
> fix(plugins/plugin-client-common): histogram animate is slow with large data

- plugins/plugin-bash-like/src/test/bash-like/grammy.ts
- plugins/plugin-client-common/src/controller/grammy.ts
> fix(plugins/plugin-client-common): improve the error handling of grammy

- plugins/plugin-bash-like/fs/src/lib/glob.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
> chore: DirentStats should include mount

- OWNERS_ALIASES
> fix: invalid OWNER_ALIASES

- .github/workflows/test.yaml
- plugins/plugin-kubectl/src/test/k8s1/describe.ts
- tools/travis/install.sh
- tools/travis/microk8s.sh
> test: Github Actions

- packages/webpack/process.js
Fixes #7243 
This PR fixes a gap in our process shim for browser clients. before, we did only a tiny bit. this PR uses the process/browser npm to fill in the rest. We had process/browser specified as a fallback entry in our webpack config.
> fix(packages/webpack): improve process shim for browser-based builds

- package-lock.json
- packages/core/src/main/headless-pretty-print.ts
- packages/core/src/main/headless-support.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
git cherry-pick da66563567ff760bee25a6ce8738afda6d7f2bfb
[cherrypick4 34371bd8a] feat: improve streaming ansi support from controllers to UI
> feat: improve streaming ansi support from controllers to UI

- packages/core/src/models/entity.ts
git cherry-pick c827bef60882b8b3b36784a3feae6ee8f4ea679d
[cherrypick5 29be8ceab] chore(packages/core): remove static import of react in the core
Fixes #7219
> chore(packages/core): remove static import of react in the core

- packages/core/src/repl/exec.ts
> fix: ignore needsUI constraint if user is asking for help

- plugins/plugin-client-common/src/controller/grammy.ts
> fix(plugins/plugin-client-common): grammy command should enforce UI

- package-lock.json
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/plugin.ts
- plugins/plugin-core-support/i18n/resources_en_US.json
- plugins/plugin-core-support/package.json
- plugins/plugin-core-support/src/lib/cmds/grammy.ts
- plugins/plugin-core-support/src/plugin.ts
> fix: cannot invoke grammy from headless mode

- packages/core/src/main/headless-support.ts
> fix(packages/core): don't add \n for headless stderr printer

- plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-vi.ts
> test: kubectl-exec-vi test issue

- plugins/plugin-client-common/src/components/Content/Editor/lib/defaults.ts
> feat(plugins/plugin-client-common): enable monaco-editor word wrapping

- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
> feat: SequenceDiagram shows row's message in the throughput column

- plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
> chore(plugins/plugin-bash-like): remove grep, gzip and gunzip from vfs

- package-lock.json
- packages/core/package.json
- packages/core/src/core/usage/pretty-code.ts
- packages/core/src/core/usage/render-usage.ts
- packages/core/src/core/usage/types.ts
- packages/core/src/index.ts
> chore(packages/core): add support for pretty ascii usage

- plugins/plugin-client-common/web/css/static/ui.css
> fix(plugins/plugin-client-common): regression in Commentary margin

- packages/builder/dist/electron/builders/electron.js
- packages/builder/dist/electron/builders/notarize.js
- packages/builder/dist/electron/builders/sign.js
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> fix(packages/builder): macOS signing logic does not sign native modules

- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Client/props/Input.ts
- plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
- plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
> feat(plugins/plugin-client-common): Improve sass mixins

- packages/core/src/index.ts
- packages/core/src/webapp/util/bytes.ts
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
> feat(packages/core): export prettyPrintBytes function

- plugins/plugin-client-common/src/components/Views/Terminal/Block/FancyPipeline.tsx
> fix(plugins/plugin-client-common): FancyPipeline renders prefix incorrectly

- plugins/plugin-client-test/src/lib/cmds/watch-until.ts
- plugins/plugin-client-test/src/plugin.ts
- plugins/plugin-client-test/src/test/api1/watch-until.ts
- plugins/plugin-core-support/src/lib/cmds/watch.ts
> feat(plugins/plugin-core-support): watch poller should support --until option to stop watcher

- OWNERS
- OWNERS_ALIASES
> chore: add OWNERS and OWNER_ALIASES files to 8_10_x branch

- plugins/plugin-core-support/src/lib/cmds/watch.ts
> fix(plugins/plugin-core-support): watch --until should poll one more time after the until condition is reached

- packages/core/src/main/spawn-electron.ts
- packages/core/src/models/SubwindowPrefs.ts
- packages/core/src/webapp/bootstrap/client.ts
- packages/core/src/webapp/bootstrap/init-electron.ts
- packages/core/src/webapp/models/table.ts
- packages/react/src/index.tsx
- plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/src/components/Content/Table/index.tsx
> feat: allow table drilldown to a new window

- package-lock.json
- package.json
> chore: bump core version to 10.3.0

- packages/core/src/core/events.ts
- packages/core/src/index.ts
- packages/core/src/models/tab-state.ts
- packages/core/src/webapp/tab.ts
- plugins/plugin-bash-like/src/tab-state.ts
- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/non-headless-preload.ts
- plugins/plugin-kubectl/src/tab-state.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
> feat(plugins/plugin-kubectl): allow for pinning a Kubernetes Context or Namespace to a tab

- package-lock.json
- package.json
- plugins/plugin-kubectl/package.json
- plugins/plugin-kubectl/src/controller/client/direct/url.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod-with-not-found.ts
> fix(plugins/plugin-kubectl): "get ingress" failed with resource type not found

- plugins/plugin-kubectl/src/controller/client/direct/delete.ts
- plugins/plugin-kubectl/src/controller/client/direct/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/explain.ts
- plugins/plugin-kubectl/src/controller/kubectl/fqn.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/test/k8s1/get-crd.ts
- plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod-with-not-found.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
- plugins/plugin-kubectl/tests/data/k8s/crd2.yaml
> fix(plugins/plugin-kubectl): direct get fails when user specifies fully/partially qualified name of a crd

- packages/core/src/core/usage-error.ts
- packages/core/src/repl/exec.ts
> chore(packages/core): repl/exec should import yargs-parser instead of require

- README.md
> docs: notify windows users about potential bugs with backslashes

- packages/core/src/main/save.ts
Fixes #7434 
Also related to #7405
> fix(packages/core): File->Save does not properly handle backslash paths

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix(plugins/plugin-client-common): the first time PTY output appears, Kui flashes briefly

- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/lib/model/resource.ts
> fix(plugins/plugin-kubectl): plugin-kubectl should expose Secret type

- plugins/plugin-client-common/web/scss/components/Accordion/PatternFly.scss
> fix(plugins/plugin-client-common): sourceRef's color isn't right in PatternFly Dark

- plugins/plugin-core-support/about/src/about.ts
- plugins/plugin-electron-components/src/plugin.ts
> fix(plugins/plugin-client-common): In Popup mode, clicking Help button will show the welcome notebook in a new window

- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/src/controller/kubectl/config.ts
- plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
- plugins/plugin-kubectl/src/index.ts
- plugins/plugin-kubectl/src/tab-state.ts
> fix(plugins/plugin-kubectl): tab-state transition optimization

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): Popover and Dropdowns require double-click to close

- packages/test/src/api/selectors.ts
- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
> fix(plugins/plugin-client-common): sidecar Kebab menu has nested <button>

- plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
> fix(plugins/plugin-client-common): sidecar screenshot button is visible even inBrowser

- plugins/plugin-client-common/src/components/spi/Modal/impl/PatternFly.tsx
> fix(plugins/plugin-client-common): Close button in confirm dialog does not work

- packages/core/src/repl/exec.ts
- packages/core/src/webapp/tab.ts
- packages/test/src/api/selectors.ts
- plugins/plugin-client-alternate/src/test/bottom-input/new-tab.ts
> fix: Bottom Input clients do not support splits

- packages/builder/dist/electron/build.sh
- packages/builder/dist/electron/builders/electron.js
- packages/builder/dist/electron/package-lock.json
- packages/webpack/headless-webpack.config.js
- packages/webpack/webpack.config.js
> chore: remove staging directory from electron build.sh

- packages/builder/dist/electron/build.sh
- packages/builder/dist/electron/builders/electron.js
> chore(packages/builder): remove icon findings from electron build.sh

- packages/test/src/api/selectors.ts
- plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
> test(plugins/plugin-core-support): close split via button

- plugins/plugin-client-common/src/components/Client/Popup.tsx
- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-default/src/index.tsx
> feat: enable splits for popup mode

- plugins/plugin-s3/ibm/src/preload.ts
> fix(plugins/plugin-s3): ibm s3 provider registers too late

- packages/test/src/api/mmr.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/sidecar-expect.ts
- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecarV2.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
- plugins/plugin-client-test/src/test/api1/mmr-mode-via-registration.ts
- plugins/plugin-client-test/src/test/api1/mmr-mode.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
> design: remove sidecar Titlebar buttons

- plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss
> fix: split close button is not tab navigable

- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
> fix(plugins/plugin-client-common): icons in dropdown in sidecar toolbar are too small

- plugins/plugin-bash-like/src/test/bash-like/rerun.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): rerunning a block when there is an active block seems to insert a new block

- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
> fix: StatusStripe text can oddly overflow

- docs/example/AnimalApp/package-lock.json
- docs/example/AnimalApp/package.json
- docs/example/AnimalApp/plugins/plugin-client-default/config.d/style.json
> docs: AnimalApp should pull in PatternFly themes and use PatternFly Light as default theme

- package-lock.json
- package.json
- packages/test/src/api/util.ts
- plugins/plugin-iter8/package.json
- plugins/plugin-iter8/src/components/delete-metric.ts
- plugins/plugin-iter8/src/components/metric-config.ts
- plugins/plugin-iter8/src/components/restore-metric.ts
- plugins/plugin-iter8/src/components/traffic-split.ts
- plugins/plugin-iter8/src/models/metrics.tsx
- plugins/plugin-iter8/src/modes/get-metrics.tsx
- plugins/plugin-kubectl-flow-views/tekton/package.json
- plugins/plugin-kubectl-flow-views/tekton/src/lib/read.ts
- plugins/plugin-kubectl-flow-views/tekton/src/model/modes/run.ts
- plugins/plugin-kubectl/logs/package.json
- plugins/plugin-kubectl/package.json
- plugins/plugin-kubectl/src/controller/client/direct/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/get.ts
- plugins/plugin-kubectl/src/controller/kubectl/kustomize.ts
- plugins/plugin-kubectl/src/controller/kubectl/status.ts
- plugins/plugin-kubectl/src/lib/util/fetch-file.ts
- plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
- plugins/plugin-kubectl/src/lib/view/modes/configmap-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/crd-summary.ts
- plugins/plugin-kubectl/src/lib/view/modes/last-applied.ts
- plugins/plugin-kubectl/src/test/k8s/contexts.ts
> chore: bump js-yaml to 4.0

- package-lock.json
- package.json
> chore: bump typescript dependency

- package-lock.json
- package.json
- plugins/plugin-kubectl/package.json
- plugins/plugin-kubectl/src/controller/client/direct/custom-columns.ts
> chore: update to use an npm-published form of our jsonpath branch

- package-lock.json
- plugins/plugin-kubectl/package.json
This pulls in the type declarations.
Fixes #7613
> chore bump to kui-shell jsonpath 1.1.1

- plugins/plugin-client-common/src/components/Client/TabContent.tsx
This PR cleans up `TabContent` so as to avoid iterative rendering due to the way we currently use setState in order to facilitate bootstrapping. This part of `TabContent` was written before we understood `React.createRef()`.
These fixes should also resolve a Content Layout Shift glitch that you can either observe visually, or via the Performance tab in chrome/electron.
Fixes #7626
> TabContent code flows multiple time through initial render()

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
> fix(plugins/plugin-client-common): initial prompt not focused

- packages/proxy/Dockerfile
- packages/proxy/build-docker.sh
> fix(packages/proxy): docker+proxy build fails

- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
> fix(plugins/plugin-client-common): tests unstable after focus fix

- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyDown.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyPress.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/OnPaste.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
- plugins/plugin-client-common/src/components/Views/util/multiline-input.ts
- plugins/plugin-client-common/src/components/spi/TextArea/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/TextArea/index.tsx
- plugins/plugin-client-common/src/components/spi/TextArea/model.ts
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/TextArea/PatternFly.scss
Also add support for HERE docs
Fixes #3281
> feat: muti-line input

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix(plugins/plugin-client-common): clearing the terminal has two bugs

- package-lock.json
- package.json
> chore: bump top-level version to 10.4.0

- plugins/plugin-core-support/tsconfig.json
- plugins/plugin-core-support/up/src/Checker.ts
- plugins/plugin-core-support/up/src/aws/index.ts
- plugins/plugin-core-support/up/src/aws/s3.ts
- plugins/plugin-core-support/up/src/ibm/base/login.ts
- plugins/plugin-core-support/up/src/ibm/base/target.ts
- plugins/plugin-core-support/up/src/ibm/ce/project.ts
- plugins/plugin-core-support/up/src/ibm/cli/ce.ts
- plugins/plugin-core-support/up/src/ibm/cli/cos.ts
- plugins/plugin-core-support/up/src/ibm/cli/ibmcloud.ts
- plugins/plugin-core-support/up/src/ibm/cos/creds.ts
- plugins/plugin-core-support/up/src/ibm/cos/default-mount.ts
- plugins/plugin-core-support/up/src/ibm/index.ts
- plugins/plugin-core-support/up/src/ibm/options.ts
- plugins/plugin-core-support/up/src/kubernetes/index.ts
- plugins/plugin-core-support/up/src/kubernetes/kubectl.ts
- plugins/plugin-core-support/up/src/kubernetes/valid-kubeconfig.ts
- plugins/plugin-core-support/up/src/options.ts
- plugins/plugin-core-support/up/src/plugin.ts
- plugins/plugin-core-support/up/src/registrar.ts
- plugins/plugin-core-support/up/src/ui.ts
- plugins/plugin-core-support/up/src/up.ts
- plugins/plugin-core-support/up/tsconfig.json
> feat: `up` command

- tools/travis/microk8s.sh
> test: k8s tests may fail because default serviceaccount is not yet ready

- packages/core/src/index.ts
- packages/core/src/models/CommentaryResponse.ts
- packages/core/src/models/execOptions.ts
- packages/test/src/api/cli.ts
- packages/test/src/api/selectors.ts
- packages/test/src/api/util.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Icons/index.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-core-support/src/test/core-support/section.ts
Fixes #7676 
Sections can be inserted by the block action button `§`, or by command `# ---`.
https://user-images.githubusercontent.com/21212160/123002909-765ccd00-d380-11eb-8bd4-8e82c053b357.mov
> feat: section blocks

- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): commentary editor does not shrink as window width

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
> fix(plugins/plugin-client-common): editing a commentary link can fail with uncaught decodeURIComponent error

- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): s3 vfs not mounted in time in headless mode

- packages/test/src/api/util.ts
- plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ClipboardTransfer.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts
- plugins/plugin-core-support/src/test/core-support/replay.ts
> fix(plugins/plugin-client-common): snapshot doesn't preserve cancelled or empty block

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
> feat(plugins/plugin-client-common): add support for <br> in Markdown

- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix: sequential execution ignores errors and in progress

- plugins/plugin-client-default/src/index.tsx
> fix(plugins/plugin-client-default): remove Screenshot component

- packages/core/src/core/userdata.ts
- packages/core/src/index.ts
- plugins/plugin-s3/ibm/src/IBMCloudS3Provider.ts
- plugins/plugin-s3/ibm/src/baseMountName.ts
- plugins/plugin-s3/ibm/src/s3provider.ts
- plugins/plugin-s3/ibm/src/specialMounts.ts
- plugins/plugin-s3/src/providers/model.ts
- plugins/plugin-s3/src/test/s3/pseudo.ts
- plugins/plugin-s3/src/test/s3/s3.ts
- plugins/plugin-s3/src/vfs/index.ts
- plugins/plugin-s3/src/vfs/split.ts
This PR does so for IBM mounts
Fixes #7721
> feat: Add support for "slash tmp" to s3 mounts

- plugins/plugin-s3/ibm/src/specialMounts.ts
> fix(plugins/plugin-s3): s3 tmp/bin mounts are not geo-specific

- plugins/plugin-bash-like/src/lib/cmds/export.ts
> fix(plugins/plugin-bash-like): `export` command stores newline in session storage

- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
> feat(plugins/plugin-client-common): top-level tabs are not allowed to be closed or added in a readonly client

- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): leftover debugging in plugin-s3

- packages/core/src/models/command.ts
- packages/core/src/repl/pipe-stages.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/FancyPipeline.tsx
> fix(packages/core): pipeStages splits command with >> incorrectly

- docs/example/AnimalApp/package-lock.json
- docs/example/AnimalApp/package.json
- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron to latest 11.x

- packages/core/src/repl/exec.ts
- plugins/plugin-bash-like/fs/src/lib/fwrite.ts
- plugins/plugin-bash-like/fs/src/vfs/controller/server-side.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/index.ts
- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
> fix: >> is not always treated as an append to the given file

- plugins/plugin-bash-like/fs/src/lib/glob.ts
- plugins/plugin-bash-like/fs/src/vfs/delegates.ts
- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-core-support/src/notebooks/vfs/index.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): wildcard cp between s3 regions/providers fails

- packages/proxy/build-docker.sh
Clean up extra spaces, although these errors are not important, they affect the code specification.
> Clean up extra spaces

- package-lock.json
- plugins/plugin-bash-like/src/lib/cmds/catchall.ts
- plugins/plugin-core-support/package.json
- plugins/plugin-core-support/up/src/Checker.ts
- plugins/plugin-core-support/up/src/Group.ts
- plugins/plugin-core-support/up/src/aws/s3.ts
- plugins/plugin-core-support/up/src/ibm/base/login.ts
- plugins/plugin-core-support/up/src/ibm/base/target.ts
- plugins/plugin-core-support/up/src/ibm/ce/project.ts
- plugins/plugin-core-support/up/src/ibm/cli/ce.ts
- plugins/plugin-core-support/up/src/ibm/cli/cos.ts
- plugins/plugin-core-support/up/src/ibm/cli/ibmcloud.ts
- plugins/plugin-core-support/up/src/ibm/cos/creds.ts
- plugins/plugin-core-support/up/src/ibm/cos/default-mount.ts
- plugins/plugin-core-support/up/src/kubernetes/kubectl.ts
- plugins/plugin-core-support/up/src/ui.ts
- plugins/plugin-core-support/up/src/up.ts
> feat: up command should use a real progress tracker

- packages/core/src/models/execOptions.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-core-support/up/src/Checker.ts
- plugins/plugin-core-support/up/src/ibm/base/login.ts
- plugins/plugin-core-support/up/src/ui.ts
- plugins/plugin-core-support/up/src/up.ts
> feat: port up --fix to use Listr

- packages/proxy/app/routes/exec.js
> fix(packages/proxy): signedCookie not a function

- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): leftover debug in s3 vfs

- plugins/plugin-s3/src/preload.ts
- plugins/plugin-s3/src/vfs/index.ts
> fix(plugins/plugin-s3): optimize s3 init a bit

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
Fixes #7811
Ready to be merged.
> Electron version bump

- package-lock.json
- packages/webpack/package.json
- packages/webpack/webpack.config.js
- plugins/plugin-bash-like/web/scss/xterm.scss
- plugins/plugin-carbon-themes/web/scss/patternfly-alignment.scss
- plugins/plugin-client-common/web/scss/components/Editor/Editor.scss
- plugins/plugin-core-themes/web/scss/Mercury.scss
- plugins/plugin-core-themes/web/scss/common.scss
- plugins/plugin-kubectl/web/scss/components/Terminal/Terminal.scss
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/sans.scss
> fix: fixes for font rendering regressions due to #7818

- plugins/plugin-client-common/src/components/Content/LinkStatus.tsx
- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
- plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Terminal/BigFonts.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/BlockLinks.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
- plugins/plugin-core-support/src/test/core-support/link-block.ts
- plugins/plugin-core-support/src/test/core-support/section.ts
This PR removes the "insert section break" block action
Fixes #7826
> fix: improve rendering of commentary in notebooks

- plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Hint/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Hint/_mixins.scss
> fix: new Hint and CodeSnippet UIs do not need a wrapping Card

- .github/workflows/test.yaml
- packages/proxy/app/app.js
- packages/proxy/app/routes/exec.js
- plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
- plugins/plugin-proxy-support/src/lib/proxy-executor.ts
Authentication token support. If the token is correct, a signed cookie is set.
This behaviour mimics the Jupyter notebooks web service.
> Auth token support

- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
- plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
Fixes #7851
also introduces some fixes for flakey tests
Fixes #7681
> fix(plugins/plugin-client-common): leftover debug in SimpleEditor

- packages/test/src/api/selectors.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
> test: additional stability improvements for pty many lines test

- .github/workflows/test.yaml
- packages/test/src/api/util.ts
- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
> test: try to improve test stability by avoiding concurrent mocha tests

- plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
> test: pty with many lines test sometimes fails

- plugins/plugin-core-support/src/test/core-standalone/text-search.ts
- plugins/plugin-electron-components/src/components/Search.tsx
Fixes #7881 
Fixes #7490 
Added feature to navigate through all search matches and added corresponding tests.
> Updated functionalities to search bar which solves #7881 and #7490

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> Electron version bump to 11.4.11

- plugins/plugin-s3/ibm/src/specialMounts.ts
> fix(plugins/plugin-s3): ibmcloud s3 /bin bind mount not showing up

- README.md
> add survey link to survey

- plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
- plugins/plugin-client-common/web/css/static/repl.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
- plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
- plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
- plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: a few more patternfly theme tweaks

- packages/test/src/api/util.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-kubectl/src/test/k8s2/get-all-namespaces.ts
> fix(plugins/plugin-client-common): React dev warning for Input

- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/Lightweight/_index.scss
- plugins/plugin-client-common/web/scss/Lightweight/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Sidecar/PatternFly.scss
> fix(plugins/plugin-client-common): improve rendering of "core" themes

- plugins/plugin-client-common/web/css/static/inverted-colors.css
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/DropDown/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Sidecar/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
- plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
- plugins/plugin-patternfly4-themes/web/scss/common.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
> fix: multiple contrast and padding issues with Dropdowns

- plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
- plugins/plugin-client-common/src/components/Content/Commentary.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-core-themes/web/scss/light.scss
- plugins/plugin-patternfly4-themes/web/scss/dark.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: Commentary Editor in patternfly4 light theme has low contrast

- plugins/plugin-client-common/package.json
> chore: bump webpack-dev-server deps to pick up security fix

- packages/core/src/webapp/models/table.ts
- plugins/plugin-client-common/i18n/resources_en_US.json
- plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat: Update tables and SequenceDiagram to support queueing delays

- plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
> fix(plugins/plugin-client-common): SequenceDiagram can bomb

- README.md
> doc: specify homebrew installation for macOS

- package-lock.json
- package.json
> chore: bump top-level version to 10.5.0

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-patternfly4-themes/web/scss/dark.scss
> fix: Commentary Hints have low contrast in PatternFly4 Dark

- packages/core/src/models/TabLayoutModificationResponse.ts
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/controller/split.ts
- plugins/plugin-client-common/src/plugin.ts
> feat: Add ability to swap the order of splits

- package-lock.json
- packages/builder/package.json
> chore: bump babel deps

- README.md
> doc: update README to pull installation up

- README.md
This PR cleans up the installation section.
> doc: minor README cleanup

- README.md
> doc: typo AppleSilicon -> Apple Silicon

- plugins/plugin-client-common/web/css/static/sidecar-main.css
- plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
> fix: sidecar contrast issues

- packages/proxy/Dockerfile
- packages/proxy/build-docker.sh
THis PR also does some cleanup to the Dockerfile, uses upx to compress the kubectl, helm, oc, etc. binaries, removes duplicate copies of those binaries.
Fixes #8000
> feat(packages/proxy): add iter8ctl to the docker base image

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
1) show duration
2) fix bug which resulted in the play icon<->check mark transition was too fast (the checkmark would often be barely if at all visible)
Fixes #8025
> fix(plugins/plugin-client-common): improve block rerun UI

- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
> fix(plugins/plugin-client-common): leftover debugging in Block/index.tsx

- packages/proxy/Dockerfile
- packages/proxy/build-docker.sh
- packages/proxy/conf.d/proxy.conf
- packages/proxy/defaults/csp.sh
- packages/proxy/defaults/opengraph.sh
- packages/webpack/webpack.config.js
Fixes #8055
This PR also includes a small update to the webpack config, to avoid compressing index.html if WEB_COMPRESS is set.
> feat(packages/proxy): dockerized kui hard-wires ContentSecurityPolicy

- plugins/plugin-client-common/src/components/Client/InputStripe.tsx
- plugins/plugin-client-common/web/css/static/Popup.scss
- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
> fix(plugins/plugin-client-common): weird blue right border in popup mode

- package-lock.json
- package.json
> chore: bump top-level version to 10.6.0

- package-lock.json
- packages/core/package.json
- plugins/plugin-core-support/package.json
- plugins/plugin-iter8/package.json
- plugins/plugin-kubectl/package.json
> chore: bump dependencies, including to patternfly 4.157.3

- packages/proxy/.dockerignore
- packages/proxy/Dockerfile
> feat(packages/proxy): add curl, sed, and git to the kuishell/kui image

- packages/core/src/repl/events.ts
- packages/core/src/repl/exec.ts
- plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix: redirect to a file also echos the output to the kui terminal

- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
> fix(plugins/plugin-client-common): Tooltip contrast issues

- packages/test/src/api/table.ts
Re: the discussion in the issue, this PR updates the test.
Fixes #8107
> test: fix instability in "test table with drilldown"

- plugins/plugin-client-common/web/scss/components/ProgressStepper/_index.scss
> fix(plugins/plugin-client-common): minor UI tweaks for progress stepper

- plugins/plugin-client-common/src/components/Client/MutabilityContext.ts
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Client/TabModel.ts
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
- plugins/plugin-client-common/src/components/Content/Commentary.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
- plugins/plugin-client-common/src/test/core/mutabilityTests.ts
- plugins/plugin-core-support/src/test/core-support/commentary.ts
Ready to be merged. 
Fixes #8043 
Fixes #8044
> fix(plugins/plugin-client-common): Notebooks default to read only mode

- plugins/plugin-client-common/src/components/spi/DescriptionList/impl/PatternFlyLabelList.tsx
- plugins/plugin-client-common/web/scss/components/DescriptionList/PatternFlyLabelList.scss
> fix(plugins/plugin-client-common): Small tweaks for LabelList variant UI

- README.md
> doc: link to api docs in top-level README

- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
- plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
- plugins/plugin-patternfly4-themes/web/scss/charts.scss
> feat: refine colorings of SequenceDiagram view

- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_index.scss
> fix(plugins/plugin-client-common): improve padding in sequence diagram

- plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
- plugins/plugin-patternfly4-themes/web/scss/charts.scss
1) improved blue scheme for patternfly4 light
2) shorter bar height for small charts
> fix: tweak stylings of sequence diagram view

- packages/core/src/models/execOptions.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/pty/client.ts
> feat: allow controllers to pass through cwd for pty execution

- plugins/plugin-bash-like/src/index.ts
- plugins/plugin-bash-like/src/lib/cmds/pipe.ts
> feat(plugins/plugin-bash-like): add doExecPipe api

- plugins/plugin-bash-like/fs/src/vfs/local.ts
- plugins/plugin-s3/src/vfs/index.ts
we have an await in a Promise without a try/catch. yay javascript
> fix: fslice vfs error handling regression

- plugins/plugin-bash-like/fs/src/vfs/CommandsFS.ts
- plugins/plugin-bash-like/fs/src/vfs/TrieVFS.ts
We just weren't handling this case well at all.
> fix(plugins/plugin-bash-like): TrieVFS fixes for ls -d

- plugins/plugin-bash-like/fs/src/vfs/TrieVFS.ts
subdirectories were not expanding
> fix(plugins/plugin-bash-like): regression in ls for CommandFS

- package-lock.json
- package.json
> chore: bump to typescript 4.5.2 

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump monaco-editor to 0.30.1

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
if that split has a previously watchable table
> fix(plugins/plugin-client-common): closing a split may can kui to crash

- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
> fix(plugins/plugin-client-common): remove debug printf

- plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix(plugins/plugin-client-common): spurious console errors on unmount

- plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
also fixes for non-text first child of content section, e.g. strong
> fix(plugins/plugin-client-common): remark-tip support for warn/etc.

- plugins/plugin-client-common/src/components/Content/Markdown.tsx
- plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
also add a bit more padding around code blocks
> fix(plugins/plugin-client-common): improve spacing around markdown tips

- plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
> chore: remove leftover debug in remark-tip/index.ts

- plugins/plugin-kubectl/helm/src/controller/helm/catchall.ts
- plugins/plugin-kubectl/helm/src/controller/helm/install.ts
> fix(plugins/plugin-kubectl): make sure to send helm to pty when needed

- plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): move back to 14px for markdown

- plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
this means use the body of the code block as the validator
> feat(plugins/plugin-client-common): support for validate: $body

- plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
> fix(plugins/plugin-client-common): restore anchors for code block

- packages/core/src/repl/exec.ts
> fix(packages/core): avoid kui handling of redirects to /dev

- packages/core/src/repl/exec.ts
> fix(packages/core): more fixes for core redirect handling versus /dev

- packages/core/src/repl/exec.ts
- plugins/plugin-bash-like/fs/src/lib/cd.ts
- plugins/plugin-bash-like/src/test/bash-like/cd.ts
> fix: `cd /tmp && echo -n hi` does not work

- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): minor tweak to markdown tip color

- packages/proxy/app/routes/exec.js
- plugins/plugin-bash-like/fs/src/lib/cd.ts
- plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
- plugins/plugin-bash-like/src/test/bash-like/cd.ts
> fix(plugins/plugin-bash-like): cd /tmp && ... does not handle streaming

- plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
- plugins/plugin-client-common/src/controller/commentary.ts
- plugins/plugin-core-support/src/lib/cmds/replay.ts
- plugins/plugin-kubectl/src/lib/util/fetch-file.ts
> feat: replay notebook from url

- plugins/plugin-client-common/src/components/Views/Terminal/Block/CodeBlockStatus.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Timer.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
also refactor Input.tsx to use that new Timer component, i.e. pull this logic out of Input!
> feat(plugins/plugin-client-common): add Timer to code block

- plugins/plugin-bash-like/web/scss/xterm.scss
> fix(plugins/plugin-bash-like): pty output should be pre-wrap, i think

- plugins/plugin-client-common/notebooks/welcome.md
> doc: update welcome notebook download links to use brew for macos

- plugins/plugin-client-common/notebooks/welcome.md
> doc: move hint to the main split in welcome notebook

- plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-client-common/notebooks/code-blocks.md
- plugins/plugin-client-common/notebooks/expandable-section.md
- plugins/plugin-client-common/notebooks/hints.md
- plugins/plugin-client-common/notebooks/playground.md
- plugins/plugin-client-common/notebooks/tabs.md
- plugins/plugin-client-common/src/components/Content/Commentary.tsx
- plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/components/ExpandableSection/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Playground.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-client-default/src/preload.ts
- plugins/plugin-core-themes/web/scss/light.scss
including Light and Carbon Gray 10 contrast fixes for editor which may benefit other use cases.
> fix: rendering improvements for playground

- plugins/plugin-client-common/notebooks/playground.md
- plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/src/test/core/markdown-helpers.ts
- plugins/plugin-client-common/src/test/core/splits-in-markdown.ts
- plugins/plugin-client-common/web/scss/components/Terminal/Maximized.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Playground.scss
> feat: support for maximized blocks in markdown notebooks

- plugins/plugin-core-support/src/lib/cmds/replay.ts
> fix(plugins/plugin-core-support): restore multi-replay support

- packages/core/src/core/events.ts
- plugins/plugin-client-common/src/components/Client/MutabilityContext.ts
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/controller/commentary.ts
> fix: commentary --readonly for offline clients results in editable tabs

- plugins/plugin-client-common/tests/data/markdown-tab-links.md
> doc: fix for improperly auto-formatted example markdown input

- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron-packager version

- plugins/plugin-kubectl/src/lib/view/modes/Logs.tsx
> fix(plugins/plugin-kubectl): logs tab may fail badly with Null pointer

- plugins/plugin-client-common/web/scss/components/Sidecar/Base.scss
probably from an update to patternfly
> fix(plugins/plugin-client-common): regression in sidecar tab font size

- plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
> fix(plugins/plugin-client-common): restore card header padding

- package.json
> chore: bump top-level package.json to 11.0.0 in preparation for release

- package-lock.json
> chore: update package-lock.json to reflect 11.0.0

- package.json
> fix: build:electron:all build target does not build headless bundles

- plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
This has been broken for a while now, and we've been ignoring test failures.
> fix(plugins/plugin-client-common): `watch ls` does not watch

- plugins/plugin-client-common/notebooks/playground.md
- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-client-default/src/preload.ts
> doc: add playground to set of kui notebooks

- package-lock.json
- package.json
- packages/core/package.json
- plugins/plugin-core-support/package.json
ref:
- https://github.com/advisories/GHSA-5rqg-jm4f-cqx7
- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
- https://twitter.com/bitandbang/status/1478786515660648448
- https://twitter.com/bitandbang/status/1480605181792370693
Signed-off-by: Stephen Augustus <foo@auggie.dev>
> */package.json: Add override for colors@1.40.0

- package-lock.json
- plugins/plugin-core-support/package.json
- plugins/plugin-electron-components/package.json
this was declared only in kui-shell/core
> fix: add missing electron/remote dependencies

- package-lock.json
- plugins/plugin-core-support/package.json
- plugins/plugin-electron-components/package.json
master PR: https://github.com/kubernetes-sigs/kui/pull/8469
> fix: back-port of electron/remote fix to 11_0_x

- plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
> fix(plugins/plugin-client-common): regression in tooltip font size

- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
> feat: update markdown tip parser to handle "todo" and "bug"

- plugins/plugin-iter8/notebooks/tutorial1.md
- plugins/plugin-iter8/notebooks/welcome.md
> doc: update iter8 tutorial1 to expand on what an Experiment is

- plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
- plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
- plugins/plugin-client-common/tests/data/wizard-with-splits.md
> feat(plugins/plugin-client-common): allow wizards with normal kui splits

- plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
> fix(plugins/plugin-client-common): wizard nav can still be too thin

- plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
> fix(plugins/plugin-client-common): yet more tweaks to wizard nav width

- plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
> fix(plugins/plugin-client-common): sigh more tweaks to wizard nav width

- plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
- plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
- plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
- plugins/plugin-core-themes/web/scss/dark-mixins.scss
- plugins/plugin-core-themes/web/scss/dark.scss
- plugins/plugin-core-themes/web/scss/light.scss
- plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
> fix: color contrast fixes for Sidebar and Wizard header

- plugins/plugin-core-support/src/lib/cmds/replay.ts
> fix(plugins/plugin-client-common): replay filepaths with spaces

- plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
> fix(plugins/plugin-client-common): more nav width tweaks

- plugins/plugin-client-common/notebooks/code-blocks.md
- plugins/plugin-client-common/notebooks/tabs.md
- plugins/plugin-client-common/notebooks/welcome.md
> doc: remove code block ids from notebooks where no longer needed

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-getting-started.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
> first draft of knative guidebook integration

- plugins/plugin-kubectl/notebooks/knative-getting-started.md
> fix(plugins/plugin-kubectl): missing wizard title in knative guidebook

- plugins/plugin-client-common/src/components/Content/Markdown/components/code/encoding.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
> chore(plugins/plugin-client-common): clean up markdown code block source

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: add remark-terms dependence (no other changes)

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-first-autoscale.md
- plugins/plugin-kubectl/notebooks/knative-first-service.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
> doc: knative first-service and first-autoscale guidebooks

- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
- plugins/plugin-client-common/web/scss/components/ExpandableSection/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
also, wizard descriptions that contain tips aren't processed properly
> fix(plugins/plugin-client-common): mis-parsing of wizard headers

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative Traffic Splitting guidebook.
> Adding first draft of Knative Traffic Splitting guidebook

- plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
- plugins/plugin-client-common/web/css/static/carbon-overrides-common.css
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
- plugins/plugin-client-default/src/index.tsx
- plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts
- plugins/plugin-core-support/src/test/core/about.ts
it doesn't really offer help, and now with the sidebar, we have a much richer way to access what the user might want, as opposed to a single fixed page
> fix(plugins/plugin-client-default): don't show ? icon in default client

- plugins/plugin-kubectl/notebooks/knative-first-autoscale.md
- plugins/plugin-kubectl/notebooks/knative-first-service.md
- plugins/plugin-kubectl/notebooks/knative-getting-started.md
- plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
- plugins/plugin-kubectl/notebooks/knative-what-is-it-good-for.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
> doc: add left split about knative to knative guidebooks

- plugins/plugin-iter8/notebooks/iter8-what-is-it-good-for.md
- plugins/plugin-iter8/notebooks/tutorial1.md
- plugins/plugin-iter8/src/preload.ts
> doc: add left split to iter8 tutorial1

- plugins/plugin-kubectl/notebooks/knative-what-is-it-good-for.md
> doc: update knative github link to avoid pointing to docs github

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative Eventing guidebook.
> fix(plugins/plugin-kubectl): First draft of Knative Eventing guidebook

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-eventing-components.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative Sources, Brokers, Triggers, and Sinks guidebook.
> fix(plugins/plugin-kubectl): Eventing Components guidebook

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/rehype-material-icons.ts
> feat: initial support for material-... icons in markdown

- plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
> doc: no need for a wizard in knative-introducing-eventing.md

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-cloud-events-player.md
- plugins/plugin-kubectl/notebooks/knative-eventing-components.md
- plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
- plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative CloudEvents Player guidebook.
> fix(plugins/plugin-kubectl): CloudEvents Player guidebook

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-first-trigger.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative Creating your first Trigger guidebook.
> fix(plugins/plugin-kubectl): Creating first Trigger guidebook

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-clean-up.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative Clean Up guidebook.
> fix(plugins/plugin-kubectl): First Pass Clean Up Guidebook

- plugins/plugin-kubectl/notebooks/knative-what-is-it-good-for.md
> fix(plugins/plugin-kubectl): broken link to knative.dev

- plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
- plugins/plugin-client-common/src/controller/snippets.ts
probably a regression from the snippet inlining work
> fix(plugins/plugin-client-common): external links in markdown broken

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-whats-next.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Created the first draft of the Knative What's Next guidebook.
> fix(plugins/plugin-kubectl): What's Next guidebook

- plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
- plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md
- plugins/plugin-kubectl/notebooks/knative-getting-started.md
> test: fix knative getting started guidebook test failures

- .github/workflows/test.yaml
> test: attempt to improve k8s test stability

- plugins/plugin-client-common/src/components/Client/StatusStripe/CurrentWorkingDirectory.tsx
- plugins/plugin-client-common/web/scss/components/Popover/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Popover/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Popover/common.scss
- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
improved width for the status stripe popovers
remove odd top:4px rule between popover select content and header
> fix: several UI tweaks to popover rendering

- plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts
- plugins/plugin-kubectl/notebooks/knative-getting-started.md
> feat: support for optional code blocks in wizards

- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
> fix(plugins/plugin-client-common): clean out leftover debug messages

- plugins/plugin-client-common/web/css/static/SidecarCommon.css
- plugins/plugin-client-common/web/css/static/ui.css
- plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
- plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/DropDown/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss
- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
- plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss
- plugins/plugin-core-themes/web/scss/Mercury.scss
also fix for the theme selector icon
> fix: more color contrast fixes for wizard

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump monaco-editor to 0.32.1

- plugins/plugin-client-common/src/components/Content/LinkStatus.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/CodeBlockProps.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
- plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
> feat(plugins/plugin-client-common): add Progress UI to Wizard component

- package-lock.json
- package.json
> chore: bump lint-staged to 12.3.3

- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/web/scss/components/Page/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndBottomComboStrips.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
This gives more room to guidebook main content.
> fix(plugins/plugin-client-common): use narrower left strip

- packages/proxy/Dockerfile
Added support for unzip command in Dockerfile when running as a proxy
> enhancement: adding support for unzip cmd to Dockerfile

- tools/travis/microk8s.sh
> Could not resolve host: mirror.openshift.com
> test: increase retry count when downloading github action CLIs

- plugins/plugin-client-common/src/components/spi/Popover/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Popover/model.ts
- plugins/plugin-electron-components/src/components/UpdateChecker.tsx
> fix: UpdateChecker component does not display popover content

- package-lock.json
- package.json
> chore: bump top-level to 11.3.0

- plugins/plugin-client-common/web/scss/components/Table/PatternFly.scss
- plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
- plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Table/tables.scss
> fix(plugins/plugin-client-common): table sticky headers are transparent

- package-lock.json
- package.json
> chore: bump top-level to 11.4.0

- plugins/plugin-client-common/notebooks/expandable-section.md
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
This PR also updates the expandable section/tip playground to document all of the options.
> feat(plugins/plugin-client-common): add gray markdown tips

- plugins/plugin-carbon-themes/web/scss/colors.scss
- plugins/plugin-core-themes/web/scss/atelier-seaside.scss
- plugins/plugin-core-themes/web/scss/dracula.scss
- plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss
- plugins/plugin-core-themes/web/scss/nord.scss
- plugins/plugin-core-themes/web/scss/paraiso.scss
- plugins/plugin-core-themes/web/scss/solarized-dark.scss
> fix: more base0E color contrast fixes

- packages/test/src/api/Markdown.ts
- plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
- plugins/plugin-client-common/src/test/core/code-blocks-in-markdown.ts
- plugins/plugin-client-common/src/test/core/markdown-helpers.ts
- plugins/plugin-client-common/tests/data/cleanup1.md
- plugins/plugin-client-common/tests/data/cleanup2.md
> feat: add guidebook code block cleanup support

- plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
- plugins/plugin-client-common/web/scss/components/Table/Grid/_index.scss
- plugins/plugin-client-common/web/scss/components/Table/Grid/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
- plugins/plugin-client-common/web/scss/components/Table/badges.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
- plugins/plugin-kubectl/src/lib/view/formatTable.ts
> feat(plugins/plugin-client-common): improved layout for grid watchers

- packages/test/src/api/repl-expect.ts
- packages/test/src/api/util.ts
remove command output verify editor content is preserved
> test: remove block test flakiness

- plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
More work on contrast improvements.
> fix(plugins/plugin-client-common): another small tweak to tooltips

- plugins/plugin-kubectl/notebooks/crud-operations.md
- plugins/plugin-kubectl/notebooks/deploy-applications.md
> doc(plugins/plugin-kubectl): add validation and cleanup logic to kube guidebooks

- plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
this is a regression from some dom changes on our side
> fix(plugins/plugin-client-common): Wizard Cancel button is visible again

- plugins/plugin-client-common/src/components/Content/Markdown/components/tag.tsx
> fix(plugins/plugin-client-common): remove leftover debugging printf

- plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndRightComboStrips.scss
> fix(plugins/plugin-client-common): with left and right strips, opening sidebar causes funky layout

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/install-knative-quickstart.md
- plugins/plugin-kubectl/notebooks/installing-serving-with-yaml.md
- plugins/plugin-kubectl/notebooks/kn-cli.md
- plugins/plugin-kubectl/notebooks/knative-serving-hello-world.md
- plugins/plugin-kubectl/notebooks/knative.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Fixes #8692 
Added a Knative Serving Example guidebook to Kui. In this first example, we deploy a "Hello World" application.
> fix(plugins/plugin-kubectl): Added a Knative Serving Example 1 guidebook

- plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
> fix(plugins/plugin-client-common): clicking on link to another guidebook quietly fails

- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-kubectl/notebooks/knative-serving-autoscaling-go.md
- plugins/plugin-kubectl/notebooks/knative-serving-traffic-management.md
- plugins/plugin-kubectl/src/non-headless-preload.ts
Fixes #8693 
Added a Knative Serving Example guidebook to Kui. In this guidebook, we learn how to scale our application using Go.
> fix(plugins/plugin-kubectl): Adding Autoscaling using Go guidebook

- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
> fix(plugins/plugin-client-common): guidebook dependence tree can have wrong Option x index

- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts
We deferred this in the first work. The algorithm needs to iterate till convergence.
> fix(plugins/plugin-client-common): add support for iterating the subtask hoisting algo

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
If you see "yoyo" somewhere in the UI, my oops. :(
> fix(plugins/plugin-client-common): Input component has leftover debugging output

- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts
We are splicing in the inherited subtasks on every call to hoist()!
> fix(plugins/plugin-client-common): Imports tree can have duplicate Prerequisites content

- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/arch.ts
- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/index.ts
> fix(plugins/plugin-client-common): auto-detect architecture for guidebook choices

- plugins/plugin-client-common/web/scss/components/Terminal/Keys.scss
> fix(plugins/plugin-client-common): <keys> tag may have poor color contrast

- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
> chore: refactor our wrapper around Patternfly's Wizard

- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/collapseMadeChoices.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/validate.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/homebrew.ts
- plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
- plugins/plugin-client-common/web/scss/components/Wizard/Imports.scss
> feat(plugins/plugin-client-common): update Guide to show step validation

- plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Playground.scss
- plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
> fix(plugins/plugin-client-common): regression in playground maximization

- plugins/plugin-client-common/src/controller/guide.ts
> fix(plugins/plugin-client-common): guide command should add a title

- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/validate.ts
> fix(plugins/plugin-client-common): graph validation logic does not obey optional bit

- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
> feat(plugins/plugin-client-common): add progress bar to guide header

- plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
> fix(plugins/plugin-client-common): markdown tip open does not survive round-trip

- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
With this PR, view components must now subscribe to onChoice/offChoice events, rather than having choices flow in view prop updates. This is because the choice state is currently managed by the Markdown component. If it keeps choices in state, then a full reparse of the entire markdown document is needed for every choice update!
> fix(plugins/plugin-client-common): performance work on guidebook choice changing

- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
- plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
> fix(plugins/plugin-client-common): wizard header minimize can result in cropped text

- plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
Hide description. Also make sure to use a consistent font-family var(--font-sans-serif-title) for the wizard title.
> fix(plugins/plugin-client-common): another minor refinement to collapsed wizard title

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix(plugins/plugin-client-common): pty output can have extra blank vertical space

- plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
> fix(plugins/plugin-client-common): remove extra margin-top in wizard header description

- plugins/plugin-client-common/i18n/markdown_en_US.json
> fix(plugins/plugin-client-common): add missing i18n for "Success" in markdown tips

- plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
> fix(plugins/plugin-client-common): avoid awkward wrapping in wizard progress bar status text

- plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/validate.ts
We are treating non-optional code blocks without validation as if they were valid.
> fix(plugins/plugin-client-common): guide validator has false positives

- plugins/plugin-client-common/i18n/markdown_en_US.json
- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/hack.ts
- plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): add support for Caution tips in markdown

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump to electron 18.0.3

- package-lock.json
- package.json
> chore: bump top level to 11.5.0

- package-lock.json
- package.json
- packages/builder/package.json
- packages/core/package.json
- packages/test/package.json
- packages/webpack/package.json
- plugins/plugin-kubectl/package.json
> chore: pass through dependency version bumps

- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
> fix(plugins/plugin-client-common): Markdown component can call setState after unmounting

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
> fix(plugins/plugin-client-common): code block component can call setState after unmounting

- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
> fix(plugins/plugin-client-common): another setState on unmounted Markdown component

- plugins/plugin-client-common/src/components/Content/Markdown/hack.ts
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
> fix(plugins/plugin-client-common): hack workaround for buggy propTypes in react-markdown

- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
> fix(plugins/plugin-client-common): two fixes for setState during render

- plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
> fix(plugins/plugin-client-common): improved fix for CodeBlock setState after unmount

- package-lock.json
- plugins/plugin-client-common/package.json
> chore(plugins/plugin-client-common): bump to fontawesome v6

- plugins/plugin-client-common/src/controller/snippets.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/7.ts
- plugins/plugin-client-common/tests/data/guidebook-tree-model7.md
- plugins/plugin-client-common/tests/data/importaa.md
- plugins/plugin-client-common/tests/data/importdd.md
- plugins/plugin-client-common/tests/data/importgg.md
> feat(plugins/plugin-client-common): add support for {% include %} syntax in markdown

- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
> fix(plugins/plugin-client-common): improved error handling in Imports component

- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/1.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/2.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/3.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/4.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/6.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/7.ts
> test(plugins/plugin-client-common): fix missing test for {% include %} support

- plugins/plugin-client-common/web/scss/components/Wizard/Imports.scss
Add a bit of grayscale to our colors for code and choices.
> fix(plugins/plugin-client-common): small tweaks to colors in dependence UI

- plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
> fix(plugins/plugin-client-common): tips in guide have too many newlines

- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
> chore(plugins/plugin-client-common): minor code cleanup to Guide.tsx

- package-lock.json
> chore: hack in async 2.6.4 in package-lock.json

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump madwizard dependence

- plugins/plugin-client-common/src/components/Views/Terminal/SplitInjector.ts
- plugins/plugin-client-common/src/index.ts
> feat: export SplitInjector from plugin-client-common

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
- plugins/plugin-client-common/src/controller/guide.ts
> chore: bump to madwizard@0.8.0 API changes

- package-lock.json
- packages/webpack/webpack.config.js
- plugins/plugin-client-common/package.json
> chore: remove "fully specified" hack from webpack config

- packages/builder/dist/electron/builders/electron.js
- packages/core/src/main/spawn-electron.ts
- packages/webpack/bin/watch.sh
There are still more issues to go, but this plugs a few gaps.
> fix: a few fixes for building on windows

- README.md
> chore: update survey link

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump from electron 18.3.1 to 18.3.3

- packages/core/src/models/command.ts
- plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/SplitPosition.ts
we are still a long ways away from being able to enable this globally, but a few small changes along the way...
> fix: a few small fixes to enhance typescript strict type checking

- plugins/plugin-bash-like/web/scss/xterm.scss
> fix(plugins/plugin-bash-like): "dim" PTY text is too dim

- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
> fix(plugins/plugin-client-common): don't constrain content width for maximized splits

- plugins/plugin-client-common/notebook/src/load.ts
e.g.
--8<-- "$MY_DIRECTORY/myfile.txt"
> feat: loadbook content loader should support env vars on path to file

- plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
> fix(plugins/plugin-client-common): Ansi.tsx renders all dim text in gray

- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts
```typescript
<Kui guidebooks={false} .../>
```
> feat: allow clients to request that the hamburger menu not be shown

- plugins/plugin-client-common/src/components/Content/Markdown/components/code/filter.ts
i.e. `.foo` instead of what we had before `foo`.
This PR also allows for a deeper path project `.foo.bar`.
This PR also allows exclusion after filtering, so that you can project out a subtree, and then exclude fields from that subtree.
> fix(plugins/plugin-client-common): adopt jq syntax for guidebook json filters

- plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
> fix(plugins/plugin-client-common): markdown tabs in dark themes can have low contrast

- plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
> fix(plugins/plugin-client-common): cursor in monaco editor can have low contrast

- packages/core/src/main/main.ts
- packages/core/src/main/spawn-electron.ts
> fix: headless-to-ui transition can emit innocuous but scary "electron not defined"

- plugins/plugin-client-common/web/css/static/ui.css
> fix(plugins/plugin-client-common): fix buggy "display: span"

- plugins/plugin-bash-like/web/scss/xterm.scss
> fix: xterm scrollbar is not visible

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 18.3.4 -> 18.3.5

- plugins/plugin-bash-like/src/test/bash-like/false.ts
- plugins/plugin-bash-like/src/test/bash-like/vi.ts
- plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
> fix: test regressions in xterm

- package-lock.json
- packages/builder/package.json
- packages/test/package.json
- packages/webpack/package.json
> chore: another round of minor bumps

- plugins/plugin-bash-like/fs/src/vfs/local.ts
> fix(plugins/plugin-bash-like): `vfs fslice` fails with uncaught exception for ENOENT

- packages/core/src/main/spawn-electron.ts
e.g. config.d/style.json
```json
{ "width": 800, "height": 600 }
```
This will set the default window size. Individual commands can still override this by setting windowWidth and windowHeight properties in their command registration options.
> feat: allow clients to specify window width in config.d

- packages/core/src/main/spawn-electron.ts
see https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions
> feat: allow clients, via config.d/styles.json, to specify any electron BrowserWindowConstructorOptions

- packages/core/src/main/spawn-electron.ts
If the controller specifies a desired window widthxheight, this only works for windows from the primary process. When using electron's "second-instance" mechanism (which allows us to run a single copy of Kui, no matter how many times it is launched by the user), those desires are not passed through.
> fix: when opening a second window, desired window dimensions ignored

- packages/webpack/headless-webpack.config.js
> chore: add helpful comment to headless webpack config

- packages/core/src/main/menu.ts
> fix(packages/core): ctrl/cmd+w can result in null pointer exception

- packages/webpack/webpack.config.js
> feat(packages/webpack): add support for asciinema "cast" files

- plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
> fix: markdown tabs should not unmount on exit

- plugins/plugin-kubectl/src/lib/view/modes/Terminal.tsx
> fix: kubernetes Terminal tab does not respond to font zooming

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 18.3.6 -> 18.3.7

- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 18.3.7 -> 18.3.9

- packages/builder/dist/electron/builders/notarize.js
- packages/builder/dist/electron/builders/sign.js
> fix: electron builder tries to notarize non-darwin targets

- package-lock.json
- package.json
- packages/builder/package.json
- packages/core/package.json
> chore: minor package bumps

- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Job.ts
> fix(plugins/plugin-kubectl): Job summary may show undefined/1

- plugins/plugin-client-common/web/scss/components/Terminal/Layout/Default.scss
> fix(plugins/plugin-client-common): in narrower windows, use top-bottom split

- plugins/plugin-kubectl/src/lib/view/modes/Events.tsx
> fix(plugins/plugin-kubectl): Show Events may show events from prior versions of resource

- plugins/plugin-kubectl/src/lib/view/modes/DeleteButton.tsx
> fix(plugins/plugin-kubectl): delete button does not pass through --kubeconfig

- plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecarV2.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/LeftNavSidecarV2.tsx
- plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx
> fix(plugins/plugin-client-common): Switching to and from Terminal tab causes reset of terminal

- plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/convert.ts
> fix(plugins/plugin-kubectl): summary cells with `0` value appear empty

- plugins/plugin-kubectl/src/lib/view/modes/pods.ts
> feat(plugins/plugin-kubectl): add "Show Pods" drilldown from Jobs

- plugins/plugin-kubectl/src/controller/kubectl/explain-openshift-fasthpath.ts
- plugins/plugin-kubectl/src/controller/kubectl/explain.ts
> fix(plugins/plugin-kubectl): oc get on cluster-scoped resources fail

- plugins/plugin-kubectl/src/controller/kubectl/get.ts
> fix(plugins/plugin-kubectl): improved support for HTTPS_PROXY vs kubectl commands

- plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx
- plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
and use distance=10 rather than the default 15
> fix(plugins/plugin-client-common): use brighter tooltip

- plugins/plugin-client-common/src/components/Views/Sidecar/Badge.tsx
- plugins/plugin-client-common/src/components/spi/Tag/impl/PatternFly.tsx
- plugins/plugin-client-common/src/components/spi/Tag/model.ts
> fix(plugins/plugin-client-common): status badge for Succeeeded shows up yellow

- plugins/plugin-kubectl/src/tray/menus/index.ts
- plugins/plugin-kubectl/src/tray/menus/resources/networking.ts
- plugins/plugin-kubectl/src/tray/menus/resources/open.ts
- plugins/plugin-kubectl/src/tray/menus/resources/storage.ts
- plugins/plugin-kubectl/src/tray/menus/resources/workloads.ts
> feat(plugins/plugin-kubectl): add Workloads, Networking, Storage to tray menu

- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
> fix(plugins/plugin-client-common): improve tooltip for table Status cells

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/guide/Guide.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/remark-keys.ts
- plugins/plugin-client-common/src/components/Content/Markdown/remark-mark.ts
- plugins/plugin-client-common/src/controller/guide.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/1.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/4.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/5.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/6.ts
> chore: bump madwizard to 0.21.7

- plugins/plugin-kubectl/src/tray/menus/resources/open.ts
> fix: make tray popup window a bit wider

- plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
> fix: tone down the tooltips a bit

- README.md
> doc: update electron version in readme badge

- package-lock.json
- package.json
> chore: bump top-level package version to 12.0.0

- packages/proxy/app/npm-shrinkwrap.json
- packages/proxy/app/package.json
> chore: bump deps in proxy app

- plugins/plugin-kubectl/src/lib/view/css-for-value.ts
> fix: Bound state for volumes should have a green traffic light color

- package-lock.json
- plugins/plugin-kubectl-tray-menu/package.json
> fix: plugin-kubectl-tray-menu had incorrect package name

- package-lock.json
- plugins/plugin-kubectl-tray-menu/package.json
- plugins/plugin-kubectl/src/lib/view/css-for-value.ts
[1201b 14b33e447] fix: Bound state for volumes should have a green traffic light color
Date: Wed Sep 7 10:36:42 2022 -0400
1 file changed, 3 insertions(+)
[1201b c40fb943e] fix: plugin-kubectl-tray-menu had incorrect package name
Date: Wed Sep 7 10:44:42 2022 -0400
2 files changed, 25 insertions(+), 30 deletions(-)
> two more cherry-picks for 12.0.1

- package-lock.json
- package.json
- packages/test/src/api/util.ts
- plugins/plugin-kubectl/src/controller/kubectl/kustomize.ts
Plus a few compiler error fixes that resulted from this.
> chore: bump js-yaml types 4.0.2 -> 4.0.5

- package-lock.json
- package.json
> chore: bump typescript 4.8.2 -> 4.8.3

- package-lock.json
- package.json
- packages/core/src/util/mimic-dom.ts
> chore: bump types/node from 12.12.31 -> 18.7.6

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 20.1.2 -> 20.1.3

- plugins/plugin-kubectl-tray-menu/src/electron-main.ts
- plugins/plugin-kubectl-tray-menu/src/tray/events.ts
- plugins/plugin-kubectl-tray-menu/src/tray/init.ts
- plugins/plugin-kubectl-tray-menu/src/tray/main.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/contexts/current.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/contexts/index.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/namespaces/current.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/namespaces/index.ts
> fix: improved debug output and error handling in tray menu code

- plugins/plugin-kubectl-tray-menu/src/electron-main.ts
- plugins/plugin-kubectl-tray-menu/src/tray/events.ts
- plugins/plugin-kubectl-tray-menu/src/tray/init.ts
- plugins/plugin-kubectl-tray-menu/src/tray/main.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/contexts/current.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/contexts/index.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/namespaces/current.ts
- plugins/plugin-kubectl-tray-menu/src/tray/menus/namespaces/index.ts
[1204b 4e2f1a7aa] fix: improved debug output and error handling in tray menu code
Date: Fri Sep 9 14:55:26 2022 -0400
8 files changed, 178 insertions(+), 78 deletions(-)
> cherry picks for 12.0.4

- package-lock.json
- package.json
> chore: bump top-level package version to 12.1.0

- packages/builder/dist/electron/builders/electron.js
> fix: electron builds should not include .log directory

- plugins/plugin-patternfly4-themes/web/scss/dark.scss
> fix: blue in sidecars has low contrast

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron to 20.1.4

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 20.1.4 -> 20.2.0

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/1.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/6.ts
- plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/7.ts
> chore: bump to madwizard 1.0.x

- plugins/plugin-client-common/web/css/static/ui.css
so that patternfly behaves nicely
> fix: override default user agent background-color for buttons

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/test/core/markdown/wizards.ts
> chore: bump madwizard 1.0.3 -> 1.6.4

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 20.2.0 -> 20.3.1

- package-lock.json
- package.json
> chore: bump top-level version to 12.2.0

- README.md
> Updated survey link in readme

- plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
Maybe at some point this will be added to `anser`. https://github.com/IonicaBizau/anser/issues/72
> feat: add support for ansi terminal link extension

- packages/core/src/core/jobs/job.ts
- plugins/plugin-bash-like/src/pty/client.ts
> feat: Job api should allow passing through desired kill signal

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
> fix: terminal link support was handling only the first link in a string

- plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
> fix: `<Ansi/>` component should use normal white-space wrapping for links

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump to madwizard@1.8.5

- plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
> fix: Ansi component can result in react key warning

- plugins/plugin-kubectl/src/test/k8s1/apply-crd.ts
- plugins/plugin-kubectl/tests/data/k8s/crd.yaml
- plugins/plugin-kubectl/tests/data/k8s/crd2.yaml
- tools/travis/microk8s.sh
> test: bump microk8s from 1.17 to 1.23

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 20.3.4 -> 20.3.6

- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx
> fix(plugins/plugin-client-common): KWizard may fail with enableNext null pointer exception

- plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Footer.tsx
> Cannot read properties of undefined (reading 'hideBackButton')
> fix(plugins/plugin-client-common): Wizard/Footer can throw null pointer exception

- package-lock.json
- package.json
- packages/test/package.json
mocha 10.0.0 -> 10.1.0
also wdio/mocha-framework 7.24.0 -> 7.26.0
> chore: bump to mocha 10.1.0

- package-lock.json
- plugins/plugin-kubectl-tray-menu/package.json
> chore: plugin-kubectl-tray-menu has unused dependences in package.json

- package-lock.json
- plugins/plugin-kubectl/package.json
> chore: bump semver 7.3.7 -> 7.3.8

- package-lock.json
- packages/builder/package.json
> chore: switch from electron-rebuild to at-electron/rebuild

- plugins/plugin-kubectl-tray-menu/src/tray/icons.ts
> fix: tray menu may not appear in popup window mode

- package-lock.json
- package.json
> chore: bump top-level version to 13.0.0

- packages/test/src/api/util.ts
> test: fix for Logs previous test failures due to tooltip obscuring click

- plugins/plugin-client-common/src/test/core/code-blocks-in-markdown.ts
- plugins/plugin-client-common/src/test/core/markdown/icons.ts
- plugins/plugin-client-common/src/test/core/markdown/kbd.ts
- plugins/plugin-client-common/src/test/core/markdown/mark.ts
- plugins/plugin-client-common/src/test/core/markdown/tab-after-tip-in-tab.ts
- plugins/plugin-client-common/src/test/core/markdown/tab-indentation-preservation.ts
- plugins/plugin-client-common/src/test/core/markdown/terminal.ts
- plugins/plugin-client-common/src/test/core/markdown/tip.ts
- plugins/plugin-client-common/src/test/core/markdown/wizards.ts
- plugins/plugin-client-common/src/test/core/snippets-in-markdown.ts
- plugins/plugin-core-support/src/test/core-support/toggle-editability.ts
> test: re-enable 'toggle edit' test

- plugins/plugin-core-support/src/test/core-support/toggle-editability.ts
> test: disable double click editability

- packages/webpack/url.js
- packages/webpack/webpack.config.js
> fix: shim `fileURLToPath` over `portable-url` npm

- package-lock.json
- packages/webpack/process.js
- plugins/plugin-client-common/package.json
> chore: bump madwizard 2.1.0 -> 2.4.8

- plugins/plugin-client-common/notebook/src/load.ts
> fix: fetching notebooks with url imports fails in browser

- package-lock.json
- packages/core/package.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/test/core/markdown/wizards.ts
- plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md
- plugins/plugin-electron-components/package.json
- plugins/plugin-kubectl/package.json
> chore: bump needle 3.1.0 -> 3.2.0

- package-lock.json
- packages/core/package.json
- plugins/plugin-client-common/package.json
- plugins/plugin-electron-components/package.json
- plugins/plugin-s3/package.json
> chore: minor bumps

- package-lock.json
- package.json
- packages/core/package.json
- plugins/plugin-kubectl/package.json
> chore: bump fs-extra 10.1.0 -> 11.1.0

- package-lock.json
- plugins/plugin-core-support/package.json
> chore: fix a trailing reference to electron/remote 2.0.8

- packages/core/src/main/spawn-electron.ts
electron has deprecated the former in favor of the latter
https://www.electronjs.org/docs/latest/breaking-changes#removed-webcontents-new-window-event
> fix: port use of deprecated new-window event to setWindowOpenHandler

- plugins/plugin-patternfly4-themes/web/scss/sans.scss
https://web.dev/avoid-invisible-text/
> fix: add font-display: swap to patternfly font-face

- packages/core/templates/index.ejs
I don't think this matters for desktop much, but it can't hurt:
https://developer.chrome.com/blog/300ms-tap-delay-gone-away/
> fix: add meta viewport to index.ejs

- plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
> fix: skip sidecar button tooltip if tooltipText==buttonLabel

- package-lock.json
- packages/webpack/package.json
- packages/webpack/webpack.config.js
1) use mini-css-extract for the main ui.css, too
2) bundle css into a single file, avoiding a bunch of small appendChilds for each of the many tiny css files from patternfly
> fix: css load time optimizations

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump madwizard 2.4.8 -> 2.4.10

- plugins/plugin-client-common/src/components/Content/Markdown/components/table.tsx
- plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
- plugins/plugin-client-common/src/components/Content/Table/TableHeader.tsx
> fix: minor load time tweaks around use of patternfly/react-table

- plugins/plugin-client-common/src/components/Content/Commentary.tsx
> fix: (minor) Commentary does not need to load Button eagerly

- plugins/plugin-client-common/src/components/Client/Kui.tsx
- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
- plugins/plugin-client-common/src/components/Client/TabContent.tsx
- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix: proper fix for onTabReady polling hack

- package-lock.json
- plugins/plugin-bash-like/package.json
> chore: bump xterm 5.0.0 -> 5.1.0

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
- plugins/plugin-client-test/src/test/api2/status-stripe.ts
> test: 'test client status stripe' test is unstable in browser-based tests

- plugins/plugin-client-common/src/components/Content/Commentary.tsx
- plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
Maybe this is a regression from react 18, or from some interim patternfly update.
> fix: playground does not update when switching tab n->m->n i.e. returning to a tab

- plugins/plugin-kubectl/src/lib/view/formatTable.ts
- plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
> fix(plugins/plugin-kubectl): kubectl get pod/nginx has buggy drilldown

- plugins/plugin-client-common/src/components/Client/TabContent.tsx
> fix: TabContent may execute initial command prior to first mount

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> fix: bump madwizard 2.5.2 -> 2.5.3 to pick up choice string expansion fix

- plugins/plugin-madwizard/components/src/AskingTerminal.tsx
> fix: AskingTerminal does not reset allotment sizes when restarting guidebook

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> chore: bump madwizard 4.0.0 -> 4.0.1 and store to pick up s3fs fixes

- plugins/plugin-client-common/notebooks/markdown-overview.md
> fix: minor tweak to markdown playground to use a hint at the top

- plugins/plugin-madwizard/.npmignore
- plugins/plugin-madwizard/package.json
> fix: flip plugin-madwizard to public npm

- .github/PULL_REQUEST_TEMPLATE.md
> chore: clean up pull request template to remove pin requirement

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> fix: bump madwizard 4.0.1->4.0.2 to pick up interactive bug fix

- plugins/plugin-madwizard/components/src/plugin.ts
> fix: plan command does not work, due to registration as /madwizard/plan

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
also picks up some s3fs fixes in the store 1.10.0 -> 1.10.1
> fix: bump madwizard 4.0.2 -> 4.0.3 to pick up ray job stop fix

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> fix: bump guidebook store and madwizard; pick up fixes for imagePullSecret

- package-lock.json
- plugins/plugin-madwizard/package.json
> fix: bump guidebook store to pick up cgroup v2 fix

- plugins/plugin-madwizard/watch/src/respawn.ts
> fix: guidebook store env var not properly passed through

- tools/travis/check-error-handlers.sh
> test: eliminate check-error-handlers.sh false positive

- plugins/plugin-madwizard/components/src/Ask.tsx
> fix: update to new phrasing of 'prior choice'

- .github/PULL_REQUEST_TEMPLATE.md
> chore: further refinement of pull request template to distinguish required vs optional items

- plugins/plugin-madwizard/components/src/Ask.tsx
- plugins/plugin-madwizard/components/src/Mdown.tsx
> fix: small optimization for Ask's use of Markdown

- plugins/plugin-madwizard/components/src/Ask.tsx
- plugins/plugin-madwizard/components/src/AskingTerminal.tsx
re: the ||'' in Ask.tsx, this is just being extra cautious
> fix: AskingTerminal can drop chunks coming from madwizard over raw stdout

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> fix: bump electron 22.0.0 -> 22.0.1

- plugins/plugin-client-common/src/components/Client/InputStripe.tsx
> fix: InputStripe may call setState prior to mount

- packages/core/src/main/headless.ts
- packages/core/src/main/spawn-electron.ts
> fix: second popup window does now execute desired command line

- plugins/plugin-kubectl/components/src/CurrentContext.tsx
- plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
> fix: CurrentContext/Namespace widgets stuck Loading in Popup windows

- README.md
> chore: bump README to show electron 22

- plugins/plugin-client-common/src/components/Client/Sidebar.tsx
> fix: Sidebar does not update active nav item ui on click

- packages/webpack/bin/watch.sh
When working with "offline" clients, this is undesirable; i.e. clients that are going to be browser-based and with no backing proxy.
Set
@kui-shell/client/config.d/client.json
```json
{
"offline": true
}
```
> fix: kui-webpack-watch always launches proxy and headless watcher

- plugins/plugin-client-common/src/components/Client/TabContainer.tsx
> fix: Sidebar should not auto-close if Client requested that the Sidebar stay open

- packages/builder/bin/pty-rebuild.sh
> fix: kui-pty-rebuild does not correctly rebuild with node-pty 0.11.0

- package-lock.json
> chore: pull in 13.0.0 versions into package-lock

- package-lock.json
- plugins/plugin-client-common/package.json
> chore: bump react-markdown 8.0.4 -> 8.0.5

- plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
> fix: ScrollableTerminal may error if command completion races with terminal clear

- plugins/plugin-client-common/src/components/Client/StatusStripe/MadeWithKui.tsx
> fix: update MadeWithKui to accept a position prop for the popover

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-default/config.d/notebooks.json
- plugins/plugin-madwizard/components/src/Playground.tsx
- plugins/plugin-madwizard/components/src/PlaygroundTextual.tsx
- plugins/plugin-madwizard/components/src/Terminal.tsx
- plugins/plugin-madwizard/notebooks/guidebook-intro.md
- plugins/plugin-madwizard/notebooks/playground.md
- plugins/plugin-madwizard/package.json
- plugins/plugin-madwizard/src/preload.ts
> feat: add textual guidebook playground

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
- plugins/plugin-s3/package.json
> fix: bump madwizard -> 4.7.0 to pick up removal of dependence on readline

- package-lock.json
- packages/core/package.json
- packages/core/src/main/headless-support.ts
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> fix: make sure to import node:readline, and get rid of npm readline dep

- plugins/plugin-madwizard/components/src/PlaygroundTextual.tsx
- plugins/plugin-madwizard/components/src/Terminal.tsx
> fix: Playground Terminal may not fill vertical space

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/components/src/Playground.tsx
- plugins/plugin-madwizard/package.json
> fix: update to madwizard 5 to pick up support for shell.exec richer return types

- plugins/plugin-core-support/src/lib/cmds/echo.ts
> fix: improve echo support in browser w.r.t. env vars

- plugins/plugin-bash-like/src/lib/cmds/export.ts
> fix: improve export behavior in browser

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/components/src/Playground.tsx
- plugins/plugin-madwizard/package.json
> fix: bump madwizard 5.0.3 to pick up support for recognizing madwizard-internal shell.execs

- plugins/plugin-madwizard/components/src/Ask.tsx
> fix: <Ask/> descriptions can have odd prefix whitespace

- plugins/plugin-client-common/web/scss/components/Terminal/BlockBorder.scss
- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
> fix: block border may show up in guidebooks

- plugins/plugin-madwizard/components/src/Ask.tsx
- plugins/plugin-madwizard/components/src/AskingTerminal.tsx
- plugins/plugin-madwizard/components/src/Guide.tsx
- plugins/plugin-madwizard/components/src/GuidebookTerminal.tsx
- plugins/plugin-madwizard/components/src/LeftRightSplit.tsx
- plugins/plugin-madwizard/components/src/Plan.tsx
- plugins/plugin-madwizard/components/src/Playground.tsx
- plugins/plugin-madwizard/components/src/PlaygroundTerminal.tsx
- plugins/plugin-madwizard/components/src/PlaygroundTextual.tsx
- plugins/plugin-madwizard/components/src/ProfileExplorer.tsx
- plugins/plugin-madwizard/components/src/RestartableTerminal.tsx
- plugins/plugin-madwizard/components/src/Terminal.tsx
- plugins/plugin-madwizard/components/src/Wizard/KWizard.tsx
- plugins/plugin-madwizard/components/src/designer.tsx
- plugins/plugin-madwizard/components/src/plugin.ts
- plugins/plugin-madwizard/components/src/read.ts
- plugins/plugin-madwizard/do/src/doMadwizard.ts
- plugins/plugin-madwizard/do/src/plugin.ts
- plugins/plugin-madwizard/do/src/util.ts
- plugins/plugin-madwizard/src/controller/hello.ts
- plugins/plugin-madwizard/src/controller/index.ts
- plugins/plugin-madwizard/src/controller/profile/delete.ts
- plugins/plugin-madwizard/src/controller/profile/rename.ts
- plugins/plugin-madwizard/src/controller/profile/reset.ts
- plugins/plugin-madwizard/src/preload.ts
- plugins/plugin-madwizard/watch/src/respawn.ts
> chore: optimize plugin-madwizard imports of kui-shell/core

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
Since we are already pulling in `entities` for a separate reason, this saves some on bundle size.
> fix: move from html-entities to entities

- plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
- plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
> fix: import just the lib/decode.js from entities

- packages/core/src/api/Client.ts
- plugins/plugin-client-common/web/scss/components/Terminal/Layout/Default.scss
> fix: improve layout on phones

- plugins/plugin-client-common/web/scss/components/Terminal/BigFonts.scss
> fix: reduce ridiculous padding in kui--18px mode

- packages/core/src/api/Client.ts
- plugins/plugin-client-common/web/scss/components/Terminal/Layout/Default.scss
> fix: improvements for phones in landscape mode

- plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
- plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
> fix: on phones, hide StatusStripe and TopTabStripe in landscape

- plugins/plugin-core-support/src/lib/cmds/quit.ts
> fix: cmd+w fails to close window with only one tab

- plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss
> fix: Sidebar css color and height regression

- plugins/plugin-core-support/src/lib/cmds/echo.ts
> fix: restore support for echo in non-proxy browser clients

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> fix: bump madwizard 5.0.4 to pick up expanded handle-by-client exec

- packages/webpack/webpack.config.js
> fix: webpack watcher did not trigger a rebuild on rerun of prescan

- package.json
> fix: babel is called twice in top-level compile scripts

- packages/builder/bin/prescan.sh
> fix: prescan of client guidebooks should follow symlinks

- plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
- plugins/plugin-madwizard/components/src/plugin.ts
- plugins/plugin-madwizard/web/scss/components/Allotment/overrides.scss
> fix: Playground should have a min height in non-maximized blocks

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/components/src/Playground.tsx
- plugins/plugin-madwizard/package.json
> fix: bump to madwizard 5.0.5 to pick up shell exec updates

- plugins/plugin-madwizard/components/src/Playground.tsx
> fix: <Playground/> may not execute correct command line

- plugins/plugin-kubectl/src/lib/model/resource.ts
- plugins/plugin-kubectl/src/lib/view/modes/Containers.ts
- plugins/plugin-kubectl/src/lib/view/modes/yaml.ts
- plugins/plugin-kubectl/src/non-headless-preload.ts
> feat: Containers kube tab

- package-lock.json
- package.json
> chore: bump top-level package.json to 13.1.0

- plugins/plugin-madwizard/components/src/WorkloadDesigner.tsx
- plugins/plugin-madwizard/components/src/designer.tsx
> fix: <ProfileExplorer/> edit button does not restart terminal with desired guidebook

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
> chore: bump electron 22.1.0 -> 22.2.0

- plugins/plugin-madwizard/do/src/doMadwizard.ts
> fix: doMadwizard does not properly pass through profile subcommands

- plugins/plugin-core-support/src/notebooks/vfs/index.ts
> fix: pick up yaml files from client/notebooks directory

- packages/builder/bin/prescan.sh
- plugins/plugin-bash-like/fs/src/vfs/TrieVFS.ts
> fix: completed support for scanning yaml files in client/notebooks

- package-lock.json
- plugins/plugin-kubectl-core/package.json
> fix: removed unused deps from plugin-kubectl-core

- plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
> fix: Sidebar selection background can cause low contrast in some themes

- package-lock.json
- package.json
- packages/builder/dist/electron/package-lock.json
- packages/builder/dist/electron/package.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> fix: bump to madwizard v6

- plugins/plugin-kubectl/src/test/k8s3/usage.ts
- tools/travis/microk8s.sh
> test: remove the tiny odo tests as the odo cli download no longer works

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> chore: bump madwizard to pick up git+ssh->https dependence of enquirer

- plugins/plugin-madwizard/do/src/doMadwizard.ts
> fix: doMadwizard was not passing through -h/-v

- package-lock.json
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/do/src/doMadwizard.ts
- plugins/plugin-madwizard/package.json
> fix: doMadwizard should pass through `appVersion` option

- plugins/plugin-madwizard/do/src/doMadwizard.ts
> fix: ugh, we were not passing through appVersion to madwizard

- package.json
[1311b 9349164ac] chore: remove git add from lint-staged tasks
Date: Tue Feb 21 18:46:40 2023 -0500
1 file changed, 2 insertions(+), 4 deletions(-)
> 13.1.1 (addon)

- packages/webpack/headless-webpack.config.js
> feat: allow headless clients to use react

- plugins/plugin-madwizard/do/src/doMadwizard.ts
> fix: pass through force option in doMadwizard

- packages/webpack/bin/watch.sh
> fix: initial run of watchers may not correctly generate prescan

- package-lock.json
- package.json
- packages/webpack/webpack.config.js
- plugins/plugin-client-common/package.json
- plugins/plugin-madwizard/package.json
> chore: bump madwizard to pick up its esm updates

- package-lock.json
- plugins/plugin-s3/package.json
- plugins/plugin-s3/src/vfs/index.ts
> chore: bump minimatch 5->9

- package-lock.json
- plugins/plugin-bash-like/package.json
- plugins/plugin-bash-like/src/pty/server.ts
> chore: bump ws 7->8

- packages/builder/bin/prescan.sh
> fix: improve prescan for windows it github actions

- packages/builder/bin/prescan.sh
Reverts kubernetes-sigs/kui#9344
> Revert "fix: improve prescan for windows it github actions"

- packages/webpack/headless-webpack.config.js
- packages/webpack/webpack.config.js
> feat: enable top-level-await feature in webpack

- packages/webpack/headless-webpack.config.js
- packages/webpack/webpack.config.js
> fix: improve handling of wasm loading

- packages/webpack/headless-webpack.config.js
- packages/webpack/webpack.config.js
> fix: update to webpack v5 support for wasm

- package-lock.json
- packages/webpack/headless-webpack.config.js
- packages/webpack/package.json
- packages/webpack/webpack.config.js
> fix: add support for plugins specifying a uint8array webpack loader
